set show advisories off .

***** Testing DNSTask in underlying DNS network
***(
load ../probabilistic/iodine_dns
load ../probabilistic/paced-client
iodine_dns loads
)

load ../../../../deps/dns_formalization/Maude/src/probabilistic-model/dns
*****  < wildcard . 'example . 'com . root, txt, 3600.0, nullAddr > .

load user-model.maude
load dnsTask.maude


mod DNSTASK-TEST is
  inc  DNS .
  inc USER-MODEL .
  inc DNS-TASK .

****** DNSTask / UserModel params
op umodelD : -> MModel .
eq umodelD = mm("dnsUM",
**** states
("query"  ; "idle"),
**** markov
   (("query" |-> ("query" |-> 0.65, "idle" |-> 0.35)),
    ("idle"  |-> ("query" |-> 0.85, "idle" |-> 0.15))),
**** waits
  (("query" |-> (mean: 10.0, std: 2.0)),
   ("idle"  |-> (mean: 10.0, std: 5.0))) ,
**** params
  ((maxSteps: 5),(stopTime: 200.0))
) .

 op dnsTPar : -> Params .
 eq dnsTPar = (
     nameDb: (('www . 'example . 'com . root) 
              ('www0 . 'example . 'com . root) 
              ('www1 . 'example . 'com . root) 
              ('www2 . 'example . 'com . root) ),
     retryTO: 5.0,
     retryMax: 2 )
 .



***(
eq monitorQueryLog? = true .

eq maxMinimiseCount = 0 .
eq maxFragmentLen = 100 .
eq maxFragmentTx = 10 .
---- iodine  client parameters
eq ackTimeoutDelay = 1.0 .
)
--- DNS Actor addresses
ops  addrNScom addrNScorporate addrNSexample addrNSpwnd2 addrNSroot  rAddr : -> Address .


************ DNS parameters
--- "SBELT": fallback if there are no known name servers
op sb1 : -> ZoneState .
eq sb1 = < root ('a . 'root-servers . 'net . root |-> addrNSroot) > .

op sb2 : -> ZoneState .
eq sb2 = < root (
              ('a . 'root-servers . 'net . root |-> addrNSroot),
              ('a . 'root-servers . 'net . root |-> addrNSroot)
             ) > .

--- Zone files
op zoneCom : -> List{Record} .
eq zoneCom =
  < 'com . root, soa, 3600.0, soaData(3600.0) >
  < 'com . root, ns, 3600.0, 'ns . 'com . root >
  < 'ns . 'com . root, a, 3600.0, addrNScom >
  < 'example . 'com . root, ns, 3600.0, 'ns . 'example . 'com . root >
  < 'ns . 'example . 'com . root, a, 3600.0, addrNSexample >
  < 'pwnd2 . 'com . root, ns, 3600.0, 'ns . 'pwnd2 . 'com . root >
  < 'ns . 'pwnd2 . 'com . root, a, 3600.0, addrNSpwnd2 >
  < 'corporate . 'com . root, ns, 3600.0, 'ns . 'corporate . 'com . root >
  < 'ns . 'corporate . 'com . root, a, 3600.0, addrNScorporate > .

op zone : -> List{Record} .
eq zone =
  < root, soa, 3600.0, soaData(3600.0) >
  < root, ns, 3600.0, 'a . 'root-servers . 'net . root >
  < 'a . 'root-servers . 'net . root, a, 3600.0, addrNSroot >
  < 'com . root, ns, 3600.0, 'ns . 'com . root >
  < 'ns . 'com . root, a, 3600.0, addrNScom > .

op zonePwnd2Com : -> List{Record} .
eq zonePwnd2Com =
  < 'pwnd2 . 'com . root, soa, 3600.0, soaData(3600.0) >
  < 'pwnd2 . 'com . root, ns, 3600.0, 'ns . 'pwnd2 . 'com . root >
  < 'ns . 'pwnd2 . 'com . root, a, 3600.0, addrNSpwnd2 >
  < 'www0 . 'pwnd2 . 'com . root, a, 3600.0, 2 . 0 . 1 . 2 >
  < 'www1 . 'pwnd2 . 'com . root, a, 3600.0, 2 . 1 . 1 . 2 >
  < wildcard . 'pwnd2 . 'com . root, txt, 3600.0, nullAddr > .

op zoneCorporateCom : -> List{Record} .
eq zoneCorporateCom =
  < 'corporate . 'com . root, soa, 3600.0, soaData(3600.0) >
  < 'corporate . 'com . root, ns, 3600.0, 'ns . 'corporate . 'com . root >
  < 'ns . 'corporate . 'com . root, a, 3600.0, addrNScorporate >
  < 'www0 . 'corporate . 'com . root, a, 3600.0, 3 . 0 . 1 . 2 >
  < 'www1 . 'corporate . 'com . root, a, 3600.0, 3 . 1 . 1 . 2 >
  < wildcard . 'corporate . 'com . root, txt, 3600.0, nullAddr > .

op zoneExampleCom : -> List{Record} .
eq zoneExampleCom =
  < 'example . 'com . root, soa, 3600.0, soaData(3600.0) >
  < 'example . 'com . root, ns, 3600.0, 'ns . 'example . 'com . root >
  < 'ns . 'example . 'com . root, a, 3600.0, addrNSexample >
  < 'www0 . 'example . 'com . root, a, 3600.0, 1 . 0 . 1 . 2 >
  < 'www1 . 'example . 'com . root, a, 3600.0, 1 . 1 . 1 . 2 >
  < wildcard . 'example . 'com . root, txt, 3600.0, nullAddr > .

--- Caches

op rsvCache1 : -> Cache .
eq rsvCache1 =
  cacheEntry(< root, ns, 3600.0, 'a . 'root-servers . 'net . root >, 1)
  cacheEntry(< 'a . 'root-servers . 'net . root, a, 3600.0, addrNSroot >, 1)
  cacheEntry(< 'com . root, ns, 3600.0, 'ns . 'com . root >, 1)
  cacheEntry(< 'ns . 'com . root, a, 3600.0, addrNScom >, 1)
  cacheEntry(< 'example . 'com . root, ns, 3600.0, 'ns . 'example . 'com . root >, 1)
  cacheEntry(< 'ns . 'example . 'com . root, a, 3600.0, addrNSexample >, 1)
  cacheEntry(< 'pwnd2 . 'com . root, ns, 3600.0, 'ns . 'pwnd2 . 'com . root >, 1)
  cacheEntry(< 'ns . 'pwnd2 . 'com . root, a, 3600.0, addrNSpwnd2 >, 1)
  cacheEntry(< 'corporate . 'com . root, ns, 3600.0, 'ns . 'corporate . 'com . root >, 1)
  cacheEntry(< 'ns . 'corporate . 'com . root, a, 3600.0, addrNScorporate >, 1)
 .
 op rsvCache2 : -> Cache .
 eq rsvCache2 =  rsvCache1 rsvCache1 .
 op rsvCache4 : -> Cache .
 eq rsvCache4 =  rsvCache2 rsvCache2 .


var cache : Cache .
var zs : ZoneState .
var freq : Nat .
var dur : Float .
vars umADDR rADDR  dnsTADDR : Address .


**** DNSTask addresses
  ops umDAddr dnsTAddr  : -> Address .


--- Initial configuration
*****                          
op initState : Cache ZoneState 
****            umAd   dnsTAdd  rsvAddr
               Address Address  Address
                -> Config .
               
eq initState (cache, zs, umADDR,dnsTADDR,rADDR) =
   --- DNS actors
  < rAddr : Resolver |
    cache: cache,
    nxdomainCache: nilNxdomainCache,
    nodataCache: nilNodataCache,
    sbelt: zs,
    workBudget: emptyIN,
    blockedQueries: eptQSS,
    sentQueries: eptQSS >
  --- Nameservers
  < addrNSroot : Nameserver |
    db: (zone),
    queue: nilQueue,
    forwardonly: nullAddr,
    queriesFwd: nilTAQL >
  < addrNScom : Nameserver |
    db: (zoneCom),
    queue: nilQueue,
    forwardonly: nullAddr,
    queriesFwd: nilTAQL >
  < addrNSexample : Nameserver |
    db: (zoneExampleCom),
    queue: nilQueue,
    forwardonly: nullAddr,
    queriesFwd: nilTAQL >
**** umActor
  mkUMactor(umADDR,umodelD, 
            (("query" |-> dnsTADDR ), ("idle" |-> nullAddr)),
            "idle")
**** dnsTActor
  mkDnsTA(dnsTADDR,rADDR,dnsTPar) 
  [1.0, (to umADDR : next), 0] 
.

 --- Link Characteristic definitions
 **** constant nonzero delay w noise, no loss
op LinkType-0 : -> AttributeSet .
eq LinkType-0 = 
  (delayStd: 0.),
  (delayType: "Constant"),
  (delayMean: 0.),
  (delayConst: 0.01),
  (noiseMin: 0.),
  (noiseMax: 0.00001),
  (dropP: 0.),
  (canDrop: false)
  .

 **** constant zero delay w noise, no loss
op LinkType-1 : -> AttributeSet .
eq LinkType-1 = 
  (delayStd: 0.),
  (delayType: "Constant"),
  (delayMean: 0.),
  (delayConst: 0.),
  (noiseMin: 0.),
  (noiseMax: 0.00001),
  (dropP: 0.),
  (canDrop: false)
  .

 **** constant nonzero delay w noise, .1 loss
op LinkType-0d : -> AttributeSet .
eq LinkType-0d = 
  (delayStd: 0.),
  (delayType: "Constant"),
  (delayMean: 0.),
  (delayConst: 0.01),
  (noiseMin: 0.),
  (noiseMax: 0.00001),
  (dropP: 0.1),
  (canDrop: true)
  .

 **** constant nonzero delay w noise, .05 loss
op LinkType-0d5 : -> AttributeSet .
eq LinkType-0d5 = 
  (delayStd: 0.),
  (delayType: "Constant"),
  (delayMean: 0.),
  (delayConst: 0.01),
  (noiseMin: 0.),
  (noiseMax: 0.00001),
  (dropP: 0.05),
  (canDrop: true)
  .

ops LinkDataNoDrop LinkDataDropCR LinkDataDropRP LinkDataDropRP5 LinkDataDropCR-RP : -> AdrAdrAttrsSet .

eq LinkDataNoDrop =
****  aaa(rAddr,addrNScorporate,LinkType-0)
****  aaa(addrNScorporate,rAddr,LinkType-0)
  aaa(addrNSroot,rAddr,LinkType-0)
  aaa(rAddr,addrNSroot,LinkType-0)
  aaa(addrNScom,rAddr,LinkType-0)
  aaa(rAddr,addrNScom,LinkType-0)
  aaa(addrNSexample,rAddr,LinkType-0)
  aaa(rAddr,addrNSexample,LinkType-0)
*****  aaa(addrNSpwnd2,rAddr,LinkType-0)
*****  aaa(rAddr,addrNSpwnd2,LinkType-0)
****  aaa(addrNScorporate,iodineC,LinkType-1)
****  aaa(iodineC,addrNScorporate,LinkType-1)
  aaa(rAddr,dnsTAddr,LinkType-0)
  aaa(dnsTAddr,rAddr,LinkType-0)
  .


  vars GT  : Float .
  vars t1 t2 : Float .
  vars  SM : ScheduleMsg .
  vars SL SL' : ScheduleList .
  vars M1 M2 : Msg .
  vars  ADDR : Address .
  var AS : AttributeSet .
  var P : Nat .
  vars St : Actor .

***(
From apmaude SCHEDULER
  --- insert a schedule msg to the scheduler 
  eq [ t1, M1, 0 ] S = insert(S, [ t1, M1, 0 ]) .
  eq [ t1, M1, P ] { GT | SL } = { GT | SL }
     [owise print "Drop " "[" t1 ", " M1  "]"  " at " GT ]
     .
)


**** replace above owise in apmaude by
op dropped:_ : ScheduleList -> Attribute [ctor]   .
op logDrop : AttributeSet ScheduleMsg -> AttributeSet .
eq logDrop((AS, dropped: SL), SM) = AS, (dropped: (SL ; SM)) .
eq logDrop(AS, SM) = AS, (dropped: SM) [owise] .

***( 
  eq [ t1, M1, P ] { GT | SL } < ADDR : WMonitor | AS >
      = { GT | SL } < ADDR : WMonitor | logDrop(AS, [GT,M1,0]) >
     [owise print "Drop " "{" GT ", " M1  "}" ]
     .
)
  var S : Scheduler .
   eq [ t1, M1, P ] S = S [owise] .
   
------------------------------------------------------------
***(
  op initTimedConfig : -> Config .
  eq initTimedConfig = 
run({0.0 | nil} initConfig( 

),limit) .
)

op iC : -> Config .
eq iC = randCtr(1) 
        initState (rsvCache1, sb1, umDAddr,dnsTAddr, rAddr) .

eq LinkData = LinkDataNoDrop .
  eq defaultDelay = 1.5 .

endm

set clear rules off .
set print attribute off .


eof


red iC .

set print attribute on .
rew run({1.0 | nil} iC,500.00) .

requestTask to umDAddr at 2.0 curState "idle"
endTask to umDAddr at 2.0 statu "noop"
requestTask to umDAddr at 1.1644675058157139e+1 curState "query"
DNSTask startDNSTask sends to rAddr from dnsTAddr : query(0, 'www2 . 'example . 'com .
    root, a)
DNSTask dnsResponse sends success to umDAddr at 1.320186206278094e+1
endTask to umDAddr at 1.320186206278094e+1 statu "success"
DNSTask dnsTOretryCancel nRetry: n 0 w4 noQuery TOQuery query(0, 'www2 . 'example . 'com
    . root, a) at 1.6644734342618776e+1
requestTask to umDAddr at 2.386253692179335e+1 curState "query"
DNSTask startDNSTask sends to rAddr from dnsTAddr : query(1, 'www0 . 'example . 'com .
    root, a)
DNSTask dnsResponse sends success to umDAddr at 2.5421008097547894e+1
endTask to umDAddr at 2.5421008097547894e+1 statu "success"
DNSTask dnsTOretryCancel nRetry: n 0 w4 noQuery TOQuery query(1, 'www0 . 'example . 'com
    . root, a) at 2.8862608440729847e+1
requestTask to umDAddr at 3.3044852839373348e+1 curState "query"
DNSTask startDNSTask sends to rAddr from dnsTAddr : query(2, 'www0 . 'example . 'com .
    root, a)
DNSTask dnsResponse sends success to umDAddr at 3.4560889390807148e+1
endTask to umDAddr at 3.4560889390807148e+1 statu "success"
DNSTask dnsTOretryCancel nRetry: n 0 w4 noQuery TOQuery query(2, 'www0 . 'example . 'com
    . root, a) at 3.8044937265947759e+1
requestTask to umDAddr at 4.3417270465612816e+1 curState "idle"
endTask to umDAddr at 4.3417270465612816e+1 statu "noop"

rewrites: 10355 in 3ms cpu (3ms real) (2716421 rewrites/second)
result Config: randCtr(20)
{4.3417270465612816e+1 |
nil}

< umDAddr : UM | mmodel: mm("dnsUM", "query" ; "idle", ("idle" |->
("idle" |-> 1.4999999999999999e-1, "query" |->
8.4999999999999998e-1), "query" |-> ("idle" |->
3.4999999999999998e-1, "query" |-> 6.5000000000000002e-1)), ("idle"
|-> mean: 1.0e+1, std: 5.0, "query" |-> mean: 1.0e+1, std: 2.0),
maxSteps: 5, stopTime: 2.0e+2), curState: "query", nsteps: 5, ready:
true, actMap: ("idle" |-> nullAddr, "query" |-> dnsTAddr) >

< dnsTAddr : DNSTask | dnsPar: (nameDb: ('www . 'example . 'com .
root 'www0 . 'example . 'com . root 'www1 . 'example . 'com . root
'www2 . 'example . 'com . root), retryTO: 5.0, retryMax: 2), ctr: 3,
lenNDB: 4, nRetry: 0, w4: noQuery, replyTo: nullAddr, dnsRsv: rAddr >
