set show advisories off .

*** sload ../../../../deps/dns_formalization/Maude/common/actor.maude
sload ../../../../deps/dns_formalization/Maude/common/apmaude.maude

sload dns-eq
  
 

mod  DNS-NET-EQ is
  inc DNS-EQ .
  inc SCHEDULER .


 ops auth-dns corporate-dns public-dns root-dns  tld-dns : -> Address .
 ops iServer masS : -> Address .

  **** "SBELT": fallback if there are no known name servers
op sb : -> ZoneState .
eq sb = < root (('a . 'root-servers . 'net . root ) |-> root-dns) > .

  **** Zone files
  op zoneCorporateCom : -> List{Record} .
  eq zoneCorporateCom =
    < 'corporate . 'com . root, soa, 3600.0, soaData(3600.0) >
    < 'corporate . 'com . root, ns, 3600.0, 'ns . 'corporate . 'com . root >
    < 'ns . 'corporate . 'com . root, a, 3600.0, corporate-dns >
    < 'tmp0 . 'corporate . 'com . root, a, 0.0, 3 . 0 . 1 . 2 >
    < wildcard . 'corporate . 'com . root, a, 0.0, 3 . 1 . 1 . 2 > .

  op zone : -> List{Record} .
  eq zone =
    < root, soa, 3600.0, soaData(3600.0) >
    < root, ns, 3600.0, 'a . 'root-servers . 'net . root >
    < 'a . 'root-servers . 'net . root, a, 3600.0, root-dns >
    < 'com . root, ns, 3600.0, 'ns . 'com . root >
    < 'ns . 'com . root, a, 3600.0, tld-dns > .

  op zoneCom : -> List{Record} .
  eq zoneCom =
    < 'com . root, soa, 3600.0, soaData(3600.0) >
    < 'com . root, ns, 3600.0, 'ns . 'com . root >
    < 'ns . 'com . root, a, 3600.0, tld-dns >
    < 'pwnd . 'com . root, ns, 3600.0, 'ns . 'pwnd . 'com . root >
    < 'ns . 'pwnd . 'com . root, a, 3600.0, auth-dns >
    < 'internet . 'com . root, ns, 3600.0, 'ns . 'internet . 'com . root >
    < 'ns . 'internet . 'com . root, a, 3600.0, auth-dns >
    < 'corporate . 'com . root, ns, 3600.0, 'ns . 'corporate . 'com . root >
    < 'ns . 'corporate . 'com . root, a, 3600.0, corporate-dns > .

  op zoneT1PwndCom : -> List{Record} .
  eq zoneT1PwndCom =
    < 't1 . 'pwnd . 'com . root, soa, 3600.0, soaData(3600.0) >
    < 't1 . 'pwnd . 'com . root, ns, 3600.0, 'ns . 't1 . 'pwnd . 'com . root >
    < 'ns . 't1 . 'pwnd . 'com . root, a, 3600.0, iServer >
    < 'tmp0 . 't1 . 'pwnd . 'com . root, a, 0.0, 2 . 0 . 1 . 2 >
    < wildcard . 't1 . 'pwnd . 'com . root, a, 0.0, 2 . 1 . 1 . 2 > .

  op zoneInternetCom : -> List{Record} .
  eq zoneInternetCom =
    < 'internet . 'com . root, soa, 3600.0, soaData(3600.0) >
    < 'internet . 'com . root, ns, 3600.0, 'ns . 'internet . 'com . root >
    < 'ns . 'internet . 'com . root, a, 3600.0, auth-dns >
    < 'tmp0 . 'internet . 'com . root, a, 0.0, 1 . 0 . 1 . 2 >
    < 't1 . 'pwnd . 'com . root, ns, 3600.0, 'ns . 't1 . 'pwnd . 'com . root >
    < 'ns . 't1 . 'pwnd . 'com . root, a, 3600.0, iServer >
    < 'mastodon . 'pwnd . 'com . root, a, 0.0, masS >
    < wildcard . 'internet . 'com . root, a, 0.0, 1 . 1 . 1 . 2 > .

  ********Caches
  op resolverCache : -> Cache .
  eq resolverCache =
    cacheEntry(< root, ns, 3600.0, 'a . 'root-servers . 'net . root >, 1)
    cacheEntry(< 'a . 'root-servers . 'net . root, a, 3600.0, root-dns >, 1) ----****
    cacheEntry(< 'com . root, ns, 3600.0, 'ns . 'com . root >, 1)
    cacheEntry(< 'ns . 'com . root, a, 3600.0, tld-dns >, 1) ----***
    cacheEntry(< 'pwnd . 'com . root, ns, 3600.0, 'ns . 'pwnd . 'com . root >, 1)
    cacheEntry(< 'ns . 'pwnd . 'com . root, a, 3600.0, auth-dns >, 1) -----****
    cacheEntry(< 'internet . 'com . root, ns, 3600.0, 'ns . 'internet . 'com . root >, 1)
    cacheEntry(< 'ns . 'internet . 'com . root, a, 3600.0, auth-dns >, 1)   -----****
    cacheEntry(< 't1 . 'pwnd . 'com . root, ns, 3600.0, 'ns . 't1 . 'pwnd . 'com . root >, 1)
    cacheEntry(< 'ns . 't1 . 'pwnd . 'com . root, a, 3600.0, iServer >, 1)  -----****
    cacheEntry(< 'corporate . 'com . root, ns, 3600.0, 'ns . 'corporate . 'com . root >, 1)
    cacheEntry(< 'ns . 'corporate . 'com . root, a, 3600.0, corporate-dns >, 1) .   
    
vars ADDR ADDR1 : Address .    
vars db : List{Record} .
vars sbx : ZoneState .
vars rcache : Cache .

op dnsNetConfig : -> Config .
eq dnsNetConfig =
  mkResolverEq(public-dns, resolverCache,  sb)
  --- Nameservers
  mkNameServerEq(root-dns, (zone), nullAddr)
  mkNameServerEq(tld-dns, (zoneCom), nullAddr)
  mkNameServerEq(auth-dns, (zoneInternetCom), nullAddr)
  mkNameServerEq(corporate-dns, (zoneCorporateCom), public-dns)    
 .

 --- Link Characteristic definitions
op LinkType-0 : -> AttributeSet .
eq LinkType-0 = 
  (delayStd: 0.),
  (delayType: "Constant"),
  (delayMean: 0.),
  (delayConst: 0.01),
  (noiseMin: 0.),
  (noiseMax: 0.00001),
  (dropP: 0.),
  (canDrop: false)
  .

op LinkType-1 : -> AttributeSet .
eq LinkType-1 = 
  (delayStd: 0.01334),
  (delayType: "Normal"),
  (delayMean: 0.025),
  (delayConst: 0.),
  (noiseMin: 0.),
  (noiseMax: 0.),
  (dropP: 0.),
  (canDrop: false)
  .

op LinkType-2 : -> AttributeSet .
eq LinkType-2 = 
  (delayStd: 0.),
  (delayType: "Constant"),
  (delayMean: 0.),
  (delayConst: 0.015),
  (noiseMin: 0.),
  (noiseMax: 0.00001),
  (dropP: 0.),
  (canDrop: false)
  .
 
 
 op DNSLinkData : -> AdrAdrAttrsSet .
 eq DNSLinkData =
   aaa(public-dns,root-dns,LinkType-0)
   aaa(root-dns,public-dns,LinkType-0)
   aaa(public-dns,tld-dns,LinkType-0)
   aaa(tld-dns,public-dns,LinkType-0)
   aaa(public-dns,auth-dns,LinkType-1)
   aaa(auth-dns,public-dns,LinkType-1)
   aaa(public-dns,corporate-dns,LinkType-2)
   aaa(corporate-dns,public-dns,LinkType-2)
 .
 
 
ops Q1 Q2 Q3 : -> Query .
eq Q1 = query(1,'www1 . 'internet . 'com . root,a) .

eq Q2 = query(2,'www1 . 't1 . 'pwnd . 'com . root,a) . 

eq Q3 = query(3,'mastodon . 'pwnd . 'com . root, a)  .

eq LinkData = DNSLinkData .

endm

eof 

red run({0.0 | nil} dnsNetConfig rCtr(1) [0.5, (to corporate-dns from masS : Q1),0] ,200.0) .

red run({0.0 | nil} dnsNetConfig rCtr(1) [0.5, (to corporate-dns from masS : Q2),0] ,200.0) .

< 'mastodon . 'pwnd . 'com . root, a, 0.0, masS >
< wildcard . 'internet . 'com . root, a, 0.0, 1 . 1 . 1 . 2 > .
< wildcard . 't1 . 'pwnd . 'com . root, a, 0.0, 2 . 1 . 1 . 2 > .


 reduce in DNS-NET-EQ : run((dnsNetConfig rCtr(1) [5.0e-1, to corporate-dns from masS : Q1, 0]) {0.0 | nil}, 2.0e+2) .
rewrites: 5791 in 5ms cpu (6ms real) (1088533 rewrites/second)
 result Config: run(rCtr(17) {5.9092244468269362e-1, to masS from corporate-dns : response(1, 'www1 . 'internet . 'com . root, < 'www1 . 'internet . 'com . root, a, 0.0, 1 . 1 . 1 . 2 >, nil, nil, 0)}
 {5.9092244468269362e-1 |
 [1.3150917230081489, to public-dns from public-dns : timeout(1 .. init, auth-dns), 0] ;
 [1.3552840814110314, to public-dns from public-dns : timeout(1 .. init ..  qm, auth-dns), 0]}

...., 200.0)


red run({0.0 | nil} dnsNetConfig rCtr(1) [0.5, (to corporate-dns from masS : Q2),0] ,200.0) .
rewrites: 4044 in 2ms cpu (2ms real) (1769028 rewrites/second)
result Config: run(rCtr(6) {5.1500592844616389e-1, to iServer from  public-dns : query(2 .. init, 'www1 . 't1 . 'pwnd . 'com . root, mx)}




