load iodine_dns
load ../../../deps/dns_formalization/Maude/test/nondet-model/test_helpers

mod TEST_IDNS is 
  inc IODINE_DNS + TEST-HELPERS .

  var NAME : Name .
  var F : Fragment .
  var B : Bool .
  
  ops addrWClient addrNScorporate addrWNS addrAlice addrBob mAddr cAddr addrNSexample addrNSpwnd2 : -> Address .

  op Q : Name -> Query .    
  op wQ : Fragment Name -> Query .    
  eq Q(NAME) = query(1, NAME . root, a) .
  eq wQ(F, NAME) = 
    query(1, nm(F) . NAME . root, a) .

  op FR : Bool -> Fragment .
  eq FR(B) = fragment(addrAlice, 1, 1, 100, false, B) .    

  eq maxFragmentLen = 200 .
  
  --- op zoneExampleCom : -> List{Record} .
  --- eq zoneExampleCom =
  --- < 'example . 'com . root, soa, 3600.0, soaData(3600.0) >
  --- < 'example . 'com . root, ns, 3600.0, 'ns . 'example . 'com . root >
  --- < 'ns . 'example . 'com . root, a, 3600.0, addrNSexample >
  --- < 'www0 . 'example . 'com . root, a, 3600.0, 1 . 0 . 1 . 2 >
  --- < 'www1 . 'example . 'com . root, a, 3600.0, 1 . 1 . 1 . 2 >
  --- < wildcard . 'example . 'com . root, txt, 3600.0, nullAddr > .

  --- op zoneCorporateCom : -> List{Record} .
  --- eq zoneCorporateCom =
  --- < 'corporate . 'com . root, soa, 3600.0, soaData(3600.0) >
  --- < 'corporate . 'com . root, ns, 3600.0, 'ns . 'corporate . 'com . root >
  --- < 'ns . 'corporate . 'com . root, a, 3600.0, addrNScorporate >
  --- < 'www . 'corporate . 'com . root, a, 3600.0, 3 . 0 . 1 . 2 >
  --- < wildcard . 'corporate . 'com . root, txt, 3600.0, nullAddr > .


  op zonePwnd2Com : -> List{Record} .
  eq zonePwnd2Com =
  < 'pwnd2 . 'com . root, soa, 3600.0, soaData(3600.0) >
  < 'pwnd2 . 'com . root, ns, 3600.0, 'ns . 'pwnd2 . 'com . root >
  < 'ns . 'pwnd2 . 'com . root, a, 3600.0, addrNSpwnd2 >
  < 'www0 . 'pwnd2 . 'com . root, a, 3600.0, 2 . 0 . 1 . 2 >
  < 'www1 . 'pwnd2 . 'com . root, a, 3600.0, 2 . 1 . 1 . 2 >
  < wildcard . 'pwnd2 . 'com . root, txt, 3600.0, nullAddr > .

  --- Initial configuration
  op initConfig : -> Config .
  eq initConfig =
  --- Start messages
  --- (to cAddr : start)
  --- (to addrWNS from cAddr : Q('www1 . 'pwnd2 . 'com))
  --- (to addrWNS from cAddr : wQ(FR(false), 'pwnd2 . 'com))
  --- Test ACK0. Message to test ACK of last fragment.
  --- Expect a message to Alice to send a new packet down, fragments empty.
   (to addrAlice from addrWNS : response(5, nm(fragment(addrAlice, 7, 2, 100, false, true)) . 'pwnd2 . 'com . 'root, nil, nil, nil, 0))
  --- Test ACK1.
  --- Expect the next fragment to the WNServer, num attempts = 1.
  --- (to addrAlice from addrWNS : response(5, nm(fragment(addrAlice, 7, 2, 100, false, false)) . 'pwnd2 . 'com . 'root, nil, nil, nil, 0))
  --- Monitor
  --- initMonitor(mAddr)
  --- Clients
  --- < cAddr : Client |
  ---   queries: query(1, 'www . 'example . 'com . root, a),
  ---   resolver: addrNSexample,
  ---   notifyDone: nullAddr >
  --- < addrNSexample : Nameserver |
  ---   db: (zoneExampleCom),
  ---   queue: nilQueue,
  ---   forwardonly: nullAddr,
  ---   queriesFwd: nilTAQL >    
  --- < addrNScorporate : Nameserver |
  ---   db: (zoneCorporateCom),
  ---   queue: nilQueue,
  ---   forwardonly: nullAddr,
  ---   queriesFwd: nilTAQL > 
---  < addrWNS : WNameserver |
---    pendingFragments: mtfl,
---    lastFragment: false,
---    conf: (mkRcvApp(addrBob) mkNameServer(addrWNS, zonePwnd2Com))
---    >
---  Test rule handling packet from Alice to Iodine Client.
---  < addrWClient : WClient |
---    resv: addrWNS,
---    wDom: 'pwnd2 . 'com . 'root,
---    queryCtr: 0,
---    seqCtr: 0,
---    ---fragmentCtr: 0,
---    fragments: mtfl,
---    fragmentsSize: 0,
---    currFragment: 3,
---    numAttempts: 1,
---    weirdQType: a,
---    conf: (makeSendApp(addrAlice, addrBob) (to addrWClient from addrAlice : packet(addrAlice, 3, 300, false)))
---  >
  --- Test ACK0: Test rule handling ACK of last Fragment from Iodine server.
  < addrWClient : WClient |
    resv: addrWNS,
    wDom: 'pwnd2 . 'com . 'root,
    queryCtr: 12,
    seqCtr: 7,
    fragments: popFront(makeFragments(packet(addrAlice, 7, 300, false), 200)),
    fragmentsSize: 2,
    currFragment: 2,
    numAttempts: 1,
    weirdQType: a,
    conf: (makeSendApp(addrAlice, addrBob))
  >
  --- Test ACK1.
---  < addrWClient : WClient |
---    resv: addrWNS,
---    wDom: 'pwnd2 . 'com . 'root,
---    queryCtr: 12,
---    seqCtr: 7,
---    fragments: popFront(makeFragments(packet(addrAlice, 7, 500, false), 200)),
---    fragmentsSize: 3,
---    currFragment: 2,
---    numAttempts: 1,
---    weirdQType: a,
---    conf: (makeSendApp(addrAlice, addrBob))
---  >
  .

endm

--- set trace on .
rew[1] initConfig .
