sload scenario1
sload ../../../../maude_hcs/lib/smc/gen-baseline
sload ../../../../maude_hcs/lib/smc/smc_cp3-refactored

mod SCENARIO-BASELINE is
  inc HCS_TEST .
  inc SMC-BASELINE-SHARED .
  inc GEN-BASELINE .
  inc SMC_CP3 .
  
ops sT wS bS : -> Float .
eq sT = 0.0 .
eq wS =  60. .
eq bS = 10. .

**** slimit default is 1hr == 3600.0
*** eq slimit = 300.0 .
eq slimit = 100.0 .

eq hcsDelay = slimit + slimit .  --- prevent hcs to start

op Vpts : -> NetIdList .
eq Vpts = (ixpN :; cl[1]  :; srvN :; masN) . **** :;  cl[2]
op ObsFs : -> FeatureList .
*** ddttt
*** eq ObsFs = (dnsQueryRate :; dnsQuerySize :; tcpUpRate :; tcpOutPktRate :; tcpPktInterarrival ) .


eq ObsFs = 
dnsQueryRate :; dnsQuerySize 
*** :; tcpUpRate :; tcpDownRate :; tcpUpToDownRate 
:; tcpOutPktRate :; tcpInPktRate  :; tcpOutToInPktRate 
*** :; tcpPktSizeStdDev :; tcpPktSize :; tcpPktInterarrival :; tcpDirectionChange :; tcpActiveFlow :; tcpNewCnx
.

*** eq ObsFs = dnsQueryRate :; dnsQuerySize :; dnsRespSize :; tcpUpRate :; tcpDownRate :; tcpUpToDownRate :; tcpOutPktRate :; tcpInPktRate :; tcpOutToInPktRate :; tcpPktSizeStdDev :; tcpPktSize :; tcpPktInterarrival :; tcpDirectionChange :; tcpActiveFlow :; tcpNewCnx .

eq finalize(c:Config) =
  genBaseLine(c:Config,Vpts,ObsFs,sT,slimit,wS,bS,false)  .
endm  

rew initConfig .  
q
eof

in lib/smc
ln -s visibility-plain.maude visibility.maude  
  
slimit 300.
rewrites: 1 074 410 648 in 216 906ms cpu 3.5min
(4 953 326 rewrites/second)

slimit 600.
rewrites: 17 343 992 389 in 1 448 678ms cpu ~ 24min
(11 972 286  rewrites/second)



maude scenario1-baseline > tmp.txt

portBaseline(tmp.txt,scenario1-baseline-actor.maude)  

insert just before endm
  eq baselineAct = <text from tmp.txt >
  that is text between  and not including
     "result Actor:" and "Bye."

