set show advisories off .

sload ../../../../maude_hcs/lib/smc/visibility-plain

mod VISIBILITY-MAP is
  inc VISIBILITY .

**** HCS and shared actors
ops masSrvAddr publicDnsAddr s3SrvAddr
  wtCl1ProxyAddr wtCl2ProxyAddr
  skyCl3SdkasAddr skyCl4SdkasAddr 
  obfsCl5ServerAddr obfsCl6ServerAddr
  iodCl7ServerAddr iodCl8ServerAddr    *****
  masCl9McacAddr  masCl9McasAddr 
  servDnsAddr
  ftpSrvAddr
  gorillaSrvAddr
  ircServerAddr
  wtCl1ClientAddr wtCl2ClientAddr
  corpRtDnsAddr    ****
  skyCl3SdkacAddr  skyCl4SdkacAddr 
  corpSkyDnsAddr    ****
  obfsCl5ClientAddr obfsCl6ClientAddr 
  corpObfsDnsAddr   ****
  corpMasDnsAddr    ****
**** dns fwd net clients  
  corpIodDnsAddr     ****
  iodCl7SrvNetClAddr iodCl8SrvNetClAddr   ****
  servNetClAddr corpRtNetClAddr       ****
  corpSkyNetClAddr corpObfsNetClAddr  ****
  corpIodNetClAddr corpMasNetClAddr   ****
  
: -> Address .

**** tgen addresses, note dnsTgenAddresses are not visible
ops 
****  masTgen<net><ix>McAddr  
masTgenMas1McAddr masTgenMas2McAddr
masTgenMas3McAddr masTgenMas4McAddr
masTgenRt1McAddr  masTgenRt2McAddr
masTgenRt3McAddr  masTgenRt4McAddr
masTgenSky1McAddr masTgenSky2McAddr
masTgenSky3McAddr masTgenSky4McAddr
masTgenObfs1McAddr masTgenObfs2McAddr
masTgenObfs3McAddr masTgenObfs4McAddr
masTgenIod1McAddr masTgenIod2McAddr
masTgenIod3McAddr masTgenIod4McAddr
masTgenSrv1McAddr masTgenSrv2McAddr
masTgenSrv3McAddr masTgenSrv4McAddr

****  minTgen<net><ix>S3ClAddr  
minTgenRt1S3ClAddr  minTgenRt2S3ClAddr 
minTgenRt3S3ClAddr  minTgenRt4S3ClAddr 
minTgenSky1S3ClAddr  minTgenSky2S3ClAddr 
minTgenSky3S3ClAddr  minTgenSky4S3ClAddr 
minTgenObfs1S3ClAddr  minTgenObfs2S3ClAddr 
minTgenObfs3S3ClAddr  minTgenObfs4S3ClAddr 
minTgenIod1S3ClAddr  minTgenIod2S3ClAddr 
minTgenIod3S3ClAddr  minTgenIod4S3ClAddr 
minTgenMas1S3ClAddr  minTgenMas2S3ClAddr 
minTgenMas3S3ClAddr  minTgenMas4S3ClAddr 
minTgenSrv1S3ClAddr  minTgenSrv2S3ClAddr 
minTgenSrv3S3ClAddr  minTgenSrv4S3ClAddr 

**** ftpTgen<net><ix>TgAddr
ftpTgenRt1TgAddr  ftpTgenRt2TgAddr 
ftpTgenRt3TgAddr  ftpTgenRt4TgAddr 
ftpTgenSky1TgAddr  ftpTgenSky2TgAddr 
ftpTgenSky3TgAddr  ftpTgenSky4TgAddr 
ftpTgenObfs1TgAddr  ftpTgenObfs2TgAddr 
ftpTgenObfs3TgAddr  ftpTgenObfs4TgAddr 
ftpTgenIod1TgAddr  ftpTgenIod2TgAddr 
ftpTgenIod3TgAddr  ftpTgenIod4TgAddr 
ftpTgenMas1TgAddr  ftpTgenMas2TgAddr 
ftpTgenMas3TgAddr  ftpTgenMas4TgAddr 

**** gorTgen<net><ix>TgAddr
gorTgenRt1TgAddr  gorTgenRt2TgAddr 
gorTgenRt3TgAddr  gorTgenRt4TgAddr  
gorTgenSky1TgAddr  gorTgenSky2TgAddr 
gorTgenSky3TgAddr  gorTgenSky4TgAddr  
gorTgenObfs1TgAddr  gorTgenObfs2TgAddr 
gorTgenObfs3TgAddr  gorTgenObfs4TgAddr  
gorTgenIod1TgAddr  gorTgenIod2TgAddr 
gorTgenIod3TgAddr  gorTgenIod4TgAddr  
gorTgenMas1TgAddr  gorTgenMas2TgAddr 
gorTgenMas3TgAddr  gorTgenMas4TgAddr  

**** ircTgen<net><ix>TgAddr
ircTgenRt1TgAddr  ircTgenRt2TgAddr 
ircTgenRt3TgAddr  ircTgenRt4TgAddr  
ircTgenSky1TgAddr  ircTgenSky2TgAddr 
ircTgenSky3TgAddr  ircTgenSky4TgAddr  
ircTgenObfs1TgAddr  ircTgenObfs2TgAddr 
ircTgenObfs3TgAddr  ircTgenObfs4TgAddr  
ircTgenIod1TgAddr  ircTgenIod2TgAddr 
ircTgenIod3TgAddr  ircTgenIod4TgAddr  
ircTgenMas1TgAddr  ircTgenMas2TgAddr 
ircTgenMas3TgAddr  ircTgenMas4TgAddr  

: -> Address .



eq visibilityMap =
--- Mastodon server 
  (masN  |-> masSrvAddr), 
--- Dns net    
  (dnsN |-> publicDnsAddr ;; 
            iodCl7SrvNetClAddr ;; iodCl8SrvNetClAddr
             ),  ---- + pwnd fwdr clients
--- s3 server 
  (minN  |-> s3SrvAddr),     
--- server  net
  (srvN |-> 
   (wtCl1ProxyAddr ;; wtCl2ProxyAddr ;;
    skyCl3SdkasAddr ;; skyCl4SdkasAddr ;;
    obfsCl5ServerAddr ;; obfsCl6ServerAddr ;;
    iodCl7ServerAddr ;; iodCl8ServerAddr ;;  
    masCl9McasAddr ;;
    ftpSrvAddr ;;
    gorillaSrvAddr ;;
    ircServerAddr ;;
    masTgenSrv1McAddr ;; masTgenSrv2McAddr ;;
    masTgenSrv3McAddr ;; masTgenSrv3McAddr ;;
    minTgenSrv1S3ClAddr ;; minTgenSrv2S3ClAddr ;;
    minTgenSrv3S3ClAddr ;; minTgenSrv3S3ClAddr ;; 
    servDnsAddr ;; servNetClAddr)  --- + assoc NetFwdCl
   ) ,
  (cl[1] |->
    (wtCl1ClientAddr ;; wtCl2ClientAddr ;;
    masTgenRt1McAddr ;; masTgenRt2McAddr ;;
    masTgenRt3McAddr ;; masTgenRt3McAddr ;;
    minTgenRt1S3ClAddr ;; minTgenRt2S3ClAddr ;;
    minTgenRt3S3ClAddr ;; minTgenRt3S3ClAddr ;;
    ftpTgenRt1TgAddr ;; ftpTgenRt2TgAddr ;;
    ftpTgenRt3TgAddr ;; ftpTgenRt3TgAddr  ;;
    gorTgenRt1TgAddr ;; gorTgenRt2TgAddr ;;
    gorTgenRt3TgAddr ;; gorTgenRt3TgAddr ;; 
    ircTgenRt1TgAddr ;; ircTgenRt2TgAddr ;;
    ircTgenRt3TgAddr ;; ircTgenRt3TgAddr ;; 
    corpRtDnsAddr ;; corpRtNetClAddr) --- + assoc NetFwdCl
    ),
--- Skyhook Client 3,4
  (cl[2] |->
    (skyCl3SdkacAddr  ;; skyCl4SdkacAddr ;;
    masTgenSky1McAddr ;; masTgenSky2McAddr ;;
    masTgenSky3McAddr ;; masTgenSky3McAddr ;;
    minTgenSky1S3ClAddr ;; minTgenSky2S3ClAddr ;;
    minTgenSky3S3ClAddr ;; minTgenSky3S3ClAddr ;; 
    ftpTgenSky1TgAddr ;; ftpTgenSky2TgAddr ;;
    ftpTgenSky3TgAddr ;; ftpTgenSky3TgAddr  ;;
    gorTgenSky1TgAddr ;; gorTgenSky2TgAddr ;;
    gorTgenSky3TgAddr ;; gorTgenSky3TgAddr ;; 
    ircTgenSky1TgAddr ;; ircTgenSky2TgAddr ;;
    ircTgenSky3TgAddr ;; ircTgenSky3TgAddr ;; 
    corpSkyDnsAddr ;; corpSkyNetClAddr) --- + assoc NetFwdCl
    ) ,
--- Obfs Client 5,6
  (cl[3] |->
    (obfsCl5ClientAddr ;; obfsCl6ClientAddr ;;
    masTgenObfs1McAddr ;; masTgenObfs2McAddr ;;
    masTgenObfs3McAddr ;; masTgenObfs3McAddr ;;
    minTgenObfs1S3ClAddr ;; minTgenObfs2S3ClAddr ;;
    minTgenObfs3S3ClAddr ;; minTgenObfs3S3ClAddr ;; 
    ftpTgenObfs1TgAddr ;; ftpTgenObfs2TgAddr ;;
    ftpTgenObfs3TgAddr ;; ftpTgenObfs3TgAddr ;; 
    gorTgenObfs1TgAddr ;; gorTgenObfs2TgAddr ;;
    gorTgenObfs3TgAddr ;; gorTgenObfs3TgAddr ;; 
    ircTgenObfs1TgAddr ;; ircTgenObfs2TgAddr ;;
    ircTgenObfs3TgAddr ;; ircTgenObfs3TgAddr ;; 
    corpObfsDnsAddr ;; corpObfsNetClAddr ) --- + assoc NetFwdCl
    ),
  --- Iodine Client 7,8  
  (cl[4] |-> 
    (masTgenIod1McAddr ;; masTgenIod2McAddr ;;
    masTgenIod3McAddr ;; masTgenIod3McAddr ;;
    minTgenIod1S3ClAddr ;; minTgenIod2S3ClAddr ;;
    minTgenIod3S3ClAddr ;; minTgenIod3S3ClAddr ;; 
    ftpTgenIod1TgAddr ;; ftpTgenIod2TgAddr ;;
    ftpTgenIod3TgAddr ;; ftpTgenIod3TgAddr ;; 
    gorTgenIod1TgAddr ;; gorTgenIod2TgAddr ;;
    gorTgenIod3TgAddr ;; gorTgenIod3TgAddr ;; 
    ircTgenIod1TgAddr ;; ircTgenIod2TgAddr ;;
    ircTgenIod3TgAddr ;; ircTgenIod3TgAddr ;; 
    corpIodDnsAddr ;; corpIodNetClAddr )  --- + assoc NetFwdCl
     ),
  --- Mastodon 9
  (cl[5] |-> 
   ( masCl9McacAddr  ;;
     masTgenMas1McAddr ;; masTgenMas2McAddr ;;
     masTgenMas3McAddr ;; masTgenMas3McAddr ;;
     minTgenMas1S3ClAddr ;; minTgenMas2S3ClAddr ;;
     minTgenMas3S3ClAddr ;; minTgenMas3S3ClAddr ;; 
     ftpTgenMas1TgAddr ;; ftpTgenMas2TgAddr ;;
     ftpTgenMas3TgAddr ;; ftpTgenMas3TgAddr ;; 
     gorTgenMas1TgAddr ;; gorTgenMas2TgAddr ;;
     gorTgenMas3TgAddr ;; gorTgenMas3TgAddr ;; 
     ircTgenMas1TgAddr ;; ircTgenMas2TgAddr ;;
     ircTgenMas3TgAddr ;; ircTgenMas3TgAddr ;; 
     corpMasDnsAddr ;; corpMasNetClAddr) --- + assoc NetFwdCl
    )
.  

endm
eof



