sload ../pwnd_cp3_scenario_1
sload ../../../../../maude_hcs/lib/smc/smc_cp3-refactored


mod PWND-CP3-SCENARIO-1-BASELINE-TCPPKTINTERARRIVAL-CL3 is
  inc HCS_TEST .  
  inc SMC_CP3 . 
  
  ----eq slimit = 100.0 . ---- redefine if needed

  eq Vpts = cl[3] .
  eq ObsFs = tcpPktInterarrival .

  eq hcsDelay = slimit + slimit .  --- prevent hcs from starting

 eq finalize(c:Config) = addK2Blist(c:Config,false) .

endm

rew run({0.0 | nil} initState(counter) [tgenDelay, (to baseLineAddr from baseLineAddr : initBase),0], slimit) .
q