--- MAUDE_HCS: maude_hcs
---
--- Software Markings (UNCLASS)
--- Maude-HCS Software
---
--- Copyright (C) 2025 RTX BBN Technologies Inc. All Rights Reserved
---
--- The computer software and computer software documentation are licensed
--- under the Apache License, Version 2.0 (the "License"); you may not use
--- this file except in compliance with the License. A copy of the License
--- is provided in the LICENSE file, but you may obtain a copy of the
--- License at:  https://www.apache.org/licenses/LICENSE-2.0
---
--- The computer software and computer software documentation are based
--- upon work supported by the Defense Advanced Research Projects Agency (DARPA)
--- under Agreement No. HR00l 12590083.
---
--- This document does not contain technology or technical data controlled under
--- either the U.S. International Traffic in Arms Regulations or the U.S. Export
--- Administration Regulations.
---
--- DISTRIBUTION STATEMENT A: Approved for public release; distribution is
--- unlimited.
---
--- Notice: Markings. Any reproduction of this computer software, computer
--- software documentation, or portions thereof must also reproduce the markings
--- contained herein. Refer to the provided NOTICE file.
---
--- MAUDE_HCS: end


sload ./common/irc_name
sload ./common/_aux
sload ./irc_prob-v2

sload ../common/maude/irc-action-actor-v2.maude
sload ../../deps/dns_formalization/Maude/common/apmaude.maude

mod IRC_PROB_TESTS is
  pr IRC-V2 .
  inc IRC-USER-ACTION-ACTOR-V2 .
  inc SCHEDULER .
  
  ops aliceIrcClientAddr bobIrcClientAddr ircServerAddr  : -> Address .
  ops aliceIrcClient bobIrcClient : -> Actor .
  ops ircMonitorAddr : -> Address .
  ops ircServer  : -> Actor .
  ops ircChannelName : -> IrcChannelName .
  ops aliceMsg bobMsg : -> Msg .

  eq ircChannelName = makeIrcChannelName("bbn") .
  op aliceDML : -> IrcMsgDelayList .
  eq aliceDML =
     imd( 0.000,"#room1",279) :: imd(28.0,"#room1",388) .
  op bobDML : -> IrcMsgDelayList .
  eq bobDML =
     imd( 8.000,"#room1",279) :: imd(48.0,"#room1",388) .

  op aliceIrcClient : -> Actor .
  eq aliceIrcClient = 
     mkIrcClient(aliceIrcClientAddr, ircServerAddr,"a", aliceDML) .

  op bobIrcClient : -> Actor .
  eq bobIrcClient = 
     mkIrcClient(bobIrcClientAddr, ircServerAddr,"b", bobDML) .

  op ircServer : -> Actor .
  eq ircServer = mkIrcServer(ircServerAddr)  .

  op aliceMsg : -> ScheduleMsg .
  eq aliceMsg = 
    [1.0, 
    (to aliceIrcClientAddr from aliceIrcClientAddr : burstDelayTO),
    0]  .
  op bobMsg : -> ScheduleMsg .
  eq bobMsg = 
    [8.0, 
    (to bobIrcClientAddr from bobIrcClientAddr : burstDelayTO),
    0]  .    

  op initState : -> Config .
  eq initState =
    rCtr(0)
    aliceIrcClient
    bobIrcClient
    ircServer
    makeIrcMonitor(ircMonitorAddr)
    [0.20, (to ircServerAddr from aliceIrcClientAddr
            : JoinChannel(makeIrcChannelName("#room1"),
                          aliceIrcClientAddr)), 0]
    [0.3, (to ircServerAddr from bobIrcClientAddr
            : JoinChannel(makeIrcChannelName("#room1"),
                          bobIrcClientAddr)), 0]
   aliceMsg
   bobMsg                          
  .

  op initConfig : -> Config .
  eq initConfig = run({0.0 | nil} initState, 300.0) .
endm
eof

rew rCtr(0) aliceIrcClient {1.0, to aliceIrcClientAddr from aliceIrcClientAddr : ircMsgSendTime} .

 rCtr(2)
< aliceIrcClientAddr : IrcClient | thisAddr: aliceIrcClientAddr,
    raceboatAddr: ircServerAddr, ircName: makeIrcUserName(
    aliceIrcClientAddr), msgSched: imd(2.8e+1, "#room1", 388),
    msgCtr: 1, userId: "a" >
   [0.0, to ircServerAddr from
    aliceIrcClientAddr : PrivMsgReq(makeIrcChannelName("#room1"),
    makeIrcUserName(aliceIrcClientAddr), "a:0:279"), 0]
   [2.8000059284461638e+1, to aliceIrcClientAddr from
    aliceIrcClientAddr : ircMsgSendTime, 0]
    
set print attribute on .
rew  initConfig .
