
--- MAUDE_HCS: maude_hcs
---
--- Software Markings (UNCLASS)
--- Maude-HCS Software
---
--- Copyright (C) 2025 RTX BBN Technologies Inc. All Rights Reserved
---
--- The computer software and computer software documentation are licensed
--- under the Apache License, Version 2.0 (the "License"); you may not use
--- this file except in compliance with the License. A copy of the License
--- is provided in the LICENSE file, but you may obtain a copy of the
--- License at:  https://www.apache.org/licenses/LICENSE-2.0
---
--- The computer software and computer software documentation are based
--- upon work supported by the Defense Advanced Research Projects Agency (DARPA)
--- under Agreement No. HR00l 12590083.
---
--- This document does not contain technology or technical data controlled under
--- either the U.S. International Traffic in Arms Regulations or the U.S. Export
--- Administration Regulations.
---
--- DISTRIBUTION STATEMENT A: Approved for public release; distribution is
--- unlimited.
---
--- Notice: Markings. Any reproduction of this computer software, computer
--- software documentation, or portions thereof must also reproduce the markings
--- contained herein. Refer to the provided NOTICE file.
---
--- MAUDE_HCS: end

sload ./common/irc_name
sload ./common/_aux
sload ./irc_prob

set print attribute on .

mod IRC_PROB_TESTS is
  pr IRC_NAMES .
  pr IRC_NODE .
  pr IRC .

  ops aliceIrcClientAddr bobIrcClientAddr ircServerAddr aliceAddr bobAddr carolynAddr rbAddr : -> Address .
  ops aliceIrcClient bobIrcClient : -> Actor .
  ops ircServer preconfiguredIrcServer : -> Actor .
  ops ircChannelName : -> IrcChannelName .
  ops aliceMsg bobMsg : -> Msg .

  eq ircChannelName = makeIrcChannelName("bbn") .

  op makeAliceIrcClient : -> Config .
  eq makeAliceIrcClient = 
    < aliceIrcClientAddr : IrcClient |
        thisAddr: aliceIrcClientAddr,
        appAddr: aliceAddr,
        raceboatAddr: ircServerAddr,
        ircName: makeIrcUserName(aliceIrcClientAddr),
        aliceAppChatsMap: ((2.0 ~> ("Alice message 0", makeIrcName(makeIrcChannelName("bbn"))))
                          : (3.5 ~> ("Alice message 1", makeIrcName(makeIrcChannelName("bbn"))))
                          : (5.4 ~> ("Alice message 2", makeIrcName(makeIrcChannelName("bbn")))))
    >
  .

  op makeBobIrcClient : -> Config .
  eq makeBobIrcClient = 
    < bobIrcClientAddr : IrcClient |
        thisAddr: bobIrcClientAddr,
        appAddr: bobAddr,
        raceboatAddr: ircServerAddr,
        ircName: makeIrcUserName(bobIrcClientAddr)
    >
  .

  op makeIrcServer : -> Config .
  eq makeIrcServer =
    < ircServerAddr : IrcServer |
        thisAddr: ircServerAddr,
        raceboatAddr: bobIrcClientAddr,
        channelMap: ((makeIrcChannelName("bbn") ~> (makeIrcUserName(aliceIrcClientAddr)))
                      : (makeIrcChannelName("sri") ~> (makeIrcUserName(aliceIrcClientAddr)))),
        clientTimestampMap: (makeIrcUserName(aliceIrcClientAddr) ~> 1.0)
    >
  .

  eq aliceMsg =
    (to aliceIrcClientAddr from aliceAddr : makeAppChat(makeIrcName(ircChannelName), "Alice's message."))
  .

  op initState : -> Config .
  eq initState =
    rCtr(0)
    makeAliceIrcClient
    makeBobIrcClient
    makeIrcServer
    [0.25, (to aliceIrcClientAddr : StartIrc), 0]
    [0.5, (to ircServerAddr from bobIrcClientAddr : JoinChannel(makeIrcChannelName("bbn"), bobIrcClientAddr)), 0]
---    [0.5, (to ircServerAddr from bobIrcClientAddr : PartChannel(makeIrcChannelName("sri"), bobIrcClientAddr)), 0]
---    [0.5, (to ircServerAddr from aliceIrcClientAddr : PartChannel(makeIrcChannelName("bbn"), aliceIrcClientAddr)), 0]
---    [1.0, aliceMsg, 0]
---    [200.0, (to ircServerAddr from ircServerAddr : PingTimeout(aliceIrcClientAddr)), 0]
  .

  op initConfig : -> Config .
  eq initConfig = run({0.0 | nil} initState, limit) .
endm



