sload test
sload /Users/lwest/Documents/pwnd2/maude-hcs/maude_hcs/lib/smc/smc_cp3-refactored


mod HCS_TEST-BASELINE is
  inc TEST .  
  inc SMC_CP3 . 
  
  eq slimit = 100 .
  ----eq slimit = 100.0 . ---- redefine if needed

  eq hcsDelay = slimit + slimit .  --- prevent hcs from starting

 eq finalize(c:Config) = addK2Blist(c:Config,false) .

endm

rew run({0.0 | nil} initState(counter) [tgenDelay, (to baseLineAddr from baseLineAddr : initBase),0], slimit) .
q