eval E[s.rval("getMinLatency(getMonitor(C), 10.0, 910.0)")]; // cumulative latency0 10 910
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 910.0, 25)")]; // cumulative latency25 10 910
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 910.0, 50)")]; // cumulative latency50 10 910
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 910.0, 75)")]; // cumulative latency75 10 910
eval E[s.rval("getMaxLatency(getMonitor(C), 10.0, 910.0)")]; // cumulative latency100 10 910
eval E[s.rval("getGoodput(getMonitor(C), 10.0, 910.0)")]; // cumulative goodput 10 910
eval E[s.rval("getSystemIntegrity(getMonitor(C), getIrcSrv(C), 10.0, 910.0)")]; // cumulative integrity 10 910
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), obfsCl1IrcAddr, 10.0, 910.0)")]; // cumulative integrity 10 910 obfsCl1IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), obfsCl2IrcAddr, 10.0, 910.0)")]; // cumulative integrity 10 910 obfsCl2IrcAddr
eval E[s.rval("getMTBF(getMonitor(C), 16.0, 10.0, 910.0)")]; // cumulative availability 10 910
eval E[s.rval("getCUSUMZt(getAdversary(C), ixpN, dnsQueryRate, 10.0, 910.0, 60.0, 10.0)")]; // cumulative dns_query_rate 10 910 ixpN
eval E[s.rval("getCUSUMZt(getAdversary(C), ixpN, tcpOutPktRate, 10.0, 910.0, 60.0, 10.0)")]; // cumulative tcp_outgoing_packet_rate 10 910 ixpN
eval E[s.rval("getCUSUMZt(getAdversary(C), ixpN, tcpInPktRate, 10.0, 910.0, 60.0, 10.0)")]; // cumulative tcp_incoming_packet_rate 10 910 ixpN
eval E[s.rval("getCUSUMZt(getAdversary(C), ixpN, tcpPktSize, 10.0, 910.0, 60.0, 10.0)")]; // cumulative packet_size_mean 10 910 ixpN
eval E[s.rval("getCUSUMZt(getAdversary(C), ixpN, tcpPktInterarrival, 10.0, 910.0, 60.0, 10.0)")]; // cumulative packet_interarrival_mean 10 910 ixpN