load ../common/_aux
load ../../../../deps/dns_formalization/Maude/src/probabilistic-model/_aux

mod IAUX is
  inc AUX + IODINE_NODE .  

  var CONF CONF1 : Config .
  var msg : Msg .

  op ackTimeout : Fragment -> Content .

  op $delayMsgs : Config Config -> Config .

  --- add delays to messages
  eq delayMsgs(CONF) = $delayMsgs(CONF, null) .
  eq $delayMsgs(null, CONF) = CONF .
  eq $delayMsgs(msg CONF, CONF1) = $delayMsgs(CONF, [delay, msg, drop?] CONF1) .


endm
