--- MAUDE_HCS: maude_hcs
---
--- Software Markings (UNCLASS)
--- PWNDD Software
---
--- Copyright (C) 2025 RTX BBN Technologies Inc. All Rights Reserved
---
--- Contract No: HR00112590083
--- Contractor Name: RTX BBN Technologies Inc.
--- Contractor Address: 10 Moulton Street, Cambridge, Massachusetts 02138
---
--- The U.S. Government's rights to use, modify, reproduce, release, perform,
--- display, or disclose these technical data and software are defined in the
--- Article VII: Data Rights clause of the OTA.
---
--- This document does not contain technology or technical data controlled under
--- either the U.S. International Traffic in Arms Regulations or the U.S. Export
--- Administration Regulations.
---
--- DISTRIBUTION STATEMENT A: Approved for public release; distribution is
--- unlimited.
---
--- Notice: Markings. Any reproduction of this computer software, computer
--- software documentation, or portions thereof must also reproduce the markings
--- contained herein.
---
--- MAUDE_HCS: end
<<<<<<<< HEAD:maude_hcs/lib/dns/maude/probabilistic/test-pings.maude



--- Test the ping functionality. Bob has a huge file to send back (100x bigger). Without pings, Alice will never receive the full file from Bob.
--- Expected behavior: Alice receives 18 packets from Bob, totaling 10k bytes plus overhead. The test is successful if the final received packet on Alice's side has the end-of-packet flag set to true.
--- Run with rew initConfig .
set clear rules off .
set print attribute on .
set show advisories off .
set verbose off .

========


load ../../../mastodon/maude/probabilistic/mastodon
>>>>>>>> a899e3c (Tests: Move end to end test):maude_hcs/lib/app/maude/test/test-e2e.needsfix.maude
load ../../../dns/maude/probabilistic/iodine_dns
load ../../../common/maude/cp2-interfaces
load ../../../common/maude/_aux
load ../../../common/maude/router
<<<<<<<< HEAD:maude_hcs/lib/dns/maude/probabilistic/test-pings.maude
load ../../../app/maude/probabilistic
========
load ../../../common/maude/adversary-observer
load ../probabilistic
>>>>>>>> a899e3c (Tests: Move end to end test):maude_hcs/lib/app/maude/test/test-e2e.needsfix.maude

set print attribute on .
set show advisories off .

mod PING_TEST is
  inc IODINE_DNS .
  inc CP2-COMMON .
  inc ROUTER .
  inc MC-INTERFACE .

<<<<<<<< HEAD:maude_hcs/lib/dns/maude/probabilistic/test-pings.maude
  ops alice bob iodineSendApp iodineRecvApp iodineClient iodineServer : -> Address .
========
  ops alice-raceboat bob-raceboat mastodon-client mastodon-server : -> Address .
  ops alice bob aliceRbClient iodineSendApp iodineRecvApp iodineClient iodineServer bobMasClient : -> Address .
  ops clientContentMgr serverContentMgr clientDestini serverDestini clientUserModel serverUserModel : -> Address .
>>>>>>>> a899e3c (Tests: Move end to end test):maude_hcs/lib/app/maude/test/test-e2e.needsfix.maude
  ops monAddr : -> Address .

eq monitorQueryLog? = true .

op router : -> Address .
op adversary : -> Address .

<<<<<<<< HEAD:maude_hcs/lib/dns/maude/probabilistic/test-pings.maude
eq fileSize = 1000 .
eq packetSize = 530 .
eq maxPacketSize = 530 .
eq packetOverhead = 33 .
eq maxFragmentLen = 200 .
eq maxFragmentTx = 20 .
---eq nsResourceBounds? = false .
eq pacingTimeoutDelay = 0.05 .
eq pacingTimeoutDelayMax = 0.05 .
eq ackTimeoutDelay = 1.0 . 
eq maxMinimiseCount = 0 .
eq pingInterval = 1.0 .
eq initialPingDelay = 0.001 .
eq receiveToPingDelay = 0.000001 .


--- This is needed so the rewrites don't freeze up when Bob receives Alice's file (normally this is handled by the other raceboat components)
vars FILE : ByteSeq .
vars BOB : Address .
vars attrs : AttributeSet .
vars T : Float .

rl [dropOutputFiles]:
    < BOB : RcvApp | attrs >
    {T, (to bob : FILE)}
    =>
    < BOB : RcvApp | attrs >
.

========
>>>>>>>> a899e3c (Tests: Move end to end test):maude_hcs/lib/app/maude/test/test-e2e.needsfix.maude
op zonePwnd2Com : -> List{Record} .
eq zonePwnd2Com =
  < 'pwnd2 . 'com . root, soa, 3600.0, soaData(3600.0) >
  < 'pwnd2 . 'com . root, ns, 3600.0, 'ns . 'pwnd2 . 'com . root >
  < 'ns . 'pwnd2 . 'com . root, a, 3600.0, iodineServer >
  < 'www0 . 'pwnd2 . 'com . root, a, 3600.0, 2 . 0 . 1 . 2 >
  < 'www1 . 'pwnd2 . 'com . root, a, 3600.0, 2 . 1 . 1 . 2 >
  < wildcard . 'pwnd2 . 'com . root, txt, 3600.0, nullAddr > .

  --- Initial configuration.

  op initState : -> Config .
  eq initState = 
    rCtr(0)
<<<<<<<< HEAD:maude_hcs/lib/dns/maude/probabilistic/test-pings.maude

========
    < alice : TxApp |
      destAddr: bob,
      rbUserModelAddr: clientUserModel,
      rbContentMgrAddr: clientContentMgr,
      iodineAddr: iodineSendApp,
      contractCount: 0,
      queue: file(0, 400),
      currentCcFile: nilBytes >
    < bob : RxApp |
      rcvd: emptyFileList,
      rbUserModelAddr: serverUserModel,
      rbContentMgrAddr: serverContentMgr >
>>>>>>>> a899e3c (Tests: Move end to end test):maude_hcs/lib/app/maude/test/test-e2e.needsfix.maude
  < iodineSendApp : SendApp |
      fileDestAddr: iodineRecvApp,
      toAddr: iodineClient,
      queuePopulated: true,
      queue: mtpl,
      numAdmittedPkts: 1,
      iodineReady: true,
      sent: mtpl,
      rcvd: mtpl > 
  < iodineRecvApp : RcvApp | rcvd: mtpl,
      fileDestAddr: bob,
      toAddr: (iodineServer),
      queuePopulated: false,
      queue: (mtpl),
      numAdmittedPkts: 1,
      iodineReady: true,
      sent: mtpl >
  makeWClient(iodineClient, iodineServer, 'pwnd2 . 'com . root, a, 0.0)
  makeWNameServer(iodineServer, 0.0, (zonePwnd2Com))
<<<<<<<< HEAD:maude_hcs/lib/dns/maude/probabilistic/test-pings.maude
  < monAddr : WMonitor |
    querySent: nilQueryTimestamp,
    queryRcvd: nilQueryTimestamp,
    pktSent: nilPacketTimestamp,
    pktRcvd: nilPacketTimestamp >
  mkRouter(router)
    [0.6, (to iodineSendApp : start), 0]
    [0.6, (to iodineRecvApp from bob : file(10000)), 0]
    .

  op LinkType-1 : -> AttributeSet .
  eq LinkType-1 =
    (delayStd: 0.),
    (delayType: "Constant"),
    (delayMean: 0.),
    (delayConst: 0.005),
    (noiseMin: 0.),
    (noiseMax: 0.00001),
    (dropP: 0.),
    (canDrop: false)
    .

========
    < mastodon-client : MasClient |
      thisAddr: mastodon-client,
      masServerAddr: mastodon-server,
      requesterAddr: alice-raceboat,
      opStack: emptyOpStack,
      postingMedia: emptyMediaFileList,
      postingMediaIds: emptyMasIdList,
      postingText: "",
      gettingMediaUrls: emptyUrlList,
      gettingMedias: emptyMediaFileList,
      gettingPosts: emptyMasIdList
    >
    < bobMasClient : MasClient |
      thisAddr: bobMasClient,
      masServerAddr: mastodon-server,
      opStack: emptyOpStack,
      postingMedia: emptyMediaFileList,
      postingMediaIds: emptyMasIdList,
      postingText: "",
      gettingMediaUrls: emptyUrlList,
      gettingMedias: emptyMediaFileList,
      gettingPosts: emptyMasIdList
    >
    < mastodon-server : MasServer |
      thisAddr: mastodon-server,
      currentMapId: 3, ---0,
      tootMap: (3 ~> makeToot("This is the #media toot with media", makeUrl(makeMediaFile("img0.jpg", 1000)) ; makeUrl(makeMediaFile("img2.jpg", 1000)), (1 : 2))), --- emptyIdTootMap,
      mediaMap: ((1 ~>(makeMediaFile("img0.jpg", 1000), makeUrl(makeMediaFile("img0.jpg", 1000)))) : 
                 (2 ~>(makeMediaFile("img1.jpg", 1000), makeUrl(makeMediaFile("img1.jpg", 1000)))) :
                 (3 ~>(makeMediaFile("img2.jpg", 1000), makeUrl(makeMediaFile("img2.jpg", 1000))))), --- emptyIdMediaMap, 
      tagMap: (makeTag("media") ~> 3) --- emptyTagPostIdsMap
    >
    makeRbClient(clientUserModel, clientContentMgr, clientDestini, mastodon-client)
    makeRbServer(serverUserModel, serverContentMgr, serverDestini, bobMasClient, bob)
    < monAddr : WMonitor |
      querySent: nilQueryTimestamp,
      queryRcvd: nilQueryTimestamp,
      pktSent: nilPacketTimestamp,
      pktRcvd: nilPacketTimestamp >
    mkRouter(router)
    mkAdversary(adversary,ObsS,ObsR)
---    (to mastodon-client from alice-raceboat : PostStatus("This is the toot"))
---    (to mastodon-client from alice-raceboat : PostStatus("This is the #tag toot"))
---    (to mastodon-client from alice-raceboat : PostMedia(makeMediaFile("cat.jpg", 1000)))
---    (to mastodon-client from alice-raceboat : PostStatus("This is the #media toot with media", (makeMediaFile("img0.jpg", 1000) :: makeMediaFile("img1.jpg", 1000))))
---    (to mastodon-client from alice-raceboat : GetPost(3))
---    (to mastodon-client from alice-raceboat : GetMedia(makeUrl(makeMediaFile("img1.jpg", 1000))))
---    (to mastodon-client from alice-raceboat : GetTimeline)
---    [1.0, (to mastodon-client from alice-raceboat : GetMediaHashtag(makeTag("media"))), 0]
      [0.5, (to alice : start), 0]
---      [1.0, (to mastodon-client from alice-raceboat  : tootQ(bHashTag(0), noBytes)), 0]
    .

>>>>>>>> a899e3c (Tests: Move end to end test):maude_hcs/lib/app/maude/test/test-e2e.needsfix.maude
    op initConfig : -> Config .
    --- redefine limit to be 50s, so that pings don't go forever
    eq limit = 50.0 .
    eq initConfig = run({0.0 | nil} initState, limit) .
endm
<<<<<<<< HEAD:maude_hcs/lib/dns/maude/probabilistic/test-pings.maude
red initConfig .
========

eof

>>>>>>>> a899e3c (Tests: Move end to end test):maude_hcs/lib/app/maude/test/test-e2e.needsfix.maude
