--- MAUDE_HCS: maude_hcs
---
--- Software Markings (UNCLASS)
--- PWNDD Software
---
--- Copyright (C) 2025 RTX BBN Technologies Inc. All Rights Reserved
---
--- Contract No: HR00112590083
--- Contractor Name: RTX BBN Technologies Inc.
--- Contractor Address: 10 Moulton Street, Cambridge, Massachusetts 02138
---
--- The U.S. Government's rights to use, modify, reproduce, release, perform,
--- display, or disclose these technical data and software are defined in the
--- Article VII: Data Rights clause of the OTA.
---
--- This document does not contain technology or technical data controlled under
--- either the U.S. International Traffic in Arms Regulations or the U.S. Export
--- Administration Regulations.
---
--- DISTRIBUTION STATEMENT A: Approved for public release; distribution is
--- unlimited.
---
--- Notice: Markings. Any reproduction of this computer software, computer
--- software documentation, or portions thereof must also reproduce the markings
--- contained herein.
---
--- MAUDE_HCS: end



--- Test the ping functionality. Bob has a huge file to send back (100x bigger). Without pings, Alice will never receive the full file from Bob.
--- Expected behavior: Alice receives 18 packets from Bob, totaling 10k bytes plus overhead. The test is successful if the final received packet on Alice's side has the end-of-packet flag set to true.
--- Run with rew initConfig .
set clear rules off .
set print attribute on .
set show advisories off .
set verbose off .

load ../../../dns/maude/probabilistic/iodine_dns
load ../../../common/maude/cp2-interfaces
load ../../../common/maude/_aux
load ../../../common/maude/router
load ../../../app/maude/probabilistic


mod PING_TEST is
  inc IODINE_DNS .
  inc CP2-COMMON .
  inc ROUTER .
  inc MC-INTERFACE .

  ops alice bob iodineSendApp iodineRecvApp iodineClient iodineServer : -> Address .
  ops monAddr : -> Address .

eq monitorQueryLog? = true .

op router : -> Address .
op adversary : -> Address .

eq fileSize = 1000 .
eq packetSize = 530 .
eq maxPacketSize = 530 .
eq packetOverhead = 33 .
eq maxFragmentLen = 200 .
eq maxFragmentTx = 20 .
---eq nsResourceBounds? = false .
eq pacingTimeoutDelay = 0.05 .
eq pacingTimeoutDelayMax = 0.05 .
eq ackTimeoutDelay = 1.0 . 
eq maxMinimiseCount = 0 .


--- This is needed so the rewrites don't freeze up when Bob receives Alice's file (normally this is handled by the other raceboat components)
vars FILE : ByteSeq .
vars BOB : Address .
vars attrs : AttributeSet .
vars T : Float .

rl [dropOutputFiles]:
    < BOB : RcvApp | attrs >
    {T, (to bob : FILE)}
    =>
    < BOB : RcvApp | attrs >
.

op zonePwnd2Com : -> List{Record} .
eq zonePwnd2Com =
  < 'pwnd2 . 'com . root, soa, 3600.0, soaData(3600.0) >
  < 'pwnd2 . 'com . root, ns, 3600.0, 'ns . 'pwnd2 . 'com . root >
  < 'ns . 'pwnd2 . 'com . root, a, 3600.0, iodineServer >
  < 'www0 . 'pwnd2 . 'com . root, a, 3600.0, 2 . 0 . 1 . 2 >
  < 'www1 . 'pwnd2 . 'com . root, a, 3600.0, 2 . 1 . 1 . 2 >
  < wildcard . 'pwnd2 . 'com . root, txt, 3600.0, nullAddr > .

  --- Initial configuration.

  op initState : -> Config .
  eq initState = 
    rCtr(0)

  < iodineSendApp : SendApp |
      fileDestAddr: iodineRecvApp,
      toAddr: iodineClient,
      queuePopulated: true,
      queue: mtpl,
      numAdmittedPkts: 1,
      iodineReady: true,
      sent: mtpl,
      rcvd: mtpl > 
  < iodineRecvApp : RcvApp | rcvd: mtpl,
      fileDestAddr: bob,
      fileSrcAddr: iodineSendApp,
      toAddr: (iodineServer),
      queuePopulated: true,
      queue: (mtpl),
      numAdmittedPkts: 1,
      iodineReady: true,
      sent: mtpl >
  makeWClient(iodineClient, iodineServer, 'pwnd2 . 'com . root, a, 0.0)
  makeWNameServer(iodineServer, 0.0, (zonePwnd2Com))
  < monAddr : WMonitor |
    querySent: nilQueryTimestamp,
    queryRcvd: nilQueryTimestamp,
    pktSent: nilPacketTimestamp,
    pktRcvd: nilPacketTimestamp >
  mkRouter(router)
    [0.6, (to iodineSendApp : start), 0]
    [0.6, (to iodineRecvApp from bob : file(10000)), 0]
    .

  op LinkType-1 : -> AttributeSet .
  eq LinkType-1 =
    (delayStd: 0.),
    (delayType: "Constant"),
    (delayMean: 0.),
    (delayConst: 0.005),
    (noiseMin: 0.),
    (noiseMax: 0.00001),
    (dropP: 0.),
    (canDrop: false)
    .

    op initConfig : -> Config .
    --- redefine limit to be 50s, so that pings don't go forever
    eq limit = 50.0 .
    eq initConfig = run({0.0 | nil} initState, limit) .
endm
red initConfig .
