import pytest
import os
import sys
from pathlib import Path
from maude_hcs.lib.common.markovJsonToMaudeParser import JsonToMaudeParser, calculate_relative_load_path


# ==========================================
# Helpers
# ==========================================
JSON_STRING = """{
    "markov": {
        "single":      {"wait_single": 1.0},
        "batch":       {"wait_batch": 1.0},
        "wait_single": {"single": 0.5,"batch": 0.5},
        "wait_batch":  {"single": 0.5,"batch": 0.5}
    },
    "actions": {
        "single": {
            "type": "resolve_a"
        },
        "batch": {
            "type": "resolve_a_batch",
            "num_to_resolve": {"random": "uniform","min": 2,"max": 4}
        },
        "wait_single": {
            "type": "wait",
            "sleep": {"random": "gaussian","mean": 0.5,"std": 0.3,"floor": 0.1},
            "start": true
        },
        "wait_batch": {
            "type": "wait",
            "sleep": {"random": "gaussian","mean": 3.0,"std": 1.0,"floor": 0.1}
        }
    },
    "parameters": {
        "model_steps": 1000,
        "domains_file": "testDomains.csv",
        "request_timeout": 5,
        "request_lifetime": 10
    }
}
"""
EXPECTED_MAUDE_STRING ="""--- MAUDE_HCS: this file is autogenerated by maude_hcs ---

load ../../../common/maude/markov-action-model.maude

fmod DNS-MAMODEL is
  inc  MARKOV-ACTION-MODEL .

op dns-markov : ->  Map{String,Map{String,Float}} .
op dns-actions : -> Map{String,JV} .
op dns-params : -> Map{String,JV} .

op dns-ma : -> MAModel .  --- markov-action
eq dns-ma =
   ma("dns",dns-markov,dns-actions,dns-params) .

eq dns-markov =  
    ( "single" |-> (("wait_single" |-> 1.0)) ) ,

    ( "batch" |-> (("wait_batch" |-> 1.0)) ) ,

    ( "wait_single" |-> (("single" |-> 0.5) , ("batch" |-> 0.5)) ) ,

    ( "wait_batch" |-> (("single" |-> 0.5) , ("batch" |-> 0.5)) ) 
  .                   

eq dns-actions = (
    ("single" |->  jo((("type" |-> js("resolve_a"))))),
    ("batch" |->  jo((("type" |-> js("resolve_a_batch")), ("num_to_resolve" |-> jo((("random" |-> js("uniform")), ("min" |-> jn(2)), ("max" |-> jn(4)))))))),
    ("wait_single" |->  jo((("type" |-> js("wait")), ("sleep" |-> jo((("random" |-> js("gaussian")), ("mean" |-> jf(0.5)), ("std" |-> jf(0.3)), ("floor" |-> jf(0.1))))), ("start" |-> jb(true))))),
    ("wait_batch" |->  jo((("type" |-> js("wait")), ("sleep" |-> jo((("random" |-> js("gaussian")), ("mean" |-> jf(3.0)), ("std" |-> jf(1.0)), ("floor" |-> jf(0.1))))))))
    ) 
 .

eq dns-params = (
        ("model_steps" |->  jn(1000)),
        ("domains_file" |->  js("testDomains.csv")),
        ("request_timeout" |->  jn(5)),
        ("request_lifetime" |->  jn(10))
        ) .

endfm 
  
eof  
"""

FILENAME = 'tmp_markov_model.maude'
TOPLEVELDIR = Path(os.path.dirname(__file__))
EXAMPLE_FILE_PATH = TOPLEVELDIR.joinpath(FILENAME)

def tokenize(text):
    """
    Simple tokenizer to enable comparison ignoring whitespace/formatting quirks.
    Splits on whitespace and captures basic tokens.
    """
    # Replace parentheses and commas with spaced versions to split easily
    text = text.replace("(", " ( ").replace(")", " ) ").replace(",", " , ")
    # Split by whitespace
    tokens = text.split()
    return tokens


def find_mismatch(gen_tokens, exp_tokens, context=5):
    """
    Finds the first mismatch between token lists and returns a descriptive error string.
    """
    limit = min(len(gen_tokens), len(exp_tokens))
    for i in range(limit):
        if gen_tokens[i] != exp_tokens[i]:
            start = max(0, i - context)
            end = min(limit, i + context)
            gen_snippet = " ".join(gen_tokens[start:end])
            exp_snippet = " ".join(exp_tokens[start:end])
            return (
                f"Mismatch at token index {i}:\n"
                f"  Expected token: '{exp_tokens[i]}'\n"
                f"  Actual token:   '{gen_tokens[i]}'\n\n"
                f"  Context (Expected): ...{exp_snippet}...\n"
                f"  Context (Actual):   ...{gen_snippet}..."
            )

    if len(gen_tokens) != len(exp_tokens):
        return f"Token count mismatch: Generated={len(gen_tokens)}, Expected={len(exp_tokens)}"

    return None


# ==========================================
# Tests
# ==========================================

def test_json_to_maude_generation():
    json_content = JSON_STRING
    expected_maude = EXPECTED_MAUDE_STRING

    # Generate Output
    parser = JsonToMaudeParser(model_name="dns", stem="dns", load_path="../../../common/maude/markov-action-model.maude")
    generated_maude = parser.generate(json_content)

    with open(EXAMPLE_FILE_PATH, 'w', encoding='utf-8') as f:
        f.write(generated_maude)

    # Tokenize both
    gen_tokens = tokenize(generated_maude)
    exp_tokens = tokenize(expected_maude)

    # Assert and provide detailed feedback on failure
    mismatch_error = find_mismatch(gen_tokens, exp_tokens)

    assert mismatch_error is None, f"Generated Maude code does not match expected output.\n{mismatch_error}"

def test_relative_path_calc():
    load_path="lib/common/maude/markov-action-model.maude"
    output_path = "/Users/jkhoury/Documents/Research/BBN/weirdnets/code/maude-hcs-fresh/maude_hcs/lib/mastodon/maude/probabilistic/file.maude"
    rel = calculate_relative_load_path(output_path, load_path)
    assert rel == "../../../common/maude/markov-action-model.maude", f"{rel} is incorrect"

    output_path = "/Users/jkhoury/Documents/Research/BBN/weirdnets/code/maude-hcs-fresh/maude_hcs/lib/mastodon/maude/probabilistic/onemore/file.maude"
    rel = calculate_relative_load_path(output_path, load_path)
    assert rel == "../../../../common/maude/markov-action-model.maude", f"{rel} is incorrect"