set show advisories off .

  sload ../../../deps/dns_formalization/Maude/common/actor.maude
****  sload ../../../deps/dns_formalization/Maude/common/apmaude.maude
  sload ../../../deps/dns_formalization/Maude/dns/probabilistic-model/parameters.maude
  
mod CP2-SCENARIO-SHARED is
  inc ACTOR-MODEL .
  inc PARAMETERS .


**** addresses
ops alice bob  : -> Address .
ops sendApp rcvApp iClient iServer : -> Address .  --- WDNS
ops cmRBC edRBC umRBC mcRBC : -> Address . --- RB client
ops cmRBS edRBS umRBS mcRBS : -> Address . --- RB server
ops masS wmon router adversary : -> Address .
ops corporate-dns public-dns : -> Address .  --- DNS interface




 --- Link Characteristic definitions
op LinkType-0 : -> AttributeSet .
eq LinkType-0 = 
  (delayStd: 0.),
  (delayType: "Constant"),
  (delayMean: 0.),
  (delayConst: 0.01),
  (noiseMin: 0.),
  (noiseMax: 0.00001),
  (dropP: 0.),
  (canDrop: false)
  .

op LinkType-1 : -> AttributeSet .
eq LinkType-1 = 
  (delayStd: 0.01334),
  (delayType: "Normal"),
  (delayMean: 0.025),
  (delayConst: 0.),
  (noiseMin: 0.),
  (noiseMax: 0.),
  (dropP: 0.),
  (canDrop: false)
  .

op LinkType-2 : -> AttributeSet .
eq LinkType-2 = 
  (delayStd: 0.),
  (delayType: "Constant"),
  (delayMean: 0.),
  (delayConst: 0.015),
  (noiseMin: 0.),
  (noiseMax: 0.00001),
  (dropP: 0.),
  (canDrop: false)
  .

**** Global parameters?

endm

