--- MAUDE_HCS: maude_hcs
---
--- Software Markings (UNCLASS)
--- Maude-HCS Software
---
--- Copyright (C) 2025 RTX BBN Technologies Inc. All Rights Reserved
---
--- The computer software and computer software documentation are licensed
--- under the Apache License, Version 2.0 (the "License"); you may not use
--- this file except in compliance with the License. A copy of the License
--- is provided in the LICENSE file, but you may obtain a copy of the
--- License at:  https://www.apache.org/licenses/LICENSE-2.0
---
--- The computer software and computer software documentation are based
--- upon work supported by the Defense Advanced Research Projects Agency (DARPA)
--- under Agreement No. HR00l 12590083.
---
--- This document does not contain technology or technical data controlled under
--- either the U.S. International Traffic in Arms Regulations or the U.S. Export
--- Administration Regulations.
---
--- DISTRIBUTION STATEMENT A: Approved for public release; distribution is
--- unlimited.
---
--- Notice: Markings. Any reproduction of this computer software, computer
--- software documentation, or portions thereof must also reproduce the markings
--- contained herein. Refer to the provided NOTICE file.
---
--- MAUDE_HCS: end

sload _aux
sload _mas_aux

mod MASTODON_TEST is
  inc MASTODON_NODE .
  inc MASAUX .

  ops masClTestAttrs masServerTestAttrs : -> AttributeSet .
  ops masClTestAttrsMsg masServerTestAttrsMsg: -> AttributeSetMsgs .
  ops TEST-HTTP-REQUEST : -> HttpRequest .
  ops TEST-TO-ADDR TEST-FROM-ADDR TEST-REQ-ADDR : -> Address .
  ops TEST-SIZE : -> Nat .
endm

---set trace on .

*** Check the behavior of the Op stack.
red peekOp(masClTestAttrs, opStack: POST-MEDIA-OP) == POST-MEDIA-OP .
red peekOp(masClTestAttrs, opStack: emptyOpStack) == nilOp .

*** Check the behavior of tables and utils.
red getMediaUrl(((46 ~> (makeMediaFile("img1.jpg",  TEST-SIZE), "url1.com")) : (88 ~> (makeMediaFile("img0.jpg",  TEST-SIZE), "url0.com"))), 88) == "url0.com" .
red getMediaAtUrl(((46 ~> (makeMediaFile("img1.jpg",  TEST-SIZE), "url1.com")) : (88 ~> (makeMediaFile("img0.jpg",  TEST-SIZE), "url0.com"))), "url0.com") == makeMediaFile("img0.jpg",  TEST-SIZE) .
red getMediaAtUrl(((46 ~> (makeMediaFile("img1.jpg",  TEST-SIZE), "url1.com")) : (88 ~> (makeMediaFile("img0.jpg",  TEST-SIZE), "url0.com"))), "url1.com") == makeMediaFile("img1.jpg",  TEST-SIZE) .
red getMediaAtUrlList(((46 ~> (makeMediaFile("img1.jpg",  TEST-SIZE), "url1.com")) : (88 ~> (makeMediaFile("img0.jpg",  TEST-SIZE), "url0.com"))), ("url1.com" ; "url0.com"))
  == (makeMediaFile("img1.jpg",  TEST-SIZE) :: makeMediaFile("img0.jpg",  TEST-SIZE))
  .

red getUrlList(((88 ~> (makeMediaFile("img0.jpg", TEST-SIZE), "url0.com")) : (66 ~> (makeMediaFile("img1.jpg", TEST-SIZE), "url1.com")) : (46 ~> (makeMediaFile("img2.jpg", TEST-SIZE), "url2.com"))), (88 : 46))
  == ("url0.com" ; "url2.com")
  .

red getUrlList((masServerTestAttrs,
                  mediaMap: ((88 ~> (makeMediaFile("img0.jpg", TEST-SIZE), "url0.com")) : (66 ~> (makeMediaFile("img1.jpg", TEST-SIZE), "url1.com")) : (46 ~> (makeMediaFile("img2.jpg", TEST-SIZE), "url2.com")))), (88 : 46)) 
  == ("url0.com" ; "url2.com")
  .

red getThisAddr(masServerTestAttrs,
                  thisAddr: TEST-TO-ADDR,
                  currentMapId: 10,
                  tootMap: emptyIdTootMap,
                  mediaMap: ((88 ~> (makeMediaFile("img0.jpg", TEST-SIZE), "url0.com")) : (46 ~> (makeMediaFile("img1.jpg", TEST-SIZE), "url1.com"))))
  == TEST-TO-ADDR
  .

red getSrcAddr((to TEST-TO-ADDR from TEST-FROM-ADDR : makeHttpRequest(postRequest, makeMediaFile("img0.jpg", TEST-SIZE)))) 
  == TEST-FROM-ADDR
  .

red getSrcAddr(makeHttpMsg(makeHttpRequest(postRequest, makeMediaFile("img0.jpg", TEST-SIZE)), TEST-TO-ADDR, TEST-FROM-ADDR)) 
  == TEST-FROM-ADDR
  .

red insertTag(emptyTagPostIdsMap, makeTag("Hashtag"), 20) == (makeTag("Hashtag") ~> 20) .
red insertTag((makeTag("Hashtag") ~> 20), makeTag("Hashtag"), 30) == (makeTag("Hashtag") ~> (20 : 30)) .

red getPostsAtHashtag((makeTag("Hashtag") ~> (20 : 30)), makeTag("Hashtag")) == (20 : 30) .
red getPostsAtHashtags(((makeTag("Hashtag") ~> (20 : 30)) : (makeTag("Tag") ~> 40) : (makeTag("Hash") ~> 50)), makeTag("Hashtag") ;; makeTag("Hash"))
  == (20 : 30 : 50)
  .

*** Check the behavior of the responses.
red getHttpRequest((to TEST-TO-ADDR from TEST-FROM-ADDR : TEST-HTTP-REQUEST)) == TEST-HTTP-REQUEST .

red makeHttpMsg(makeHttpResponse("OK", makeResponseToot(11)), TEST-TO-ADDR, TEST-FROM-ADDR)
  == (to TEST-TO-ADDR from TEST-FROM-ADDR : makeHttpResponse("OK", makeResponseToot(11)))
  .

red insertToot((masClTestAttrs, currentMapId: 10, tootMap: emptyIdTootMap), makeToot("This is the toot"))
  == (masClTestAttrs, currentMapId: 11, tootMap: (11 ~> makeToot("This is the toot")))
  .

red insertToot((masClTestAttrs, currentMapId: 10, tootMap: emptyIdTootMap, tagMap: emptyTagPostIdsMap), makeToot("This is the toot with #tag hashtag."))
  == (masClTestAttrs, currentMapId: 11, tootMap: (11 ~> makeToot("This is the toot with #tag hashtag.")), tagMap: (makeTag("tag") ~> 11))
  .

*** Clean upload of file media.
red uploadNewMedia((masClTestAttrs,
                      thisAddr: TEST-FROM-ADDR,
                      masServerAddr: TEST-TO-ADDR,
                      opStack: emptyOpStack),
                    makeMediaFile("img0.jpg", TEST-SIZE))
  == { (masClTestAttrs,
          thisAddr: TEST-FROM-ADDR,
          masServerAddr: TEST-TO-ADDR,
          opStack: POST-MEDIA-OP), 
       (to TEST-TO-ADDR from TEST-FROM-ADDR : makeHttpRequest(postRequest, makeMediaFile("img0.jpg", TEST-SIZE))) }
  .

*** Test a media post reply (no other context).
red handleReply(makeHttpResponse("OK", makeResponseToot(445)),
                (masClTestAttrs,
                opStack: (POST-MEDIA-OP : emptyOpStack),
                postingMedia: emptyMediaFileList,
                postingMediaIds: emptyMasIdList))
  == { (masClTestAttrs,
          opStack: emptyOpStack,
          postingMedia: emptyMediaFileList,
          postingMediaIds: 445),
       nullMsg }
  .

*** Clean upload of status.
red uploadNewStatus((masClTestAttrs, thisAddr: TEST-FROM-ADDR, masServerAddr: TEST-TO-ADDR, opStack: emptyOpStack), "This is a new toot", emptyMasIdList)
  == { (masClTestAttrs, thisAddr: TEST-FROM-ADDR, masServerAddr: TEST-TO-ADDR, opStack: POST-STATUS-OP),
       (to TEST-TO-ADDR from TEST-FROM-ADDR : makeHttpRequest(postRequest, "This is a new toot")) }
  .
*** Clean upload of status with media Ids.
red uploadNewStatus((masClTestAttrs, thisAddr: TEST-FROM-ADDR, masServerAddr: TEST-TO-ADDR, opStack: emptyOpStack), "This is a new toot", (45 : 98))
  == { (masClTestAttrs, thisAddr: TEST-FROM-ADDR, masServerAddr: TEST-TO-ADDR, opStack: POST-STATUS-OP),
       (to TEST-TO-ADDR from TEST-FROM-ADDR : makeHttpRequest(postRequest, "This is a new toot", (45 : 98))) }
  .

*** Test a clean status post reply (no other context).
red handleReply(makeHttpResponse("OK", makeResponseToot(445)), (masClTestAttrs, postingMediaIds: (45 : 98), opStack: (POST-STATUS-OP : emptyOpStack)))
  == { (masClTestAttrs, postingMediaIds: emptyMasIdList, opStack: emptyOpStack),
       nullMsg }
  .

*** Test a status with media post.
red uploadNewStatusWImages((masClTestAttrs,
                              thisAddr: TEST-FROM-ADDR,
                              masServerAddr: TEST-TO-ADDR,
                              opStack: emptyOpStack,
                              postingText: "",
                              postingMedia: emptyMediaFileList),
                            "This is a new toot with image attachments", makeMediaFile("img0.jpg", TEST-SIZE))
  == { (masClTestAttrs,
          thisAddr: TEST-FROM-ADDR,
          masServerAddr: TEST-TO-ADDR,
          opStack: (POST-MEDIA-OP : POST-STATUS-W-MEDIA-OP),
          postingText: "This is a new toot with image attachments",
          postingMedia: emptyMediaFileList),
       (to TEST-TO-ADDR from TEST-FROM-ADDR : makeHttpRequest(postRequest, makeMediaFile("img0.jpg", TEST-SIZE))) }
  .

*** Test a media post reply in the context of a status upload with media attachments when there is no media left to upload.
red handleReply(makeHttpResponse("OK", makeResponseToot(445)),
                (masClTestAttrs,
                  thisAddr: TEST-FROM-ADDR,
                  masServerAddr: TEST-TO-ADDR,
                  opStack: (POST-MEDIA-OP : POST-STATUS-W-MEDIA-OP),
                  postingMedia: emptyMediaFileList,
                  postingMediaIds: emptyMasIdList,
                  postingText: "Toot with media"))
  == { (masClTestAttrs,
          thisAddr: TEST-FROM-ADDR,
          masServerAddr: TEST-TO-ADDR,
          opStack: (POST-STATUS-OP : POST-STATUS-W-MEDIA-OP),
          postingMedia: emptyMediaFileList,
          postingMediaIds: 445,
          postingText: "Toot with media"),
       (to TEST-TO-ADDR from TEST-FROM-ADDR : makeHttpRequest(postRequest, "Toot with media", 445)) }
  .

*** Test a media post reply in the context of a status upload with media attachments when there is one media left to upload.
red handleReply(makeHttpResponse("OK", makeResponseToot(445)),
                  (masClTestAttrs,
                    thisAddr: TEST-FROM-ADDR,
                    masServerAddr: TEST-TO-ADDR,
                    opStack: (POST-MEDIA-OP : POST-STATUS-W-MEDIA-OP),
                    postingMedia: makeMediaFile("img1.jpg", TEST-SIZE),
                    postingMediaIds: emptyMasIdList))
  == { (masClTestAttrs,
          thisAddr: TEST-FROM-ADDR,
          masServerAddr: TEST-TO-ADDR,
          opStack: (POST-MEDIA-OP : POST-STATUS-W-MEDIA-OP),
          postingMedia: emptyMediaFileList,
          postingMediaIds: 445),
       (to TEST-TO-ADDR from TEST-FROM-ADDR : makeHttpRequest(postRequest, makeMediaFile("img1.jpg", TEST-SIZE))) }
  .

*** Get a post by Id.
red downloadPost((masClTestAttrs, thisAddr: TEST-FROM-ADDR, masServerAddr: TEST-TO-ADDR, opStack: emptyOpStack), 8)
  == { (masClTestAttrs, thisAddr: TEST-FROM-ADDR, masServerAddr: TEST-TO-ADDR, opStack: GET-STATUS-OP),
       (to TEST-TO-ADDR from TEST-FROM-ADDR : makeHttpRequest(getRequest, 8)) }
  .


*** Get a media at a given URL.
red downloadMediaAtUrl((masClTestAttrs, thisAddr: TEST-FROM-ADDR, masServerAddr: TEST-TO-ADDR, opStack: emptyOpStack), "www.media_location.com")
  == { (masClTestAttrs, thisAddr: TEST-FROM-ADDR, masServerAddr: TEST-TO-ADDR, opStack: GET-MEDIA-URL-OP),
       (to TEST-TO-ADDR from TEST-FROM-ADDR : makeHttpRequest(getRequest, "www.media_location.com")) }
  .

*** Get all media from a post Id.
red downloadMediaAtPost((masClTestAttrs, thisAddr: TEST-FROM-ADDR, masServerAddr: TEST-TO-ADDR, opStack: emptyOpStack), 446)
  == { (masClTestAttrs, thisAddr: TEST-FROM-ADDR, masServerAddr: TEST-TO-ADDR, opStack: GET-MEDIA-POST-OP),
       (to TEST-TO-ADDR from TEST-FROM-ADDR : makeHttpRequest(getRequest, 446)) }
  .

*** Get all media from a hashtag search.
red downloadMediaAtHashtag((masClTestAttrs, thisAddr: TEST-FROM-ADDR, masServerAddr: TEST-TO-ADDR, opStack: emptyOpStack, gettingMediaUrls: "url0", gettingTag: nilTag), makeTag("cat"))
  == { (masClTestAttrs, thisAddr: TEST-FROM-ADDR, masServerAddr: TEST-TO-ADDR, opStack: (GET-STATUS-OP : GET-MEDIA-HASHTAG-OP), gettingMediaUrls: emptyUrlList, gettingTag: makeTag("cat")),
       (to TEST-TO-ADDR from TEST-FROM-ADDR : makeHttpRequest(getRequest, makeTag("cat"))) }
  .

*** Test a status get reply in the context of an all-media download via hashtag search.
red handleReply(makeHttpResponse("OK", makeResponseToot(88, "Post 88 text", ("url0.com" ; "url1.com" ; "url2.com"), (80 : 81 : 82))),
                (masClTestAttrs, thisAddr: TEST-FROM-ADDR, masServerAddr: TEST-TO-ADDR, opStack: (GET-STATUS-OP : GET-MEDIA-HASHTAG-OP), gettingMediaUrls: emptyUrlList))
  == { (masClTestAttrs, thisAddr: TEST-FROM-ADDR, masServerAddr: TEST-TO-ADDR, opStack: (GET-MEDIA-URL-OP : GET-MEDIA-HASHTAG-OP), gettingMediaUrls: ("url1.com" ; "url2.com")),
       (to TEST-TO-ADDR from TEST-FROM-ADDR : makeHttpRequest(getRequest, "url0.com")) }
  .

*** Test a media get reply (from a post id).
red handleReply(makeHttpResponse("OK", makeResponseToot(88, "Post 88 text", ("url0.com" ; "url1.com" ; "url2.com"), (80 : 81 : 82))), (masClTestAttrs, thisAddr: TEST-FROM-ADDR, masServerAddr: TEST-TO-ADDR, opStack: GET-MEDIA-POST-OP, gettingMediaUrls: emptyUrlList))
  == { (masClTestAttrs, thisAddr: TEST-FROM-ADDR, masServerAddr: TEST-TO-ADDR, opStack: (GET-MEDIA-URL-OP : GET-MEDIA-POST-OP), gettingMediaUrls: ("url1.com" ; "url2.com")),
       (to TEST-TO-ADDR from TEST-FROM-ADDR : makeHttpRequest(getRequest, "url0.com")) }
  .

*** Test a media get reply (from a URL) during the process of getting all media from all posts with a certain hashtag.
*** There is only one post with the hashtag, and only one media to retreive.
red handleReply(makeHttpResponse("OK",
                                 makeMediaFile("img0.jpg", TEST-SIZE)),
                (masClTestAttrs,
                  thisAddr: TEST-FROM-ADDR,
                  masServerAddr: TEST-TO-ADDR,
                  requesterAddr: TEST-REQ-ADDR,
                  opStack: (GET-MEDIA-URL-OP : GET-MEDIA-HASHTAG-OP),
                  gettingMediaUrls: emptyUrlList,
                  gettingMedias: emptyMediaFileList,
                  gettingTag: makeTag("cat")))
  == { (masClTestAttrs,
        thisAddr: TEST-FROM-ADDR,
        masServerAddr: TEST-TO-ADDR,
        requesterAddr: TEST-REQ-ADDR,
        opStack: emptyOpStack,
        gettingMediaUrls: emptyUrlList,
        gettingMedias: makeMediaFile("img0.jpg", TEST-SIZE),
        gettingTag: makeTag("cat")),
       (to TEST-REQ-ADDR from TEST-FROM-ADDR : ResponseMediaList(makeMediaFile("img0.jpg", TEST-SIZE))) }
  .

*** Test a media get reply (from a URL) during the process of getting all media from all posts with a certain hashtag.
*** There is only one post with the hashtag, and three media to retreive.
red handleReply(makeHttpResponse("OK",
                                 makeMediaFile("img0.jpg", TEST-SIZE)),
                (masClTestAttrs,
                  thisAddr: TEST-FROM-ADDR,
                  masServerAddr: TEST-TO-ADDR,
                  opStack: (GET-MEDIA-URL-OP : GET-MEDIA-HASHTAG-OP),
                  gettingMediaUrls: ("url1" ; "url2"),
                  gettingMedias: emptyMediaFileList))
  == { (masClTestAttrs,
          thisAddr: TEST-FROM-ADDR,
          masServerAddr: TEST-TO-ADDR,
          opStack: (GET-MEDIA-URL-OP : GET-MEDIA-HASHTAG-OP),
          gettingMediaUrls: "url2",
          gettingMedias: makeMediaFile("img0.jpg", TEST-SIZE)),
       (to TEST-TO-ADDR from TEST-FROM-ADDR : makeHttpRequest(getRequest, "url1")) }
  .

*** Test handling a media post request.
red handleRequest(TEST-FROM-ADDR,
                  makeHttpRequest(postRequest, makeMediaFile("img0.jpg", TEST-SIZE)),
                  (masServerTestAttrs,
                    thisAddr: TEST-TO-ADDR,
                    currentMapId: 10,
                    mediaMap: emptyIdMediaMap))
  == { (masServerTestAttrs,
          thisAddr: TEST-TO-ADDR,
          currentMapId: 11,
          mediaMap: (11 ~> (makeMediaFile("img0.jpg", TEST-SIZE), makeUrl(makeMediaFile("img0.jpg", TEST-SIZE))))),
       (to TEST-FROM-ADDR from TEST-TO-ADDR : makeHttpResponse("OK", makeResponseToot(11))) }
  .

red handleRequest((to TEST-TO-ADDR from TEST-FROM-ADDR : makeHttpRequest(postRequest, makeMediaFile("img0.jpg", TEST-SIZE))),
                  (masServerTestAttrs,
                    thisAddr: TEST-TO-ADDR,
                    currentMapId: 10,
                    mediaMap: emptyIdMediaMap))
  == { (masServerTestAttrs,
          thisAddr: TEST-TO-ADDR,
          currentMapId: 11,
          mediaMap: (11 ~> (makeMediaFile("img0.jpg", TEST-SIZE), makeUrl(makeMediaFile("img0.jpg", TEST-SIZE))))),
       (to TEST-FROM-ADDR from TEST-TO-ADDR : makeHttpResponse("OK", makeResponseToot(11))) }
  .

*** Test handling a status post (with nothing else).
red handleRequest(TEST-FROM-ADDR,
                  makeHttpRequest(postRequest, "A new toot with attachments"),
                  (masServerTestAttrs,
                    thisAddr: TEST-TO-ADDR,
                    currentMapId: 10,
                    tootMap: emptyIdTootMap,
                    mediaMap: ((88 ~> (makeMediaFile("img0.jpg", TEST-SIZE), "url0.com")) : (46 ~> (makeMediaFile("img1.jpg", TEST-SIZE), "url1.com")))))
  == { (masServerTestAttrs,
          thisAddr: TEST-TO-ADDR,
          currentMapId: 11,
          tootMap: (11 ~> makeToot("A new toot with attachments", emptyUrlList, emptyMasIdList)),
          mediaMap: ((88 ~> (makeMediaFile("img0.jpg", TEST-SIZE), "url0.com")) : (46 ~> (makeMediaFile("img1.jpg", TEST-SIZE), "url1.com")))),
      (to TEST-FROM-ADDR from TEST-TO-ADDR : makeHttpResponse("OK", makeResponseToot(11))) }
  .

*** Test handling a status post with media Ids.
red handleRequest(TEST-FROM-ADDR,
                  makeHttpRequest(postRequest, "A new toot with attachments", (88 : 46)),
                  (masServerTestAttrs,
                    thisAddr: TEST-TO-ADDR,
                    currentMapId: 10,
                    tootMap: emptyIdTootMap,
                    mediaMap: ((88 ~> (makeMediaFile("img0.jpg", TEST-SIZE), "url0.com")) : (46 ~> (makeMediaFile("img1.jpg", TEST-SIZE), "url1.com")))))
  == { (masServerTestAttrs,
          thisAddr: TEST-TO-ADDR,
          currentMapId: 11,
          tootMap: (11 ~> makeToot("A new toot with attachments", ("url0.com" ; "url1.com"), (88 : 46))),
          mediaMap: ((88 ~> (makeMediaFile("img0.jpg", TEST-SIZE), "url0.com")) : (46 ~> (makeMediaFile("img1.jpg", TEST-SIZE), "url1.com")))),
      (to TEST-FROM-ADDR from TEST-TO-ADDR : makeHttpResponse("OK", makeResponseToot(11))) }
  .

--- Test handle a status get request by post Id.
red handleRequest(TEST-FROM-ADDR,
                  makeHttpRequest(getRequest, 8),
                  (masServerTestAttrs,
                   thisAddr: TEST-TO-ADDR,
                   tootMap: ((40 ~> makeToot("Toot with hashtag #Tag", "www.catimg.com", 40)) : (8 ~> makeToot("Other too", emptyUrlList, emptyMasIdList)))))
  == { (masServerTestAttrs,
          thisAddr: TEST-TO-ADDR,
          tootMap: ((40 ~> makeToot("Toot with hashtag #Tag", "www.catimg.com", 40)) : (8 ~> makeToot("Other too", emptyUrlList, emptyMasIdList)))) ,
       (to TEST-FROM-ADDR from TEST-TO-ADDR : makeHttpResponse("OK", makeResponseToot(8, makeToot("Other too", emptyUrlList, emptyMasIdList)))) }
  .

--- Test handling a media get request from URL -- not found.
red handleRequest(TEST-FROM-ADDR,
                  makeHttpRequest(getRequest, "url0.com"),
                  (masServerTestAttrs, thisAddr: TEST-TO-ADDR, mediaMap: emptyIdMediaMap))
  == { (masServerTestAttrs, thisAddr: TEST-TO-ADDR, mediaMap: emptyIdMediaMap),
        (to TEST-FROM-ADDR from TEST-TO-ADDR : makeHttpResponse("NOT_FOUND")) }
  .

--- Test handling a media get request from URL -- found and returned.
red handleRequest(TEST-FROM-ADDR,
                  makeHttpRequest(getRequest, "url0.com"),
                  (masServerTestAttrs,
                    thisAddr: TEST-TO-ADDR,
                    mediaMap: ((88 ~> (makeMediaFile("img0.jpg", TEST-SIZE), "url0.com")) : (46 ~> (makeMediaFile("img1.jpg", TEST-SIZE), "url1.com")))))
  == { (masServerTestAttrs,
          thisAddr: TEST-TO-ADDR,
          mediaMap: ((88 ~> (makeMediaFile("img0.jpg", TEST-SIZE), "url0.com")) : (46 ~> (makeMediaFile("img1.jpg", TEST-SIZE), "url1.com")))),
        (to TEST-FROM-ADDR from TEST-TO-ADDR : makeHttpResponse("OK", makeMediaFile("img0.jpg", TEST-SIZE))) }
  .

--- Test handle a status search by hashtag.
red handleRequest(TEST-FROM-ADDR,
                  makeHttpRequest(getRequest, makeTag("Tag")),
                  ((masServerTestAttrs,
                      thisAddr: TEST-TO-ADDR,
                      tootMap: (40 ~> makeToot("Toot with hashtag #Tag", "www.catimg.com", 39)),
                      tagMap: ((makeTag("Hashtag") ~> (20 : 30)) : (makeTag("Tag") ~> 40) : (makeTag("Hash") ~> 50)))))
  == { (masServerTestAttrs,
          thisAddr: TEST-TO-ADDR,
          tootMap: (40 ~> makeToot("Toot with hashtag #Tag", "www.catimg.com", 39)),
          tagMap: ((makeTag("Hashtag") ~> (20 : 30)) : (makeTag("Tag") ~> 40) : (makeTag("Hash") ~> 50))),
        (to TEST-FROM-ADDR from TEST-TO-ADDR : makeHttpResponse("OK", makeResponseToot(40, makeToot("Toot with hashtag #Tag", "www.catimg.com", 39)))) }
  .


---------------------
--- MAS AUX Tests ---
---------------------
red translateRbToMasCommand(tootQ(bHashTag(4), noBytes))
  == PostStatus("#4")
  .

red dispatchRaceboatCommand(attrs:AttributeSet, tootQ(bHashTag(4), noBytes))
  == uploadNewStatus(attrs:AttributeSet, "#4", emptyMasIdList)
  .


------------------
--- Toot Tests ---
------------------

red getUrlList(makeResponseToot(88, "Post text", ("url0.com" ; "url1.com"), (86 : 87))) == ("url0.com" ; "url1.com") .
red getUrlList((makeResponseToot(88, "Post 88 text", ("url0.com" ; "url1.com"), (86 : 87))) : (makeResponseToot(109, "Post 109 text", ("url2.com"), 108))) == ("url0.com" ; "url1.com" ; "url2.com") .
red createArbitraryToots(3) == (createArbitraryToot : createArbitraryToot : createArbitraryToot) .
red getUrlList(makeResponseToot(88, "text")) == emptyUrlList .
red getUrlList(createArbitraryToot)  == emptyUrlList .
red getUrlList(createArbitraryToots(5)) == emptyUrlList .


------------------------
--- Media File Tests ---
------------------------

red getPayload(makeMediaFile("img0.jpg", 100)) == noBytes .
red popMediaList(emptyMediaFileList) == emptyMediaFileList .


-----------------
--- Tag Tests ---
-----------------

red $extractTag("#hashtag string") == makeTag("hashtag") .
red $extractTag("This string has a #hashtag tag and #another one.") == makeTag("hashtag") ;; makeTag("another") .
red $extractTag("This string last #hashtag") == makeTag("hashtag") .
red $extractTag("This string has no hashtag.") == emptyTagList .


-----------------
--- URL Tests ---
-----------------
red rand .
red generateRandUrlString .
red makeUrl .
red makeUrl("img0.jpg") == url("randimg0.com") .
red makeUrl("img0") == url("randimg0.com") .

