sload ../pwnd_cp3_scenario_1
sload ../../../../../maude_hcs/lib/smc/smc_cp3-refactored


mod HCS-TEST-BASELINE-TCPPKTINTERARRIVAL-CL5 is
  inc PWND-CP3-SCENARIO-1 .  
  inc SMC_CP3 . 
  
  eq slimit = 7211.0 .

  eq Vpts = cl[5] .
  eq ObsFs = tcpPktInterarrival .

  eq hcsDelay = slimit + slimit .  --- prevent hcs from starting

 eq finalize(c:Config) = addK2Blist(c:Config,false) .

endm

rew run({0.0 | nil} initState(counter) [tgenDelay, (to baseLineAddr from baseLineAddr : initBase),0], slimit) .
q