load dns-mamodel.maude

red dns-markov == ("batch" |-> "wait_batch" |-> 1.0,
    "single" |-> "wait_single" |-> 1.0, "wait_batch" |-> ("batch" |->
    5.0e-1, "single" |-> 5.0e-1), "wait_single" |-> ("batch" |-> 5.0e-1,
    "single" |-> 5.0e-1)) .

red getActions(dns-ma) == dns-actions .
red getParams(dns-ma) == dns-params .

red getStart(dns-ma) == "single" .
red getMaxSteps(dns-ma) == 100 .

red isWaitType(getJOmap(dns-actions["single"])) == false .
red isWaitType(getJOmap(dns-actions["wait_single"])) == true .

red realizeParams(dns-actions["batch"], 0) == 
                    {"num_to_resolve" |-> jn(6), 
                    "type" |-> js("resolve_a_batch")
                    , 1} .