--- MAUDE_HCS: maude_hcs
---
--- Software Markings (UNCLASS)
--- PWNDD Software
---
--- Copyright (C) 2025 RTX BBN Technologies Inc. All Rights Reserved
---
--- Contract No: HR00112590083
--- Contractor Name: RTX BBN Technologies Inc.
--- Contractor Address: 10 Moulton Street, Cambridge, Massachusetts 02138
---
--- The U.S. Government's rights to use, modify, reproduce, release, perform,
--- display, or disclose these technical data and software are defined in the
--- Article VII: Data Rights clause of the OTA.
---
--- This document does not contain technology or technical data controlled under
--- either the U.S. International Traffic in Arms Regulations or the U.S. Export
--- Administration Regulations.
---
--- DISTRIBUTION STATEMENT A: Approved for public release; distribution is
--- unlimited.
---
--- Notice: Markings. Any reproduction of this computer software, computer
--- software documentation, or portions thereof must also reproduce the markings
--- contained herein.
---
--- MAUDE_HCS: end


load ./mastodon
load ../../../dns/maude/probabilistic/iodine_dns
load ../../../common/maude/adversary-observer
load ../../../common/maude/cp2-interfaces
load ../../../common/maude/_aux
load ../../../common/maude/router
load ../../../common/maude/adversary-observer
load ../../../app/maude/probabilistic

set print attribute on .
set show advisories off .

mod MASTODON_TEST is
  inc IODINE_DNS .
  inc ADVERSARY-OBSERVER .
  inc MASTODON .
  inc CP2-COMMON .
  inc ROUTER .
  inc ADVERSARY-OBSERVER .
  inc CP2_APP . ---- loads rb-integration 
  inc MC-INTERFACE .

  ops alice-raceboat bob-raceboat mastodon-client mastodon-server : -> Address .
  ops alice bob aliceRbClient iodineSendApp iodineRecvApp iodineClient iodineServer bobMasClient : -> Address .
  ops clientContentMgr serverContentMgr clientDestini serverDestini clientUserModel serverUserModel : -> Address .
  ops monAddr : -> Address .
  op adversary : -> Address .
  ---- the sendtime / receive time collection patterns
  ops ObsS ObsR : -> Observable .
  eq ObsS = mtObs [owise] .
  eq ObsR = mtObs [owise] .

  --- uncomment to model aversary at router inside corporate
  --- collects msgs received by router from interal actors
  --- (stored as sent by local-dns)
  eq ObsR = obsC .  

eq monitorQueryLog? = true .

op router : -> Address .
op adversary : -> Address .

eq fileSize = 1000 .
eq packetSize = 530 .
eq maxPacketSize = 530 .
eq packetOverhead = 33 .
eq maxFragmentLen = 200 .
eq maxFragmentTx = 20 .
---eq nsResourceBounds? = false .
eq pacingTimeoutDelay = 0.05 .
eq pacingTimeoutDelayMax = 0.05 .
eq ackTimeoutDelay = 1.0 . 
eq maxMinimiseCount = 0 .

op zonePwnd2Com : -> List{Record} .
eq zonePwnd2Com =
  < 'pwnd2 . 'com . root, soa, 3600.0, soaData(3600.0) >
  < 'pwnd2 . 'com . root, ns, 3600.0, 'ns . 'pwnd2 . 'com . root >
  < 'ns . 'pwnd2 . 'com . root, a, 3600.0, iodineServer >
  < 'www0 . 'pwnd2 . 'com . root, a, 3600.0, 2 . 0 . 1 . 2 >
  < 'www1 . 'pwnd2 . 'com . root, a, 3600.0, 2 . 1 . 1 . 2 >
  < wildcard . 'pwnd2 . 'com . root, txt, 3600.0, nullAddr > .

  --- Initial configuration.

  op initState : -> Config .
  eq initState = 
    rCtr(0)
    < alice : TxApp |
      destAddr: bob,
      rbClientAddr: aliceRbClient,
      rbUserModelAddr: clientUserModel,
      rbContentMgrAddr: clientContentMgr,
      iodineClientAddr: iodineSendApp,
      contractCount: 0,
      queue: file(0, 30),
      currentCcFile: nilBytes >
    < bob : RxApp |
      rcvd: emptyFileList,
      currentKey: nilBytes,
      rbUserModelAddr: serverUserModel,
      rbContentMgrAddr: serverContentMgr >
  < iodineSendApp : SendApp |
      fileDestAddr: iodineRecvApp,
      toAddr: iodineClient,
      queuePopulated: false,
      queue: mtpl,
      numAdmittedPkts: 1,
      iodineReady: true,
      sent: mtpl,
      rcvd: mtpl > 
  < iodineRecvApp : RcvApp | rcvd: mtpl,
      fileDestAddr: bob,
      toAddr: (iodineServer),
      queuePopulated: false,
      queue: (mtpl),
      numAdmittedPkts: 1,
      iodineReady: true,
      sent: mtpl >
  < iodineClient : WClient |
      resv: iodineServer, ---addrNScorporate,
      wDom: 'pwnd2 . 'com . root,
      weirdQType: a,
      queryCtr: 0,
      outSeqNo: 0,
      fragmentsToSend: mtfl,
      fragmentsSize: 0,
      outFragNo: 0,
      appAddrMap: mtIdAddr,
      numAttempts: 0,
      fragmentsReceived: mtfl,
      inSeqNo: 0,
      inFragNo: 0,
      lastFragment: false,
      severWResponseTTL: 0.0 >
    makeMastodonClient(mastodon-client,
                       mastodon-server,
                       clientContentMgr)
  < iodineServer : WNameserver |
      fragmentsReceived: mtfl,
      inSeqNo: 0,
      inFragNo: 0,
      lastFragment: false,
      severWResponseTTL: 0.0,
      outSeqNo: 0,
      fragmentsToSend: mtfl,
      fragmentsSize: 0,
      outFragNo: 0,
      numAttempts: 0,
      conf: (< iodineServer : Nameserver |  db: (zonePwnd2Com),
                                            queue: nilQueue,
                                            forwardonly: nullAddr,
                                            queriesFwd: nilTAQL >) >
    makeMastodonClient(bobMasClient,
                       mastodon-server,
                       serverContentMgr)
    makeMastodonServer(mastodon-server)
    makeRbClient(clientUserModel, clientContentMgr, clientDestini, mastodon-client)
    makeRbServer(serverUserModel, serverContentMgr, serverDestini, bobMasClient, bob)
    < monAddr : WMonitor |
      querySent: nilQueryTimestamp,
      queryRcvd: nilQueryTimestamp,
      pktSent: nilPacketTimestamp,
      pktRcvd: nilPacketTimestamp >
    mkRouter(router)
    mkAdversary(adversary,ObsS,ObsR)
---    (to mastodon-client from alice-raceboat : PostStatus("This is the toot"))
---    (to mastodon-client from alice-raceboat : PostStatus("This is the #tag toot"))
---    (to mastodon-client from alice-raceboat : PostMedia(makeMediaFile("cat.jpg", 1000)))
---    (to mastodon-client from alice-raceboat : PostStatus("This is the #media toot with media", (makeMediaFile("img0.jpg", 1000) :: makeMediaFile("img1.jpg", 1000))))
---    (to mastodon-client from alice-raceboat : GetPost(3))
---    (to mastodon-client from alice-raceboat : GetMedia(makeUrl(makeMediaFile("img1.jpg", 1000))))
---    (to mastodon-client from alice-raceboat : GetTimeline)
---    [1.0, (to mastodon-client from alice-raceboat : GetMediaHashtag(makeTag("media"))), 0]
      [0.5, (to alice : start), 0]
      [21.0, (to bob : start), 0]
---      [1.0, (to mastodon-client from alice-raceboat  : tootQ(bHashTag(0), noBytes)), 0]
    .

    op initConfig : -> Config .
    eq initConfig = run({0.0 | nil} initState, limit) .
endm
rew initConfig .
eof

