--- MAUDE_HCS: maude_hcs
---
--- Software Markings (UNCLASS)
--- Maude-HCS Software
---
--- Copyright (C) 2025 RTX BBN Technologies Inc. All Rights Reserved
---
--- The computer software and computer software documentation are licensed
--- under the Apache License, Version 2.0 (the "License"); you may not use
--- this file except in compliance with the License. A copy of the License
--- is provided in the LICENSE file, but you may obtain a copy of the
--- License at:  https://www.apache.org/licenses/LICENSE-2.0
---
--- The computer software and computer software documentation are based
--- upon work supported by the Defense Advanced Research Projects Agency (DARPA)
--- under Agreement No. HR00l 12590083.
---
--- This document does not contain technology or technical data controlled under
--- either the U.S. International Traffic in Arms Regulations or the U.S. Export
--- Administration Regulations.
---
--- DISTRIBUTION STATEMENT A: Approved for public release; distribution is
--- unlimited.
---
--- Notice: Markings. Any reproduction of this computer software, computer
--- software documentation, or portions thereof must also reproduce the markings
--- contained herein. Refer to the provided NOTICE file.
---
--- MAUDE_HCS: end

sload ../irc/irc_prob
sload ../irc/irc_monitor.maude
sload ./skyhook_prob
sload ../s3/s3_protocol
sload ../common/maude/cp2-interfaces.maude

set print attribute on .

mod TEST_PACKAGE_2 is
  pr IRC .
  pr S3_PROTOCOL .
  pr SKYHOOK .
  pr IRC_MONITOR .

  **** .-------.       .--------------.      .--------.
  **** |IRC Cl0|  ---> |(rbC0toS0) pu0| ---> |S3C0toS0| -
  **** `-------'       `--------------'      `--------'  \_
  ****                                                     _| .---------.
  **** .-------.       .--------------.      .--------.       |         |
  **** |IRC    | ,---> |(rbS0toC0) ah0| ---> |S3C0toC0| --->  |S3       |
  **** |       |<      >==============<      >========<       |   Server|
  **** |    Srv| `---> |(rbS1toC1) ah1| ---> |S3C1toC1| --->  `---------'
  **** `-------'       `--------------'      `--------'    _
  ****                                                    _ |
  **** .-------.       .--------------.      .--------.  /
  **** |IRC Cl1|  ---> |(rbC1toS1) pu1| ---> |S3C1toS1| -
  **** `-------'       `--------------'      `--------'


  ops ircClient0 ircClient1 ircServer s3Server : -> Actor .
  ops skyhookPU0 skyhookPU1 skyhookAH0 skyhookAH1 awsServer awsSdkActor : -> Actor .
  ops s3Client0Tos0 s3Client1Tos1 s3Client0Toc0 s3Client1Toc1 s3Server : -> Actor .
  ops client0Iface serverClientIface client1Iface serverClient1Iface : -> Actor .
  ops ircMonitor : -> Actor .
  ops ircClient0Addr ircClient1Addr ircServerAddr : -> Address .
  ops client0IfaceAddr serverClient0IfaceAddr client1IfaceAddr serverClient1IfaceAddr : -> Address .
  ops pu0Addr pu1Addr ah0Addr ah1Addr rbc0Tos0Addr rbc1Tos1Addr rbs0Toc0Addr rbs1Toc1Addr userAddr awsAddr s3ClientAddr : -> Address .
  ops s3Client0Tos0Addr s3Client1Tos1Addr s3Client0Toc0Addr s3Client1Toc1Addr s3ServerAddr : -> Address .
  ops ircMonitorAddr : -> Address .

  eq ircClient0 = mkIrcClient(ircClient0Addr,
                              pu0Addr,
                              "alice",
                                 imd(2.0, "bbn", 279)
                              :: imd(3.5, "bbn", 258)
                              :: imd(5.4, "bbn", 171)) .
  eq ircClient1 = makeIrcClient(ircClient1Addr, pu1Addr) .
  eq ircServer  = makeIrcServer(ircServerAddr) .

  eq client0Iface     = mkIrcByteSeqIface(client0IfaceAddr, ircServerAddr, pu0Addr, pu0Addr) .
  eq serverClient0Iface = mkIrcByteSeqIface(serverClient0IfaceAddr, ircClient0Addr, ah0Addr, ah0Addr) .
  eq client1Iface     = mkIrcByteSeqIface(client1IfaceAddr, ircServerAddr, pu1Addr, pu1Addr) .
  eq clientClient1Iface = mkIrcByteSeqIface(serverClient1IfaceAddr, ircClient1Addr, ah1Affr, ah1Addr) .

  eq skyhookPU0 = makeSkyhookPU(pu0Addr,
                                rbc0Tos0Addr,
                                s3Client0Tos0Addr,
                                "s_to_c_bucket_0",
                                "c_to_s_bucket_0",
                                "s_to_c_uuid_0-hash",
                                "c_to_s_uuid_0-hash")
  .

  eq s3Client0Tos0 = < s3Client0Tos0Addr : S3SdkClient | thisAddr: s3Client0Tos0Addr, realAwsAddr: s3ServerAddr, nextId: 1, pendingReqs: emptyS3ReqMap > .

  eq skyhookPU1 = makeSkyhookPU(pu1Addr,
                                rbc1Tos1Addr,
                                s3Client1Tos1Addr,
                                "s_to_c_bucket_1",
                                "c_to_s_bucket_1",
                                "s_to_c_uuid_1",
                                "c_to_s_uuid_1")
  .

  eq s3Client1Tos1 = < s3Client1Tos1Addr : S3SdkClient | thisAddr: s3Client1Tos1Addr, realAwsAddr: s3ServerAddr, nextId: 1, pendingReqs: emptyS3ReqMap > .

  eq skyhookAH0 = makeSkyhookAH(ah0Addr,
                                rbs0Toc0Addr,
                                s3Client0Toc0Addr,
                                "c_to_s_bucket_0",
                                "s_to_c_bucket_0",
                                "c_to_s_uuid_0",
                                "s_to_c_uuid_0",
                                "post_uuid_0")
  .

  eq s3Client0Toc0 = < s3Client0Toc0Addr : S3SdkClient | thisAddr: s3Client0Toc0Addr, realAwsAddr: s3ServerAddr, nextId: 1, pendingReqs: emptyS3ReqMap > .

  eq skyhookAH1 = makeSkyhookAH(ah1Addr,
                                rbs1Toc1Addr,
                                s3Client1Toc1Addr,
                                "c_to_s_bucket_1",
                                "s_to_c_bucket_1",
                                "c_to_s_uuid_1",
                                "s_to_c_uuid_1",
                                "s_to_c_uuid_1")
  .

  eq s3Client1Toc1 = < s3Client1Toc1Addr : S3SdkClient | thisAddr: s3Client1Toc1Addr, realAwsAddr: s3ServerAddr, nextId: 1, pendingReqs: emptyS3ReqMap > .

  eq s3Server = < s3ServerAddr : AwsS3HttpServer | thisAddr: s3ServerAddr, s3DataMap: emptyS3DataMap > .

  op toByteseq : IrcMsg -> ByteSeq .

  eq ircMonitor = 
      makeIrcMonitor(ircMonitorAddr,
                    (ircServerAddr ;; ircClient0Addr ;; ircClient1Addr)) .
                  
  op initState : -> Config .
  eq initState =
    rCtr(0)
    ircClient0
    ircClient1
    ircServer
    ircMonitor
    skyhookPU0
    s3Client0Tos0
    skyhookPU1
    s3Client1Tos1
    skyhookAH0
    s3Client0Toc0
    skyhookAH1
    s3Client1Toc1
    s3Server
    [0.001, (to ah0Addr from rbs0Toc0Addr : SkyhookStartCmd), 0]
    [0.25, (to ircClient0Addr from ircClient0Addr : ircMsgSendTime), 0]
    --- Bypass RB for these joins.
    [0.40, (to ircServerAddr from ircClient0Addr
              : JoinChannel(makeIrcChannelName("bbn"), ircClient0Addr)), 0]
    [0.5, (to ircServerAddr from ircClient1Addr
              : JoinChannel(makeIrcChannelName("bbn"), ircClient1Addr)), 0]
    [2.0, (to ah0Addr from rbs0Toc0Addr : SkyhookFetchCmd), 0]
    [3.2, (to pu1Addr from rbc1Tos1Addr : SkyhookFetchCmd), 0]
    [4.0, (to ah0Addr from rbs0Toc0Addr : SkyhookFetchCmd), 0]
    [5.0, (to pu1Addr from rbc1Tos1Addr : SkyhookFetchCmd), 0]
    [6.0, (to ah0Addr from rbs0Toc0Addr : SkyhookFetchCmd), 0]
    [7.0, (to pu1Addr from rbc1Tos1Addr : SkyhookFetchCmd), 0]
  .

  op initConfig : -> Config .
  eq limit = 200. .
  eq initConfig = run({0.0 | nil} initState, limit) .
endm

rew initConfig .
q

