set show advisories off .

**** sload ../../../use-cases/challenge-problem-3/cp3_scenarios/scenario1/z-scenario1

sload ../../../use-cases/challenge-problem-3/cp3_scenarios/scenario1/scenario1.maude

sload ../smc/smc_cp3-refactored
sload baseline-actor
sload smc-params


mod SCENARIO-BASELINE is
  inc HCS_TEST .
  inc SMC-PARAMS .
  inc SMC_CP3 .
  
  **** slimit default is 1hr == 3600.0
  eq slimit = 100.0 .

  eq hcsDelay = slimit + slimit .  --- prevent hcs to start

 eq finalize(c:Config) = addK2Blist(c:Config,true) .

endm

set print attr on .
set print attr select on .
print attr select initBaseline .
print attr select slideWdoBase .

rew run({0.0 | nil} initState(1) [30.0, (to baseLineAddr from baseLineAddr : initBase),0], 100.0) .
q
eof
rew initConfig .  

