set show advisories off .
sload ../smc/smc-baseline-shared 
**** sload smc-baseline-shared 

mod SMC-PARAMS is
  inc SMC-BASELINE-SHARED .
  
  ops slimit hcsDelay : -> Float .
  *** ops sT wS bS  eT : -> Float .
  eq sT = 0.0 .
  eq wS =  60. .
  eq bS = 10. .
  eq eT = slimit .


  *** op Vpts : -> NetIdList .
  eq Vpts = (ixpN :; cl[1]  :; srvN :; masN) . **** :;  cl[2]

  *** op ObsFs : -> FeatureList .
  eq ObsFs = 
  dnsQueryRate 
  *** :; dnsQuerySize 
  *** :; tcpUpRate :; tcpDownRate :; tcpUpToDownRate 
  :; tcpOutPktRate :; tcpInPktRate  :; tcpOutToInPktRate 
  :; tcpPktSizeStdDev :; tcpPktSize :; tcpPktInterarrival 
  :; tcpDirectionChange
  *** :; tcpActiveFlow :; tcpNewCnx
  .
  
  
endm  
