--- MAUDE_HCS: maude_hcs
---
--- Software Markings (UNCLASS)
--- Maude-HCS Software
---
--- Copyright (C) 2025 RTX BBN Technologies Inc. All Rights Reserved
---
--- The computer software and computer software documentation are licensed
--- under the Apache License, Version 2.0 (the "License"); you may not use
--- this file except in compliance with the License. A copy of the License
--- is provided in the LICENSE file, but you may obtain a copy of the
--- License at:  https://www.apache.org/licenses/LICENSE-2.0
---
--- The computer software and computer software documentation are based
--- upon work supported by the Defense Advanced Research Projects Agency (DARPA)
--- under Agreement No. HR00l 12590083.
---
--- This document does not contain technology or technical data controlled under
--- either the U.S. International Traffic in Arms Regulations or the U.S. Export
--- Administration Regulations.
---
--- DISTRIBUTION STATEMENT A: Approved for public release; distribution is
--- unlimited.
---
--- Notice: Markings. Any reproduction of this computer software, computer
--- software documentation, or portions thereof must also reproduce the markings
--- contained herein. Refer to the provided NOTICE file.
---
--- MAUDE_HCS: end

set clear rules off .
set print attribute off .
set show advisories off .

sload ../../../common/maude/user-action-actor
sload ../enc-dec-actor
sload ../rb-cm-sender-mas
sload ../rb-cm-receiver-mas
sload ../../../mastodon/maude/probabilistic/mastodon

---- raceboat  user models
**** sload ../../raceboat/maude/mastodonprofiles/client_config_cp2_scenario_1_new.maude
**** sload ../../raceboat/maude/mastodonprofiles/server_config_cp2_scenario_1_new.maude

sload ../client_config_cp2_scenario_1_new.maude
sload ../server_config_cp2_scenario_1_new.maude

sload ../../../common/maude/http-overhead.maude

sload ../../../irc/common/irc_name
sload ../../../irc/common/_aux
sload ../../../irc/irc_prob

**** sload ../../common/maude/irc-rbmas-interface
---- this should go in a scenario dir
sload ../irc-rbmas-interface  
sload ../logging

mod RB-BIDIR-MAS-IRC-SCENARIO is
  inc USER-ACTION-ACTOR .
  inc ENC-DEC .
  inc CONTENT-MANAGER-SENDER .
  inc CONTENT-MANAGER-RECEIVER . 
  inc MASTODON .
 ---- raceboat model includes
 inc MASTODON-CLIENT-CONFIG-CP2-SCENARIO-1-NEW-MAMODEL .
 inc MASTODON-SERVER-CONFIG-CP2-SCENARIO-1-NEW-MAMODEL .
 inc SCHEDULER .
**** inc IRC-INTERFACE .   
 inc IRC .
 inc IRC-RBMAS-INTERFACE  .
 inc LOGGING .
 
 
vars j : Nat .

eq encOH(fsize:Nat,ksize:Nat)  = 0 .
eq noiseMin(msg:Msg) = 0.001 .

op ed-images : -> ByteSeqL .
eq ed-images = image(1, 3779, 500) :: image(2, 2405, 1000) :: image(3, 36861, 1000) :: image(4, 25377, 500) :: image(5, 2440, 300) :: image(6, 1275, 300) :: image(7, 7710, 1000) :: image(8, 3577, 500) :: image(9, 3415, 300) :: image(10, 74123, 600) .


**** addresses
*** alice
ops aliceAddr ircaAddr : -> Address .
**** alice channel interfaces
ops ifaceACAddr ifaceASAddr : -> Address .

*** client endpoint ac
ops umacSndAddr  cmacSndAddr mcacSndAddr 
    umacRcvAddr  cmacRcvAddr mcacRcvAddr 
    edacAddr : -> Address .
*** server endpoint as
ops umasSndAddr  cmasSndAddr mcasSndAddr 
    umasRcvAddr  cmasRcvAddr mcasRcvAddr 
    edasAddr : -> Address .

*** bob
ops bobAddr ircbAddr : -> Address .
**** bobs channel endpoint interfaces
ops ifaceBCAddr ifaceBSAddr : -> Address .

*** client endpointl  ..bc.. ..bs..
ops umbcSndAddr  cmbcSndAddr mcbcSndAddr 
    umbcRcvAddr  cmbcRcvAddr mcbcRcvAddr 
    edbcAddr : -> Address .
*** server endpoint
ops umbsSndAddr  cmbsSndAddr mcbsSndAddr 
    umbsRcvAddr  cmbsRcvAddr mcbsRcvAddr 
    edbsAddr : -> Address .

ops ircSrvAddr masSrvAddr : -> Address .
op logAddr : -> Address .

-----------------------
**** actors
*** alice
op ircaAct : -> Actor .
ops ifaceACAct ifaceASAct : -> Actor .

*** client endpoint
ops umacSndAct  cmacSndAct mcacSndAct 
    umacRcvAct  cmacRcvAct mcacRcvAct 
    edacAct : -> Actor .
*** server endpoint
ops umasSndAct  cmasSndAct mcasSndAct 
    umasRcvAct  cmasRcvAct mcasRcvAct 
    edasAct : -> Actor .

*** bob
op ircbAct : -> Actor .
ops ifaceBCAct ifaceBSAct : -> Actor .

*** client endpoint
ops umbcSndAct  cmbcSndAct mcbcSndAct 
    umbcRcvAct  cmbcRcvAct mcbcRcvAct 
    edbcAct : -> Actor .
*** server endpoint
ops umbsSndAct  cmbsSndAct mcbsSndAct 
    umbsRcvAct  cmbsRcvAct mcbsRcvAct 
    edbsAct : -> Actor .

ops ircSrvAct masSrvAct : -> Actor .
op logAct : -> Actor .

************** actor defns
***** aliceIrc
eq ircaAct =
  < ircaAddr : IrcClient |
    thisAddr: ircaAddr,
    raceboatAddr: ifaceACAddr,  ---- rb ircclient interface
    ircName: makeIrcUserName(ircaAddr),
    aliceAppChatsMap: (
       (2.0 ~> ("Alice message 0", makeIrcChannelName("ab")))
     : (20. ~> ("Alice message 1", makeIrcChannelName("ab")))
     : (40. ~> ("Alice message 2", makeIrcChannelName("ab"))))
  >
  .
  
eq ifaceACAct =
mkIrcMasIface(ifaceACAddr,ircaAddr,
              cmacSndAddr,cmacRcvAddr) .

**** alice client rb endpoint
eq umacSndAct = mkUMactor(umacSndAddr, 
            mastodon-client-config-cp2-scenario-1-new-ma,
            cmacSndAddr) .
eq cmacSndAct = 
    mkCMSender(cmacSndAddr,edacAddr,mcacSndAddr,
               ifaceACAddr,  ---- rcv from   ircaAddr, 
               "client0") .
eq mcacSndAct =
   makeMastodonClient(mcacSndAddr, masSrvAddr,cmacSndAddr) .

eq umacRcvAct =
  mkUMactor(umacRcvAddr, 
            mastodon-server-config-cp2-scenario-1-new-ma,
            cmacRcvAddr) .
eq cmacRcvAct =
  mkCMReceiver(cmacRcvAddr,edacAddr,mcacRcvAddr,
   ifaceACAddr,  ---- ircaAddr, send rcvd to
  "server0") .  --- posted by server end
eq mcacRcvAct =
  makeMastodonClient(mcacRcvAddr, masSrvAddr,cmacRcvAddr) .
eq edacAct = makeDestiniActor(edacAddr, ed-images) .

***  alice server endpoint

eq ifaceASAct = mkIrcMasIface(ifaceASAddr,ircSrvAddr, 
                              cmasSndAddr,cmasRcvAddr) .
eq umasSndAct = mkUMactor(umasSndAddr, 
            mastodon-client-config-cp2-scenario-1-new-ma,
            cmasSndAddr) .
eq cmasSndAct = ---- to client from server
    mkCMSender(cmasSndAddr,edasAddr,mcasSndAddr,
               ifaceASAddr, ---- sndAddr
               "server0") .
eq mcasSndAct =
   makeMastodonClient(mcasSndAddr, masSrvAddr,cmasSndAddr) .

eq umasRcvAct =
  mkUMactor(umasRcvAddr, 
            mastodon-server-config-cp2-scenario-1-new-ma,
            cmasRcvAddr) .
eq cmasRcvAct =
  mkCMReceiver(cmasRcvAddr,edasAddr,mcasRcvAddr,
   ifaceASAddr, --- 
  "client0") .  --- posted by server end
eq mcasRcvAct =
  makeMastodonClient(mcasRcvAddr, masSrvAddr,cmasRcvAddr) .
eq edasAct = makeDestiniActor(edasAddr, ed-images) .

********************************
*** bob
eq ircbAct =
    < ircbAddr : IrcClient |
        thisAddr: ircbAddr,
        raceboatAddr: ifaceBCAddr,  ---- rb interface
        ircName: makeIrcUserName(ircbAddr)
    >
  .

eq ifaceBCAct =
mkIrcMasIface(ifaceBCAddr,ircbAddr,
              cmbcSndAddr,cmbcRcvAddr) .

*** bob client  rbendpoint
eq umbcSndAct = mkUMactor(umbcSndAddr, 
            mastodon-client-config-cp2-scenario-1-new-ma,
            cmbcSndAddr) .
eq cmbcSndAct = 
    mkCMSender(cmbcSndAddr,edbcAddr,mcbcSndAddr,
               ifaceBCAddr, ---- sndAddr
               "client1") .
eq mcbcSndAct =
   makeMastodonClient(mcbcSndAddr, masSrvAddr,cmbcSndAddr) .

eq umbcRcvAct =
  mkUMactor(umbcRcvAddr, 
            mastodon-server-config-cp2-scenario-1-new-ma,
            cmbcRcvAddr) .
eq cmbcRcvAct =
  mkCMReceiver(cmbcRcvAddr,edbcAddr,mcbcRcvAddr,
   ifaceBCAddr, --- client end
  "server1") .  --- posted by server end
eq mcbcRcvAct =
  makeMastodonClient(mcbcRcvAddr, masSrvAddr,cmbcRcvAddr) .
eq edbcAct = makeDestiniActor(edbcAddr, ed-images) .

*** bob server endpoint
eq ifaceBSAct = mkIrcMasIface(ifaceBSAddr,ircSrvAddr, 
              cmbsSndAddr,cmbsRcvAddr) .

eq umbsSndAct = mkUMactor(umbsSndAddr, 
            mastodon-client-config-cp2-scenario-1-new-ma,
            cmbsSndAddr) .
eq cmbsSndAct = ---- to client from server
    mkCMSender(cmbsSndAddr,edbsAddr,mcbsSndAddr,
               ifaceBSAddr, ---- sndAddr
               "server1") .
eq mcbsSndAct =
   makeMastodonClient(mcbsSndAddr, masSrvAddr,cmbsSndAddr) .

eq umbsRcvAct =
  mkUMactor(umbsRcvAddr, 
            mastodon-server-config-cp2-scenario-1-new-ma,
            cmbsRcvAddr) .
eq cmbsRcvAct =
  mkCMReceiver(cmbsRcvAddr,edbsAddr,mcbsRcvAddr,
   ifaceBSAddr, --- client end
  "client1") .  --- posted by server end
eq mcbsRcvAct =
  makeMastodonClient(mcbsRcvAddr, masSrvAddr,cmbsRcvAddr) .
eq edbsAct = makeDestiniActor(edbsAddr, ed-images) .


******** global actors
eq masSrvAct = makeMastodonServer(masSrvAddr) .
eq ircSrvAct =
    < ircSrvAddr : IrcServer |
        thisAddr: ircSrvAddr,
        channelMap: emptyNameClientsMap,
        clientTimestampMap: emptyClientTimestampMap,
        clientAddressMap: emptyClientAddressMap
    >
  .
eq logAct =
  < logAddr : MsgLog | 
      sent: nilTML,
      rcvd: nilTML,
      toLog: (ircSrvAddr ;; ircaAddr ;; ircbAddr)
  > .     


op LinkType-2 : -> AttributeSet .
eq LinkType-2 = 
  (delayStd: 0.),
  (delayType: "Constant"),
  (delayMean: 0.),
  (delayConst: 0.005),
  (noiseMin: 0.),
  (noiseMax: 0.00001),
  (dropP: 0.),
  (canDrop: false)
  .

eq LinkData =
  aaa(masSrvAddr,mcacSndAddr,LinkType-2)
  aaa(masSrvAddr,mcacRcvAddr,LinkType-2)
  aaa(masSrvAddr,mcasSndAddr,LinkType-2)
  aaa(masSrvAddr,mcasRcvAddr,LinkType-2)
  aaa(masSrvAddr,mcbcSndAddr,LinkType-2)
  aaa(masSrvAddr,mcbcRcvAddr,LinkType-2)
  aaa(masSrvAddr,mcbsSndAddr,LinkType-2)
  aaa(masSrvAddr,mcbsRcvAddr,LinkType-2)
 
  aaa(mcacSndAddr,masSrvAddr,LinkType-2)
  aaa(mcacRcvAddr,masSrvAddr,LinkType-2)
  aaa(mcasSndAddr,masSrvAddr,LinkType-2)
  aaa(mcasRcvAddr,masSrvAddr,LinkType-2)
  aaa(mcbcSndAddr,masSrvAddr,LinkType-2)
  aaa(mcbcRcvAddr,masSrvAddr,LinkType-2)
  aaa(mcbsSndAddr,masSrvAddr,LinkType-2)
  aaa(mcbsRcvAddr,masSrvAddr,LinkType-2)
.
 
op initState : Nat -> Config .
eq initState(j ) =
     rCtr(j + 8)
******* alice 
   ircaAct 
*** alice client endpoint
   ifaceACAct
   umacSndAct  cmacSndAct mcacSndAct 
   umacRcvAct  cmacRcvAct mcacRcvAct 
   edacAct
**** alice server endpoint
   ifaceASAct
   umasSndAct  cmasSndAct mcasSndAct 
   umasRcvAct  cmasRcvAct mcasRcvAct 
   edasAct 
******* bob
   ircbAct 
**** bob client endpoint
   ifaceBCAct
   umbcSndAct  cmbcSndAct mcbcSndAct 
   umbcRcvAct  cmbcRcvAct mcbcRcvAct 
   edbcAct
***** bob server endpoint
   ifaceBSAct
   umbsSndAct  cmbsSndAct mcbsSndAct 
   umbsRcvAct  cmbsRcvAct mcbsRcvAct 
   edbsAct 
**** global
   ircSrvAct masSrvAct logAct
**** start messages  
**** alice channel  
  [1.0 + genRandomX(j,0.0, 0.0001),
   (to umacSndAddr from umacSndAddr : actionR("ok")),0]
  [1.0 + genRandomX(s j,0.0, 0.0001),
    (to umacRcvAddr from umacRcvAddr : actionR("ok")),0]
  [1.0  + genRandomX(s s j,0.0, 0.0001),
    (to umasSndAddr from umasSndAddr : actionR("ok")),0]
  [1.0  + genRandomX(s s s j,0.0, 0.0001),
   (to umasRcvAddr from umasRcvAddr : actionR("ok")),0]

**** bob channel   
  [1.0 + genRandomX(j + 4,0.0, 0.0001),
   (to umbcSndAddr from umbcSndAddr : actionR("ok")),0]
  [1.0 + genRandomX(j + 5,0.0, 0.0001),
   (to umbcRcvAddr from umbcRcvAddr : actionR("ok")),0]
  [1.0  + genRandomX(j + 6,0.0, 0.0001),
   (to umbsSndAddr from umbsSndAddr : actionR("ok")),0]
  [1.0  + genRandomX(j + 7,0.0, 0.0001),
   (to umbsRcvAddr from umbsRcvAddr : actionR("ok")),0]

**** start alice
  [0.25, (to ircaAddr : StartIrc), 0]
**** alice joins with cnx rb server send addr
**** if sent by alice, it would come from rcv addr!!
  [0.40, (to ircSrvAddr from ifaceASAddr : 
        JoinChannel(makeIrcChannelName("ab"),ircaAddr)),
     0]
  [0.5, (to ircSrvAddr from  ifaceBSAddr :
       JoinChannel(makeIrcChannelName("ab"),ircbAddr)),
     0]
.

op slimit : -> Float .
eq slimit = 300.0 .

op initConfig : -> Config .
rl[init]: initConfig 
   => run({0.0 | nil} initState(counter),slimit) .

 endm
 red "Alice,Bob join ab, Alice sends 3 texts" .
 set print attribute on .
 rew initConfig .
 q
 eof

  
