import pathlib

from .common import Counter, Cp3ConfigChunk, Lines, indented_lines, Insert, InsertType, pairs_to_names_and_binds

def mk_static_sloads() -> Lines:

  thispath = pathlib.Path(__file__).resolve()
  libpath = (thispath.parent.parent.parent / "lib").resolve()

  return Lines(
    '--- Core Infrastructure',
    f'sload {libpath / "webtunnel/webtunnel_prob.maude"}',
    f'sload {libpath / "irc/irc_prob-v2"}',
    f'sload {libpath / "irc/ircMonitor"}',
    f'sload {libpath / "irc/irc-byteseq-interface"}',
    f'sload {libpath / "common/maude/irc-action-actor-v2.maude"}',
    f'sload {libpath / "irc/common/irc_name"}',
    f'sload {libpath / "irc/common/_aux"}',
    f'sload {libpath / "irc/common/app_chat"}',
    f'sload {libpath / "irc/_irc_aux"}',
    f'sload {libpath / "../deps/dns_formalization/Maude/common/apmaude.maude"}',
    f'sload {libpath / "obfs4/_obfs4_aux.maude"}',
    f'sload {libpath / "obfs4/obfs4_prob.maude"}',
    f'sload {libpath / "common/maude/user-action-actor"}',
    f'sload {libpath / "raceboatMastodon/maude/enc-dec-actor"}',
    f'sload {libpath / "raceboatMastodonBidir/maude/rb-cm-bidir-mas.maude"}',
    f'sload {libpath / "mastodon/maude/probabilistic/mastodon"}',
    f'sload {libpath / "raceboatMastodon/maude/user_models/client_config_mastodon_bidi"}',
    f'sload {libpath / "raceboatMastodon/maude/user_models/server_config_mastodon_bidi"}',
    f'sload {libpath / "common/maude/http-overhead.maude"}',
    f'sload {libpath / "cp3-tests/skyhook/skyhook-um-mamodel-1"}',
    f'sload {libpath / "irc/common/irc-msg-model"}',
    f'sload {libpath / "raceboatSkyhook/maude/rb-cm-simple-bi"}',
    f'sload {libpath / "skyhook/skyhook_prob"}',
    f'sload {libpath / "s3/s3_protocol"}',
    f'sload {libpath / "dns/maude/probabilistic/iodine_dns.maude"}',
    f'sload {libpath / "dns/maude/common/_aux.maude"}',
    f'sload {libpath / "network/net_prob.maude"}',
    f'sload {libpath / "common/maude/structured-addresses.maude"}',
    '',
    f'--- TGEN Actor Infrastructure',
    f'sload {libpath / "common/maude/tgen-action-actor-v2.maude"}',
    f'sload {libpath / "tgen/maude/ftp/ftpTgen-actor.maude"}',
    f'sload {libpath / "tgen/maude/ftp/ftpServer-actor.maude"}',
    f'sload {libpath / "tgen/maude/gorillachat/gorilla-Tgen-actor.maude"}',
    f'sload {libpath / "tgen/maude/minio/minioTgen-actor.maude"}',
    f'sload {libpath / "s3/s3_protocol.maude"}',
    f'sload {libpath / "tgen/maude/dnsTgen-actor.maude"}',
    f'sload {libpath / "tgen/maude/masTGen.maude"}',
    f'sload {libpath / "tgen/maude/irc/ircTgen-actor.maude"}',
    '',
    '--- HCS IRC User Models (v2)',
    f'sload irc_user_models/irc_10.maude',
    f'sload irc_user_models/irc_11.maude',
    f'sload irc_user_models/irc_2.maude',
    f'sload irc_user_models/irc_3.maude',
    f'sload irc_user_models/irc_6.maude',
    f'sload irc_user_models/irc_7.maude',
    '',
    f'--- IRC TGEN Profiles (v2)',
    f'sload tgen_user_models/irc/irc_11.maude',
    f'sload tgen_user_models/irc/irc_12.maude',
    f'sload tgen_user_models/irc/irc_2.maude',
    f'sload tgen_user_models/irc/irc_4.maude',
    f'sload tgen_user_models/irc/irc_5.maude',
    f'sload tgen_user_models/irc/irc_6.maude',
    f'sload tgen_user_models/irc/irc_7.maude',
    f'sload tgen_user_models/irc/irc_8.maude',
    f'sload tgen_user_models/irc/irc_9.maude',
    '',
    f'--- FTP TGEN Profiles (v2)',
    f'sload tgen_user_models/ftp/fast.maude',
    f'sload tgen_user_models/ftp/medium.maude',
    f'sload tgen_user_models/ftp/slow.maude',
    '',
    '--- MinIO TGEN Profiles (v2)',
    f'sload tgen_user_models/minio/fast.maude',
    f'sload tgen_user_models/minio/medium.maude',
    f'sload tgen_user_models/minio/slow.maude',
    '',
    '--- Gorilla TGEN Profiles (v2)',
    f'sload tgen_user_models/gorilla/irc_1.maude',
    f'sload tgen_user_models/gorilla/irc_10.maude',
    f'sload tgen_user_models/gorilla/irc_11.maude',
    f'sload tgen_user_models/gorilla/irc_12.maude',
    f'sload tgen_user_models/gorilla/irc_2.maude',
    f'sload tgen_user_models/gorilla/irc_3.maude',
    f'sload tgen_user_models/gorilla/irc_4.maude',
    f'sload tgen_user_models/gorilla/irc_5.maude',
    f'sload tgen_user_models/gorilla/irc_6.maude',
    f'sload tgen_user_models/gorilla/irc_7.maude',
    f'sload tgen_user_models/gorilla/irc_8.maude',
    f'sload tgen_user_models/gorilla/irc_9.maude',
    '',
    '--- DNS TGEN Profiles (v1 from library)',
    f'sload {libpath / "tgen/maude/dnsprofiles/markov/config_fast_1.maude"}',
    f'sload {libpath / "tgen/maude/dnsprofiles/markov/config_fast_2.maude"}',
    f'sload {libpath / "tgen/maude/dnsprofiles/markov/config_fast_3.maude"}',
    f'sload {libpath / "tgen/maude/dnsprofiles/markov/config_fast_4.maude"}',
    f'sload {libpath / "tgen/maude/dnsprofiles/markov/config_normal_1.maude"}',
    f'sload {libpath / "tgen/maude/dnsprofiles/markov/config_normal_2.maude"}',
    f'sload {libpath / "tgen/maude/dnsprofiles/markov/config_normal_3.maude"}',
    f'sload {libpath / "tgen/maude/dnsprofiles/markov/config_normal_4.maude"}',
    f'sload {libpath / "tgen/maude/dnsprofiles/markov/config_slow_1.maude"}',
    f'sload {libpath / "tgen/maude/dnsprofiles/markov/config_slow_2.maude"}',
    f'sload {libpath / "tgen/maude/dnsprofiles/markov/config_slow_3.maude"}',
    f'sload {libpath / "tgen/maude/dnsprofiles/markov/config_slow_4.maude"}',
    '',
    '--- Mastodon TGEN Profiles (v1 from library)',
    f'sload {libpath / "tgen/maude/mastodonprofiles/markov/config_influencer_1.maude"}',
    f'sload {libpath / "tgen/maude/mastodonprofiles/markov/config_influencer_2.maude"}',
    f'sload {libpath / "tgen/maude/mastodonprofiles/markov/config_influencer_3.maude"}',
    f'sload {libpath / "tgen/maude/mastodonprofiles/markov/config_influencer_4.maude"}',
    f'sload {libpath / "tgen/maude/mastodonprofiles/markov/config_lurker_1.maude"}',
    f'sload {libpath / "tgen/maude/mastodonprofiles/markov/config_lurker_2.maude"}',
    f'sload {libpath / "tgen/maude/mastodonprofiles/markov/config_lurker_3.maude"}',
    f'sload {libpath / "tgen/maude/mastodonprofiles/markov/config_lurker_4.maude"}',
    f'sload {libpath / "tgen/maude/mastodonprofiles/markov/config_normal_1.maude"}',
    f'sload {libpath / "tgen/maude/mastodonprofiles/markov/config_normal_2.maude"}',
    f'sload {libpath / "tgen/maude/mastodonprofiles/markov/config_normal_3.maude"}',
    f'sload {libpath / "tgen/maude/mastodonprofiles/markov/config_normal_4.maude"}',
    '',
    '--- For SMC',
    f'sload {libpath / "common/maude/visibility"}',
    '',
    '--- Address mapping',
    f'sload scenario1_addresses',
  )

def mk_static_includes() -> Lines:
  return Lines(
    'pr SCHEDULER .',
    'pr USER-ACTION-ACTOR .',
    'pr SKYHOOK-UM-MAMODEL-1 .',
    'pr IRC-V2 .',
    'pr IRC-USER-ACTION-ACTOR-V2 .',
    'pr IRC-BYTESEQ-INTERFACE .',
    'pr CONTENT-MANAGER-SIMPLE-BI .',
    'inc ENC-DEC .',
    'inc CONTENT-MANAGER-BIDIR .',
    'inc MASTODON .',
    'inc MASTODON-CLIENT-CONFIG-MASTODON-BIDI-MAMODEL .',
    'inc MASTODON-SERVER-CONFIG-MASTODON-BIDI-MAMODEL .',
    'pr SKYHOOK .',
    'pr S3_PROTOCOL .',
    'pr IRC_MONITOR .',
    'pr OBFS4 .',
    'pr APP_CHATS .',
    'pr IRC_NODE .',
    'pr WEBTUNNEL .',
    'pr IRC_NAMES .',
    'pr IODINE_NODE .',
    'pr IODINE_DNS .',
    'pr TCP_SOCKET .',
    'pr NETWORK_NODE .',
    'pr NETWORK_CONNECTION .',
    'inc STRUCTURED-ADDRESSES .',
    'inc VISIBILITY .',
    'inc SCENARIO1-ADDRESSES .',
    '',
    '--- TGEN Modules',
    'inc USER-ACTION-ACTOR-V2 .',
    'inc FTP-TGEN .',
    'inc FTP-SERVER .',
    'inc GORILLACHAT-TGEN .',
    'inc MINIO-TGEN .',
    'inc DNS-TGEN .',
    'inc MAS-TGEN .',
    'inc IRC-TGEN .',
    '',
    '--- HCS IRC Profile Modules',
    'inc IRC-IRC-10-MAMODEL-V2 .',
    'inc IRC-IRC-11-MAMODEL-V2 .',
    'inc IRC-IRC-2-MAMODEL-V2 .',
    'inc IRC-IRC-3-MAMODEL-V2 .',
    'inc IRC-IRC-6-MAMODEL-V2 .',
    'inc IRC-IRC-7-MAMODEL-V2 .',
    '',
    '--- IRC TGEN Profile Modules',
    'inc IRC-TGEN-IRC-11-MAMODEL-V2 .',
    'inc IRC-TGEN-IRC-12-MAMODEL-V2 .',
    'inc IRC-TGEN-IRC-2-MAMODEL-V2 .',
    'inc IRC-TGEN-IRC-4-MAMODEL-V2 .',
    'inc IRC-TGEN-IRC-5-MAMODEL-V2 .',
    'inc IRC-TGEN-IRC-6-MAMODEL-V2 .',
    'inc IRC-TGEN-IRC-7-MAMODEL-V2 .',
    'inc IRC-TGEN-IRC-8-MAMODEL-V2 .',
    'inc IRC-TGEN-IRC-9-MAMODEL-V2 .',
    '',
    '--- FTP Profile Modules',
    'inc FTP-TGEN-FAST-MAMODEL-V2 .',
    'inc FTP-TGEN-MEDIUM-MAMODEL-V2 .',
    'inc FTP-TGEN-SLOW-MAMODEL-V2 .',
    '',
    '--- MinIO Profile Modules',
    'inc MINIO-TGEN-FAST-MAMODEL-V2 .',
    'inc MINIO-TGEN-MEDIUM-MAMODEL-V2 .',
    'inc MINIO-TGEN-SLOW-MAMODEL-V2 .',
    '',
    '--- Gorilla Profile Modules',
    'inc GORILLA-TGEN-IRC-1-MAMODEL-V2 .',
    'inc GORILLA-TGEN-IRC-10-MAMODEL-V2 .',
    'inc GORILLA-TGEN-IRC-11-MAMODEL-V2 .',
    'inc GORILLA-TGEN-IRC-12-MAMODEL-V2 .',
    'inc GORILLA-TGEN-IRC-2-MAMODEL-V2 .',
    'inc GORILLA-TGEN-IRC-3-MAMODEL-V2 .',
    'inc GORILLA-TGEN-IRC-4-MAMODEL-V2 .',
    'inc GORILLA-TGEN-IRC-5-MAMODEL-V2 .',
    'inc GORILLA-TGEN-IRC-6-MAMODEL-V2 .',
    'inc GORILLA-TGEN-IRC-7-MAMODEL-V2 .',
    'inc GORILLA-TGEN-IRC-8-MAMODEL-V2 .',
    'inc GORILLA-TGEN-IRC-9-MAMODEL-V2 .',
    '',
    '--- DNS Profile Modules (v1)',
    'inc DNS-CONFIG-FAST-1-MAMODEL .',
    'inc DNS-CONFIG-FAST-2-MAMODEL .',
    'inc DNS-CONFIG-FAST-3-MAMODEL .',
    'inc DNS-CONFIG-FAST-4-MAMODEL .',
    'inc DNS-CONFIG-NORMAL-1-MAMODEL .',
    'inc DNS-CONFIG-NORMAL-2-MAMODEL .',
    'inc DNS-CONFIG-NORMAL-3-MAMODEL .',
    'inc DNS-CONFIG-NORMAL-4-MAMODEL .',
    'inc DNS-CONFIG-SLOW-1-MAMODEL .',
    'inc DNS-CONFIG-SLOW-2-MAMODEL .',
    'inc DNS-CONFIG-SLOW-3-MAMODEL .',
    'inc DNS-CONFIG-SLOW-4-MAMODEL .',
    '',
    '--- Mastodon TGEN Profile Modules (v1)',
    'inc MASTODON-CONFIG-INFLUENCER-1-MAMODEL .',
    'inc MASTODON-CONFIG-INFLUENCER-2-MAMODEL .',
    'inc MASTODON-CONFIG-INFLUENCER-3-MAMODEL .',
    'inc MASTODON-CONFIG-INFLUENCER-4-MAMODEL .',
    'inc MASTODON-CONFIG-LURKER-1-MAMODEL .',
    'inc MASTODON-CONFIG-LURKER-2-MAMODEL .',
    'inc MASTODON-CONFIG-LURKER-3-MAMODEL .',
    'inc MASTODON-CONFIG-LURKER-4-MAMODEL .',
    'inc MASTODON-CONFIG-NORMAL-1-MAMODEL .',
    'inc MASTODON-CONFIG-NORMAL-2-MAMODEL .',
    'inc MASTODON-CONFIG-NORMAL-3-MAMODEL .',
    'inc MASTODON-CONFIG-NORMAL-4-MAMODEL .',
  )

def mk_static_model_map() -> Lines:
  return Lines(
    '"irc-irc-10" |-> irc-irc-10-ma-v2,',
    '"irc-irc-11" |-> irc-irc-11-ma-v2,',
    '"irc-irc-2" |-> irc-irc-2-ma-v2,',
    '"irc-irc-3" |-> irc-irc-3-ma-v2,',
    '"irc-irc-6" |-> irc-irc-6-ma-v2,',
    '"irc-irc-7" |-> irc-irc-7-ma-v2,',
    '"irc-tgen-irc-11" |-> irc-tgen-irc-11-ma-v2,',
    '"irc-tgen-irc-12" |-> irc-tgen-irc-12-ma-v2,',
    '"irc-tgen-irc-2" |-> irc-tgen-irc-2-ma-v2,',
    '"irc-tgen-irc-4" |-> irc-tgen-irc-4-ma-v2,',
    '"irc-tgen-irc-5" |-> irc-tgen-irc-5-ma-v2,',
    '"irc-tgen-irc-6" |-> irc-tgen-irc-6-ma-v2,',
    '"irc-tgen-irc-7" |-> irc-tgen-irc-7-ma-v2,',
    '"irc-tgen-irc-8" |-> irc-tgen-irc-8-ma-v2,',
    '"irc-tgen-irc-9" |-> irc-tgen-irc-9-ma-v2,',
    '"ftp-tgen-fast" |-> ftp-tgen-fast-ma-v2,',
    '"ftp-tgen-medium" |-> ftp-tgen-medium-ma-v2,',
    '"ftp-tgen-slow" |-> ftp-tgen-slow-ma-v2,',
    '"minio-tgen-fast" |-> minio-tgen-fast-ma-v2,',
    '"minio-tgen-medium" |-> minio-tgen-medium-ma-v2,',
    '"minio-tgen-slow" |-> minio-tgen-slow-ma-v2,',
    '"gorilla-tgen-irc-1" |-> gorilla-tgen-irc-1-ma-v2,',
    '"gorilla-tgen-irc-10" |-> gorilla-tgen-irc-10-ma-v2,',
    '"gorilla-tgen-irc-11" |-> gorilla-tgen-irc-11-ma-v2,',
    '"gorilla-tgen-irc-12" |-> gorilla-tgen-irc-12-ma-v2,',
    '"gorilla-tgen-irc-2" |-> gorilla-tgen-irc-2-ma-v2,',
    '"gorilla-tgen-irc-3" |-> gorilla-tgen-irc-3-ma-v2,',
    '"gorilla-tgen-irc-4" |-> gorilla-tgen-irc-4-ma-v2,',
    '"gorilla-tgen-irc-5" |-> gorilla-tgen-irc-5-ma-v2,',
    '"gorilla-tgen-irc-6" |-> gorilla-tgen-irc-6-ma-v2,',
    '"gorilla-tgen-irc-7" |-> gorilla-tgen-irc-7-ma-v2,',
    '"gorilla-tgen-irc-8" |-> gorilla-tgen-irc-8-ma-v2,',
    '"gorilla-tgen-irc-9" |-> gorilla-tgen-irc-9-ma-v2',
  )

def mk_static_images() -> Lines:
  return Lines(
    "image(1, 3779, 500)",
    ":: image(2, 2405, 1000)",
    ":: image(3, 36861, 1000)",
    ":: image(4, 25377, 500)",
    ":: image(5, 2440, 300)",
    ":: image(6, 1275, 300)",
    ":: image(7, 7710, 1000)",
    ":: image(8, 3577, 500)",
    ":: image(9, 3415, 300)",
    ":: image(10, 74123, 600)",
  )

def mk_static_zones() -> Lines:
  return Lines(
    "op zone : -> List{Record} .",
    "eq zone =",
    indented_lines(
      "< root, soa, 360000.0, soaData(360000.0) >",
      "< root, ns, 360000.0, 'a . 'root-servers . 'net . root >",
      "< 'a . 'root-servers . 'net . root, a, 360000.0, root-dns-addr >",
      "< 'com . root, ns, 360000.0, 'ns . 'com . root >",
      "< 'ns . 'com . root, a, 360000.0, tld-dns-addr >",),
    ".",
    "",
    "op zone-mas-com : -> List{Record} .",
    "eq zone-mas-com =",
    indented_lines(
      "< 'mas . 'com . root, soa, 360000.0, soaData(360000.0) >",
      "< 'mas . 'com . root, ns, 360000.0, 'ns . 'mas . 'com . root >",
      "< 'ns . 'mas . 'com . root, a, 360000.0, corp-mast-dns-addr >",
      "< 'tmp0 . 'mas . 'com . root, a, 0.0, 3 . 0 . 1 . 2 >",
      "< wildcard . 'mas . 'com . root, a, 0.0, 3 . 1 . 1 . 2 >",),
    ".",
    "",
    "op zone-rt-com : -> List{Record} .",
    "eq zone-rt-com =",
    indented_lines(
      "< 'rt . 'com . root, soa, 360000.0, soaData(360000.0) >",
      "< 'rt . 'com . root, ns, 360000.0, 'ns . 'rt . 'com . root >",
      "< 'ns . 'rt . 'com . root, a, 360000.0, corp-rt-dns-addr >",
      "< 'tmp0 . 'rt . 'com . root, a, 0.0, 3 . 0 . 1 . 2 >",
      "< wildcard . 'rt . 'com . root, a, 0.0, 3 . 1 . 1 . 2 >",),
    ".",
    "",
    "op zone-iod-com : -> List{Record} .",
    "eq zone-iod-com =",
    indented_lines(
      "< 'iod . 'com . root, soa, 360000.0, soaData(360000.0) >",
      "< 'iod . 'com . root, ns, 360000.0, 'ns . 'iod . 'com . root >",
      "< 'ns . 'iod . 'com . root, a, 360000.0, corp-iod-dns-addr >",
      "< 'tmp0 . 'iod . 'com . root, a, 0.0, 3 . 0 . 1 . 2 >",
      "< wildcard . 'iod . 'com . root, a, 0.0, 3 . 1 . 1 . 2 >",),
    ".",
    "",
    "op zone-obfs-com : -> List{Record} .",
    "eq zone-obfs-com =",
    indented_lines(
      "< 'obfs . 'com . root, soa, 360000.0, soaData(360000.0) >",
      "< 'obfs . 'com . root, ns, 360000.0, 'ns . 'obfs . 'com . root >",
      "< 'ns . 'obfs . 'com . root, a, 360000.0, corp-obfs-dns-addr >",
      "< 'tmp0 . 'obfs . 'com . root, a, 0.0, 3 . 0 . 1 . 2 >",
      "< wildcard . 'obfs . 'com . root, a, 0.0, 3 . 1 . 1 . 2 >",),
    ".",
    "",
    "op zone-sky-com : -> List{Record} .",
    "eq zone-sky-com =",
    indented_lines(
      "< 'sky . 'com . root, soa, 360000.0, soaData(360000.0) >",
      "< 'sky . 'com . root, ns, 360000.0, 'ns . 'sky . 'com . root >",
      "< 'ns . 'sky . 'com . root, a, 360000.0, corp-sky-dns-addr >",
      "< 'tmp0 . 'sky . 'com . root, a, 0.0, 3 . 0 . 1 . 2 >",
      "< wildcard . 'sky . 'com . root, a, 0.0, 3 . 1 . 1 . 2 >",),
    ".",
    "",
    "op zone-serv-com : -> List{Record} .",
    "eq zone-serv-com =",
    indented_lines(
      "< 'serv . 'com . root, soa, 360000.0, soaData(360000.0) >",
      "< 'serv . 'com . root, ns, 360000.0, 'ns . 'serv . 'com . root >",
      "< 'ns . 'serv . 'com . root, a, 360000.0, serv-dns-addr >",
      "< 'tmp0 . 'serv . 'com . root, a, 0.0, 3 . 0 . 1 . 2 >",
      "< wildcard . 'serv . 'com . root, a, 0.0, 3 . 1 . 1 . 2 >",),
    ".",
    "",
    "op zone-com : -> List{Record} .",
    "eq zone-com =",
    indented_lines(
      "< 'com . root, soa, 360000.0, soaData(360000.0) >",
      "< 'com . root, ns, 360000.0, 'ns . 'com . root >",
      "< 'ns . 'com . root, a, 360000.0, tld-dns-addr >",
      "< 'pwnd . 'com . root, ns, 360000.0, 'ns . 'pwnd . 'com . root >",
      "< 'ns . 'pwnd . 'com . root, a, 360000.0, auth-dns-addr >",
      "< 'internet . 'com . root, ns, 360000.0, 'ns . 'internet . 'com . root >",
      "< 'ns . 'internet . 'com . root, a, 360000.0, auth-dns-addr >",
      "< 'mas . 'com . root, ns, 360000.0, 'ns . 'mas . 'com . root >",
      "< 'ns . 'mas . 'com . root, a, 360000.0, corp-mas-dns-addr >",
      "< 'rt . 'com . root, ns, 360000.0, 'ns . 'rt . 'com . root >",
      "< 'ns . 'rt . 'com . root, a, 360000.0, corp-rt-dns-addr >",
      "< 'iod . 'com . root, ns, 360000.0, 'ns . 'iod . 'com . root >",
      "< 'ns . 'iod . 'com . root, a, 360000.0, corp-iod-dns-addr >",
      "< 'obfs . 'com . root, ns, 360000.0, 'ns . 'obfs . 'com . root >",
      "< 'ns . 'obfs . 'com . root, a, 360000.0, corp-obfs-dns-addr >",
      "< 'sky . 'com . root, ns, 360000.0, 'ns . 'sky . 'com . root >",
      "< 'ns . 'sky . 'com . root, a, 360000.0, corp-sky-dns-addr >",
      "< 'serv . 'com . root, ns, 360000.0, 'ns . 'serv . 'com . root >",
      "< 'ns . 'serv . 'com . root, a, 360000.0, serv-dns-addr >",),
    ".",
  )

def mk_static_resolver_caches() -> Lines:
  return Lines(
    "cacheEntry(< root, ns, 360000.0, 'a . 'root-servers . 'net . root >, 1)",
    "cacheEntry(< 'a . 'root-servers . 'net . root, a, 360000.0, rootDnsAddr >, 1)",
    "cacheEntry(< 'com . root, ns, 360000.0, 'ns . 'com . root >, 1)",
    "cacheEntry(< 'ns . 'com . root, a, 360000.0, tldDnsAddr >, 1)",
    "cacheEntry(< 'pwnd . 'com . root, ns, 360000.0, 'ns . 'pwnd . 'com . root >, 1)",
    "cacheEntry(< 'ns . 'pwnd . 'com . root, a, 360000.0, authDnsAddr >, 1)",
    "cacheEntry(< 'internet . 'com . root, ns, 360000.0, 'ns . 'internet . 'com . root >, 1)",
    "cacheEntry(< 'ns . 'internet . 'com . root, a, 360000.0, authDnsAddr >, 1)",
    "cacheEntry(< 't1 . 'pwnd . 'com . root, ns, 360000.0, 'ns . 't1 . 'pwnd . 'com . root >, 1)",
    "cacheEntry(< 'mas . 'com . root, ns, 360000.0, 'ns . 'mas . 'com . root >, 1)",
    "cacheEntry(< 'ns . 'mas . 'com . root, a, 360000.0, corpMasDnsAddr >, 1)",
    "cacheEntry(< 'rt . 'com . root, ns, 360000.0, 'ns . 'rt . 'com . root >, 1)",
    "cacheEntry(< 'ns . 'rt . 'com . root, a, 360000.0, corpRtDnsAddr >, 1)",
    "cacheEntry(< 'iod . 'com . root, ns, 360000.0, 'ns . 'iod . 'com . root >, 1)",
    "cacheEntry(< 'ns . 'iod . 'com . root, a, 360000.0, corpIodDnsAddr >, 1)",
    "cacheEntry(< 'obfs . 'com . root, ns, 360000.0, 'ns . 'obfs . 'com . root >, 1)",
    "cacheEntry(< 'ns . 'obfs . 'com . root, a, 360000.0, corpObfsDnsAddr >, 1)",
    "cacheEntry(< 'sky . 'com . root, ns, 360000.0, 'ns . 'sky . 'com . root >, 1)",
    "cacheEntry(< 'ns . 'sky . 'com . root, a, 360000.0, corpSkyDnsAddr >, 1)",
    "cacheEntry(< 'serv . 'com . root, ns, 360000.0, 'ns . 'serv . 'com . root >, 1)",
    "cacheEntry(< 'ns . 'serv . 'com . root, a, 360000.0, servDnsAddr >, 1)",
  )

def mk_static_chunk(addr_ctr: Counter, ixp_linktype) -> Cp3ConfigChunk:

  model_map = mk_static_model_map()
  images = mk_static_images()
  nameservers = mk_static_zones()
  resolver_caches = mk_static_resolver_caches()

  addr_pairs: list[tuple[str, str] | Insert] = [
    Insert(InsertType.BIND, Lines("--- Addresses for static HCS protocol actors")),
    ("irc-server-addr", f"a(srvN, srv, irc, srv, {addr_ctr()})"),
    ("s3-server-addr", f"a(minN, srv, min, srv, {addr_ctr()})"),
    ("irc-monitor-addr", f"a(srvN, srv, irc, cl, {addr_ctr()})"),
    ("iod-monitor-addr", f"a(srvN, srv, iod, cl, {addr_ctr()})"),
    ("mas-server-addr", f"a(masN, srv, mas, srv, {addr_ctr()})"),

    Insert(InsertType.BIND, Lines("")),
    ("adv-addr", f"a(ixpN, srv, irc, cl, {addr_ctr()})"),

    Insert(InsertType.BIND, Lines("", "--- Addresses for dns servers")),
    ("public-dns-addr", f"a(dnsN, dns, dns, srv, {addr_ctr()})"),
    ("root-dns-addr", f"a(dnsN, dns, dns, srv, {addr_ctr()})"),
    ("tld-dns-addr", f"a(dnsN, dns, dns, srv, {addr_ctr()})"),
    ("auth-dns-addr", f"a(dnsN, dns, dns, srv, {addr_ctr()})"),
    ("corp-mas-dns-addr", f"a(cl[1], dns, dns, cl, {addr_ctr()})"),
    ("corp-rt-dns-addr", f"a(cl[2], dns, dns, cl, {addr_ctr()})"),
    ("corp-iod-dns-addr", f"a(cl[3], dns, dns, cl, {addr_ctr()})"),
    ("corp-obfs-dns-addr", f"a(cl[4], dns, dns, cl, {addr_ctr()})"),
    ("corp-sky-dns-addr", f"a(cl[5], dns, dns, cl, {addr_ctr()})"),
    ("serv-dns-addr", f"a(srvN, dns, dns, cl, {addr_ctr()})"),

    #TODO are these really static?
    Insert(InsertType.BIND, Lines("", "--- Addresses for HCS protocol netclients - are these really static?")),
    ("corp-mas-netclient-addr", f"a(cl[1], udp, dns, cl, {addr_ctr()})"),
    ("corp-rt-netclient-addr", f"a(cl[2], udp, dns, cl, {addr_ctr()})"),
    ("corp-iod-netclient-addr", f"a(cl[3], udp, dns, cl, {addr_ctr()})"),
    ("corp-obfs-netclient-addr", f"a(cl[4], udp, dns, cl, {addr_ctr()})"),
    ("corp-sky-netclient-addr", f"a(cl[5], udp, dns, cl, {addr_ctr()})"),
    ("serv-netclient-addr", f"a(srvN, udp, dns, cl, {addr_ctr()})"),

    Insert(InsertType.BIND, Lines("")),
    ("public-resolver-netclient-addr", f"a(dnsN, udp, dns, cl, {addr_ctr()})"),

    Insert(InsertType.BIND, Lines("", "--- Addresses for tgen servers")),
    ("ftp-server-addr", f"a(srvN, tgen, ftp, srv, {addr_ctr()})"),
    ("minio-s3-server-addr", f"a(srvN, tgen, min, srv, {addr_ctr()})"),
  ]

  addr_decls, addr_binds = pairs_to_names_and_binds(addr_pairs)

  transports = Lines(
    "eq transport(s3SrvAddr) = tcp(s3SrvAddr) .",
    "eq transport(masSrvAddr) = tcp(masSrvAddr) .",
    "eq transport(ftpSrvAddr) = tcp(ftpSrvAddr) .",
    "eq transport(gorillaSrvAddr) = tcp(gorillaSrvAddr) .",
    "eq transport(minioS3SrvAddr) = tcp(minioS3SrvAddr) .",
    "eq transport(ircServerAddr) = tcp(ircServerAddr) .",
    "",
    "--- UDP transport for DNS resolvers",
    "eq transport(publicDnsAddr) = udp(publicDnsAddr) .",
    "eq transport(corpMasDnsAddr) = udp(corpMasDnsAddr) .",
    "eq transport(corpRtDnsAddr) = udp(corpRtDnsAddr) .",
    "eq transport(corpIodDnsAddr) = udp(corpIodDnsAddr) .",
    "eq transport(corpObfsDnsAddr) = udp(corpObfsDnsAddr) .",
    "eq transport(corpSkyDnsAddr) = udp(corpSkyDnsAddr) .",
    "eq transport(servDnsAddr) = udp(servDnsAddr) .",
    "eq transport(corpIodDnsAddr)    = corpIodDnsAddr .",
  )

  linktype_names = Lines(
    f'LinkType-Dns',
  )

  linktype_binds = Lines(
    f'eq LinkType-Dns =',
    indented_lines(
      f'(delayStd:  0.0),',
      f'(delayType: "Constant"),',
      f'(delayMean: 0.),',
      f'(delayConst: 0.001),',
      f'(noiseMin: 0.),',
      f'(noiseMax: 0.00001),',
      f'(dropP: 0.),',
      f'(canDrop: false),',
      f'(4stateLoss:',
      indented_lines(
        f'(p13: 0.0,',
        f'p31: 1.0,',
        f'p32: 0.0,',
        f'p23: 0.0,',
        f'p14: 0.0,',
        f'oneWayDelay: 0.01)',),
      f')',),
  )

  linkdata = Lines(
    "aaa(publicDnsAddr, corpMasDnsAddr, LinkType-Dns)",
    "aaa(corpMasDnsAddr, publicDnsAddr, LinkType-Dns)",
    "aaa(IXP-DEFAULT-ADDR, corpMasDnsAddr, LinkType-Dns)",
    "aaa(corpMasDnsAddr, IXP-DEFAULT-ADDR, LinkType-Dns)",
    "aaa(publicDnsAddr, corpRtDnsAddr, LinkType-Dns)",
    "aaa(corpRtDnsAddr, publicDnsAddr, LinkType-Dns)",
    "aaa(IXP-DEFAULT-ADDR, corpRtDnsAddr, LinkType-Dns)",
    "aaa(corpRtDnsAddr, IXP-DEFAULT-ADDR, LinkType-Dns)",
    "aaa(publicDnsAddr, corpIodDnsAddr, LinkType-Dns)",
    "aaa(corpIodDnsAddr, publicDnsAddr, LinkType-Dns)",
    "aaa(IXP-DEFAULT-ADDR, corpIodDnsAddr, LinkType-Dns)",
    "aaa(corpIodDnsAddr, IXP-DEFAULT-ADDR, LinkType-Dns)",
    "aaa(publicDnsAddr, corpObfsDnsAddr, LinkType-Dns)",
    "aaa(corpObfsDnsAddr, publicDnsAddr, LinkType-Dns)",
    "aaa(IXP-DEFAULT-ADDR, corpObfsDnsAddr, LinkType-Dns)",
    "aaa(corpObfsDnsAddr, IXP-DEFAULT-ADDR, LinkType-Dns)",
    "aaa(publicDnsAddr, corpSkyDnsAddr, LinkType-Dns)",
    "aaa(corpSkyDnsAddr, publicDnsAddr, LinkType-Dns)",
    "aaa(IXP-DEFAULT-ADDR, corpSkyDnsAddr, LinkType-Dns)",
    "aaa(corpSkyDnsAddr, IXP-DEFAULT-ADDR, LinkType-Dns)",
    "aaa(publicDnsAddr, servDnsAddr, LinkType-Dns)",
    "aaa(servDnsAddr, publicDnsAddr, LinkType-Dns)",
    "aaa(IXP-DEFAULT-ADDR, servDnsAddr, LinkType-Dns)",
    "aaa(servDnsAddr, IXP-DEFAULT-ADDR, LinkType-Dns)",
    "aaa(publicDnsAddr, IXP-DEFAULT-ADDR, LinkType-Dns)",
    "aaa(IXP-DEFAULT-ADDR, publicDnsAddr, LinkType-Dns)",
    "aaa(ftpSrvAddr, IXP-DEFAULT-ADDR, LinkType-Ixp)",
    "aaa(IXP-DEFAULT-ADDR, ftpSrvAddr, LinkType-Ixp)",
    "aaa(gorillaSrvAddr, IXP-DEFAULT-ADDR, LinkType-Ixp)",
    "aaa(IXP-DEFAULT-ADDR, gorillaSrvAddr, LinkType-Ixp)",
    "aaa(minioS3SrvAddr, IXP-DEFAULT-ADDR, LinkType-Ixp)",
    "aaa(IXP-DEFAULT-ADDR, minioS3SrvAddr, LinkType-Ixp)",
  )

  actor_pairs = [
    Insert(InsertType.BIND, Lines("", "--- Static HCS protocol actors")),
    ("irc-server", "mkIrcServer(irc-server-addr)"),
    ("s3-server", "makeS3Server(s3-server-addr)"),
    ("mas-server", "makeMastodonServer(mas-server-addr)"),
    ("iod-monitor", "mkWMonitor(iod-monitor-addr)"),

    Insert(InsertType.BIND, Lines("")),
    ("adv", "mkAdversaryCp3(adv-addr)"),

    # TODO: this is wrong I think, I think these are specific to subnets (maybe only when they have NAT enabled?) anyways, they're not static.
    # They probably need to live in __init__, and we'll need  to keep a dictionary mapping subnet names to dns addrs names.
    Insert(InsertType.BIND, Lines("", "--- DNS server actors")),
    ("corp-mas-dns", "mkNameServer(corp-mas-dns-addr, (zone-mas-com), public-dns-addr)"),
    ("corp-rt-dns", "mkNameServer(corp-rt-dns-addr, (zone-rt-com), public-dns-addr)"),
    ("corp-iod-dns", "mkNameServer(corp-iod-dns-addr, (zone-iod-com), public-dns-addr)"),
    ("corp-obfs-dns", "mkNameServer(corp-obfs-dns-addr, (zone-obfs-com), public-dns-addr)"),
    ("corp-sky-dns", "mkNameServer(corp-sky-dns-addr, (zone-sky-com), public-dns-addr)"),
    ("serv-dns", "mkNameServer(serv-dns-addr, (zone-serv-com), public-dns-addr)"),

    Insert(InsertType.BIND, Lines("")),
    ("root-dns", "mkNameServer(root-dns-addr, (zone), nullAddr)"),
    ("tld-dns", "mkNameServer(tld-dns-addr, (zone-com), nullAddr)"),
    ("auth-dns", "mkNameServer(auth-dns-addr, (zone-internet-com), nullAddr)"),

    Insert(InsertType.BIND, Lines("")),
    ("public-resolver", "mkResolver(public-dns-addr, resolver-cache, sb)"),

    # TODO: again, are these actually static?
    Insert(InsertType.BIND, Lines("", "--- Static HCS protocol netclient actors - again, are these really static?")),
    ("corp-mas-netclient", "makeNetClient(corp-mas-netclient-addr, public-dns-addr, corp-mas-dns-addr, true)"),
    ("corp-rt-netclient", "makeNetClient(corp-rt-netclient-addr, public-dns-addr, corp-rt-dns-addr, true)"),
    ("corp-iod-netclient", "makeNetClient(corp-iod-netclient-addr, public-dns-addr, corp-iod-dns-addr, true)"),
    ("corp-obfs-netclient", "makeNetClient(corp-obfs-netclient-addr, public-dns-addr, corp-obfs-dns-addr, true)"),
    ("corp-sky-netclient", "makeNetClient(corp-sky-netclient-addr, public-dns-addr, corp-sky-dns-addr, true)"),
    ("serv-netclient", "makeNetClient(serv-netclient-addr, public-dns-addr, serv-dns-addr, true)"),
    ("public-resolver-netclient", "makeNetClient(public-resolver-netclient-addr, public-dns-addr, public-dns-addr, true)"),

    Insert(InsertType.BIND, Lines("", "--- Static tgen servers")),
  ]

  # TODO: wasn't sure about the others, cuz they seem like netservers and I thought netservers were one-to-one with clients?
  # ftpSrvAct ftpNetSrvAct
  # gorillaSrvAct gorillaNetSrvAct
  # minioS3SrvAct
  # ircTgenSrvNet

  ftp_server_lines = Lines(
    "eq ftp-server = mkFtpServerA(ftp-server-addr) ."
  )
  
  minio_s3_server_lines = Lines(
    "eq minio-s3-server =",
    indented_lines(
      "< minio-s3-server-addr : AwsS3HttpServer | ",
      indented_lines(
        "s3DataMap: (",
        indented_lines(
          "(\"/tgen/list-1\" -> restToByteSeq(\"obj1.zip;obj2.zip;data/\")) ;",
          "(\"/tgen/stat-1\" -> restToByteSeq(\"obj1.zip:1024:2025-01-01\")) ;",
          "(\"/tgen/cd-1\" -> restToByteSeq(\"subdir1/;subdir2/\")) ;",
          "(\"/tgen/retr-1\" -> restToByteSeq(\"mock_file_content_bytes\"))",),
        ")",),
    ">",),
  )

  actor_decls, actor_binds = pairs_to_names_and_binds(actor_pairs)
  actor_decls = actor_decls.join(Lines("ftp-server, minio-s3-server"))
  actor_binds = actor_binds.join(Lines(ftp_server_lines, minio_s3_server_lines))

  init_actors = Lines(
    "irc-server s3-server iodine-monitor mas-server",
    "mkIrcMonitor(irc-monitor-addr)",
    "serv-dns serv-netclient",
    "adv",
    "",
    "public-resolver public-resolver-netclient",
    "root-dns tld-dns auth-dns",
    "",
    "ftp-server",
    "minio-s3-server",
    "corp-mas-dns",
    "corp-mas-netclient",
  )


  return Cp3ConfigChunk(
    images=images,
    model_map=model_map,
    zones=nameservers,
    resolver_cache=resolver_caches,
    addr_decls=addr_decls,
    addr_binds=addr_binds,
    transports=transports,
    linktype_decls=linktype_names,
    linktype_binds=linktype_binds,
    linkdata=linkdata,
    actor_decls=actor_decls,
    actor_binds=actor_binds,
    init_actors=init_actors,
    # There are no static initial trigger messages
    # There are no static clients
  )
  