load ./mastodon

set print attribute on .
set show advisories off .

mod MASTODON_TEST is

  inc MASTODON .

  ops alice-raceboat bob-raceboat mastodon-client mastodon-server : -> Address .

  --- Initial configuration.

  op initConfig : -> Config .
  eq initConfig = 
    < mastodon-client : MasClient |
      thisAddr: mastodon-client,
      masServerAddr: mastodon-server,
      opStack: emptyOpStack,
      postingMedia: emptyMediaFilenameList,
      postingMediaIds: emptyMasIdList,
      postingText: "",
      gettingMediaUrls: emptyUrlList,
      gettingMedias: emptyMediaFilenameList,
      gettingPosts: emptyMasIdList
    >
    < mastodon-server : MasServer |
      thisAddr: mastodon-server,
      currentMapId: 0,
      tootMap: emptyIdTootMap,
      mediaMap: emptyIdMediaMap      
    >
    (to mastodon-client : GetMediaHashtag("DUMMY"))
    .
endm


