--- MAUDE_HCS: maude_hcs
---
--- Software Markings (UNCLASS)
--- PWNDD Software
---
--- Copyright (C) 2025 RTX BBN Technologies Inc. All Rights Reserved
---
--- Contract No: HR00112590083
--- Contractor Name: RTX BBN Technologies Inc.
--- Contractor Address: 10 Moulton Street, Cambridge, Massachusetts 02138
---
--- The U.S. Government's rights to use, modify, reproduce, release, perform,
--- display, or disclose these technical data and software are defined in the
--- Article VII: Data Rights clause of the OTA.
---
--- This document does not contain technology or technical data controlled under
--- either the U.S. International Traffic in Arms Regulations or the U.S. Export
--- Administration Regulations.
---
--- DISTRIBUTION STATEMENT A: Approved for public release; distribution is
--- unlimited.
---
--- Notice: Markings. Any reproduction of this computer software, computer
--- software documentation, or portions thereof must also reproduce the markings
--- contained herein.
---
--- MAUDE_HCS: end


load ./mastodon

set print attribute on .
set show advisories off .

mod MASTODON_TEST is

  inc MASTODON .

  ops alice-raceboat bob-raceboat mastodon-client mastodon-server : -> Address .

  --- Initial configuration.

  op initConfig : -> Config .
  eq initConfig = 
    < mastodon-client : MasClient |
      thisAddr: mastodon-client,
      masServerAddr: mastodon-server,
      opStack: emptyOpStack,
      postingMedia: emptyMediaFilenameList,
      postingMediaIds: emptyMasIdList,
      postingText: "",
      gettingMediaUrls: emptyUrlList,
      gettingMedias: emptyMediaFilenameList,
      gettingPosts: emptyMasIdList
    >
    < mastodon-server : MasServer |
      thisAddr: mastodon-server,
      currentMapId: 3, ---0,
      tootMap: (3 ~> makeToot("This is the #media toot with media", makeUrl(makeMediaFilename("img0.jpg")) ; makeUrl(makeMediaFilename("img2.jpg")))), --- emptyIdTootMap,
      mediaMap: ((1 ~>(makeMediaFilename("img0.jpg"), makeUrl(makeMediaFilename("img0.jpg")))) : 
                 (2 ~>(makeMediaFilename("img1.jpg"), makeUrl(makeMediaFilename("img1.jpg")))) :
                 (3 ~>(makeMediaFilename("img2.jpg"), makeUrl(makeMediaFilename("img2.jpg"))))), --- emptyIdMediaMap, 
      tagMap: (makeTag("media") ~> 3) --- emptyTagPostIdsMap
    >
---    (to mastodon-client from alice-raceboat : PostStatus("This is the toot"))
---    (to mastodon-client from alice-raceboat : PostStatus("This is the #tag toot"))
---    (to mastodon-client from alice-raceboat : PostMedia(makeMediaFilename("cat.jpg")))
---    (to mastodon-client from alice-raceboat : PostStatus("This is the #media toot with media", (makeMediaFilename("img0.jpg") :: makeMediaFilename("img1.jpg"))))
---    (to mastodon-client from alice-raceboat : GetPost(3))
---    (to mastodon-client from alice-raceboat : GetMedia(makeUrl(makeMediaFilename("img1.jpg"))))
    (to mastodon-client from alice-raceboat : GetMediaHashtag(makeTag("media")))
    .
endm


