load ./mastodon

set print attribute on .
set show advisories off .

mod MASTODON_TEST is

  inc MASTODON .

  ops alice-raceboat bob-raceboat mastodon-client mastodon-server : -> Address .

  --- Initial configuration.

  op initConfig : -> Config .
  eq initConfig = 
    < mastodon-client : MasClient |
      thisAddr: mastodon-client,
      masServerAddr: mastodon-server,
      opStack: emptyOpStack,
      postingMedia: emptyMediaFilenameList,
      postingMediaIds: emptyMasIdList,
      postingText: "",
      gettingMediaUrls: emptyUrlList,
      gettingMedias: emptyMediaFilenameList,
      gettingPosts: emptyMasIdList
    >
    < mastodon-server : MasServer |
      thisAddr: mastodon-server,
      currentMapId: 3, ---0,
      tootMap:(3 ~> makeToot("This is the #media toot with media", makeUrl ; makeUrl)), --- emptyIdTootMap,
      mediaMap: ((1 ~>(makeMediaFilename("img0.jpg"), makeUrl)) : 2 ~>(makeMediaFilename("img1.jpg"), makeUrl)), --- emptyIdMediaMap, 
      tagMap: (makeTag("media") ~> 3) --- emptyTagPostIdsMap
    >
---    (to mastodon-client from alice-raceboat : PostStatus("This is the toot"))
---    (to mastodon-client from alice-raceboat : PostStatus("This is the #tag toot"))
---    (to mastodon-client from alice-raceboat : PostMedia(makeMediaFilename("cat.jpg")))
---    (to mastodon-client from alice-raceboat : PostStatus("This is the #media toot with media", (makeMediaFilename("img0.jpg") :: makeMediaFilename("img1.jpg"))))
    (to mastodon-client from alice-raceboat : GetMediaHashtag(makeTag("media")))
    .
endm


