--- MAUDE_HCS: maude_hcs
---
--- Software Markings (UNCLASS)
--- Maude-HCS Software
---
--- Copyright (C) 2025 RTX BBN Technologies Inc. All Rights Reserved
---
--- The computer software and computer software documentation are licensed
--- under the Apache License, Version 2.0 (the "License"); you may not use
--- this file except in compliance with the License. A copy of the License
--- is provided in the LICENSE file, but you may obtain a copy of the
--- License at:  https://www.apache.org/licenses/LICENSE-2.0
---
--- The computer software and computer software documentation are based
--- upon work supported by the Defense Advanced Research Projects Agency (DARPA)
--- under Agreement No. HR00l 12590083.
---
--- This document does not contain technology or technical data controlled under
--- either the U.S. International Traffic in Arms Regulations or the U.S. Export
--- Administration Regulations.
---
--- DISTRIBUTION STATEMENT A: Approved for public release; distribution is
--- unlimited.
---
--- Notice: Markings. Any reproduction of this computer software, computer
--- software documentation, or portions thereof must also reproduce the markings
--- contained herein. Refer to the provided NOTICE file.
---
--- MAUDE_HCS: end

**** sload ../common/maude/markov-action-model.maude
**** sload ../common/maude/cp2-interfaces 
sload cm-aux-oneHash.maude
**** sload user-interface 

***(
req/rsp for CMServer

UM -actionQ(downloadAct)-> CMC 
    (replyTo: ummsg)
            [ht := curHashtag]  --- pend if any, ow bHash
            CMC -fetchQ(ht)-> MC
    (w4c: mcmsg)
            CMC <fetchR(images) - MC
            [process fetch results ]
    (if file complete
     then [Bob <file,ht- CMS]
     else null fi)
    (w4c: null)            
UM <actionR("ok")- CMC   
    (replyTo: null)
)

fmod RB-DEFRAGMENT is
  inc BYTESEQ .

vars bytes bytes0 efrag ef efile : ByteSeq .
vars efl efl1 efl0 : ByteSeqL .
vars id n j k l l0 cap tot tot0 oh ix ix0  : Nat .
vars fragMx last accum : Nat .
vars fls fls0 fls1 : FragLSet .

sorts  FragLElt FragLSet  .
subsort FragLElt < FragLSet  .
op mtFragL : -> FragLSet [ctor] .
op fle : ByteSeqL -> FragLElt .
op __ : FragLSet FragLSet -> FragLSet 
[ctor assoc comm id: mtFragL] .

---- accumulate efragments of file in lists sorted by ix
---- if efl is sorted by increasing ix
---- then addEfrags(efl0,efl) is sorted by inc ix
op addEfrags : ByteSeqL FragLSet -> FragLSet .
op addEfrag : ByteSeq ByteSeqL ByteSeqL -> ByteSeqL .
op addEfrag2Fls : ByteSeq FragLSet -> FragLSet .

eq addEfrags(nilBS,fls) = fls . 
eq addEfrags(ef :: efl0, fls) =
      addEfrags(efl0, addEfrag2Fls(ef,fls)) .

--- fragment of accumulating file
eq addEfrag2Fls(efrag(bytes,tot,ix,l),
                fle(efrag(bytes,tot0,ix0,l0) :: efl) fls)
   = fle(addEfrag(efrag(bytes,tot,ix,l),
                  efrag(bytes,tot0,ix0,l0) :: efl, nilBS))
     fls                  
  .
---- fragment of new file
eq addEfrag2Fls(ef,fls) = fle(ef) fls [owise] .

**************************
eq addEfrag(ef,nilBS,efl) =  efl :: ef .
eq addEfrag(efrag(bytes,tot,ix,l),
            efrag(bytes,tot0,ix0,l0) :: efl0,efl)  = 
 (if ix < ix0
 then  efl :: efrag(bytes,tot,ix,l) ::
       efrag(bytes,tot0,ix0,l0) :: efl0
 else (if ix == ix0   ---- drop duplicates
       then efl :: efrag(bytes,tot0,ix0,l0) :: efl0
       else addEfrag(efrag(bytes,tot,ix,l), efl0, 
               efl :: efrag(bytes,tot0,ix0,l0) ) 
     fi) fi)
.

**** Should not happen
eq addEfrag(efrag(bytes,tot,ix,l),
          efrag(bytes0,tot0,ix0,l0) :: efl0,
          efl)  = 
         efl :: efrag(bytes0,tot0,ix0,l0) :: efl0 
 [owise print "Bad frag dropped " bytes " expected " bytes0]
  .

---- efl is sorted by ix,  should have 0 1 ... last
op efraglComplete? : ByteSeqL -> ByteSeqL . --- nil or efile
op efraglComplete?X : ByteSeqL Nat -> Bool .
op hasLastFrag : ByteSeqL -> ByteSeqL .

eq efraglComplete?(efl) = 
   (if efraglComplete?X(efl,0) 
    then hasLastFrag(efl) 
    else nilBS
    fi) .
   
eq efraglComplete?X(efrag(efile,tot,ix,l) :: efl, ix)
     =  efraglComplete?X(efl, s ix) .
eq  efraglComplete?X(nilBS, ix) = true .
eq  efraglComplete?X(efl,ix) = false [owise] .

eq hasLastFrag(efl :: efrag(efile,tot,ix,l)) 
   =
   (if tot >= nbytes(efile) 
    then efile
    else nilBS
    fi )
   .   
   
eq hasLastFrag(efl) = nilBS [owise] .

endfm


mod CONTENT-MANAGER-RECEIVER-AUX is
  inc CONTENT-MANAGER .
  inc CP2_SORTS .  ---- AttributeSetMsgs from _aux
  inc CP2-COMMON .
  inc RB-DEFRAGMENT .
  inc MC-INTERFACE  .
  inc ED-INTERFACE .
  inc TGEN-INTERFACE .
****  inc USER-INTERFACE .

vars attrs attrs0 attrs1 attrs2 hattrs hattrs0 : AttributeSet .
vars cmsAtts cmsAtts1 cmsAtts2 : AttributeSet .
vars msg msg0 msg1 : Msg .
vars msgs msgs0 config config0 : Config .
vars j j1 i k l n cap : Nat .
vars bAddr cmsAddr umAddr edAddr mcAddr : Address .
vars T : Float .
vars mcResponse : Content .
vars efile efrag image ht hashtag bytes : ByteSeq .
vars efilel efragl efragl0 efragl1 efragl3 imagel hashtagl efl : ByteSeqL .
vars str : String .
vars ract : Map{String,JV} .

vars  cmAddr rcvAddr : Address .
vars  fls fls1 fls0 fls2 : FragLSet .

op pendingFragLs:_ : FragLSet -> Attribute [ctor] .
op getPendingFragLs : AttributeSet -> FragLSet .
op setPendingFragLs : AttributeSet FragLSet 
                       -> AttributeSet .

eq getPendingFragLs((attrs, pendingFragLs: fls)) = fls .
eq getPendingFragLs(attrs) = mtFragL [owise] .
eq setPendingFragLs((attrs, pendingFragLs: fls), fls0) 
    = (attrs, pendingFragLs: fls0) .
eq setPendingFragLs(attrs, fls0) =
     (attrs, pendingFragLs: fls0) [owise] .


op srcvActionQ : AttributeSet String Msg
                   -> AttributeSetMsgs . 

ceq srcvActionQ(attrs,str,msg) = {attrs,msg0}
if (to cmsAddr from umAddr : actionQ(ract)) := msg
/\ msg0 := (to umAddr from cmsAddr : actionR("notRecognized"))
 [owise] .

---- download case fetch using current W hashTag 
---- until fragments assembled and forwarded
ceq srcvActionQ(attrs, "download", msg0) = {attrs2,msg}
if (to cmsAddr from umAddr : actionQ(ract) ) := msg0
/\ attrs0, replyTo: null, w4c: null := attrs
/\ attrs1, mcAddress: mcAddr := attrs
/\ hashtag := getWHashtag(getRcvHashTagAttrs(attrs))
/\ msg1 := (to mcAddr from cmsAddr : fetchQ(hashtag))
/\ msg := (to mcAddr from cmsAddr : 
             translateFetchQ(fetchQ(hashtag)))
/\ attrs2 := attrs0, replyTo: msg0, w4c: msg1
**** [ print "Raceboat cm : cmsAddr " got fetch request, set replyTo " msg0 " and w4c " msg1 ]
.


vars  mediaFileList : MediaFileList .
vars  tag : Tag .

 ---- rcv fetchR , ask ed to decode imagel
 ---- only fetching with weird hash tags
 
op srcvFetchR : AttributeSet Msg -> AttributeSetMsgs .
eq srcvFetchR(attrs,msg) = {attrs,null} [owise] .

---- w Hashtag download no images
ceq srcvFetchR(attrs,(to cmsAddr from mcAddr :
                       fetchR(nilBS,ht)) )  
         = {attrs2,msg}
if attrs0, w4c: (to mcAddr from cmsAddr : fetchQ(ht)),
    replyTo: (to cmsAddr from umAddr : actionQ(ract))
           := attrs
**** assume responses to earlier hts won't occur
/\ msg := (to umAddr from cmsAddr : actionR("ok"))
/\ attrs2 := attrs0,  w4c: null, replyTo: null
**** [ print "Raceboat server has download of pending hashtag " ht ", no images." ]
.   
 
---- wHashtag download non nil result
ceq srcvFetchR(attrs,(to cmsAddr from mcAddr :
                       fetchR(image :: imagel,ht)) )  
         = {attrs2,msg}
if attrs0, w4c: (to mcAddr from cmsAddr : fetchQ(ht)) 
           := attrs
/\ attrs1,  edAddress: edAddr := attrs
/\ msg := 
    (to edAddr from cmsAddr : decQ(image :: imagel))    
/\ attrs2 := attrs0,  w4c: msg
**** [ print "Raceboat server has weird download for tag " ht  ]
.    

var efileX : ByteSeqL .


op srcvDecR : AttributeSet  Msg -> AttributeSetMsgs .
 ---- add efragl to current fragls
 ----  clear w4c, clear replyTO
 ---- msg0 - status to umAddr
 ---- msgs -- for complete fragl elements

 eq srcvDecR(attrs, msg) = {attrs,null}
[owise print "srcvDecR no match for msg " msg] .

 ceq srcvDecR(attrs, 
            (to cmsAddr from edAddr : decR(efragl))) 
    = {attrs2, msg0 msgs}
if attrs0, w4c: (to edAddr from cmsAddr : decQ(imagel)),
   replyTo: (to cmsAddr from umAddr : actionQ(ract))
  := attrs    
/\ fls0 := getPendingFragLs(attrs)   
/\ fls1 := addEfrags(efragl,fls0)
/\ {pendingFragLs: fls2, msgs} := 
      sendCompletedFiles(pendingFragLs: fls1,
               umAddr, cmsAddr,getReceiverAddress(attrs))
/\ msg0 := (to umAddr from cmsAddr : actionR("ok"))
/\ hattrs := (if msgs == null
              then getRcvHashTagAttrs(attrs0)
              else nextWHashtag( 
                      getRcvHashTagAttrs(attrs0))
               fi)
/\ attrs2 := setPendingFragLs(
               setRcvHashTagAttrs(attrs0,hattrs),
               fls2),
             w4c: null, replyTo: null
       .        



op sendCompletedFiles : 
      AttributeSet Address Address Address 
      -> AttributeSetMsgs . 
op sendCompletedFilesX :
     AttributeSet Address Address Address FragLSet Config
     -> AttributeSetMsgs . 

eq sendCompletedFiles(attrs,umAddr,cmAddr,rcvAddr)  =
    sendCompletedFilesX(attrs,umAddr,cmAddr,rcvAddr,
                        mtFragL,null) .
    
ceq sendCompletedFilesX(attrs,umAddr,cmAddr,rcvAddr,
                        fls,msgs) 
  = {(attrs0, pendingFragLs: fls), msgs}
 if attrs0, pendingFragLs: mtFragL := attrs
.

ceq sendCompletedFilesX(attrs,umAddr,cmAddr,rcvAddr,
                        fls,msgs) 
  = sendCompletedFilesX((attrs0,pendingFragLs: fls0),
            umAddr,cmAddr,rcvAddr,fls fls1, msgs msgs0)
 if attrs0, pendingFragLs: (fle(efl) fls0) := attrs
 /\ efileX := efraglComplete?(efl)
 /\ fls1 := (if efileX == nilBS
                then fle(efl) else mtFragL fi)
 /\ msg0 := (to umAddr from cmAddr : actionR("ok"))
 /\ msgs0 :=
       (if efileX == nilBS 
        then null
        else (to rcvAddr from cmAddr : efileX )
       fi)
.


endm

**** sload ../tgen/maude/mas-mamodel

mod CM-RECEIVER-TEST is
  inc CONTENT-MANAGER-RECEIVER-AUX .

ops cmA edA mcA rcvA umA : -> Address .

op F0 : -> ByteSeq .
eq F0 = file(0,20) .

op FR0 : -> ByteSeq .
eq FR0 =  efrag(F0,20,0,20) .     


op F1 : -> ByteSeq .
eq F1 = file(0,120) .

ops FR1x0 FR1x1 : -> ByteSeq .
eq FR1x0 =  efrag(F1,60,0,60) .     
eq FR1x1 =  efrag(F1,120,1,60) .     

ops FrLS0  FrLS01 FrLS1x10 FrLS1x1 : -> FragLSet .
eq FrLS0 = addEfrags(FR0,mtFragL) .
eq FrLS1x1 = addEfrags(FR1x1,mtFragL) .
eq FrLS1x10 = addEfrags(FR1x0,FrLS1x1) .
eq FrLS01 = addEfrags(FR1x1 :: FR1x0, FrLS0) .

**** fle(efrag(file(0, 120), 60, 0, 60) :: efrag( file(0, 120), 120, 1, 60)) 
**** fle(efrag(file(0, 20), 20, 0, 20))

ops AtMsg0 AtMsg1x1 AtMsg1x10 AtMsg01
     : -> AttributeSetMsgs .
eq AtMsg0 =
  sendCompletedFiles(pendingFragLs: FrLS0,umA,cmA,rcvA) .
***( {pendingFragLs: mtFragL, 
      to rcvA from cmA : file(0, 20)} )      
      
eq AtMsg1x1 =
 sendCompletedFiles(pendingFragLs: FrLS1x1,umA,cmA,rcvA) .
***( {pendingFragLs: fle(efrag(file(0, 120), 120, 1, 60)),
      null})

eq AtMsg1x10 =
 sendCompletedFiles(pendingFragLs: FrLS1x10,umA,cmA,rcvA) .
***({pendingFragLs: mtFragL, 
     to rcvA from cmA : file(0, 120)})

eq AtMsg01 =
 sendCompletedFiles(pendingFragLs: FrLS01,umA,cmA,rcvA) .
***( {pendingFragLs: mtFragL, (to rcvA from
    cmA : file(0, 20)) to rcvA from cmA : file(0, 120)})


***(
red  sendCompletedFiles(pendingFragLs: (FrLS0 FrLS1x1),umA,cmA,rcvA) .

 {pendingFragLs: fle(efrag(file(0, 120), 120, 1, 60)), 
)
endm
eof









ops wTAG0  bTAG0 : -> Tag .
eq wTAG0 = hashtag2tag(wHT0) .
eq bTAG0 = hashtag2tag(bHT0) .
op wHT0 : -> ByteSeq .
eq wHT0 = hashTag("man") .

op bHT0 : -> ByteSeq .
eq bHT0 = hashTag("meow") .

ops Mhash Mmedia Mdown MencR MencR0 MdecR MtootR 
 MfetchRb  MfetchRw0  MfetchRw MrequestR
   : -> ActiveMsg .

---- rew CMS Mhash .
---- CMSh

---- crl [rbs-rcv-actionQ] :
eq Mmedia =
  {0.2,(to cmsA from umA : 
           actionQ(("type" |->  js("media")) ) )} .
---- pendingFiles: nilBS or EF0
---- (w4c: null), (replyTo: null), 
 
---- rew CMS Mmedia .  #
--- CMSm = 

**** [0.0, to edA from cmsA : encQ(noBytes), 0]
***** FIX rcv encR

eq Mdown = 
  {0.2,(to cmsA from umA : 
         actionQ(("type" |->  js("download")) ) )} .
---- (w4c: null), (replyTo: null), 
---- rew CMS Mdown .  #
---- CMSd 

**** [0.0, to mcA from cmsA : GetMediaHashtag(makeTag("meow")), 0]


---- rew CMSh Mdown .   #
--- CMShd = 
**** [0.0, to mcA from cmsA : GetMediaHashtag(makeTag("man")), 0]

***(
eq MfetchRw = 
   {2.0,(to cmsA from mcA :  fetchR(nilBS,wHT0))} .
eq MfetchRb = 
  {2.0,(to cmsA from mcA :  fetchR(IM0,bHT0))} .
eq MfetchRw0 = 
    {2.0,(to cmsA from mcA : fetchR(IM00,wHT0))} .
)
---- rcv fetch response from mcAddr
---- crl [rbs-rcv-fetchR] :
eq MfetchRw = {2.0,(to cmsA from mcA : 
           ResponseMediaList(wTAG0,emptyMediaFileList) )} .
eq MfetchRb = 
  {2.0,(to cmsA from mcA : ResponseMediaList(bTAG0,MF0))} .
eq MfetchRw0 = {2.0,(to cmsA from mcA : 
                      ResponseMediaList(wTAG0,MF00))} .
    
---- rew CMSd MfetchRb .  #
**** [0.0, to umA from cmsA : actionR("ok"), 0]

---- rew CMShd MfetchRw .  #
**** [0.0, to umA from cmsA : actionR("ok"), 0]

---- rew CMShd MrequestR .  #
---- CMShd
---- rew CMShd MfetchRw0 . #


---- rcv dec response from edAddr
---- crl [rbs-rcv-decR] :
--- need w4c and replyTo non null

---- rew CMShdf MdecR .   #
---- CMS  
---- crl [rbs-rcv-encR] :
eq MencR = {2.0, (to cmsA from edA :  encR(IM00) )} .
eq MencR0 = {2.0, (to cmsA from edA :  encR(IM0) )} .

---- rew CMSm MencR0 .   #
--- CMSme  

**** [0.0, to mcA from cmsA : PostStatus("hashtag is #meow", makeMediaFile(makeMediaFilename(image(0, 500, 50)), 500, image(0, 500, 50))), 0]

---- crl [rbs-rcv-tootR] :
**** eq MtootR =  {2.5,(to cmsA from mcA :  tootR("ok") )} .
eq MtootR =  {2.5,(to cmsA from mcA : 
                    mkRequestResponse("ok") )} .
eq MrequestR = 
{2.0,(to cmsA from mcA : mkRequestResponse("ACCEPT") )} .

 
---- rew CMSme MrequestR .  #

**** [0.0, to umA from cmsA : actionR("ok"), 0]


endm  

eof

Tests

CMS Mhash -> CMSh
CMS Mmedia -> CMSm MencR ->  CMSme MtootR -> .
CMS Mdown -> CMSd MfetchRb -> .
CMSh Mdown -> CMShd MfetchRw -> CMShdf ~ CMShd ~ .
              CMShd MfetchRw0 -> CMShdf MdecR ->  .
##







