import json
import os
import sys
import re

# Standard header from the provided example
HEADER = """--- MAUDE_HCS: this file is autogenerated by maude_hcs ---

load ../../../common/maude/markov-action-model.maude"""


class JsonToMaudeParser:
    def __init__(self, model_name="dns"):
        self.model_name = model_name

    def format_float(self, val):
        """Ensures floats look like 1.0 instead of 1"""
        s = str(float(val))
        return s

    def to_maude_jv(self, val, indent=0):
        """
        Converts a python value (from JSON) into a Maude JV (Json Value).
        recursive for objects (jo) and lists (jl).
        """
        if isinstance(val, dict):
            # Map{String, JV} inside a jo(...)
            # Format: jo( (key |-> val), (key2 |-> val2) )
            if not val:
                return "jo(empty)"

            items = []
            keys = list(val.keys())  # Maintain order

            # Simple heuristic for formatting:
            # If it's a small object (like random params), keep it compact.
            # If deeply nested, use newlines.

            entry_strs = []
            for k, v in val.items():
                v_str = self.to_maude_jv(v, indent + 4)
                # keys in Maude JV are usually quoted strings?
                # looking at example: "type" |-> js("wait")
                # keys are Strings.
                entry_strs.append(f'("{k}" |-> {v_str})')

            inner = ", ".join(entry_strs)
            # Wrap in double parens for the Map
            return f"jo(({inner}))"

        elif isinstance(val, list):
            # List{JV} inside a jl(...)
            # Format: jl( v1 ; v2 )
            if not val:
                return "jl(empty)"
            items = [self.to_maude_jv(x, indent) for x in val]
            return f"jl({' ; '.join(items)})"

        elif isinstance(val, str):
            return f'js("{val}")'

        elif isinstance(val, bool):
            return f'jb({str(val).lower()})'

        elif isinstance(val, int):
            return f'jn({val})'

        elif isinstance(val, float):
            return f'jf({self.format_float(val)})'

        else:
            return "nullJV"

    def convert_markov_section(self, markov_data):
        """
        Converts the 'markov' JSON object.
        Target: Map{String, Map{String, Float}}
        Format: ( "state" |-> ("next" |-> 1.0, "next2" |-> 0.5) )
        """
        entries = []
        for state, transitions in markov_data.items():
            trans_entries = []
            for next_state, prob in transitions.items():
                trans_entries.append(f'("{next_state}" |-> {self.format_float(prob)})')

            trans_block = " , ".join(trans_entries)
            # Parentheses around the inner map
            entries.append(f'( "{state}" |-> ({trans_block}) )')

        return " ,\n\n    ".join(entries)

    def convert_actions_section(self, actions_data):
        """
        Converts the 'actions' JSON object.
        Target: Map{String, JV}
        Format: ( "name" |-> jo(...) )
        """
        entries = []
        for name, action_def in actions_data.items():
            jv_str = self.to_maude_jv(action_def)
            entries.append(f'("{name}" |->  {jv_str})')

        return ",\n    ".join(entries)

    def convert_params_section(self, params_data):
        """
        Converts the 'parameters' JSON object.
        Target: Map{String, JV}
        Format: ( "key" |-> val )
        """
        entries = []
        for k, v in params_data.items():
            jv_str = self.to_maude_jv(v)
            entries.append(f'("{k}" |->  {jv_str})')

        return ",\n        ".join(entries)

    def generate(self, json_content):
        data = json.loads(json_content)

        m_name = self.model_name
        upper_name = m_name.upper()

        # 1. Generate sections
        markov_str = self.convert_markov_section(data.get("markov", {}))
        actions_str = self.convert_actions_section(data.get("actions", {}))
        params_str = self.convert_params_section(data.get("parameters", {}))

        # 2. Construct file
        output = []
        output.append(HEADER)
        output.append("")
        output.append(f"fmod {upper_name}-MAMODEL is")
        output.append("  inc  MARKOV-ACTION-MODEL .")
        output.append("")
        output.append(f"op {m_name}-markov : ->  Map{{String,Map{{String,Float}}}} .")
        output.append(f"op {m_name}-actions : -> Map{{String,JV}} .")
        output.append(f"op {m_name}-params : -> Map{{String,JV}} .")
        output.append("")
        output.append(f"op {m_name}-ma : -> MAModel .  --- markov-action")
        output.append(f"eq {m_name}-ma =")
        output.append(f'   ma("{m_name}",{m_name}-markov,{m_name}-actions,{m_name}-params) .')
        output.append("")

        output.append(f"eq {m_name}-markov =  ")
        output.append(f"    {markov_str} ")
        output.append("  .                   ")
        output.append("")

        output.append(f"eq {m_name}-actions = (")
        output.append(f"    {actions_str}")
        output.append("    ) ")
        output.append(" .")
        output.append("")

        output.append(f"eq {m_name}-params = (")
        output.append(f"        {params_str}")
        output.append("        ) .")
        output.append("")
        output.append("endfm ")
        output.append("  ")
        output.append("eof  ")

        return "\n".join(output)