red 
{3.1396310546607548e+1, to umEqAd1 from umEqAd1 : actionR("ok")}
< umEqAd1 : UM-EQ | 
markov: ("download" |-> "wait_download" |-> 1.0, "media" |-> "wait_media" |-> 1.0, "wait" |-> ("download" |-> 1.0000000000000001e-1, "media" |-> 2.9999999999999999e-1, "wait" |-> 6.9999999999999996e-1), "wait_download" |-> ("download" |-> 1.0000000000000001e-1, "media" |-> 2.9999999999999999e-1, "wait" |-> 6.9999999999999996e-1), "wait_media" |-> ("download" |-> 1.0000000000000001e-1, "media" |-> 2.9999999999999999e-1, "wait" |-> 6.9999999999999996e-1)), 
actions: ("download" |-> jo("type" |-> js( "download")), "media" |-> jo(("num_to_post" |-> jo(("max" |-> jn(4), "min" |-> jn(1), "random" |-> js("uniform"))), "type" |-> js("media"))), "wait" |-> jo(("sleep" |-> jo(("floor" |-> jf(1.0), "mean" |-> jf( 3.5e+1), "random" |-> js("gaussian"), "std" |-> jf(1.5e+1))), "start" |-> jb(true), "type" |-> js("wait"))), "wait_download" |-> jo(("sleep" |-> jo(("floor" |-> jf(1.0), "mean" |-> jf(4.5e+1), "random" |-> js( "gaussian"), "std" |-> jf(2.0e+1))), "type" |-> js("wait"))), "wait_media" |-> jo(("sleep" |-> jo(("floor" |-> jf(1.0), "mean" |-> jf( 6.0e+1), "random" |-> js("gaussian"), "std" |-> jf(3.0e+1))), "type" |-> js("wait")))), 
curState: "media", 
nsteps: 999, 
actAddress: masTgenEqAd1,
 
w4: (to umEqAd1 from umEqAd1 : actionR("ok")), 
default: "wait", 
mSum: ( "download" |-> 1.0, "media" |-> 1.0, "wait" |-> 1.1000000000000001, "wait_download" |-> 1.1000000000000001, "wait_media" |-> 1.1000000000000001), 

stateLM: ("download" |-> jl(js("wait_download")), "media" |-> jl(js("wait_media")), "wait" |-> jl(js("download") ; js( "media") ; js("wait")), "wait_download" |-> jl(js("download") ; js( "media") ; js("wait")), "wait_media" |-> jl(js("download") ; js("media") ; js("wait"))), 
weightLM: ("download" |-> jl(jf(1.0)), "media" |-> jl( jf(1.0)), "wait" |-> jl(jf(1.0000000000000001e-1) ; jf( 4.0000000000000002e-1) ; jf(1.1000000000000001)), "wait_download" |-> jl(jf(1.0000000000000001e-1) ; jf(4.0000000000000002e-1) ; jf( 1.1000000000000001)), "wait_media" |-> jl(jf(1.0000000000000001e-1) ; jf(4.0000000000000002e-1) ; jf(1.1000000000000001))), 

stopTime: 3.0e+1 >
.    