load ../common/_aux

mod IAUX is  
  inc IODINE_NODE .

  --- var wattrs wattrsTrans Attrs : AttributeSet .  
  --- var msgOut : Msg .
  --- var NAME NAME1 : Name .
  --- var F : Fragment .
  --- var ADDR ADDR1 : Address .
  --- var ID : Id .
  --- var QTYPE : RType .
  --- var B : Bool .
  --- vars N : Nat .
  --- vars FRAGMENT_LIST : FragmentList .
  --- var PACKET : Packet .
  --- var PACKET_LIST : PacketList .


  var CONF : Config .

  --- passthru
  eq _transform(CONF) = CONF .

endm