eval E[s.rval("getMinLatency(getMonitor(C), 10.0, 910.0)")]; // cumulative latency0 10.0 910.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 910.0, 25)")]; // cumulative latency25 10.0 910.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 910.0, 50)")]; // cumulative latency50 10.0 910.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 910.0, 75)")]; // cumulative latency75 10.0 910.0
eval E[s.rval("getMaxLatency(getMonitor(C), 10.0, 910.0)")]; // cumulative latency100 10.0 910.0
eval E[s.rval("getGoodput(getMonitor(C), 10.0, 910.0)")]; // cumulative goodput 10.0 910.0
eval E[s.rval("getMinLatency(getMonitor(C), 10.0, 1810.0)")]; // cumulative latency0 10.0 1810.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 1810.0, 25)")]; // cumulative latency25 10.0 1810.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 1810.0, 50)")]; // cumulative latency50 10.0 1810.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 1810.0, 75)")]; // cumulative latency75 10.0 1810.0
eval E[s.rval("getMaxLatency(getMonitor(C), 10.0, 1810.0)")]; // cumulative latency100 10.0 1810.0
eval E[s.rval("getGoodput(getMonitor(C), 10.0, 1810.0)")]; // cumulative goodput 10.0 1810.0
eval E[s.rval("getMinLatency(getMonitor(C), 910.0, 1810.0)")]; // independent latency0 910.0 1810.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 910.0, 1810.0, 25)")]; // independent latency25 910.0 1810.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 910.0, 1810.0, 50)")]; // independent latency50 910.0 1810.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 910.0, 1810.0, 75)")]; // independent latency75 910.0 1810.0
eval E[s.rval("getMaxLatency(getMonitor(C), 910.0, 1810.0)")]; // independent latency100 910.0 1810.0
eval E[s.rval("getGoodput(getMonitor(C), 910.0, 1810.0)")]; // independent goodput 910.0 1810.0
eval E[s.rval("getMinLatency(getMonitor(C), 10.0, 2710.0)")]; // cumulative latency0 10.0 2710.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 2710.0, 25)")]; // cumulative latency25 10.0 2710.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 2710.0, 50)")]; // cumulative latency50 10.0 2710.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 2710.0, 75)")]; // cumulative latency75 10.0 2710.0
eval E[s.rval("getMaxLatency(getMonitor(C), 10.0, 2710.0)")]; // cumulative latency100 10.0 2710.0
eval E[s.rval("getGoodput(getMonitor(C), 10.0, 2710.0)")]; // cumulative goodput 10.0 2710.0
eval E[s.rval("getMinLatency(getMonitor(C), 1810.0, 2710.0)")]; // independent latency0 1810.0 2710.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 1810.0, 2710.0, 25)")]; // independent latency25 1810.0 2710.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 1810.0, 2710.0, 50)")]; // independent latency50 1810.0 2710.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 1810.0, 2710.0, 75)")]; // independent latency75 1810.0 2710.0
eval E[s.rval("getMaxLatency(getMonitor(C), 1810.0, 2710.0)")]; // independent latency100 1810.0 2710.0
eval E[s.rval("getGoodput(getMonitor(C), 1810.0, 2710.0)")]; // independent goodput 1810.0 2710.0
eval E[s.rval("getMinLatency(getMonitor(C), 10.0, 3610.0)")]; // cumulative latency0 10.0 3610.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 3610.0, 25)")]; // cumulative latency25 10.0 3610.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 3610.0, 50)")]; // cumulative latency50 10.0 3610.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 3610.0, 75)")]; // cumulative latency75 10.0 3610.0
eval E[s.rval("getMaxLatency(getMonitor(C), 10.0, 3610.0)")]; // cumulative latency100 10.0 3610.0
eval E[s.rval("getGoodput(getMonitor(C), 10.0, 3610.0)")]; // cumulative goodput 10.0 3610.0
eval E[s.rval("getMinLatency(getMonitor(C), 2710.0, 3610.0)")]; // independent latency0 2710.0 3610.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 2710.0, 3610.0, 25)")]; // independent latency25 2710.0 3610.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 2710.0, 3610.0, 50)")]; // independent latency50 2710.0 3610.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 2710.0, 3610.0, 75)")]; // independent latency75 2710.0 3610.0
eval E[s.rval("getMaxLatency(getMonitor(C), 2710.0, 3610.0)")]; // independent latency100 2710.0 3610.0
eval E[s.rval("getGoodput(getMonitor(C), 2710.0, 3610.0)")]; // independent goodput 2710.0 3610.0
eval E[s.rval("getMinLatency(getMonitor(C), 10.0, 4510.0)")]; // cumulative latency0 10.0 4510.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 4510.0, 25)")]; // cumulative latency25 10.0 4510.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 4510.0, 50)")]; // cumulative latency50 10.0 4510.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 4510.0, 75)")]; // cumulative latency75 10.0 4510.0
eval E[s.rval("getMaxLatency(getMonitor(C), 10.0, 4510.0)")]; // cumulative latency100 10.0 4510.0
eval E[s.rval("getGoodput(getMonitor(C), 10.0, 4510.0)")]; // cumulative goodput 10.0 4510.0
eval E[s.rval("getMinLatency(getMonitor(C), 3610.0, 4510.0)")]; // independent latency0 3610.0 4510.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 3610.0, 4510.0, 25)")]; // independent latency25 3610.0 4510.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 3610.0, 4510.0, 50)")]; // independent latency50 3610.0 4510.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 3610.0, 4510.0, 75)")]; // independent latency75 3610.0 4510.0
eval E[s.rval("getMaxLatency(getMonitor(C), 3610.0, 4510.0)")]; // independent latency100 3610.0 4510.0
eval E[s.rval("getGoodput(getMonitor(C), 3610.0, 4510.0)")]; // independent goodput 3610.0 4510.0
eval E[s.rval("getMinLatency(getMonitor(C), 10.0, 5410.0)")]; // cumulative latency0 10.0 5410.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 5410.0, 25)")]; // cumulative latency25 10.0 5410.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 5410.0, 50)")]; // cumulative latency50 10.0 5410.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 5410.0, 75)")]; // cumulative latency75 10.0 5410.0
eval E[s.rval("getMaxLatency(getMonitor(C), 10.0, 5410.0)")]; // cumulative latency100 10.0 5410.0
eval E[s.rval("getGoodput(getMonitor(C), 10.0, 5410.0)")]; // cumulative goodput 10.0 5410.0
eval E[s.rval("getMinLatency(getMonitor(C), 4510.0, 5410.0)")]; // independent latency0 4510.0 5410.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 4510.0, 5410.0, 25)")]; // independent latency25 4510.0 5410.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 4510.0, 5410.0, 50)")]; // independent latency50 4510.0 5410.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 4510.0, 5410.0, 75)")]; // independent latency75 4510.0 5410.0
eval E[s.rval("getMaxLatency(getMonitor(C), 4510.0, 5410.0)")]; // independent latency100 4510.0 5410.0
eval E[s.rval("getGoodput(getMonitor(C), 4510.0, 5410.0)")]; // independent goodput 4510.0 5410.0
eval E[s.rval("getMinLatency(getMonitor(C), 10.0, 6310.0)")]; // cumulative latency0 10.0 6310.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 6310.0, 25)")]; // cumulative latency25 10.0 6310.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 6310.0, 50)")]; // cumulative latency50 10.0 6310.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 6310.0, 75)")]; // cumulative latency75 10.0 6310.0
eval E[s.rval("getMaxLatency(getMonitor(C), 10.0, 6310.0)")]; // cumulative latency100 10.0 6310.0
eval E[s.rval("getGoodput(getMonitor(C), 10.0, 6310.0)")]; // cumulative goodput 10.0 6310.0
eval E[s.rval("getMinLatency(getMonitor(C), 5410.0, 6310.0)")]; // independent latency0 5410.0 6310.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 5410.0, 6310.0, 25)")]; // independent latency25 5410.0 6310.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 5410.0, 6310.0, 50)")]; // independent latency50 5410.0 6310.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 5410.0, 6310.0, 75)")]; // independent latency75 5410.0 6310.0
eval E[s.rval("getMaxLatency(getMonitor(C), 5410.0, 6310.0)")]; // independent latency100 5410.0 6310.0
eval E[s.rval("getGoodput(getMonitor(C), 5410.0, 6310.0)")]; // independent goodput 5410.0 6310.0
eval E[s.rval("getMinLatency(getMonitor(C), 10.0, 7210.0)")]; // cumulative latency0 10.0 7210.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 7210.0, 25)")]; // cumulative latency25 10.0 7210.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 7210.0, 50)")]; // cumulative latency50 10.0 7210.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 10.0, 7210.0, 75)")]; // cumulative latency75 10.0 7210.0
eval E[s.rval("getMaxLatency(getMonitor(C), 10.0, 7210.0)")]; // cumulative latency100 10.0 7210.0
eval E[s.rval("getGoodput(getMonitor(C), 10.0, 7210.0)")]; // cumulative goodput 10.0 7210.0
eval E[s.rval("getMinLatency(getMonitor(C), 6310.0, 7210.0)")]; // independent latency0 6310.0 7210.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 6310.0, 7210.0, 25)")]; // independent latency25 6310.0 7210.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 6310.0, 7210.0, 50)")]; // independent latency50 6310.0 7210.0
eval E[s.rval("getPercentileLatency(getMonitor(C), 6310.0, 7210.0, 75)")]; // independent latency75 6310.0 7210.0
eval E[s.rval("getMaxLatency(getMonitor(C), 6310.0, 7210.0)")]; // independent latency100 6310.0 7210.0
eval E[s.rval("getGoodput(getMonitor(C), 6310.0, 7210.0)")]; // independent goodput 6310.0 7210.0
eval E[s.rval("getSystemIntegrity(getMonitor(C), getIrcSrv(C), 10.0, 910.0)")]; // cumulative integrity 10.0 910.0
eval E[s.rval("getSystemIntegrity(getMonitor(C), getIrcSrv(C), 10.0, 1810.0)")]; // cumulative integrity 10.0 1810.0
eval E[s.rval("getSystemIntegrity(getMonitor(C), getIrcSrv(C), 910.0, 1810.0)")]; // independent integrity 910.0 1810.0
eval E[s.rval("getSystemIntegrity(getMonitor(C), getIrcSrv(C), 10.0, 2710.0)")]; // cumulative integrity 10.0 2710.0
eval E[s.rval("getSystemIntegrity(getMonitor(C), getIrcSrv(C), 1810.0, 2710.0)")]; // independent integrity 1810.0 2710.0
eval E[s.rval("getSystemIntegrity(getMonitor(C), getIrcSrv(C), 10.0, 3610.0)")]; // cumulative integrity 10.0 3610.0
eval E[s.rval("getSystemIntegrity(getMonitor(C), getIrcSrv(C), 2710.0, 3610.0)")]; // independent integrity 2710.0 3610.0
eval E[s.rval("getSystemIntegrity(getMonitor(C), getIrcSrv(C), 10.0, 4510.0)")]; // cumulative integrity 10.0 4510.0
eval E[s.rval("getSystemIntegrity(getMonitor(C), getIrcSrv(C), 3610.0, 4510.0)")]; // independent integrity 3610.0 4510.0
eval E[s.rval("getSystemIntegrity(getMonitor(C), getIrcSrv(C), 10.0, 5410.0)")]; // cumulative integrity 10.0 5410.0
eval E[s.rval("getSystemIntegrity(getMonitor(C), getIrcSrv(C), 4510.0, 5410.0)")]; // independent integrity 4510.0 5410.0
eval E[s.rval("getSystemIntegrity(getMonitor(C), getIrcSrv(C), 10.0, 6310.0)")]; // cumulative integrity 10.0 6310.0
eval E[s.rval("getSystemIntegrity(getMonitor(C), getIrcSrv(C), 5410.0, 6310.0)")]; // independent integrity 5410.0 6310.0
eval E[s.rval("getSystemIntegrity(getMonitor(C), getIrcSrv(C), 10.0, 7210.0)")]; // cumulative integrity 10.0 7210.0
eval E[s.rval("getSystemIntegrity(getMonitor(C), getIrcSrv(C), 6310.0, 7210.0)")]; // independent integrity 6310.0 7210.0
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), wtCl1IrcAddr, 10.0, 910.0)")]; // cumulative integrity 10.0 910.0 wtCl1IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), skyCl2IrcAddr, 10.0, 910.0)")]; // cumulative integrity 10.0 910.0 skyCl2IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), obfsCl3IrcAddr, 10.0, 910.0)")]; // cumulative integrity 10.0 910.0 obfsCl3IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), masCl4IrcAddr, 10.0, 910.0)")]; // cumulative integrity 10.0 910.0 masCl4IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), wtCl1IrcAddr, 10.0, 1810.0)")]; // cumulative integrity 10.0 1810.0 wtCl1IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), skyCl2IrcAddr, 10.0, 1810.0)")]; // cumulative integrity 10.0 1810.0 skyCl2IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), obfsCl3IrcAddr, 10.0, 1810.0)")]; // cumulative integrity 10.0 1810.0 obfsCl3IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), masCl4IrcAddr, 10.0, 1810.0)")]; // cumulative integrity 10.0 1810.0 masCl4IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), wtCl1IrcAddr, 910.0, 1810.0)")]; // independent integrity 910.0 1810.0 wtCl1IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), skyCl2IrcAddr, 910.0, 1810.0)")]; // independent integrity 910.0 1810.0 skyCl2IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), obfsCl3IrcAddr, 910.0, 1810.0)")]; // independent integrity 910.0 1810.0 obfsCl3IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), masCl4IrcAddr, 910.0, 1810.0)")]; // independent integrity 910.0 1810.0 masCl4IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), wtCl1IrcAddr, 10.0, 2710.0)")]; // cumulative integrity 10.0 2710.0 wtCl1IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), skyCl2IrcAddr, 10.0, 2710.0)")]; // cumulative integrity 10.0 2710.0 skyCl2IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), obfsCl3IrcAddr, 10.0, 2710.0)")]; // cumulative integrity 10.0 2710.0 obfsCl3IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), masCl4IrcAddr, 10.0, 2710.0)")]; // cumulative integrity 10.0 2710.0 masCl4IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), wtCl1IrcAddr, 1810.0, 2710.0)")]; // independent integrity 1810.0 2710.0 wtCl1IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), skyCl2IrcAddr, 1810.0, 2710.0)")]; // independent integrity 1810.0 2710.0 skyCl2IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), obfsCl3IrcAddr, 1810.0, 2710.0)")]; // independent integrity 1810.0 2710.0 obfsCl3IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), masCl4IrcAddr, 1810.0, 2710.0)")]; // independent integrity 1810.0 2710.0 masCl4IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), wtCl1IrcAddr, 10.0, 3610.0)")]; // cumulative integrity 10.0 3610.0 wtCl1IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), skyCl2IrcAddr, 10.0, 3610.0)")]; // cumulative integrity 10.0 3610.0 skyCl2IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), obfsCl3IrcAddr, 10.0, 3610.0)")]; // cumulative integrity 10.0 3610.0 obfsCl3IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), masCl4IrcAddr, 10.0, 3610.0)")]; // cumulative integrity 10.0 3610.0 masCl4IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), wtCl1IrcAddr, 2710.0, 3610.0)")]; // independent integrity 2710.0 3610.0 wtCl1IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), skyCl2IrcAddr, 2710.0, 3610.0)")]; // independent integrity 2710.0 3610.0 skyCl2IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), obfsCl3IrcAddr, 2710.0, 3610.0)")]; // independent integrity 2710.0 3610.0 obfsCl3IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), masCl4IrcAddr, 2710.0, 3610.0)")]; // independent integrity 2710.0 3610.0 masCl4IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), wtCl1IrcAddr, 10.0, 4510.0)")]; // cumulative integrity 10.0 4510.0 wtCl1IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), skyCl2IrcAddr, 10.0, 4510.0)")]; // cumulative integrity 10.0 4510.0 skyCl2IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), obfsCl3IrcAddr, 10.0, 4510.0)")]; // cumulative integrity 10.0 4510.0 obfsCl3IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), masCl4IrcAddr, 10.0, 4510.0)")]; // cumulative integrity 10.0 4510.0 masCl4IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), wtCl1IrcAddr, 3610.0, 4510.0)")]; // independent integrity 3610.0 4510.0 wtCl1IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), skyCl2IrcAddr, 3610.0, 4510.0)")]; // independent integrity 3610.0 4510.0 skyCl2IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), obfsCl3IrcAddr, 3610.0, 4510.0)")]; // independent integrity 3610.0 4510.0 obfsCl3IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), masCl4IrcAddr, 3610.0, 4510.0)")]; // independent integrity 3610.0 4510.0 masCl4IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), wtCl1IrcAddr, 10.0, 5410.0)")]; // cumulative integrity 10.0 5410.0 wtCl1IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), skyCl2IrcAddr, 10.0, 5410.0)")]; // cumulative integrity 10.0 5410.0 skyCl2IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), obfsCl3IrcAddr, 10.0, 5410.0)")]; // cumulative integrity 10.0 5410.0 obfsCl3IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), masCl4IrcAddr, 10.0, 5410.0)")]; // cumulative integrity 10.0 5410.0 masCl4IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), wtCl1IrcAddr, 4510.0, 5410.0)")]; // independent integrity 4510.0 5410.0 wtCl1IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), skyCl2IrcAddr, 4510.0, 5410.0)")]; // independent integrity 4510.0 5410.0 skyCl2IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), obfsCl3IrcAddr, 4510.0, 5410.0)")]; // independent integrity 4510.0 5410.0 obfsCl3IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), masCl4IrcAddr, 4510.0, 5410.0)")]; // independent integrity 4510.0 5410.0 masCl4IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), wtCl1IrcAddr, 10.0, 6310.0)")]; // cumulative integrity 10.0 6310.0 wtCl1IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), skyCl2IrcAddr, 10.0, 6310.0)")]; // cumulative integrity 10.0 6310.0 skyCl2IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), obfsCl3IrcAddr, 10.0, 6310.0)")]; // cumulative integrity 10.0 6310.0 obfsCl3IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), masCl4IrcAddr, 10.0, 6310.0)")]; // cumulative integrity 10.0 6310.0 masCl4IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), wtCl1IrcAddr, 5410.0, 6310.0)")]; // independent integrity 5410.0 6310.0 wtCl1IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), skyCl2IrcAddr, 5410.0, 6310.0)")]; // independent integrity 5410.0 6310.0 skyCl2IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), obfsCl3IrcAddr, 5410.0, 6310.0)")]; // independent integrity 5410.0 6310.0 obfsCl3IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), masCl4IrcAddr, 5410.0, 6310.0)")]; // independent integrity 5410.0 6310.0 masCl4IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), wtCl1IrcAddr, 10.0, 7210.0)")]; // cumulative integrity 10.0 7210.0 wtCl1IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), skyCl2IrcAddr, 10.0, 7210.0)")]; // cumulative integrity 10.0 7210.0 skyCl2IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), obfsCl3IrcAddr, 10.0, 7210.0)")]; // cumulative integrity 10.0 7210.0 obfsCl3IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), masCl4IrcAddr, 10.0, 7210.0)")]; // cumulative integrity 10.0 7210.0 masCl4IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), wtCl1IrcAddr, 6310.0, 7210.0)")]; // independent integrity 6310.0 7210.0 wtCl1IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), skyCl2IrcAddr, 6310.0, 7210.0)")]; // independent integrity 6310.0 7210.0 skyCl2IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), obfsCl3IrcAddr, 6310.0, 7210.0)")]; // independent integrity 6310.0 7210.0 obfsCl3IrcAddr
eval E[s.rval("getClientIntegrity(getMonitor(C), getIrcSrv(C), masCl4IrcAddr, 6310.0, 7210.0)")]; // independent integrity 6310.0 7210.0 masCl4IrcAddr
eval E[s.rval("getMTBF(getMonitor(C), 16.0, 10.0, 910.0)")]; // cumulative availability 10.0 910.0
eval E[s.rval("getMTBF(getMonitor(C), 16.0, 10.0, 1810.0)")]; // cumulative availability 10.0 1810.0
eval E[s.rval("getMTBF(getMonitor(C), 16.0, 910.0, 1810.0)")]; // independent availability 910.0 1810.0
eval E[s.rval("getMTBF(getMonitor(C), 16.0, 10.0, 2710.0)")]; // cumulative availability 10.0 2710.0
eval E[s.rval("getMTBF(getMonitor(C), 16.0, 1810.0, 2710.0)")]; // independent availability 1810.0 2710.0
eval E[s.rval("getMTBF(getMonitor(C), 16.0, 10.0, 3610.0)")]; // cumulative availability 10.0 3610.0
eval E[s.rval("getMTBF(getMonitor(C), 16.0, 2710.0, 3610.0)")]; // independent availability 2710.0 3610.0
eval E[s.rval("getMTBF(getMonitor(C), 16.0, 10.0, 4510.0)")]; // cumulative availability 10.0 4510.0
eval E[s.rval("getMTBF(getMonitor(C), 16.0, 3610.0, 4510.0)")]; // independent availability 3610.0 4510.0
eval E[s.rval("getMTBF(getMonitor(C), 16.0, 10.0, 5410.0)")]; // cumulative availability 10.0 5410.0
eval E[s.rval("getMTBF(getMonitor(C), 16.0, 4510.0, 5410.0)")]; // independent availability 4510.0 5410.0
eval E[s.rval("getMTBF(getMonitor(C), 16.0, 10.0, 6310.0)")]; // cumulative availability 10.0 6310.0
eval E[s.rval("getMTBF(getMonitor(C), 16.0, 5410.0, 6310.0)")]; // independent availability 5410.0 6310.0
eval E[s.rval("getMTBF(getMonitor(C), 16.0, 10.0, 7210.0)")]; // cumulative availability 10.0 7210.0
eval E[s.rval("getMTBF(getMonitor(C), 16.0, 6310.0, 7210.0)")]; // independent availability 6310.0 7210.0