set show advisories off .

sload ../../../deps/dns_formalization/Maude/common/actor


mod ADVERSARY-CP3-DATA is
  inc ACTOR-MODEL .
  inc CONVERSION .

vars tsnd : Float .
vars tixp trcv : FloatInf .
vars msg : Msg .
vars pkt : Pkt  .
vars addr src tgt : Address .
vars new? : Bool .
vars cnx size : Nat .

vars tol0 tol1 tol : TimesObsList .
vars to0 to1 : TimesObs .



sort FloatInf .
subsort Float < FloatInf .
op infty : -> FloatInf [ctor] .

sorts TimesMsg TimesPkt TimesObs .
subsort TimesMsg  < TimesObs .
subsort TimesPkt  < TimesObs .
sort TimesObsList .
**** subsort TimesMsg TimesPkt < TimesObsList .
subsort TimesObs < TimesObsList .
op nilTO : -> TimesObsList [ctor] .
op _;;_ : TimesObsList TimesObsList -> TimesObsList
            [ctor assoc id: nilTO] .
op tm : Float FloatInf FloatInf Msg -> TimesMsg [ctor] .

op len : TimesObsList -> Nat .
eq len(nilTO) = 0 .
eq len(to0 ;; tol0) = s len(tol0) .


op getSendTime : TimesMsg -> Float .
eq getSendTime(tm(tsnd,tixp,trcv,msg)) = tsnd .
op getRecvTime : TimesMsg -> FloatInf .
eq getRecvTime(tm(tsnd,tixp,trcv,msg)) = trcv .
op getIXPTime : TimesMsg -> FloatInf .
eq getIXPTime(tm(tsnd,tixp,trcv,msg)) = tixp .

op getSender : TimesMsg -> Address .
eq getSender(tm(tsnd,tixp,trcv, 
                (to tgt from src : c:Content))) = src .
op getReceiver : TimesMsg -> Address .
eq getReceiver(tm(tsnd,tixp,trcv, 
                (to tgt from src : c:Content))) = tgt .



sort Pkt .
-----                     new? cnx size
op pkt : Address Address  Bool Nat Nat -> Pkt [ctor] .

op tp : Float FloatInf FloatInf Pkt -> TimesPkt [ctor] .


op getSendTime : TimesPkt -> Float .
eq getSendTime(tp(tsnd,tixp,trcv,pkt)) = tsnd .
op getRecvTime : TimesPkt -> FloatInf .
eq getRecvTime(tp(tsnd,tixp,trcv,pkt)) = trcv .
op getIXPTime : TimesPkt -> FloatInf .
eq getIXPTime(tp(tsnd,tixp,trcv,pkt)) = tixp .

op getSender : TimesPkt -> Address .
eq getSender(tp(tsnd,tixp,trcv,pkt(tgt,src,new?,cnx,size))) 
      =  src .
op getReceiver : TimesMsg -> Address .
eq getReceiver(tp(tsnd,tixp,trcv, pkt(tgt,src,new?,cnx,size))) 
      =  tgt .


sort Flow .
op flow : Address Address Nat -> Flow [ctor] .

op getFlow : TimesPkt -> Flow .
op getFlow : Pkt -> Flow .
eq getFlow (tp(tsnd,tixp,trcv,pkt)) = getFlow(pkt) .
eq getFlow(pkt(tgt,src,new?,cnx,size)) =
           flow(tgt,src,cnx) .

op getSize : TimesPkt -> Nat .
op getSize : Pkt -> Nat .
eq getSize (tp(tsnd,tixp,trcv,pkt)) = getSize(pkt) .
eq getSize(pkt(tgt,src,new?,cnx,size)) = size .

op mergeTOL :  TimesObsList TimesObsList -> TimesObsList .
op toInsert :  TimesObsList TimesObsList TimesObsList -> TimesObsList .
eq mergeTOL(tol0,nilTO) = tol0 .
ceq mergeTOL(tol0,to0 ;; tol) = mergeTOL(tol1,tol) 
  if tol1 := toInsert(tol0,to0,nilTO) .

eq toInsert(nilTO,to0,tol1)  = to0 ;; tol1 . 
eq toInsert(tol0 ;; to1,to0,tol1) =
  (if getSendTime(to1) <= getSendTime(to0)
  then tol0 ;; to1 ;; to0 ;; tol1
  else toInsert(tol0,to0, to1 ;; tol1)
  fi)
  .
  
endm


mod ADVERSARY-CP3 is
  inc ADVERSARY-CP3-DATA .
  
vars addr : Address .
  
op Adversary : -> ActorType .

op dns:_ : TimesObsList -> Attribute [ctor] .
op tcp:_ : TimesObsList -> Attribute [ctor] .

op mkAdversaryCp3 : Address -> Actor .
eq mkAdversaryCp3(addr) =
  < addr : Adversary | 
      dns: nilTO,
      tcp: nilTO
  >
.   
     
endm

mod TEST-ADVERSARY-CP3-DATA is
  inc ADVERSARY-CP3-DATA .

ops aDr0 aDr1 : -> Address .
ops Q0 Q1 Q2 Q3 : -> Content .

ops tmL0 tmL1 : -> TimesObsList .
ops tpL0 tpL1 : -> TimesObsList .

eq tpL0 =
tp(2.0456611545367629e-2, 2.5456611545367634e-2, 3.0456611545367631e-2, pkt(aDr0, aDr1, false, 0, 52)) ;; 
tp(4.0456611545367629e-2, 2.5456611545367634e-2, 3.0456611545367631e-2, pkt(aDr0, aDr1, false, 0, 1500)) ;; 
tp(8.0456611545367623e-2, 4.5456611545367634e-2, 5.0456611545367638e-2, pkt(aDr0, aDr1, false, 0, 1500)) 
.

eq tpL1 = 
tp(3.0456611545367626e-2, 4.5456611545367634e-2, 5.0456611545367638e-2, pkt(aDr1, aDr0, false, 0, 52)) ;;
tp(4.00703725921623399e-2, 2.570372592162341e-2, 3.0703725921623407e-2, pkt(aDr1, aDr0, false, 0, 1500)) ;;
tp(1.0045661154536761e-1, 4.5456611545367634e-2, 5.0456611545367638e-2, pkt(aDr0, aDr1, false, 0, 252)) 
.

eq tmL0 =
tm(1.2129300074488858e-3, 1.4042894572811203e-3, 1.6167725515807982e-3, to aDr0 from aDr1 : Q0) ;; 
tm(1.656334999531973e-3, 2.032445014314726e-3, 1.6709835267974993e-3, to aDr0 from aDr1 : Q3) ;;
tm(1.8660735806613231e-3, 2.6039156608958728e-3, 2.1616652487777173e-3, to aDr1 from aDr0 : Q1) 
.
eq tmL1 =
tm( 1.6358449236908927e-3, 1.8091359796700997e-3, 2.466495551732369e-3, to aDr1 from aDr0 : Q1) ;; 
 tm(1.7847280164342374e-3, 3.3586502367677169e-3, 3.0620359053951688e-3, to aDr0 from aDr1 : Q0) ;;
 tm(1.8948197013954633e-3, 2.8573863608622923e-3, 2.3337748846109026e-3, to aDr0 from aDr1 : Q2)
 .
  
endm  
eof

red mergeTOL(tmL0,tmL1) .
***(

tm(1.2129300074488858e-3, 1.4042894572811203e-3, 1.6167725515807982e-3, to aDr0 from aDr1 : Q0) ;; 
tm( 1.6358449236908927e-3, 1.8091359796700997e-3, 2.466495551732369e-3, to aDr1 from aDr0 : Q1) ;; 
tm(1.656334999531973e-3, 2.032445014314726e-3, 1.6709835267974993e-3, to aDr0 from aDr1 : Q3) ;; 
tm(1.7847280164342374e-3, 3.3586502367677169e-3, 3.0620359053951688e-3, to aDr0 from aDr1 : Q0) ;; 
tm( 1.8660735806613231e-3, 2.6039156608958728e-3, 2.1616652487777173e-3, to aDr1 from aDr0 : Q1) ;; 
tm( 1.8948197013954633e-3, 2.8573863608622923e-3, 2.3337748846109026e-3, to aDr0 from aDr1 : Q2)
)

red mergeTOL(tmL1,tmLo0) .
*** ok

red mergeTOL(tpL0,tpL1) .
***(
tp(2.0456611545367629e-2, 2.5456611545367634e-2, 3.0456611545367631e-2, pkt(aDr0, aDr1, false, 0, 52)) ;; 
tp( 3.0456611545367628e-2, 4.5456611545367634e-2, 5.0456611545367638e-2, pkt(aDr1, aDr0, false, 0, 52)) ;; 
tp( 4.007037259216234e-2, 2.570372592162341e-2, 3.0703725921623407e-2, pkt(aDr1, aDr0, false, 0, 1500)) ;;
tp(4.0456611545367629e-2, 2.5456611545367634e-2, 3.0456611545367631e-2, pkt(aDr0, aDr1, false, 0, 1500)) ;; 
tp(8.0456611545367623e-2, 4.5456611545367634e-2, 5.0456611545367638e-2, pkt(aDr0, aDr1, false, 0, 1500)) ;; 
tp(1.0045661154536761e-1, 4.5456611545367634e-2, 5.0456611545367638e-2, pkt(aDr0, aDr1, false, 0, 252))
)

