set show advisories off .

sload ../../../deps/dns_formalization/Maude/dns/common/prelim

mod DNS-UTIL is
  inc MSG .
  

  op qrMatch : Query Response  -> Bool .

  eq qrMatch(query(id:Id,name:Name,r:RType),
               response(id:Id,name:Name,l1:List{Record}, 
                        l2:List{Record} ,l3:List{Record},j:Nat) )
     = true .             
  eq qrMatch(Q:Query,R:Response) = false [owise] .


  
endm  