set clear rules off .
set print attribute off .
set show advisories off .


sload ../../deps/dns_formalization/Maude/common/actor
sload ../common/maude/structured-addresses
sload ../common/maude/adversary-cp3

mod SMC-BASELINE-SHARED is
  inc ACTOR-MODEL .
  inc ADVERSARY-CP3 .
  inc STRUCTURED-ADDRESSES .
  inc LIST{Float} .
  
  
  
  vars vp nid : NetId .
  vars vpts : NetIdList .
  vars obsF : Feature .
  vars obsFs : FeatureList .
  vars TOL F0Z GtZ mTOL pTOL : TimesObsList .
  vars bcdf : List{Float} .
  vars Tstart Tend winSize binSize  k : Float .
  vars attrs attrs0 attrs1 attrs2 : AttributeSet .
  vars blist : BaseLineList .
  vars conf conf0 : Config .
  vars b : Bool .
  vars blAct : Actor .
  vars aAddr : Address .
  
  sort Feature .
  ops dnsQueryRate dnsQuerySize dnsRespSize : -> Feature .
  ops tcpUpRate tcpDownRate tcpUpToDownRate tcpOutPktRate tcpInPktRate tcpOutToInPktRate tcpPktSizeStdDev tcpPktSize tcpPktInterarrival tcpDirectionChange tcpActiveFlow tcpNewCnx : -> Feature .
  
op  ircServerAddr : -> Address .
op allClientsAddr : -> AddrList .


  sort NetIdList .
  subsort NetId < NetIdList .
  op nilNetId : -> NetIdList .
  op _:;_ : NetIdList NetIdList -> NetIdList 
            [ctor assoc id: nilNetId] .
  
  sort FeatureList .
  subsort Feature < FeatureList .
  op nilFeature : -> FeatureList .
  op _:;_ : FeatureList FeatureList -> FeatureList 
           [ctor assoc id: nilFeature] .
  
op isDnsFeature : Feature -> Bool .
eq isDnsFeature(dnsQueryRate) = true .
eq isDnsFeature(dnsQuerySize) = true .
eq isDnsFeature(dnsRespSize) = true .
eq isDnsFeature(obsF) = false [owise] .

sorts BaseLineElement BaseLineList .
subsort BaseLineElement < BaseLineList .
op nilBaseLine : -> BaseLineList .
op _:;_ : BaseLineList BaseLineList -> BaseLineList
               [ctor assoc id: nilBaseLine] .
op bl : NetId Feature Float List{Float}  
        -> BaseLineElement [ctor] .
  
op baseLineAddr : -> Address .
op BaseLineMonitor : -> ActorType .

op viewPts:_ : NetIdList -> Attribute [ctor] .
op features:_ : FeatureList -> Attribute [ctor] .
op baseLine:_ : BaseLineList -> Attribute [ctor] .
ops tStart:_ tEnd:_ : Float -> Attribute [ctor] .
ops winSize:_ binSize:_ : Float -> Attribute [ctor] .

op mkBaseLineAttrs : NetIdList FeatureList 
               Float Float Float Float -> AttributeSet .
eq  mkBaseLineAttrs(vpts,obsFs, 
                    Tstart,Tend,winSize,binSize) =
      (viewPts: vpts,
      features: obsFs,
      tStart: Tstart,
      tEnd: Tend,
      winSize: winSize,
      binSize: binSize,
      baseLine: nilBaseLine)
       .

op initBaseLine :  NetIdList FeatureList 
                Float Float Float Float -> Actor .
ceq initBaseLine(vpts,obsFs,Tstart,Tend,winSize,binSize) = blAct 
if attrs := mkBaseLineAttrs(vpts,obsFs, 
                      Tstart,Tend,winSize,binSize)
/\ blAct := <  baseLineAddr : BaseLineMonitor | attrs >
.

op addToBaseLine : AttributeSet NetId Feature 
                 Float List{Float} -> AttributeSet .
ceq addToBaseLine(attrs,vp,obsF,k,bcdf) =
   attrs0, baseLine: (blist :; bl(vp,obsF,k,bcdf) ) 
if attrs0,baseLine: blist := attrs
.
eq addToBaseLine(attrs,nid,obsF,k,bcdf) = attrs [owise] .

endm
eof


