--- This maude file has been created automatically from the Python representation ---
load ../dns/maude/probabilistic/iodine_dns
load ../../deps/dns_formalization/Maude/test/probabilistic-model/test_helpers
load ../common/maude/router
load ../common/maude/adversary-observer
load ../app/maude/probabilistic

mod HCS_TEST is

  inc IODINE_DNS + TEST-HELPERS .
  inc CP2_APP .
  inc ROUTER .
  inc ADVERSARY-OBSERVER .

  ops adversary mastodonServer aliceMasClient Alice Bob iodineAlice iodineBob bobapp application-client application-server dnsperf internet-dns local-dns mAddr monAddr public-dns root-dns tld-dns : -> Address .

  op myIC : -> Config .
  eq myIC = 
***(
< adversary : Adversary | sent: (

tm(1.1416581186931581e-5, to X(public-dns) from local-dns : query(0, 'www2 . 'internet . 'com . root, a)) ; 
tm(1.8568474836647513e-5, to public-dns from Z( 0, local-dns) : query(0, 'www2 . 'internet . 'com . root, a)) ; 
tm(1.7000052889492152, to X(public-dns) from local-dns : query(7727, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(1.7000109693948529, to public-dns from Z(1, local-dns) : query(7727, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(1.7010083607876882, to X(public-dns) from local-dns : query(15454, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(1.7010090711482753, to public-dns from Z(2, local-dns) : query(15454, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(1.8090516124621681, to X(public-dns) from local-dns : query(23181, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(1.809056817236973, to public-dns from Z(3, local-dns) : query(23181, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(1.9170908629187122, to X(public-dns) from local-dns : query(30908, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 2, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(1.9170955989229395, to public-dns from Z(4, local-dns) : query(30908, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 2, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a))), 
rcvd: nilTML, canSeeS: (pat("X", "addr") pat("addr", "Z")), canSeeR: mtObs >
.
)

< adversary : Adversary | 
sent: (
tm(1.1416581186931581e-5, to X(public-dns) from local-dns : query(0, 'www2 . 'internet . 'com . root, a)) ; 
tm(1.8568474836647513e-5, to public-dns from Z(0, local-dns) : query(0, 'www2 . 'internet . 'com . root, a)) ; 
tm(1.1307116878349738e-1, to Z(0, local-dns) from public-dns : response(0, 'www2 .  'internet . 'com . root, < 'www2 . 'internet . 'com . root, a, 0.0, 1 . 1 . 1 . 2 >, nil, nil, 0)) ; 
tm(1.7000052889492152, to X(public-dns) from local-dns : query(7727, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(1.7000109693948529, to public-dns from Z(1, local-dns) : query(7727, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(1.7010083607876882, to X(public-dns) from local-dns : query(15454, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(1.7010090711482753, to public-dns from Z(2, local-dns) : query(15454, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(1.8090308756886047, to Z(2, local-dns) from public-dns : response(15454, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com . root, < nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com . root, a, 0.0, nm(fragment(iodineAlice, iodineBob, file(0), 0, 0, 0, 0, 0, false, false)) >, nil, nil, 0)) ; 
tm(1.8090516124621681, to X(public-dns) from local-dns : query(23181, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd .  'com . root, a)) ; 
tm(1.809056817236973, to public-dns from Z(3, local-dns) : query(23181, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(1.917076999203162, to Z(3, local-dns) from public-dns : response(23181, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, < nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a, 0.0, nm( fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 1, 0, false, false)) >, nil, nil, 0)) ; 
tm(1.9170908629187122, to X(public-dns) from local-dns : query(30908, nm( fragment(iodineAlice, iodineBob, file(10000), 0, 2, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(1.9170955989229395, to public-dns from Z(4, local-dns) : query(30908, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 2, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a))), 

rcvd: (
tm(1.130776277246483e-1, to local-dns from X(public-dns) : response(0, 'www2 . 'internet . 'com . root, < 'www2 . 'internet . 'com . root, a, 0.0, 1 . 1 . 1 . 2 >, nil, nil, 0)) ; 
tm(1.8090356117690047, to local-dns from X(public-dns) : response(15454, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com . root, < nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com . root, a, 0.0, nm(fragment(iodineAlice, iodineBob, file(0), 0, 0, 0, 0, 0, false, false)) >, nil, nil, 0)) ; 
tm(1.9170845853593663, to local-dns from X(public-dns) : response(23181, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd .  'com . root, < nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a, 0.0, nm(fragment(iodineBob, iodineAlice, file( 0), 0, 0, 0, 1, 0, false, false)) >, nil, nil, 0))), 

canSeeS: (pat("X", "addr") pat("addr", "Z")), canSeeR: (pat("Z", "addr") pat("addr", "X")) >
.

endm

load smc
set print attribute on .

red getToDCumulativeNQueryPreNAT (myIC, 0) == 1.7000052889492152 .
red getToDCumulativeNQueryPreNAT(myIC, 1) == 1.7010083607876882 . 
red getToDCumulativeNQueryPreNAT(myIC, 3) == 1.9170908629187122 .
red getToDCumulativeNQueryPreNAT(myIC, 5) == 0.0 . 

red getToDCumulativeNQueryPostNAT(myIC, 0) == 1.8568474836647513e-5 .
red getToDCumulativeNQueryPostNAT(myIC, 1) == 1.7000109693948529 .
red getToDCumulativeNQueryPostNAT(myIC, 3) == 1.809056817236973 . 
red getToDCumulativeNQueryPostNAT(myIC, 5) == 0.0 .

red size(query(0, 'www2 . 'internet . 'com . root, a)) == 19 .
red size(query(7727, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) == 146 .
red size(query(15454, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com . root, a)) == 10 .

red getToDCumulativeQuerySizePreNAT (myIC, 0) == 1.7000052889492152 . 
red getToDCumulativeQuerySizePreNAT (myIC, 10) == 1.7000052889492152 .
red getToDCumulativeQuerySizePreNAT (myIC, 145) == 1.7000052889492152 .
red getToDCumulativeQuerySizePreNAT (myIC, 146) == 1.7010083607876882 . 
red getToDCumulativeQuerySizePreNAT (myIC, 170) == 1.8090516124621681 .
red getToDCumulativeQuerySizePreNAT (myIC, 500) == 0.0 .

red getToDCumulativeQuerySizePostNAT (myIC, 0) == 1.8568474836647513e-5 .
red getToDCumulativeQuerySizePostNAT (myIC, 10) == 1.8568474836647513e-5 .
red getToDCumulativeQuerySizePostNAT (myIC, 18) == 1.8568474836647513e-5 .
red getToDCumulativeQuerySizePostNAT (myIC, 19) == 1.7000109693948529 . 
red getToDCumulativeQuerySizePostNAT (myIC, 170) == 1.7010090711482753 .
red getToDCumulativeQuerySizePostNAT (myIC, 320) == 1.809056817236973 . 
red getToDCumulativeQuerySizePostNAT (myIC, 321) == 1.9170955989229395 .
red getToDCumulativeQuerySizePostNAT (myIC, 2000) == 0.0 .

red size(response(0, 'www2 . 'internet . 'com . root, < 'www2 . 'internet . 'com . root, a, 0.0, 1 . 1 . 1 . 2 >, nil, nil, 0)) == 19 .
red size(response(23181, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd .  'com . root, < nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a, 0.0, nm(fragment(iodineBob, iodineAlice, file( 0), 0, 0, 0, 1, 0, false, false)) >, nil, nil, 0)) == 146 .
red size(response(15454, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com . root, < nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com . root, a, 0.0, nm(fragment(iodineAlice, iodineBob, file(0), 0, 0, 0, 0, 0, false, false)) >, nil, nil, 0)) == 10 .

red getToDCumulativeResponsePostNAT(myIC, 0) == 1.1307116878349738e-1 .
red getToDCumulativeResponsePostNAT(myIC, 20) == 1.8090308756886047 .
red getToDCumulativeResponsePostNAT(myIC, 155) == 1.917076999203162 .
red getToDCumulativeResponsePostNAT(myIC, 200) == 0.0 .

red getToDCumulativeResponsePreNAT(myIC, 0) == 1.8090356117690047 .
red getToDCumulativeResponsePreNAT(myIC, 9) == 1.8090356117690047 .
red getToDCumulativeResponsePreNAT(myIC, 10) == 1.9170845853593663 .
red getToDCumulativeResponsePreNAT(myIC, 155) == 1.9170845853593663 .
red getToDCumulativeResponsePreNAT(myIC, 156) == 0.0 .

