--- This maude file has been created automatically from the Python representation ---
sload ../mastodon/maude/probabilistic/mastodon
sload ../dns/maude/probabilistic/iodine_dns
sload ../common/maude/user-action-actor.maude
sload ../tgen/maude/dnsTgen-actor.maude
sload ../tgen/maude/masTGen.maude
sload ../common/maude/router
sload ../common/maude/adversary-observer
sload ../app/maude/probabilistic
sload ../../deps/dns_formalization/Maude/test/probabilistic-model/test_helpers

sload ../../../use-cases/challenge-problem-2/cp2_scenarios/cp2_scenario_1.maude

load smc
---set print attribute on .
set clear rules on .

--- baseline 
rew abs(getToDCumulativeNQueryPostNAT(getAdversary(initConfig), 166) - 300.0) < 0.01 .
rew abs(getToDCumulativeQuerySizePostNAT(getAdversary(initConfig), 12261) - 300.0) < 0.01 .
rew getToDCumulativeQuerySizePostNAT(getAdversary(initConfig),12261) .
