--- This maude file has been created automatically from the Python representation ---
sload ../mastodon/maude/probabilistic/mastodon
sload ../dns/maude/probabilistic/iodine_dns
sload ../common/maude/user-action-actor.maude
sload ../tgen/maude/dnsTgen-actor.maude
sload ../tgen/maude/masTGen.maude
sload ../common/maude/router
sload ../common/maude/adversary-observer
sload ../app/maude/probabilistic
sload ../../deps/dns_formalization/Maude/test/probabilistic-model/test_helpers

mod HCS_TEST is
  inc DNS .
  inc USER-ACTION-ACTOR .
  inc DNS-TGEN .
  inc DNS-MAMODEL .
  inc MASTODON .
  inc MAS-TGEN .
  inc IODINE_DNS . --- + TEST-HELPERS .
  inc CP2_APP .
  inc ROUTER .
  inc ADVERSARY-OBSERVER .

op qps-offset : -> Float .
eq qps-offset = 0.0 .
op qsize-offset : -> Float .
eq qsize-offset = 0.0 .
op respsize-offset : -> Float .
eq respsize-offset = 0.0 .
op uploadrate-offset : -> Float .
eq uploadrate-offset = 0.0 .

  ops adversary mastodon-proxy alice-raceboat-client-mas-client Alice Bob iodineAlice iodineBob bobapp application-client application-server dnsperf internet-dns corporate-dns mAddr monAddr public-dns root-dns tld-dns mcA : -> Address .

  op myIC : -> Config .
  eq myIC = 
< adversary : Adversary | 
sent: (
tm(1.1416581186931581e-5, to X(public-dns) from corporate-dns : query(0, 'www2 . 'internet . 'com . root, a)) ;
tm(1.8568474836647513e-5, to public-dns from Z(0, corporate-dns) : query(0, 'www2 . 'internet . 'com . root, a)) ;
tm(1.7000052889492152, to X(public-dns) from corporate-dns : query(7727, nm(fragment( iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ;
tm(1.7000109693948529, to public-dns from Z(1, corporate-dns) : query(7727, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ;
tm(1.7010083607876882, to X(public-dns) from corporate-dns : query(15454, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com . root, a)) ;
tm(1.7010090711482753, to public-dns from Z(2, corporate-dns) : query(15454, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com . root, a)) ;
tm(1.8090516124621681, to X(public-dns) from corporate-dns : query(23181, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ;
tm(1.809056817236973, to public-dns from Z(3, corporate-dns) : query(23181, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ;
tm( 1.9170908629187122, to X(public-dns) from corporate-dns : query(30908, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 2, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ;
tm(1.9170955989229395, to public-dns from Z(4, corporate-dns) : query(30908, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 2, 0, 0, 136, false, false)) . 'pwnd .  'com . root, a))), 

rcvd: (
tm(1.1307116878349738e-1, to Z(0, corporate-dns) from public-dns : response(0, 'www2 . 'internet . 'com . root, < 'www2 . 'internet . 'com . root, a, 0.0, 1 . 1 . 1 . 2 >, nil, nil, 0)) ;
tm(1.130776277246483e-1, to corporate-dns from X(public-dns) : response(0, 'www2 . 'internet . 'com . root, < 'www2 . 'internet .  'com . root, a, 0.0, 1 . 1 . 1 . 2 >, nil, nil, 0)) ;
tm(1.5000084725173726, to mastodon-proxy from alice-raceboat-client-mas-client : makeHttpRequest(postRequest, makeMediaFile( "image:I-0-500-50", 500, image(0, 500, 50)))) ;
tm(1.5000084725173726, to mastodon-proxy from alice-raceboat-client-mas-client : makeHttpRequest(postRequest, "hashtag is #meow", 1)) ;
tm(1.8090308756886047, to Z(2, corporate-dns) from public-dns : response(15454, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com . root, < nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com . root, a, 0.0, nm(fragment(iodineAlice, iodineBob, file(0), 0, 0, 0, 0, 0, false, false)) >, nil, nil, 0)) ;
tm(1.8090356117690047, to corporate-dns from X(public-dns) : response(15454, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com . root, < nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com . root, a, 0.0, nm(fragment(iodineAlice, iodineBob, file(0), 0, 0, 0, 0, 0, false, false)) >, nil, nil, 0)) ;
tm(1.917076999203162, to Z(3, corporate-dns) from public-dns : response(23181, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, < nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a, 0.0, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 1, 0, false, false)) >, nil, nil, 0)) ;
tm(1.9170845853593663, to corporate-dns from X( public-dns) : response(23181, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, < nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a, 0.0, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 1, 0, false, false)) >, nil, nil, 0))),

canSeeS: (pat("X", "addr") pat("addr", "Z")), canSeeR: (pat("Z", "addr") pat("addr", "X") pat(mastodon-proxy, "addr")) >
.

  op myIC2 : -> Config .
  eq myIC2 =
< adversary : Adversary | 
sent: (
tm(5.9284461638890209e-6, to X(mastodon-proxy) from mcA : makeHttpRequest(postRequest, makeMediaFile("image:I-1-500-60", 500, image(1, 500, 60)))) ; 
tm(5.9384461638890209e-6, to mastodon-proxy from Z(0, mcA) : makeHttpRequest(postRequest, makeMediaFile("image:I-1-500-60", 500, image(1, 500, 60)))) ; 
tm(5.9484461638890209e-6, to X(mastodon-proxy) from mcA : makeHttpRequest(postRequest, "hashtag is #purple", 1)) ; 
tm(5.9584461638890209e-6, to mastodon-proxy from Z(1, mcA) : makeHttpRequest(postRequest, "hashtag is #purple", 1)) ; 
tm(1.7986706900410356e-5, to X(public-dns) from corporate-dns : query(0, 'www1 . 'internet . 'com . root, a)) ; 
tm(1.7986706900410356e-5, to public-dns from Z(2, corporate-dns) : query(0, 'www1 . 'internet . 'com . root, a)) ; 
tm(1.5000029753460526, to X(mastodon-proxy) from alice-raceboat-client-mas-client : makeHttpRequest(postRequest, makeMediaFile("image:I-0-50-50", 50, image(0, 50, 50)))) ; 
tm(1.5100029753460526, to mastodon-proxy from Z(3, alice-raceboat-client-mas-client) : makeHttpRequest(postRequest, makeMediaFile("image:I-0-50-50", 50, image(0, 50, 50)))) ; 
tm(1.5200029753460526, to X(mastodon-proxy) from alice-raceboat-client-mas-client : makeHttpRequest( postRequest, "hashtag is #meow", 3)) ; 
tm(1.5300029753460526, to mastodon-proxy from Z(4, alice-raceboat-client-mas-client) : makeHttpRequest(postRequest, "hashtag is #meow", 3)) ; 
tm(1.7000164816890215, to X(public-dns) from corporate-dns : query(7727, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(1.7000164816890215, to public-dns from Z(5, corporate-dns) : query(7727, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com .  root, a)) ; 
tm(1.7010127276660383, to X(public-dns) from corporate-dns : query(15454, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com .  root, a)) ; 
tm(1.7010127276660383, to public-dns from Z(6, corporate-dns) : query(15454, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd .  'com . root, a)) ; 
tm(1.8080604077560198, to X(public-dns) from corporate-dns : query(23181, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 2, 0, 0, 136, false, false)) .  'pwnd . 'com . root, a)) ; 
tm(1.8080604077560198, to public-dns from Z(7, corporate-dns) : query(23181, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 2, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(1.8090417531003524, to X(public-dns) from corporate-dns : query(30908, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 2, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(1.8090417531003524, to public-dns from Z(8, corporate-dns) : query(30908, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 2, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(1.9161053217128945, to X(public-dns) from corporate-dns : query(38635, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 3, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(1.9161053217128945, to public-dns from Z(9, corporate-dns) : query(38635, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 3, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(1.9170753982834798, to X(public-dns) from corporate-dns : query(46362, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 3, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(1.9170753982834798, to public-dns from Z(10, corporate-dns) : query(46362, nm(fragment( iodineAlice, iodineBob, file(10000), 0, 3, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(2.0241440795613315, to X(public-dns) from corporate-dns : query(54089, nm( fragment(iodineAlice, iodineBob, file(10000), 0, 4, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(2.0241440795613315, to public-dns from Z(11, corporate-dns) : query(54089, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 4, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(2.0251164979861955, to X(public-dns) from corporate-dns : query(61816, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 4, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(2.0251164979861955, to public-dns from Z(12, corporate-dns) : query(61816, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 4, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) ; 
tm(2.1322014922479986, to X(public-dns) from corporate-dns : query(69543, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 5, 0, 0, 127, false, true)) . 'pwnd . 'com . root, a)) ; 
tm(2.1322014922479986, to public-dns from Z(13, corporate-dns) : query(69543, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 5, 0, 0, 127, false, true)) . 'pwnd . 'com . root, a))), 
rcvd: (
tm(5.9284461638890209e-6, to Z(0, mcA) from mastodon-proxy : makeHttpResponse("OK", makeResponseToot(1))) ; 
tm(5.9284461638890209e-6, to mcA from X( mastodon-proxy) : makeHttpResponse("OK", makeResponseToot(1))) ; 
tm(5.9284461638890209e-6, to Z(1, mcA) from mastodon-proxy : makeHttpResponse("OK", makeResponseToot(2))) ;
tm(5.9284461638890209e-6, to mcA from X(mastodon-proxy) : makeHttpResponse("OK", makeResponseToot(2))) ; 
tm(1.3092496312639623e-1, to Z(2, corporate-dns) from public-dns : response(0, 'www1 . 'internet . 'com . root, < 'www1 . 'internet . 'com . root, a, 0.0, 1 . 1 . 1 . 2 >, nil, nil, 0)) ; 
tm(1.3192496312639623e-1, to corporate-dns from X( public-dns) : response(0, 'www1 . 'internet . 'com . root, < 'www1 . 'internet . 'com . root, a, 0.0, 1 . 1 . 1 . 2 >, nil, nil, 0)) ; 
tm(1.5000029753460526, to Z(3, alice-raceboat-client-mas-client) from mastodon-proxy : makeHttpResponse("OK", makeResponseToot(3))) ; 
tm(1.5100029753460526, to alice-raceboat-client-mas-client from X(mastodon-proxy) : makeHttpResponse("OK", makeResponseToot(3))) ; 
tm(1.5200029753460526, to Z(4, alice-raceboat-client-mas-client) from mastodon-proxy : makeHttpResponse("OK", makeResponseToot(4))) ; 
tm(1.5300029753460526, to alice-raceboat-client-mas-client from X(mastodon-proxy) : makeHttpResponse("OK", makeResponseToot(4))) ; 
tm(1.8080437936904536, to Z(5, corporate-dns) from public-dns : response(7727, nm( fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, < nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a, 0.0, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 1, 0, false, false)) >, nil, nil, 0)) ; 
tm(1.8180437936904536, to corporate-dns from X(public-dns) : response(7727, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, < nm(fragment( iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a, 0.0, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 1, 0, false, false)) >, nil, nil, 0)) ; 
tm(1.8090283523261477, to Z(6, corporate-dns) from public-dns : response(15454, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com . root, < nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com . root, a, 0.0, nm(fragment(iodineAlice, iodineBob, file(0), 0, 0, 0, 1, 0, false, false)) >, nil, nil, 0)) ; 
tm(1.8190283523261477, to corporate-dns from X(public-dns) : response(15454, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com . root, < nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com .  root, a, 0.0, nm(fragment(iodineAlice, iodineBob, file(0), 0, 0, 0, 1, 0, false, false)) >, nil, nil, 0)) ; 
tm(1.9160807154589123, to Z(7, corporate-dns) from public-dns : response(23181, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 2, 0, 0, 136, false, false)) . 'pwnd . 'com . root, < nm(fragment(iodineAlice, iodineBob, file(10000), 0, 2, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a, 0.0, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 2, 0, false, false)) >, nil, nil, 0)) ; 
tm(1.9260807154589123, to corporate-dns from X(public-dns) : response(23181, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 2, 0, 0, 136, false, false)) . 'pwnd . 'com . root, < nm(fragment(iodineAlice, iodineBob, file(10000), 0, 2, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a, 0.0, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 2, 0, false, false)) >, nil, nil, 0)) ; 
tm(1.9170598107678769, to Z(8, corporate-dns) from public-dns : response(30908, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 2, 0, 0, 136, false, false)) . 'pwnd . 'com . root, < nm(fragment(iodineAlice, iodineBob, file(10000), 0, 2, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a, 0.0, nm(fragment( iodineBob, iodineAlice, file(0), 0, 0, 0, 2, 0, false, false)) >, nil, nil, 0)) ; 
tm(1.9270598107678769, to corporate-dns from X(public-dns) : response(30908, nm(fragment( iodineAlice, iodineBob, file(10000), 0, 2, 0, 0, 136, false, false)) . 'pwnd . 'com . root, < nm(fragment(iodineAlice, iodineBob, file(10000), 0, 2, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a, 0.0, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 2, 0, false, false)) >, nil, nil, 0)) ; 
tm(2.0241242906916121, to Z(9, corporate-dns) from public-dns : response(38635, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 3, 0, 0, 136, false, false)) . 'pwnd . 'com . root, < nm(fragment( iodineAlice, iodineBob, file(10000), 0, 3, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a, 0.0, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 3, 0, false, false)) >, nil, nil, 0)) ; 
tm(2.0341242906916121, to corporate-dns from X(public-dns) : response(38635, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 3, 0, 0, 136, false, false)) . 'pwnd . 'com . root, < nm(fragment(iodineAlice, iodineBob, file(10000), 0, 3, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a, 0.0, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 3, 0, false, false)) >, nil, nil, 0)) ; 
tm(2.0251007015861662, to Z(10, corporate-dns) from public-dns : response(46362, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 3, 0, 0, 136, false, false)) . 'pwnd . 'com . root, < nm(fragment(iodineAlice, iodineBob, file(10000), 0, 3, 0, 0, 136, false, false)) . 'pwnd .  'com . root, a, 0.0, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 3, 0, false, false)) >, nil, nil, 0)) ; 
tm(2.0351007015861662, to corporate-dns from X(public-dns) : response(46362, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 3, 0, 0, 136, false, false)) . 'pwnd . 'com . root, < nm(fragment(iodineAlice, iodineBob, file(10000), 0, 3, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a, 0.0, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 3, 0, false, false)) >, nil, nil, 0)) ; 
tm(2.1321681300249535, to Z(11, corporate-dns) from public-dns : response(54089, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 4, 0, 0, 136, false, false)) . 'pwnd . 'com .  root, < nm(fragment(iodineAlice, iodineBob, file(10000), 0, 4, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a, 0.0, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 4, 0, false, false)) >, nil, nil, 0)) ; 
tm(2.1421681300249535, to corporate-dns from X(public-dns) : response(54089, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 4, 0, 0, 136, false, false)) . 'pwnd . 'com . root, < nm(fragment(iodineAlice, iodineBob, file(10000), 0, 4, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a, 0.0, nm(fragment( iodineBob, iodineAlice, file(0), 0, 0, 0, 4, 0, false, false)) >, nil, nil, 0))), 

canSeeS: (pat("addr", "X") pat("addr", "Z")), canSeeR: (pat("X", "addr") pat("Z", "addr")) >
.

  op myIC3 : -> Config .
  eq myIC3 =
< adversary : Adversary | 
sent: (
tm(5.9384461638890209e-6, to mastodon-proxy from Z(0, mcA) : makeHttpRequest(postRequest, makeMediaFile("image:I-1-500-60", 500, image(1, 500, 60)))) ; 
tm(5.9584461638890209e-6, to mastodon-proxy from Z(1, mcA) : makeHttpRequest(postRequest, "hashtag is #purple", 1)) ; 
tm(1.5100029753460526, to mastodon-proxy from Z(3, alice-raceboat-client-mas-client) : makeHttpRequest(postRequest, makeMediaFile("image:I-0-50-50", 50, image(0, 50, 50)))) ; 
tm(1.5300029753460526, to mastodon-proxy from Z(4, alice-raceboat-client-mas-client) : makeHttpRequest(postRequest, "hashtag is #meow", 3)) ; 
tm(1.7100029753460526, to mastodon-proxy from Z(3, alice-raceboat-client-mas-client) : makeHttpRequest(postRequest, makeMediaFile("image:I-0-50-50", 150, image(0, 50, 50)))) ; 
tm(1.7300029753460526, to mastodon-proxy from Z(4, alice-raceboat-client-mas-client) : makeHttpRequest(postRequest, "hashtag is #meow1", 3)) ; 
tm(1.9100029753460526, to mastodon-proxy from Z(3, alice-raceboat-client-mas-client) : makeHttpRequest(postRequest, makeMediaFile("image:I-0-50-50", 250, image(0, 50, 50)))) ; 
tm(1.9300029753460526, to mastodon-proxy from Z(4, alice-raceboat-client-mas-client) : makeHttpRequest(postRequest, "hashtag is #meow11", 3)) ; 
tm(2.1100029753460526, to mastodon-proxy from Z(3, alice-raceboat-client-mas-client) : makeHttpRequest(postRequest, makeMediaFile("image:I-0-50-50", 59, image(0, 50, 50)))) ; 
tm(2.1300029753460526, to mastodon-proxy from Z(4, alice-raceboat-client-mas-client) : makeHttpRequest(postRequest, "hashtag is #meow111", 3)) ; 
tm(2.2100029753460526, to mastodon-proxy from Z(3, alice-raceboat-client-mas-client) : makeHttpRequest(postRequest, makeMediaFile("image:I-0-50-50", 55, image(0, 50, 50)))) ; 
tm(2.2300029753460526, to mastodon-proxy from Z(4, alice-raceboat-client-mas-client) : makeHttpRequest(postRequest, "hashtag is #meow1111", 3)) ; 
tm(2.3100029753460526, to mastodon-proxy from Z(3, alice-raceboat-client-mas-client) : makeHttpRequest(postRequest, makeMediaFile("image:I-0-50-50", 111, image(0, 50, 50)))) ; 
tm(2.3300029753460526, to mastodon-proxy from Z(4, alice-raceboat-client-mas-client) : makeHttpRequest(postRequest, "hashtag is #meow11111", 3)) ; 
tm(2.4100029753460526, to mastodon-proxy from Z(3, alice-raceboat-client-mas-client) : makeHttpRequest(postRequest, makeMediaFile("image:I-0-50-50", 222, image(0, 50, 50)))) ; 
tm(2.4300029753460526, to mastodon-proxy from Z(4, alice-raceboat-client-mas-client) : makeHttpRequest(postRequest, "hashtag is #meow111111", 3))),
rcvd: nilTML, 
canSeeS: (pat("addr", "X") pat("addr", "Z")), canSeeR: (pat("X", "addr") pat("Z", "addr")) >
. 

endm

load smc
set print attribute on .

--- C.1
red getToDCumulativeNQueryPreNAT(myIC, 0) == 1.7000052889492152 .
red getToDCumulativeNQueryPreNAT(myIC, 1) == 1.7010083607876882 . 
red getToDCumulativeNQueryPreNAT(myIC, 3) == 1.9170908629187122 .
red getToDCumulativeNQueryPreNAT(myIC, 5) == 0.0 . 

--- C.2
red getToDCumulativeNQueryPostNAT(myIC, 0) == 1.8568474836647513e-5 .
red getToDCumulativeNQueryPostNAT(myIC, 1) == 1.7000109693948529 .
red getToDCumulativeNQueryPostNAT(myIC, 3) == 1.809056817236973 . 
red getToDCumulativeNQueryPostNAT(myIC, 5) == 0.0 .

red size(query(0, 'www2 . 'internet . 'com . root, a)) == 19 .
red size(query(7727, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a)) == 146 .
red size(query(15454, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com . root, a)) == 10 .
red size (query(69543, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 5, 0, 0, 127, false, true)) . 'pwnd . 'com . root, a)) == 137 .

--- C.3
red getToDCumulativeQuerySizePreNAT (myIC, 0) == 1.7000052889492152 . 
red getToDCumulativeQuerySizePreNAT (myIC, 10) == 1.7000052889492152 .
red getToDCumulativeQuerySizePreNAT (myIC, 145) == 1.7000052889492152 .
red getToDCumulativeQuerySizePreNAT (myIC, 146) == 1.7010083607876882 . 
red getToDCumulativeQuerySizePreNAT (myIC, 170) == 1.8090516124621681 .
red getToDCumulativeQuerySizePreNAT (myIC, 500) == 0.0 .

--- C.4
red getToDCumulativeQuerySizePostNAT (myIC, 0) == 1.8568474836647513e-5 .
red getToDCumulativeQuerySizePostNAT (myIC, 10) == 1.8568474836647513e-5 .
red getToDCumulativeQuerySizePostNAT (myIC, 18) == 1.8568474836647513e-5 .
red getToDCumulativeQuerySizePostNAT (myIC, 19) == 1.7000109693948529 . 
red getToDCumulativeQuerySizePostNAT (myIC, 170) == 1.7010090711482753 .
red getToDCumulativeQuerySizePostNAT (myIC, 320) == 1.809056817236973 . 
red getToDCumulativeQuerySizePostNAT (myIC, 321) == 1.9170955989229395 .
red getToDCumulativeQuerySizePostNAT (myIC, 2000) == 0.0 .

red size(response(0, 'www2 . 'internet . 'com . root, < 'www2 . 'internet . 'com . root, a, 0.0, 1 . 1 . 1 . 2 >, nil, nil, 0)) == 19 .
red size(response(23181, nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd .  'com . root, < nm(fragment(iodineAlice, iodineBob, file(10000), 0, 1, 0, 0, 136, false, false)) . 'pwnd . 'com . root, a, 0.0, nm(fragment(iodineBob, iodineAlice, file( 0), 0, 0, 0, 1, 0, false, false)) >, nil, nil, 0)) == 146 .
red size(response(15454, nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com . root, < nm(fragment(iodineBob, iodineAlice, file(0), 0, 0, 0, 0, 0, false, false)) . 'pwnd . 'com . root, a, 0.0, nm(fragment(iodineAlice, iodineBob, file(0), 0, 0, 0, 0, 0, false, false)) >, nil, nil, 0)) == 10 .

--- C.5
red getToDCumulativeResponsePreNAT(myIC, 0) == 1.8090356117690047 .
red getToDCumulativeResponsePreNAT(myIC, 9) == 1.8090356117690047 .
red getToDCumulativeResponsePreNAT(myIC, 10) == 1.9170845853593663 .
red getToDCumulativeResponsePreNAT(myIC, 155) == 1.9170845853593663 .
red getToDCumulativeResponsePreNAT(myIC, 156) == 0.0 .

--- C.6
red getToDCumulativeResponsePostNAT(myIC, 0) == 1.1307116878349738e-1 .
red getToDCumulativeResponsePostNAT(myIC, 20) == 1.8090308756886047 .
red getToDCumulativeResponsePostNAT(myIC, 155) == 1.917076999203162 .
red getToDCumulativeResponsePostNAT(myIC, 200) == 0.0 .

--- C.7
red getToDCumulativeHttpConnectionPreNAT(myIC2, 0) == 1.5000029753460526 .
red getToDCumulativeHttpConnectionPreNAT(myIC2, 1) == 1.5200029753460527 .
red getToDCumulativeHttpConnectionPreNAT(myIC2, 2) == 0.0 .

--- C.8
red getToDCumulativeHttpConnectionPostNAT (myIC2, 0) == 5.9384461638890209e-6 .
red getToDCumulativeHttpConnectionPostNAT (myIC2, 1) == 5.9584461638890207e-6 .
red getToDCumulativeHttpConnectionPostNAT (myIC2, 2) == 1.5100029753460526 .
red getToDCumulativeHttpConnectionPostNAT (myIC2, 3) == 1.5300029753460527 .
red getToDCumulativeHttpConnectionPostNAT (myIC2, 4) == 0.0 .

red size (makeHttpRequest(postRequest, "hashtag is #purple", 1)) == 28 .
red size (makeHttpRequest(postRequest, makeMediaFile("image:I-1-500-60", 500, image(1, 500, 60)))) == 510 .

--- C.9
red getToDCumulativeHttpUploadPreNAT(myIC2, 0) == 1.5000029753460526 .
red getToDCumulativeHttpUploadPreNAT(myIC2, 60) == 1.5200029753460527 .
red getToDCumulativeHttpUploadPreNAT(myIC2, 85) == 1.5200029753460527 .
red getToDCumulativeHttpUploadPreNAT(myIC2, 86) == 0.0 .

--- C.10 
red getToDCumulativeHttpUploadPostNAT(myIC2, 0) == 5.9384461638890209e-6 .
red getToDCumulativeHttpUploadPostNAT(myIC2, 510) == 5.9584461638890206e-6 .
red getToDCumulativeHttpUploadPostNAT(myIC2, 538) == 1.5100029753460527 .
red getToDCumulativeHttpUploadPostNAT(myIC2, 598) == 1.5300029753460527 .
red getToDCumulativeHttpUploadPostNAT(myIC2, 700) == 0.0 .

--- MA.1
red getInitialQPS(myIC2, 0.0) == 0.0 .
red getInitialQPS(myIC2, 1.0) == 1.0 .
red getInitialQPS(myIC2, 2.0) == 3.5 .
red getPerWindowQPs(myIC2, 1.0, 0.5, 0.25) == 0.0 4.0 1.2e+1 1.4e+1 6.0 . 
red getPerWindowQPs(myIC2, 1.0, 1.0, 0.25) == 6.0 9.0 9.0 7.0 3.0 .
red getToD(myIC2, 1.0, 1.0, 0.25, 3.0, 1) == 2.0 .
red getToD(myIC2, 1.0, 1.0, 0.25, 3.0, 2) == 2.25 .
red getToD(myIC2, 1.0, 1.0, 0.25, 3.0, 3) == 2.5 .
red getToD(myIC2, 1.0, 1.0, 0.25, 3.0, 4) == 2.75 .
red getToD(myIC2, 1.0, 1.0, 0.25, 3.0, 5) == 0.0 .
red getToD(myIC2, 1.0, 1.0, 0.25, 8.0, 1) == 2.25 .
red getToD(myIC2, 1.0, 1.0, 0.25, 8.0, 2) == 2.5 .
red getToD(myIC2, 1.0, 1.0, 0.25, 10.0, 1) == 0.0 .

--- MA.2
red getAvgQuerySize(myIC2, 0.0, 2.25) == 118.8 .
red getAvgQuerySize(myIC2, 0.0, 1.0) == 19.0 .
red getAvgQuerySize(myIC2, 0.75, 1.0) == 78.0 .
red getPerWindowQS(myIC2, 0.0, 1.0, 0.25) == 19.0 0.0 0.0 78.0 1.2333333333333333e+2 1.2988888888888889e+2 1.2988888888888889e+2 1.4471428571428572e+2 143.0 . 
red getToDAvgQuerySize(myIC2, 1.0, 1.0, 0.25, 4.0, 1) == 1.75 .
red getToDAvgQuerySize(myIC2, 1.0, 1.0, 0.25, 4.0, 2) == 2.0 .
red getToDAvgQuerySize(myIC2, 1.0, 1.0, 0.25, 4.0, 6) == 3.0 .
red getToDAvgQuerySize(myIC2, 1.0, 1.0, 0.25, 4.0, 7) == 0.0 .
red getToDAvgQuerySize(myIC2, 1.0, 1.0, 0.25, 4.5, 1) == 2.0 .
red getToDAvgQuerySize(myIC2, 1.0, 1.0, 0.25, 8.0, 1) == 0.0 .

--- MA.3 
red getAvgRespSize(myIC2, 0.0, 0.25) == 19.0 .
red getAvgRespSize(myIC2, 0.25, 1.5) == 0.0 .
red getAvgRespSize(myIC2, 1.75, 0.25) == 112.0 .
red getAvgRespSize(myIC2, 2.0, 0.25) == 146.0 .
red getPerWindowRS(myIC2, 0.0, 1.0, 0.25) == 19.0 0.0 0.0 0.0 112.0 1.2657142857142857e+2 1.2657142857142857e+2 1.2657142857142857e+2 146.0 .
red getToDAvgResponseSize(myIC2, 1.0, 1.0, 0.25, 5.0, 1) == 2.0 .
red getToDAvgResponseSize(myIC2, 1.0, 1.0, 0.25, 5.0, 5) == 3.0 .
red getToDAvgResponseSize(myIC2, 1.0, 1.0, 0.25, 5.0, 6) == 0.0 .
red getToDAvgResponseSize(myIC2, 1.0, 1.0, 0.25, 6.0, 1) == 2.25 .
red getToDAvgResponseSize(myIC2, 1.0, 1.0, 0.25, 6.0, 3) == 2.75 .
red getToDAvgResponseSize(myIC2, 1.0, 1.0, 0.25, 7.0, 1) == 3.0 .
red getToDAvgResponseSize(myIC2, 1.0, 1.0, 0.25, 8.0, 1) == 0.0 .

--- MA.4 
red getAvgUploadRate(myIC3, 0.0, 0.25) == 17.216e+3 .  
red getAvgUploadRate(myIC3, 1.5, 0.25) == 8.736e+3 .
red getAvgUploadRate(myIC3, 1.75, 0.25) == 9.216e+3 .
red getAvgUploadRate(myIC3, 2.0, 0.25) == 6.176e+3 .
red getAvgUploadRate(myIC3, 2.25, 0.25) == 13.312e+3 .
red getAvgUploadRate(myIC3, 2.5, 0.25) == 0.0 .
red getPerWindowUR(myIC3, 0.0, 1.0, 0.25) == 4.304e+3 0.0 0.0 2.184e+3 4.488e+3 6.032e+3 9.36e+3 7.176e+3 4.872e+3 3.328e+3 . 
red getToDAvgUploadRate(myIC3, 1.0, 1.0, 0.25, 1.0, 1) == 2.0 . 
red getToDAvgUploadRate(myIC3, 1.0, 1.0, 0.25, 1.0, 2) == 2.25 . 
red getToDAvgUploadRate(myIC3, 1.0, 1.0, 0.25, 1.0, 3) == 2.5 . 
red getToDAvgUploadRate(myIC3, 1.0, 1.0, 0.25, 1.0, 4) == 2.75 . 
red getToDAvgUploadRate(myIC3, 1.0, 1.0, 0.25, 1.0, 5) == 3.0 . 
red getToDAvgUploadRate(myIC3, 1.0, 1.0, 0.25, 1.0, 6) == 0.0 . 
red getToDAvgUploadRate(myIC3, 1.0, 1.0, 0.25, 1.5, 1) == 2.5 . 
red getToDAvgUploadRate(myIC3, 1.0, 1.0, 0.25, 1.5, 2) == 2.75 . 
red getToDAvgUploadRate(myIC3, 1.0, 1.0, 0.25, 1.5, 3) == 0.0 . 
red getToDAvgUploadRate(myIC3, 1.0, 1.0, 0.25, 2.0, 1) == 2.5 . 
red getToDAvgUploadRate(myIC3, 1.0, 1.0, 0.25, 2.0, 2) == 0.0 . 
