--- This maude file has been created automatically from the Python representation ---
load ../dns/maude/probabilistic/iodine_dns
--- load ../dns/maude/probabilistic/paced-client-checkdone
load ../../deps/dns_formalization/Maude/test/probabilistic-model/test_helpers
load ../common/maude/router
load ../common/maude/adversary-observer
load ../app/maude/probabilistic

mod HCS_TEST is

  inc IODINE_DNS + TEST-HELPERS .
  inc CP2_APP .
  inc ROUTER .
  inc ADVERSARY-OBSERVER .

  ops adversary Alice Bob bobapp application-client application-server dnsperf internet-dns local-dns mAddr monAddr public-dns root-dns tld-dns : -> Address .

  op myIC : -> Config .
  eq myIC = < adversary : Adversary | 
    sent: (tm(6.2033243880141526e-5, to X(public-dns) from local-dns : query(0, 'www0 . 'internet . 'com .    root, a)) ;
      tm(6.6784676295618212e-2, to X(public-dns) from local-dns : query(1, 'www1 . 'internet . 'com . root, a)) ;
      tm(    1.3351481511965704e-1, to X(public-dns) from local-dns : query(2, 'www2 . 'internet . 'com . root, a)) ;
      tm(    2.0027849546140059e-1, to X(public-dns) from local-dns : query(3, 'www3 . 'internet . 'com . root, a)) ;
      tm(    2.6695759189377455e-1, to X(public-dns) from local-dns : query(4, 'www4 . 'internet . 'com . root, a)) ;
      tm(    3.3363638231206755e-1, to X(public-dns) from local-dns : query(5, 'www5 . 'internet . 'com . root, a)) ;
      tm(    4.0037953158424461e-1, to X(public-dns) from local-dns : query(6, 'www6 . 'internet . 'com . root, a)) ;
      tm(    4.6711900683323998e-1, to X(public-dns) from local-dns : query(7, 'www7 . 'internet . 'com . root, a)) ;
      tm(    5.3383524398715998e-1, to X(public-dns) from local-dns : query(8, 'www8 . 'internet . 'com . root, a)) ;
      tm(    6.0051978066876288e-1, to X(public-dns) from local-dns : query(9, 'www9 . 'internet . 'com . root, a)) ;
      tm(    6.672276584452359e-1, to X(public-dns) from local-dns : query(10, 'www10 . 'internet . 'com . root, a)) ;
      tm(    7.3395485463696364e-1, to X(public-dns) from local-dns : query(11, 'www11 . 'internet . 'com . root, a)) ;
      tm(    8.00679769822082e-1, to X(public-dns) from local-dns : query(12, 'www12 . 'internet . 'com . root, a)) ;
      tm(    8.6741456438240283e-1, to X(public-dns) from local-dns : query(13, 'www13 . 'internet . 'com . root, a)) ;
      tm(    9.3410140433038202e-1, to X(public-dns) from local-dns : query(14, 'www14 . 'internet . 'com . root, a)) ;
      tm(    1.0000164560463001, to X(public-dns) from local-dns : query(7727, nm(fragment(Alice, Bob, file(10000), 0, 1, 200, false,    false)) . 'pwnd . 'com . root, a)) ;
      tm(1.0008486262336374, to X(public-dns) from local-dns : query(15, 'www15 . 'internet .    'com . root, a)) ;
      tm(1.020052419786742, to X(public-dns) from local-dns : query(15454, nm(fragment(Alice, Bob, file(10000),    0, 2, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(1.0400917807912062, to X(public-dns) from local-dns : query(23181,    nm(fragment(Alice, Bob, file(10000), 0, 3, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(1.0601396896929789, to X(    public-dns) from local-dns : query(30908, nm(fragment(Alice, Bob, file(10000), 0, 4, 200, false, false)) . 'pwnd . 'com .    root, a)) ;
      tm(1.0676068491559678, to X(public-dns) from local-dns : query(16, 'www16 . 'internet . 'com . root, a)) ;
      tm(    1.0801690040081, to X(public-dns) from local-dns : query(38635, nm(fragment(Alice, Bob, file(10000), 0, 5, 109, false, true))    . 'pwnd . 'com . root, a)) ;
      tm(1.1201984134733705, to X(public-dns) from local-dns : query(46362, nm(fragment(Alice, Bob,    file(10000), 1, 1, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(1.1343357944222501, to X(public-dns) from local-dns :    query(17, 'www17 . 'internet . 'com . root, a)) ;
      tm(1.1402540347947578, to X(public-dns) from local-dns : query(54089, nm(    fragment(Alice, Bob, file(10000), 1, 2, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(1.1603036408284428, to X(    public-dns) from local-dns : query(61816, nm(fragment(Alice, Bob, file(10000), 1, 3, 200, false, false)) . 'pwnd . 'com .    root, a)) ;
      tm(1.1803594978631431, to X(public-dns) from local-dns : query(69543, nm(fragment(Alice, Bob, file(10000), 1, 4,    200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(1.2003954724058301, to X(public-dns) from local-dns : query(77270, nm(    fragment(Alice, Bob, file(10000), 1, 5, 118, false, true)) . 'pwnd . 'com . root, a)) ;
      tm(1.2010590166158228, to X(    public-dns) from local-dns : query(18, 'www18 . 'internet . 'com . root, a)) ;
      tm(1.2404253629195927, to X(public-dns) from    local-dns : query(84997, nm(fragment(Alice, Bob, file(10000), 2, 1, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(    1.2604665237295003, to X(public-dns) from local-dns : query(92724, nm(fragment(Alice, Bob, file(10000), 2, 2, 200, false,    false)) . 'pwnd . 'com . root, a)) ;
      tm(1.2677586204926288, to X(public-dns) from local-dns : query(19, 'www19 . 'internet .    'com . root, a)) ;
      tm(1.2805214304939658, to X(public-dns) from local-dns : query(100451, nm(fragment(Alice, Bob, file(    10000), 2, 3, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(1.3005553715847549, to X(public-dns) from local-dns :    query(108178, nm(fragment(Alice, Bob, file(10000), 2, 4, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(    1.3206004621802176, to X(public-dns) from local-dns : query(115905, nm(fragment(Alice, Bob, file(10000), 2, 5, 143, false,    true)) . 'pwnd . 'com . root, a)) ;
      tm(1.3344720676659845, to X(public-dns) from local-dns : query(20, 'www20 . 'internet .    'com . root, a)) ;
      tm(1.3606433260577635, to X(public-dns) from local-dns : query(123632, nm(fragment(Alice, Bob, file(    10000), 3, 1, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(1.3806804870748095, to X(public-dns) from local-dns :    query(131359, nm(fragment(Alice, Bob, file(10000), 3, 2, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(    1.4007084048958842, to X(public-dns) from local-dns : query(139086, nm(fragment(Alice, Bob, file(10000), 3, 3, 200, false,    false)) . 'pwnd . 'com . root, a)) ;
      tm(1.4011643640513369, to X(public-dns) from local-dns : query(21, 'www21 . 'internet .    'com . root, a)) ;
      tm(1.4207603601057477, to X(public-dns) from local-dns : query(146813, nm(fragment(Alice, Bob, file(    10000), 3, 4, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(1.4407954095257449, to X(public-dns) from local-dns :    query(154540, nm(fragment(Alice, Bob, file(10000), 3, 5, 168, false, true)) . 'pwnd . 'com . root, a)) ;
      tm(    1.4679305895384254, to X(public-dns) from local-dns : query(22, 'www22 . 'internet . 'com . root, a)) ;
      tm(    1.4808347048058503, to X(public-dns) from local-dns : query(162267, nm(fragment(Alice, Bob, file(10000), 4, 1, 200, false,    false)) . 'pwnd . 'com . root, a)) ;
      tm(1.5008866073462228, to X(public-dns) from local-dns : query(169994, nm(fragment(    Alice, Bob, file(10000), 4, 2, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(1.5209281561295782, to X(public-dns) from    local-dns : query(177721, nm(fragment(Alice, Bob, file(10000), 4, 3, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(    1.5346196263006922, to X(public-dns) from local-dns : query(23, 'www23 . 'internet . 'com . root, a)) ;
      tm(    1.5409738199655665, to X(public-dns) from local-dns : query(185448, nm(fragment(Alice, Bob, file(10000), 4, 4, 200, false,    false)) . 'pwnd . 'com . root, a)) ;
      tm(1.5610169147157251, to X(public-dns) from local-dns : query(193175, nm(fragment(    Alice, Bob, file(10000), 4, 5, 120, false, true)) . 'pwnd . 'com . root, a)) ;
      tm(1.6010616222304062, to X(public-dns) from    local-dns : query(200902, nm(fragment(Alice, Bob, file(10000), 5, 1, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(    1.6013550584422032, to X(public-dns) from local-dns : query(24, 'www24 . 'internet . 'com . root, a)) ;
      tm(    1.6210951787657921, to X(public-dns) from local-dns : query(208629, nm(fragment(Alice, Bob, file(10000), 5, 2, 200, false,    false)) . 'pwnd . 'com . root, a)) ;
      tm(1.6411208806933815, to X(public-dns) from local-dns : query(216356, nm(fragment(    Alice, Bob, file(10000), 5, 3, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(1.6611722759163658, to X(public-dns) from    local-dns : query(224083, nm(fragment(Alice, Bob, file(10000), 5, 4, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(    1.6680441224511124, to X(public-dns) from local-dns : query(25, 'www25 . 'internet . 'com . root, a)) ;
      tm(    1.6812012524593505, to X(public-dns) from local-dns : query(231810, nm(fragment(Alice, Bob, file(10000), 5, 5, 171, false,    true)) . 'pwnd . 'com . root, a)) ;
      tm(1.7212574122075437, to X(public-dns) from local-dns : query(239537, nm(fragment(Alice,    Bob, file(10000), 6, 1, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(1.7347152244057655, to X(public-dns) from    local-dns : query(26, 'www26 . 'internet . 'com . root, a)) ;
      tm(1.7413041756896188, to X(public-dns) from local-dns : query(    247264, nm(fragment(Alice, Bob, file(10000), 6, 2, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(1.7613499048955554, to    X(public-dns) from local-dns : query(254991, nm(fragment(Alice, Bob, file(10000), 6, 3, 200, false, false)) . 'pwnd . 'com .    root, a)) ;
      tm(1.7813886189630628, to X(public-dns) from local-dns : query(262718, nm(fragment(Alice, Bob, file(10000), 6, 4,    200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(1.8014195024370752, to X(public-dns) from local-dns : query(270445, nm(    fragment(Alice, Bob, file(10000), 6, 5, 108, false, true)) . 'pwnd . 'com . root, a)) ;
      tm(1.801470014053006, to X(    public-dns) from local-dns : query(27, 'www27 . 'internet . 'com . root, a)) ;
      tm(1.8414600053798735, to X(public-dns) from    local-dns : query(278172, nm(fragment(Alice, Bob, file(10000), 7, 1, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(    1.8615051502513305, to X(public-dns) from local-dns : query(285899, nm(fragment(Alice, Bob, file(10000), 7, 2, 200, false,    false)) . 'pwnd . 'com . root, a)) ;
      tm(1.868190593078457, to X(public-dns) from local-dns : query(28, 'www28 . 'internet .    'com . root, a)) ;
      tm(1.8815481723813436, to X(public-dns) from local-dns : query(293626, nm(fragment(Alice, Bob, file(    10000), 7, 3, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(1.9015754176177531, to X(public-dns) from local-dns :    query(301353, nm(fragment(Alice, Bob, file(10000), 7, 4, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(    1.9216157463529431, to X(public-dns) from local-dns : query(309080, nm(fragment(Alice, Bob, file(10000), 7, 5, 169, false,    true)) . 'pwnd . 'com . root, a)) ;
      tm(1.9349260674035094, to X(public-dns) from local-dns : query(29, 'www29 . 'internet .    'com . root, a)) ;
      tm(1.9616408688218196, to X(public-dns) from local-dns : query(316807, nm(fragment(Alice, Bob, file(    10000), 8, 1, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(1.9816798798827735, to X(public-dns) from local-dns :    query(324534, nm(fragment(Alice, Bob, file(10000), 8, 2, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(    2.0016073476962655, to X(public-dns) from local-dns : query(30, 'www30 . 'internet . 'com . root, a)) ;
      tm(    2.0017160713638482, to X(public-dns) from local-dns : query(332261, nm(fragment(Alice, Bob, file(10000), 8, 3, 200, false,    false)) . 'pwnd . 'com . root, a)) ;
      tm(2.0217432882455384, to X(public-dns) from local-dns : query(339988, nm(fragment(    Alice, Bob, file(10000), 8, 4, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(2.0417860402986667, to X(public-dns) from    local-dns : query(347715, nm(fragment(Alice, Bob, file(10000), 8, 5, 84, false, true)) . 'pwnd . 'com . root, a)) ;
      tm(    2.0683722068311106, to X(public-dns) from local-dns : query(31, 'www31 . 'internet . 'com . root, a)) ;
      tm(    2.0818361620966348, to X(public-dns) from local-dns : query(355442, nm(fragment(Alice, Bob, file(10000), 9, 1, 200, false,    false)) . 'pwnd . 'com . root, a)) ;
      tm(2.1018668364447031, to X(public-dns) from local-dns : query(363169, nm(fragment(    Alice, Bob, file(10000), 9, 2, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(2.121916571146599, to X(public-dns) from    local-dns : query(370896, nm(fragment(Alice, Bob, file(10000), 9, 3, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(    2.1351235409204907, to X(public-dns) from local-dns : query(32, 'www32 . 'internet . 'com . root, a)) ;
      tm(    2.1419615185527734, to X(public-dns) from local-dns : query(378623, nm(fragment(Alice, Bob, file(10000), 9, 4, 200, false,    false)) . 'pwnd . 'com . root, a)) ;
      tm(2.1619917843487504, to X(public-dns) from local-dns : query(386350, nm(fragment(    Alice, Bob, file(10000), 9, 5, 124, false, true)) . 'pwnd . 'com . root, a)) ;
      tm(2.2018062006036518, to X(public-dns) from    local-dns : query(33, 'www33 . 'internet . 'com . root, a)) ;
      tm(2.2020241784024255, to X(public-dns) from local-dns : query(    394077, nm(fragment(Alice, Bob, file(10000), 10, 1, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(2.2220528632953016,    to X(public-dns) from local-dns : query(401804, nm(fragment(Alice, Bob, file(10000), 10, 2, 200, false, false)) . 'pwnd .    'com . root, a)) ;
      tm(2.242077851293895, to X(public-dns) from local-dns : query(409531, nm(fragment(Alice, Bob, file(10000),    10, 3, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(2.262115337671796, to X(public-dns) from local-dns : query(417258,    nm(fragment(Alice, Bob, file(10000), 10, 4, 200, false, false)) . 'pwnd . 'com . root, a)) ;
      tm(2.2685430256695738, to X(    public-dns) from local-dns : query(34, 'www34 . 'internet . 'com . root, a)) ;
      tm(2.282167341922908, to X(public-dns) from    local-dns : query(424985, nm(fragment(Alice, Bob, file(10000), 10, 5, 129, false, true)) . 'pwnd . 'com . root, a)) ;
      tm(    2.3222177245871536, to X(public-dns) from local-dns : query(432712, nm(fragment(Alice, Bob, file(10000), 11, 1, 153, true,    true)) . 'pwnd . 'com . root, a))), 
    rcvd: nilTML, 
    canSeeS: mtObs, 
    canSeeR: pat("X", "addr") > .

endm

load smc
set print attribute on .
red getInitialQPS(myIC, 1.0) == 15.0 .
red getPerWindowQPs(myIC, 1.0, 0.5, 0.25) == 58.0 58.0 56.0 56.0 38.0 8.0 .
red getToD(myIC, 1.0, 0.5, 0.25, 3.0, 1) == 1.5 .
red getToD(myIC, 1.0, 0.5, 0.25, 3.0, 2) == 1.75 .
red getToD(myIC, 1.0, 0.5, 0.25, 3.0, 3) == 2.0 .
red getToD(myIC, 1.0, 0.5, 0.25, 3.0, 4) == 2.25 .
red getToD(myIC, 1.0, 0.5, 0.25, 3.0, 5) == 0.0 .

