--- MAUDE_HCS: maude_hcs
---
--- Software Markings (UNCLASS)
--- Maude-HCS Software
---
--- Copyright (C) 2025 RTX BBN Technologies Inc. All Rights Reserved
---
--- The computer software and computer software documentation are licensed
--- under the Apache License, Version 2.0 (the "License"); you may not use
--- this file except in compliance with the License. A copy of the License
--- is provided in the LICENSE file, but you may obtain a copy of the
--- License at:  https://www.apache.org/licenses/LICENSE-2.0
---
--- The computer software and computer software documentation are based
--- upon work supported by the Defense Advanced Research Projects Agency (DARPA)
--- under Agreement No. HR00l 12590083.
---
--- This document does not contain technology or technical data controlled under
--- either the U.S. International Traffic in Arms Regulations or the U.S. Export
--- Administration Regulations.
---
--- DISTRIBUTION STATEMENT A: Approved for public release; distribution is
--- unlimited.
---
--- Notice: Markings. Any reproduction of this computer software, computer
--- software documentation, or portions thereof must also reproduce the markings
--- contained herein. Refer to the provided NOTICE file.
---
--- MAUDE_HCS: end

set clear rules off .
set print attribute off .
set show advisories off .

---- raceboat  user models
sload ../../deps/dns_formalization/Maude/common/apmaude
sload ../common/maude/user-action-actor
sload ../cp3-tests/skyhook/skyhook-um-mamodel-1

**** sload ../../../common/maude/http-overhead.maude

---- irc 
sload ../irc/common/irc_name
sload ../irc/common/_aux
sload ../irc/irc_prob

---- this should go in a scenario dir
sload ../raceboatSkyhook/maude/irc-rbbyteseq-interface  
sload ../irc/irc_monitor

------ raceboat 4 skyhook
sload ../raceboatSkyhook/maude/rb-cm-simple-bi

----- skyhook

sload ../skyhook/skyhook_prob
sload ../s3/s3_protocol


mod HCS_TEST is
  inc SCHEDULER .
  inc USER-ACTION-ACTOR .
  inc SKYHOOK-UM-MAMODEL-1 .
  inc IRC .
  inc IRC-RBBYTESEQ-INTERFACE .
  inc CONTENT-MANAGER-SIMPLE-BI .
  inc SKYHOOK .
  inc S3_PROTOCOL .
  inc IRC_MONITOR .
 
vars j : Nat .

eq encOH(fsize:Nat,ksize:Nat)  = 0 .
eq noiseMin(msg:Msg) = 0.001 .

**** addresses
*** alice
ops ircaAddr : -> Address .
**** alice channel endpoint interfaces
ops ifaceACAddr ifaceASAddr : -> Address .

*** client endpoint ac
ops umacAddr  cmacAddr puaAddr sdkacAddr : -> Address .
*** server endpoint as
ops umasAddr  cmasAddr ahaAddr sdkasAddr : -> Address .
op irccAddr : -> Address .

*** bob
ops ircbAddr : -> Address .
**** bobs channel endpoint interfaces
ops ifaceBCAddr ifaceBSAddr : -> Address .

*** client endpoint  ..bc.. 
ops umbcAddr  cmbcAddr pubAddr sdkbcAddr : -> Address .
*** server endpoint ..bs..
ops umbsAddr  cmbsAddr ahbAddr sdkbsAddr : -> Address .

ops ircSrvAddr  s3SrvAddr : -> Address .
op ircMonitorAddr : -> Address .

-----------------------
**** actors
*** alice
op ircaAct : -> Actor .
ops ifaceACAct ifaceASAct : -> Actor .


*** client endpoint ac
ops umacAct  cmacAct puaAct sdkacAct : -> Actor .
*** server endpoint as
ops umasAct  cmasAct ahaAct sdkasAct : -> Actor .

*** bob
op ircbAct : -> Actor .
ops ifaceBCAct ifaceBSAct : -> Actor .

*** client endpoint  ..bc.. 
ops umbcAct  cmbcAct pubAct sdkbcAct : -> Actor .
*** server endpoint ..bs..
ops umbsAct  cmbsAct ahbAct sdkbsAct : -> Actor .

ops ircSrvAct  s3SrvAct : -> Actor .
op ircMonitorAct : -> Actor .

************** actor defns
***** aliceIrc
eq ircaAct =
   makeIrcClient(ircaAddr, ifaceACAddr,
    (1.000 ~> ("qahUgAL6bnl9XWg2NwSM40SLBwV2Jf7nAi1s0As6K9fsNxwdo2e6xxFjftx5VXoEzMT9dWnYPu8EkyZXLAUpFdTl1GmYI5ND6ObJ5hUAVGVmm15qh2MKQPVlbgUs2nNTeB0knENw97eC1ahIQGw2HJDJIDyP1spYBxnDO4FMnPxspP7gPqC3eSdXAXQd5U9K9V1iNOfvkcQBKC8DFKUrE6jgYeD2vUHG0yCCdFZI3N2gTqhnSUGUVthn6TuG4Dofs2Pt2bOSh20QzqHsTcw1U0yImFJbjJoHB", makeIrcChannelName("room1")))
    : (8.278 ~> ("7EAayAkk7DcRboy8BHWDQdiwmScPu6MgLCJ9rkt3eQa5PLAsUprwAuILVdwdgMfMY3R5Z1qAkOOkyppKMrG1063RMGYK0ooFIR6VsMqROFxbeJahNthQDQfzwGUDC5cErzBxtqCEIDQN7koJE6vFzS2Vq6zfZH5D0QKniHWr1b9dusKSzhZ0v7XRen08aR5wcmK3UmwUwaNol6PDiASiJXvjNLQsGtbavCnbUdfXE8oLAU3Z951HYD0Pr1inF8FENTKwwQHAGVBhaKpPRylapzYw12aNhQFovOKJdOYfeZ9K7Aq1eJ4XymIJqapMdJ0bWbqklJtzTTWZxmCDnJ5oR3nseLiqqv11SvVqoBNRVTgd4FoZl7xC49TvWVmV", makeIrcChannelName("room1")))
    : (19.992 ~> ("5suQEFWFfW8lxk05Yiqift37gcEwsPtlBHLybHUktsVq2e75FY2i6HJvNbtBVYhGsrsL1GDGVDM7TN6hPyC9rAFxaWP8jhxgihZ7kMteTAAQSxBV8AGctqwvmnDIVcfoRVYqQ6TNvDOfSNLHf4mgg55F35NpLvhuHgg6y6Drx00lb5ZqOPB688meBp2l6mtLhBOg7YxuAwOvNP8M5GikfsGu2PMYCais16zBO0Is0utY0uskDgLzs0oGakpL5MSaAMJtPHclfB2UqiT5jtoW24jsQB", makeIrcChannelName("room1")))
    : (29.485 ~> ("5rIwqLwb1MOkySNLhUrqM7VyK9cVwGFhSb9upgMsR7x8s0ZI2Q2wLrbV2bwIPzL3MxKVxPVlctxzM48PsvrSKc9hPLNgESqadWEJcvRS7eR7XZKgqEPRVzcgrNe1VEdNJdR5lbahaLPPR2MHroYX5Mc2lDtjFfb5Ucmb7zuwQvk7hrx01pdG1tYyJiBJmy4ZB8FHaoh6SEU1kJyNb9sxpvaHdNDWFJunvHWLVCPXH7g8u58UEV2QLDMbMG5ng3zyXdlH5KciuoW7eW21tFQPpBH1hhxE9ddkMYDsdmrMpt6Hh9CtYIrCWL8yG5gxQn46KJVcyEyUdFT7Dkhu6bcdnlwoCiNi8S7plCUY6B", makeIrcChannelName("room1")))
    : (40.801 ~> ("JNRJQ6ETMkNY1PkDurtZCbCPNznK8gJBQ4eglbbsniHlmjRp7sPMPIgaqQ474DRvcbR2GqzeoTgVzmkmFzLaUSWOKAUaQ8flGN25Px1GmTVa01R1a5iqh4gi2NfQs0QZv3HiGVyPwVxOIrhyBHk8GGB", makeIrcChannelName("room2")))
    : (49.595 ~> ("dHPf794ZW2A2kH1EqUnJXEyA1npPwfZzPbKg5s8uodZI4OKyRFYlDwoJIqTjF1ulkWPy0OoyJTMIQUngickcdGezGdbYmf0LJPZ8wLlQKPLHQ7jMPW0tgRHWeXrKLF3qfDJDT2G7XNJD73IZkA3souQLVcw1WzqR1PBxrQVPD8b9IfaGe3dRVjBXgHhIgYjvJDVUsph5wtzhIUJQFGRoyKQjLiyux9I7xmGM2t6Gyf5gleCbo", makeIrcChannelName("room1")))
    : (61.541 ~> ("QCaHXwODyyLcAC0lKKpEFNk5obkaiMaupuARX9e9gBELR2mDB6L61CNbdZoCdq2IasPMdW0v3wlgzQpPMiLlfuz13j2s98CkC2xErKKMHZiuLb2RHxwYQLYYO", makeIrcChannelName("room2")))
    : (71.305 ~> ("Ok1DiJ3zodOm5ccUzNJxqgmLRpdreirBh79UeNPkUsYynAJ5vPMcWPgblh9eHohvIUkpmz9Alt5OOwHZ7J3bkgG2yHfLY29wr2M5cWLYAuAoUWO1B5bo6tUztpoBDEeWLgny5adk0MAX2y0v0slbITRsrZtHwTAE9QbvONmpjt4T2HiWGiEIEsfgn7ndlXqzRwcu2Ih6OWlCxPyHS7OmeUp1jDhNqOmZSYv6aHZJeCYZDY1gQuMjAfczJm6tryGIbgxvURn6LRW8dbaWSypYVzUalPi18DjHCmTShS0toa2yHiZqNv8QDGgmgjC4WCIDboDVoqCblLSovlhngZgQ2NtMV9NwL736zwH", makeIrcChannelName("room1")))
    : (79.889 ~> ("MWmjHR6Uf4bQ8WVBtY20uWQwOBEL4mT4AXNwTisu4MIfTEpXoGpl2b5PdqMgCATPSfU67fbcx43KBLdIQxNzSgprvdipHQeH8koDSBze4r0k2gow0SjgmlQFsNaJlM1qcmrFpQDFyfErcM98PvqgBNsaPWq6S7nCCgnulclRAATxJ3tQKCyVwZoIoRxf2ZzAcX0HQa4TzQ6tGL75MzkdacVcmVSNpoguo0Tkg4dqsGz0c7VAg60v188Rkb7PmIxZf1OAmCDsJx1P26VFTRSPj48nmp331iuplk9BRD2VUmnBAVLIx68wDjglvPnH6mqSEOS", makeIrcChannelName("room2")))
    : (89.784 ~> ("sve0SUcIeLLxEBqvBFzca8TzYhBjoDoWredRIps43GPx2eYbjzOpYM77BkQEj9h6We2oe3K3JWveHJbLVodT78S6LwUC7bjJuDPBQVoqcy5Rtv7bGaxNq4pki", makeIrcChannelName("room1")))
    : (100.969 ~> ("CFjNbzsYguF0RGSx8XhMaE9ZTm0tZDioxCuteotjG8jCaOIucQPGFfVIoXIgIBfvmGpclbLdmRFH4OxlC6PDVfVr1OKpJZV4dXChiBQXY7ct7pjqVD7mu9xgdQFTQxkNtDaujrliv1QqEiCAsIpEBWzYS2DfDmDq611pqeocmmnSDfDnUNQANcK1iOVZ2P7Ua18vAutvARgG82nUz0Dbs4772tWaVveFQwjDrbc4CW9AQoaj6uRNJAaQc4oeJ9nMDcZVJXyN36XMJvT9yNaQMifpPFEwVir7viuzavvxEpHHpHU79xUUkGRETp5axPZHbONZaWThkXDG20hqxMnCcpRw4ayqCsb0XW7n5t8iYNyR4QGqe7noN0x8stmfik6GM0vZQ8", makeIrcChannelName("room2")))
    : (109.505 ~> ("M0FHZ5mzhXKcLnZqb73Xt5ip33MyCko7ErZh6CW8VIP4aX92jpy4yG4bVyr2kYJlgU5axGjh4AUfQz92KBUE3FwXJQgHAs1RUy05waRUUokTun4EpPwkZcLsMKu03Eo3YreE6", makeIrcChannelName("room2")))
    : (117.833 ~> ("DrXRBVeYvKxOR9t4KAirQvBboXXjX1RcSzB1PCvWB2VNRcJGz0kN7HtDc0tIZzDTdf4BVi3a9Fd2FunTHyIwy81NeXaoggI0pTehaKFtd6KZ9glMsQYddEUBbbrdeXJyic6EdpagvaOqHBOiykl1rHfZfLildftUU5GMZdkNryJs5HF9t1eBj2l4MDBH9fcHZpyAoVlq9dUrPTaci0G1tECQzfrDRiNFqnz", makeIrcChannelName("room1")))
   ) .   
***(
  < ircaAddr : IrcClient |
    thisAddr: ircaAddr,
    appAddr: aliceAddr,
    raceboatAddr: ifaceACAddr,  ---- rb ircclient interface
    ircName: makeIrcUserName(ircaAddr),
    aliceAppChatsMap: (
       (2.0 ~> ("Alice message 0", makeIrcChannelName("ab")))
     : (20. ~> ("Alice message 1", makeIrcChannelName("ab")))
     : (40. ~> ("Alice message 2", makeIrcChannelName("ab"))))
  >
  .
)  
  
**** TEST-PKG2 uses 2.0 3.5 5.4
eq ifaceACAct =
   mkIrcByteSeqIface(ifaceACAddr,ircaAddr,
                     cmacAddr,cmacAddr) .

**** alice client rb endpoint
eq umacAct = 
   mkUMactor(umacAddr,skyhook-um-mamodel-1-ma,cmacAddr) 
   .
eq cmacAct = 
    mkCMSimpleBi(cmacAddr,ifaceACAddr,puaAddr) .


**** buckets: "bucket:a2s"  "bucket:s2a"  
**** uuidSeeds: "uuid:a2s"  "uuid:s2a"  
eq puaAct = makeSkyhookPU(
          puaAddr,
          cmacAddr,  --- rbc0Tos0Addr
          sdkacAddr,  ---  s3Client0Tos0Addr,
          "s_to_c_bucket_a",
          "c_to_s_bucket_a",
          "s_to_c_uuid_a",  --- fetch
          "c_to_s_uuid_a-hash" --- post
                ----"c_to_s_uuid_a"
          )
      .
eq sdkacAct = 
    < sdkacAddr : S3SdkClient | 
       thisAddr: sdkacAddr, realAwsAddr: s3SrvAddr, 
       nextId: 1, pendingReqs: emptyS3ReqMap > .

***  alice server endpoint
eq ifaceASAct =
   mkIrcByteSeqIface(ifaceASAddr,ircSrvAddr,
                     cmasAddr,cmasAddr) .

eq umasAct = 
   mkUMactor(umasAddr,skyhook-um-mamodel-1-ma,cmasAddr) 
   .
eq cmasAct = 
    mkCMSimpleBi(cmasAddr,ifaceASAddr,ahaAddr) .

eq ahaAct = makeSkyhookAH(ahaAddr,
              cmasAddr,  ---- rbs0Toc0Addr,
              sdkasAddr, 
                      ---- s3Client0Toc0Addr,
              "c_to_s_bucket_a",
              "s_to_c_bucket_a",
              "c_to_s_uuid_a",
              "s_to_c_uuid_a",
              "s_to_c_uuid_a"   ---"post_uuid_a"
              )
.

eq sdkasAct = 
       < sdkasAddr : S3SdkClient | 
         thisAddr: sdkasAddr, realAwsAddr: s3SrvAddr,
         nextId: 1, pendingReqs: emptyS3ReqMap > .

********************************
*** bob
***** bob Irc 
eq ircbAct =
   makeIrcClient(ircbAddr, ifaceBCAddr,
    (110.104 ~> ("h3wf8zxY06F4iV9KCZxcenEfDKzAcdcwTgulkAod4I9zCRpVDKfkz0YdpUBF9BrXSdVL2BbCOGoxJq1PM8ud1HtGWZ4bBFJLNiXwTNuf05Sa3Hyn3boaqrTfE0srQPhV22l8otWvK1JlVxS1ChUT1TUINFjVrgB1iuaMG7idbejOtPL7DfnApQ9qsogYwZkGsLyWgMZhKWmpQQ9fmLp93jEz5xX0e6EY7EhJMoJFOOHlrwCEh2P7OsEP118bEtJStiXzdFocxph7wLwR9O5iZaK6qfWJ15zo0LJRDh2ArerihbpSIEv0YgqcTJjyqdGZgwgKw0yIaW2tIrwMs7GHtg6IKluXQ3pIfGyJDdPdSDnBALRApYvILpDzwzyfmEHws1NnxGrIQEupDJ", makeIrcChannelName("room2")))
    : (119.482 ~> ("TQ1x4saVeH4ynb7CeJkmDLr09myZW6W6TrlOm1LxqxCuKACwYKkd646hFV7E8Qt2OD3N3PS1GVDuCWkw0oNeBLox6cX8xyw5z9yrUyYOxaPlm0Imzxj6440LO9YFMeA7SEWAliVuKdtLyuzMUo6Ig1EzXr494TkOP54GSZxHZlEY38A44S6pUNchnSl5Ay6qK3KGwqCVpOLizVstRFG91UkydNErMVVOH53M0qYZXnc9QXGI0i487DUQnbtGDOJfFV1tOlm35XefF9nE7kz3OhPN2e8wlSOXIXXniP9jZyX3Mi0eiH5GKPXFOv1YarfA07CJCt8CpD7fPkK98HKPQSBoSRQYQeWcIo6xTpNBuBjdtW6ysSDQKsrWHdax", makeIrcChannelName("room1")))
   ) .
   
***(
  < ircbAddr : IrcClient |
    thisAddr: ircbAddr,
    appAddr: bobAddr,
    raceboatAddr: ifaceBCAddr, --- rb ircclient interface
    ircName: makeIrcUserName(ircbAddr),
    aliceAppChatsMap: (
      (6.0 ~> ("Bob message 0", makeIrcChannelName("ab")))
     : (30. ~> ("Bob message 1", makeIrcChannelName("ab")))
     : (60. ~> ("Bob message 2", makeIrcChannelName("ab"))))
  >
  .
)

eq ifaceBCAct =
   mkIrcByteSeqIface(ifaceBCAddr,ircbAddr,
                     cmbcAddr,cmbcAddr) .

**** bob client rb endpoint
eq umbcAct = 
   mkUMactor(umbcAddr,skyhook-um-mamodel-1-ma,cmbcAddr) 
   .
eq cmbcAct = 
    mkCMSimpleBi(cmbcAddr,ifaceBCAddr,pubAddr) .

**** buckets: "bucket:a2s"  "bucket:s2a"  
**** uuidSeeds: "uuid:a2s"  "uuid:s2a"  
eq pubAct = makeSkyhookPU(
          pubAddr,
          cmbcAddr,  --- rbc0Tos0Addr
          sdkbcAddr,  ---  s3Client0Tos0Addr,
          "s_to_c_bucket_b",
          "c_to_s_bucket_b",
          "s_to_c_uuid_b",
          "c_to_s_uuid_b-hash"
          )
      .

eq sdkbcAct = 
    < sdkbcAddr : S3SdkClient | 
       thisAddr: sdkbcAddr, realAwsAddr: s3SrvAddr, 
       nextId: 1, pendingReqs: emptyS3ReqMap > .

***  alice server endpoint
eq ifaceBSAct =
   mkIrcByteSeqIface(ifaceBSAddr,ircSrvAddr,
                     cmbsAddr,cmbsAddr) .

eq umbsAct = 
   mkUMactor(umbsAddr,skyhook-um-mamodel-1-ma,cmbsAddr) 
   .
eq cmbsAct = 
    mkCMSimpleBi(cmbsAddr,ifaceBSAddr,ahbAddr) .

eq ahbAct = makeSkyhookAH(ahbAddr,
                  cmbsAddr,  ---- rbs0Toc0Addr,
                  sdkbsAddr, ---- s3Client0Toc0Addr,
                  "c_to_s_bucket_b",
                  "s_to_c_bucket_b",
                  "c_to_s_uuid_b",
                  "s_to_c_uuid_b",
                  "s_to_c_uuid_b" ---- "post_uuid_b"
              )
.

eq sdkbsAct = 
       < sdkbsAddr : S3SdkClient | 
         thisAddr: sdkbsAddr, realAwsAddr: s3SrvAddr,
         nextId: 1, pendingReqs: emptyS3ReqMap > .


******** global actors
eq s3SrvAct  = < s3SrvAddr : AwsS3HttpServer |
      thisAddr: s3SrvAddr, s3DataMap: emptyS3DataMap > .

**** makeIrcServer takes an unused address arg
eq ircSrvAct =
    < ircSrvAddr : IrcServer |
        thisAddr: ircSrvAddr,
        channelMap: emptyNameClientsMap,
        clientTimestampMap: emptyClientTimestampMap,
        clientAddressMap: emptyClientAddressMap
    >
  .

eq ircMonitorAct = 
    makeIrcMonitor(ircMonitorAddr,
               (ircSrvAddr ;; ircaAddr ;; ircbAddr)) .  
                
------------ end actors               

op LinkType-2 : -> AttributeSet .
eq LinkType-2 = 
  (delayStd: 0.),
  (delayType: "Constant"),
  (delayMean: 0.),
  (delayConst: 0.1),
  (noiseMin: 0.),
  (noiseMax: 0.00001),
  (dropP: 0.),
  (canDrop: false)
  .

**** ircc-if-rb...pu-skdc === s3srv sdkbcAddr s3SrvAddr
**** ircs ifs-rbs--ah-skds ==== s3srv sdkbsAddr

eq LinkData =
  aaa(s3SrvAddr,sdkacAddr,LinkType-2)
  aaa(s3SrvAddr,sdkasAddr,LinkType-2)
  aaa(s3SrvAddr,sdkbcAddr,LinkType-2)
  aaa(s3SrvAddr,sdkbsAddr,LinkType-2)
 
  aaa(sdkacAddr,s3SrvAddr,LinkType-2)
  aaa(sdkasAddr,s3SrvAddr,LinkType-2)
  aaa(sdkbcAddr,s3SrvAddr,LinkType-2)
  aaa(sdkbsAddr,s3SrvAddr,LinkType-2)
.
 
op initState : Nat -> Config .
eq initState(j ) =
     rCtr(j + 8)
******* alice 
   ircaAct 
*** alice client endpoint
   ifaceACAct
   umacAct  cmacAct puaAct sdkacAct
**** alice server endpoint
   ifaceASAct
   umasAct  cmasAct ahaAct sdkasAct

******* bob
   ircbAct 
**** bob client endpoint
   ifaceBCAct
   umbcAct  cmbcAct pubAct sdkbcAct
***** bob server endpoint
   ifaceBSAct
   umbsAct  cmbsAct ahbAct sdkbsAct
   
**** global
   ircSrvAct s3SrvAct
   ircMonitorAct
   
**** start messages  
**** alice channel  
  [1.0 + genRandomX(j,0.0, 0.0001),
   (to umacAddr from umacAddr : actionR("ok")),0]
  [1.0  + genRandomX(s s j,0.0, 0.0001),
    (to umasAddr from umasAddr : actionR("ok")),0]

**** bob channel   
  [1.0 + genRandomX(j + 4,0.0, 0.0001),
   (to umbcAddr from umbcAddr : actionR("ok")),0]
  [1.0  + genRandomX(j + 6,0.0, 0.0001),
   (to umbsAddr from umbsAddr : actionR("ok")),0]

**** start ahAlice
    [0.001, (to ahaAddr from  ahaAddr : SkyhookStartCmd), 0]

**** start ahBob
    [0.002, (to ahbAddr from ahbAddr : SkyhookStartCmd), 0]

**** start alice
  [0.25, (to ircaAddr : StartIrc), 0]
**** start bob
  [0.33, (to ircbAddr : StartIrc), 0]
**** alice joins with cnx rb server send addr
**** if sent by alice, it would come from rcv addr!!
  [0.40, (to ircSrvAddr from ifaceASAddr : 
        JoinChannel(makeIrcChannelName("room1"),ircaAddr)),
     0]
  [0.41, (to ircSrvAddr from ifaceASAddr : 
        JoinChannel(makeIrcChannelName("room2"),ircaAddr)),
     0]
  [0.5, (to ircSrvAddr from  ifaceBSAddr :
       JoinChannel(makeIrcChannelName("room1"),ircbAddr)),
     0]
  [0.51, (to ircSrvAddr from  ifaceBSAddr :
       JoinChannel(makeIrcChannelName("room2"),ircbAddr)),
     0]
.

op slimit : -> Float .
eq slimit = 1000.0 .

op initConfig : -> Config .
rl[init]: initConfig 
   => run({0.0 | nil} initState(counter),slimit) .

 endm
eof
 red "Alice,Bob join room1 room2, Alice,Bob send texts ircMonitor" .
**** red initState(0) .
set print attribute on .
 rew initConfig .
 q
 eof

  
