sload pwnd_cp3_scenario_2
sload ../../../../maude_hcs/lib/smc/smc_cp3-refactored

sload pwnd_cp3_scenario_2-baseline-eq

mod PWND-CP3-SCENARIO-2-RUN is
  inc HCS_TEST .  
  inc SMC_CP3 . 
  inc PWND-CP3-SCENARIO-2-BASELINE-EQ . 
  
  ----eq slimit = 100.0 . ---- redefine if needed

 eq finalize(c:Config) = mvKs2Adv(c:Config,false) .

endm

rew run({0.0 | nil} initState(counter) [hcsDelay, (to baseLineAddr from baseLineAddr : initKs),0], slimit) .
q