sload scenario2_perf
sload ../../../../maude_hcs/lib/smc/smc_cp3-refactored

sload scenario2_perf-baseline-eq

mod SCENARIO2-PERF-RUN is
  inc HCS_TEST .  
  inc SMC_CP3 . 
  inc SCENARIO2-PERF-BASELINE-EQ . 
  
  ----eq slimit = 100.0 . ---- redefine if needed

 eq finalize(c:Config) = mvKs2Adv(c:Config,false) .

endm

rew run({0.0 | nil} initState(counter) [hcsDelay, (to baseLineAddr from baseLineAddr : initKs),0], slimit) .
q