sload scenario2
sload ../../../../maude_hcs/lib/smc/smc_cp3-refactored
sload scenario2-baseline-eq


mod SCENARIO2-BASELINE is
  inc HCS_TEST .  
  inc SMC_CP3 . 
  
  ----eq slimit = 100.0 . ---- redefine if needed

  eq hcsDelay = slimit + slimit .  --- prevent hcs from starting

 eq finalize(c:Config) = addK2Blist(c:Config,false) .

endm

rew run({0.0 | nil} initState(counter) [tgenDelay, (to baseLineAddr from baseLineAddr : initBase),0], slimit) .
q