import logging
import json
import os
import sys
import re

logger = logging.getLogger(__name__)

# Standard header from the provided example
HEADER = """--- MAUDE_HCS: this file is autogenerated by maude_hcs ---
"""


class JsonToMaudeParser:
    def __init__(self, model_name, stem, load_path="lib/common/maude/markov-action-model.maude"):
        self.model_name = model_name  # the fmod module name
        self.stem = stem # the file name
        self.load_path = load_path

    def format_float(self, val):
        """Ensures floats look like 1.0 instead of 1"""
        s = str(float(val))
        return s

    def to_maude_jv(self, val, indent=0):
        """
        Converts a python value (from JSON) into a Maude JV (Json Value).
        recursive for objects (jo) and lists (jl).
        """
        if isinstance(val, dict):
            # Map{String, JV} inside a jo(...)
            # Format: jo( (key |-> val), (key2 |-> val2) )
            if not val:
                return "jo(empty)"

            items = []
            keys = list(val.keys())  # Maintain order

            # Simple heuristic for formatting:
            # If it's a small object (like random params), keep it compact.
            # If deeply nested, use newlines.

            entry_strs = []
            for k, v in val.items():
                v_str = self.to_maude_jv(v, indent + 4)
                # keys in Maude JV are usually quoted strings?
                # looking at example: "type" |-> js("wait")
                # keys are Strings.
                entry_strs.append(f'("{k}" |-> {v_str})')

            inner = ", ".join(entry_strs)
            # Wrap in double parens for the Map
            return f"jo(({inner}))"

        elif isinstance(val, list):
            # List{JV} inside a jl(...)
            # Format: jl( v1 ; v2 )
            if not val:
                return "jl(empty)"
            items = [self.to_maude_jv(x, indent) for x in val]
            return f"jl({' ; '.join(items)})"

        elif isinstance(val, str):
            return f'js("{val}")'

        elif isinstance(val, bool):
            return f'jb({str(val).lower()})'

        elif isinstance(val, int):
            return f'jn({val})'

        elif isinstance(val, float):
            return f'jf({self.format_float(val)})'

        else:
            return "nullJV"

    def convert_markov_section(self, markov_data):
        """
        Converts the 'markov' JSON object.
        Target: Map{String, Map{String, Float}}
        Format: ( "state" |-> ("next" |-> 1.0, "next2" |-> 0.5) )
        """
        entries = []
        for state, transitions in markov_data.items():
            trans_entries = []
            for next_state, prob in transitions.items():
                trans_entries.append(f'("{next_state}" |-> {self.format_float(prob)})')

            trans_block = " , ".join(trans_entries)
            # Parentheses around the inner map
            entries.append(f'( "{state}" |-> ({trans_block}) )')

        return " ,\n\n    ".join(entries)

    def convert_actions_section(self, actions_data):
        """
        Converts the 'actions' JSON object.
        Target: Map{String, JV}
        Format: ( "name" |-> jo(...) )
        """
        entries = []
        for name, action_def in actions_data.items():
            jv_str = self.to_maude_jv(action_def)
            entries.append(f'("{name}" |->  {jv_str})')

        return ",\n    ".join(entries)

    def convert_params_section(self, params_data):
        """
        Converts the 'parameters' JSON object.
        Target: Map{String, JV}
        Format: ( "key" |-> val )
        """
        entries = []
        for k, v in params_data.items():
            jv_str = self.to_maude_jv(v)
            entries.append(f'("{k}" |->  {jv_str})')

        return ",\n        ".join(entries)

    def generate(self, json_content):
        data = json.loads(json_content)

        m_name = self.model_name
        upper_name = m_name.upper()

        # 1. Generate sections
        markov_str = self.convert_markov_section(data.get("markov", {}))
        actions_str = self.convert_actions_section(data.get("actions", {}))
        params_str = self.convert_params_section(data.get("parameters", {}))

        # 2. Construct file
        output = []
        output.append(HEADER)
        output.append("")
        output.append(f"load {self.load_path}")
        output.append("")
        output.append(f"fmod {upper_name}-MAMODEL is")
        output.append("  inc  MARKOV-ACTION-MODEL .")
        output.append("")
        output.append(f"op {m_name}-markov : ->  Map{{String,Map{{String,Float}}}} .")
        output.append(f"op {m_name}-actions : -> Map{{String,JV}} .")
        output.append(f"op {m_name}-params : -> Map{{String,JV}} .")
        output.append("")
        output.append(f"op {m_name}-ma : -> MAModel .  --- markov-action")
        output.append(f"eq {m_name}-ma =")
        output.append(f'   ma("{m_name}",{m_name}-markov,{m_name}-actions,{m_name}-params) .')
        output.append("")

        output.append(f"eq {m_name}-markov =  ")
        output.append(f"    {markov_str} ")
        output.append("  .                   ")
        output.append("")

        output.append(f"eq {m_name}-actions = (")
        output.append(f"    {actions_str}")
        output.append("    ) ")
        output.append(" .")
        output.append("")

        output.append(f"eq {m_name}-params = (")
        output.append(f"        {params_str}")
        output.append("        ) .")
        output.append("")
        output.append("endfm ")
        output.append("  ")
        output.append("eof  ")

        return "\n".join(output)


def calculate_relative_load_path(full_output_path, target_lib_suffix="lib/common/maude/markov-action-model.maude"):
    """
    Calculates the relative path for the 'load' statement by anchoring on the 'lib' directory.

    If full_output_path is '.../dir1/dir2/lib/mastodon/maude/file.maude'
    and target_lib_suffix is 'lib/common/maude/markov-action-model.maude',
    it assumes the anchor 'lib' is shared.

    The target full path is constructed as:
    [Path before 'lib'] + [target_lib_suffix]

    Then the relative path from the output file's directory to this target is calculated.
    """
    # Normalize inputs to absolute paths
    abs_output_path = os.path.abspath(full_output_path)

    # Split path into components to find "lib"
    parts = list(os.path.normpath(abs_output_path).split(os.sep))

    if "lib" not in parts:
        print(
            f"Warning: Could not correctly determine the relative import. 'lib' directory not found in path: {full_output_path}")
        return target_lib_suffix

    # Find the index of "lib". We use the first occurrence to establish the anchor root.
    lib_index = parts.index("lib")

    # Construct the base directory (the parent of 'lib')
    # Use os.path.join(*parts[:lib_index])
    # Handle the case where parts[:lib_index] is empty or starts with empty string (Linux absolute root)
    root_parts = parts[:lib_index]

    if abs_output_path.startswith(os.sep):
        # Linux/Unix absolute path (starts with /)
        base_dir = os.sep + os.path.join(*root_parts) if root_parts else os.sep
    elif parts[0].endswith(':'):
        # Windows absolute path
        base_dir = os.path.join(*root_parts)
    else:
        # Fallback
        base_dir = os.path.join(*root_parts) if root_parts else "."

    # Construct the absolute path to the target library
    # Note: target_lib_suffix may contain forward slashes, normalize it
    norm_suffix = os.path.normpath(target_lib_suffix)
    target_abs_path = os.path.join(base_dir, norm_suffix)

    # Directory where the generated Maude file resides
    source_dir = os.path.dirname(abs_output_path)

    # Calculate relative path
    rel_path = os.path.relpath(target_abs_path, start=source_dir)

    # Force forward slashes for Maude compatibility (even on Windows)
    return rel_path.replace(os.sep, '/')

def process_directories(args, input_root, output_root):
    """
    Recursively finds all .json files in input_root, converts them to Maude,
    and writes them to the same relative path in output_root with .maude extension.

    For example:
      Input:  json_root/dir1/file1.json
      Output: maude_root/dir1/file1.maude
    """
    if not os.path.exists(input_root):
        logger.error(f"Error: Input directory '{input_root}' does not exist.")
        return

    logger.debug(f"Starting conversion from '{input_root}' to '{output_root}'...")

    count = 0
    for root, dirs, files in os.walk(input_root):
        for file in files:
            if file.endswith(".json"):
                # 1. Determine paths
                full_input_path = os.path.join(root, file)

                # Relative path from the input root (e.g., "dir1")
                rel_dir = os.path.relpath(root, input_root)

                # Filename stem (e.g., "file1" from "file1.json")
                stem = os.path.splitext(file)[0]
                stem_clean = args.protocol + "-" + stem.replace("_", "-")

                # Construct output directory path
                target_dir = os.path.join(output_root, rel_dir)
                os.makedirs(target_dir, exist_ok=True)

                # Construct output file path
                output_filename = f"{stem}.maude"
                full_output_path = os.path.join(target_dir, output_filename)

                # 2. Calculate the relative load path using the new anchor logic
                rel_load_path = calculate_relative_load_path(full_output_path)

                try:
                    # 2. Read JSON
                    with open(full_input_path, 'r') as f:
                        json_content = f.read()

                        # 4. Convert
                        # Pass the dynamically calculated load path
                        parser = JsonToMaudeParser(model_name=stem_clean, stem=stem, load_path=rel_load_path)
                        maude_content = parser.generate(json_content)

                    # 4. Write Maude
                    with open(full_output_path, 'w') as f:
                        f.write(maude_content)

                    logger.debug(f"Generated: {full_output_path}")
                    count += 1

                except Exception as e:
                    logger.error(f"Error processing {full_input_path}: {e}")

    logger.info(f"Done. Processed {count} files.")
