import argparse
import logging
import json
import os
import sys

logger = logging.getLogger(__name__)

HEADER = """--- MAUDE_HCS: this file is autogenerated by maude_hcs ---
"""


class JsonToMaudeV2Parser:
    """
    Converts a v2 Markov-action JSON config (with top-level 'markov',
    'states', and 'parameters' sections) into a Maude MAModel-v2 definition.

    The v2 format has a two-level Markov structure:
      - Top-level 'markov': mode-to-mode transitions (Map{String,JV})
      - Per-state 'markov': action-to-action transitions within a mode
      - Per-state 'actions', 'dwell_steps', 'burst_steps', etc.

    Output uses mav2(markov, states, parameters) constructor from
    MARKOV-ACTION-MODEL-V2.
    """

    def __init__(self, model_name, stem, load_path="lib/common/maude/markov-action-model-v2.maude"):
        self.model_name = model_name
        self.stem = stem
        self.load_path = load_path

    def format_float(self, val):
        """Ensures floats look like 1.0 instead of 1"""
        return str(float(val))

    def to_maude_jv(self, val, indent=0):
        """
        Converts a Python value (from JSON) into a Maude JV (Json Value).
        Recursive for objects (jo) and lists (jl).
        """
        if isinstance(val, dict):
            if not val:
                return "jo(empty)"
            entry_strs = []
            for k, v in val.items():
                v_str = self.to_maude_jv(v, indent + 4)
                entry_strs.append(f'("{k}" |-> {v_str})')
            inner = ", ".join(entry_strs)
            return f"jo(({inner}))"

        elif isinstance(val, list):
            if not val:
                return "jl(empty)"
            items = [self.to_maude_jv(x, indent) for x in val]
            return f"jl({' ; '.join(items)})"

        elif isinstance(val, str):
            return f'js("{val}")'

        elif isinstance(val, bool):
            return f'jb({str(val).lower()})'

        elif isinstance(val, int):
            return f'jn({val})'

        elif isinstance(val, float):
            return f'jf({self.format_float(val)})'

        else:
            return "nullJV"

    def expand_idle_state(self, state_data):
        """
        Transforms a 'type': 'wait' state (like idle) into a proper v2 state
        block so the UM-V2 framework can handle it uniformly.

        Input:  {"type": "wait", "sleep": {"random": "gaussian", "mean": 300.0, "std": 80.0}}
        Output: Full v2 state block with noop action and inter_burst_delay from sleep.
        """
        sleep = state_data.get("sleep", {"random": "gaussian", "mean": 300.0, "std": 80.0})

        return {
            "type": "state",
            "initial_action": "noop",
            "dwell_steps": {"random": "gaussian", "mean": 1.0, "std": 0.0},
            "actions": {
                "noop": {"type": "noop"}
            },
            "markov": {
                "noop": {"noop": 1.0}
            },
            "burst_prob": 0.0,
            "burst_steps": {"random": "gaussian", "mean": 0.0, "std": 0.0},
            "inter_burst_delay": sleep,
            "intra_burst_delay": {"random": "gaussian", "mean": 0.0, "std": 0.0}
        }

    def convert_v2_markov_section(self, markov_data):
        """
        Converts the top-level 'markov' section into Map{String,JV}.
        Each value is a jo(...) of (state -> jf(weight)) entries.

        Output format:
          "browse" |-> jo(("browse" |-> jf(0.5)), ("download" |-> jf(0.3)), ...),
          "download" |-> jo(...)
        """
        entries = []
        for state, transitions in markov_data.items():
            trans_entries = []
            for next_state, prob in transitions.items():
                trans_entries.append(f'("{next_state}" |-> jf({self.format_float(prob)}))')
            trans_inner = ", ".join(trans_entries)
            entries.append(f'  "{state}" |-> jo(({trans_inner}))')
        return ",\n".join(entries)

    def convert_state_block(self, state_name, state_data):
        """
        Converts a single state block into a jo(...) JV expression.
        Handles all fields: type, initial_action, dwell_steps, actions,
        markov, burst_prob, burst_steps, intra/inter_burst_delay.
        """
        inner_parts = []

        # type
        stype = state_data.get("type", "state")
        inner_parts.append(f'("type" |-> js("{stype}"))')

        # initial_action (optional)
        if "initial_action" in state_data:
            inner_parts.append(f'("initial_action" |-> js("{state_data["initial_action"]}"))')

        # dwell_steps (random distribution)
        if "dwell_steps" in state_data:
            inner_parts.append(f'("dwell_steps" |-> {self.to_maude_jv(state_data["dwell_steps"])})')

        # entry (optional, usually empty)
        if "entry" in state_data:
            inner_parts.append(f'("entry" |-> {self.to_maude_jv(state_data["entry"])})')

        # exit (optional, usually empty)
        if "exit" in state_data:
            inner_parts.append(f'("exit" |-> {self.to_maude_jv(state_data["exit"])})')

        # actions - Map{String, JV}
        if "actions" in state_data:
            act_entries = []
            for aname, adef in state_data["actions"].items():
                act_entries.append(f'("{aname}" |-> {self.to_maude_jv(adef)})')
            act_inner = ",\n          ".join(act_entries)
            inner_parts.append(f'("actions" |-> jo((\n          {act_inner})))')

        # markov - inner action-level markov chain
        if "markov" in state_data:
            mk_entries = []
            for from_act, transitions in state_data["markov"].items():
                tr_entries = []
                for to_act, prob in transitions.items():
                    tr_entries.append(f'("{to_act}" |-> jf({self.format_float(prob)}))')
                tr_inner = ", ".join(tr_entries)
                mk_entries.append(f'("{from_act}" |-> jo(({tr_inner})))')
            mk_inner = ",\n          ".join(mk_entries)
            inner_parts.append(f'("markov" |-> jo((\n          {mk_inner})))')

        # burst_prob
        if "burst_prob" in state_data:
            inner_parts.append(f'("burst_prob" |-> jf({self.format_float(state_data["burst_prob"])}))')

        # burst_steps (random distribution)
        if "burst_steps" in state_data:
            inner_parts.append(f'("burst_steps" |-> {self.to_maude_jv(state_data["burst_steps"])})')

        # inter_burst_delay (random distribution)
        if "inter_burst_delay" in state_data:
            inner_parts.append(f'("inter_burst_delay" |-> {self.to_maude_jv(state_data["inter_burst_delay"])})')

        # intra_burst_delay (random distribution or scalar)
        if "intra_burst_delay" in state_data:
            inner_parts.append(f'("intra_burst_delay" |-> {self.to_maude_jv(state_data["intra_burst_delay"])})')

        joined = ",\n      ".join(inner_parts)
        return f'jo((\n      {joined}))'

    def convert_v2_states_section(self, states_data):
        """
        Converts the 'states' section into Map{String,JV}.
        Each state maps to a jo(...) containing its full state block.
        Idle/wait states are auto-expanded.
        """
        entries = []
        for sname, sdata in states_data.items():
            # Expand idle/wait states into full v2 state blocks
            if sdata.get("type") == "wait":
                sdata = self.expand_idle_state(sdata)
            else:
                # Ensure all required v2 fields have defaults for non-idle states
                sdata = dict(sdata)  # copy to avoid mutating input
                if "burst_prob" not in sdata:
                    sdata["burst_prob"] = 0.0
                # Auto-populate initial_action if missing — the UM-V2 framework
                # calls getInitialAction(stateBlock) which returns "none" when
                # this key is absent, and "none" won't match any action.
                if "initial_action" not in sdata:
                    if "actions" in sdata and sdata["actions"]:
                        sdata["initial_action"] = next(iter(sdata["actions"]))
                    elif "markov" in sdata and sdata["markov"]:
                        sdata["initial_action"] = next(iter(sdata["markov"]))

            # Ensure random distribution params use floats for realizeRand
            sdata = self._ensure_distribution_floats(sdata)

            block_str = self.convert_state_block(sname, sdata)
            entries.append(f'  "{sname}" |-> {block_str}')

        return ",\n\n".join(entries)

    def _ensure_distribution_floats(self, state_data):
        """
        Ensures that random distribution parameters (mean, std, min, max, floor,
        scale, alpha, beta) are always floats, since Maude's realizeRand expects
        jf() not jn() values.
        """
        dist_keys = ["dwell_steps", "burst_steps", "intra_burst_delay", "inter_burst_delay"]
        float_params = {"mean", "std", "min", "max", "floor", "scale", "alpha", "beta"}

        result = dict(state_data)
        for dk in dist_keys:
            if dk in result and isinstance(result[dk], dict) and "random" in result[dk]:
                dist = dict(result[dk])
                for pk in float_params:
                    if pk in dist and isinstance(dist[pk], (int, float)):
                        dist[pk] = float(dist[pk])
                result[dk] = dist
        return result

    def convert_params_section(self, params_data):
        """
        Converts the 'parameters' section into Map{String,JV}.
        """
        entries = []
        for k, v in params_data.items():
            jv_str = self.to_maude_jv(v)
            entries.append(f'("{k}" |-> {jv_str})')
        return ",\n        ".join(entries)

    def generate(self, json_content):
        data = json.loads(json_content)

        m_name = self.model_name
        upper_name = m_name.upper().replace("-", "-")

        # Extract sections
        markov_data = data.get("markov", {})
        states_data = data.get("states", {})
        params_data = data.get("parameters", {})

        # Convert sections
        markov_str = self.convert_v2_markov_section(markov_data)
        states_str = self.convert_v2_states_section(states_data)
        params_str = self.convert_params_section(params_data)

        # Build output
        output = []
        output.append(HEADER)
        output.append(f"sload {self.load_path}")
        output.append("")
        output.append(f"fmod {upper_name}-MAMODEL-V2 is")
        output.append("  inc  MARKOV-ACTION-MODEL-V2 .")
        output.append("")

        output.append(f"op {m_name}-markov : -> Map{{String,JV}} .")
        output.append(f"op {m_name}-states : -> Map{{String,JV}} .")
        output.append(f"op {m_name}-params : -> Map{{String,JV}} .")
        output.append("")

        output.append(f"op {m_name}-ma-v2 : -> MAModel-v2 .")
        output.append(f"eq {m_name}-ma-v2 =")
        output.append(f"   mav2({m_name}-markov, {m_name}-states, {m_name}-params) .")
        output.append("")

        output.append(f"eq {m_name}-markov =")
        output.append(f"{markov_str}")
        output.append("  .")
        output.append("")

        output.append(f"eq {m_name}-states =")
        output.append(f"{states_str}")
        output.append("  .")
        output.append("")

        output.append(f"eq {m_name}-params = (")
        output.append(f"        {params_str}")
        output.append("        ) .")
        output.append("")
        output.append("endfm")
        output.append("")
        output.append("eof")

        return "\n".join(output)


def calculate_relative_load_path(full_output_path, target_lib_suffix="lib/common/maude/markov-action-model-v2.maude"):
    """
    Calculates the relative path for the 'sload' statement by anchoring on the 'lib' directory.
    """
    abs_output_path = os.path.abspath(full_output_path)
    parts = list(os.path.normpath(abs_output_path).split(os.sep))

    if "lib" not in parts:
        print(
            f"Warning: Could not correctly determine the relative import. "
            f"'lib' directory not found in path: {full_output_path}")
        return target_lib_suffix

    lib_index = parts.index("lib")
    root_parts = parts[:lib_index]

    if abs_output_path.startswith(os.sep):
        base_dir = os.sep + os.path.join(*root_parts) if root_parts else os.sep
    elif parts[0].endswith(':'):
        base_dir = os.path.join(*root_parts)
    else:
        base_dir = os.path.join(*root_parts) if root_parts else "."

    norm_suffix = os.path.normpath(target_lib_suffix)
    target_abs_path = os.path.join(base_dir, norm_suffix)
    source_dir = os.path.dirname(abs_output_path)
    rel_path = os.path.relpath(target_abs_path, start=source_dir)

    return rel_path.replace(os.sep, '/')


def process_directories(args, input_root, output_root):
    """
    Recursively finds all .json files in input_root, converts them to Maude v2,
    and writes them to the same relative path in output_root.
    """
    if not os.path.exists(input_root):
        logger.error(f"Error: Input directory '{input_root}' does not exist.")
        return

    logger.debug(f"Starting v2 conversion from '{input_root}' to '{output_root}'...")

    count = 0
    for root, dirs, files in os.walk(input_root):
        for file in files:
            if file.endswith(".json"):
                full_input_path = os.path.join(root, file)
                rel_dir = os.path.relpath(root, input_root)
                stem = os.path.splitext(file)[0]
                stem_clean = args.protocol + "-" + stem.replace("_", "-")

                target_dir = os.path.join(output_root, rel_dir)
                os.makedirs(target_dir, exist_ok=True)

                output_filename = f"{stem}-v2.maude"
                full_output_path = os.path.join(target_dir, output_filename)

                rel_load_path = calculate_relative_load_path(full_output_path)

                try:
                    with open(full_input_path, 'r') as f:
                        json_content = f.read()

                    parser = JsonToMaudeV2Parser(
                        model_name=stem_clean,
                        stem=stem,
                        load_path=rel_load_path
                    )
                    maude_content = parser.generate(json_content)

                    with open(full_output_path, 'w') as f:
                        f.write(maude_content)

                    logger.debug(f"Generated: {full_output_path}")
                    count += 1

                except Exception as e:
                    logger.error(f"Error processing {full_input_path}: {e}")
                    import traceback
                    traceback.print_exc()

    logger.info(f"Done. Processed {count} files.")


def convert_single_file(args):
    """Convert a single JSON file to Maude v2 format."""
    input_path = args.input_file
    output_path = args.output_file

    if not os.path.exists(input_path):
        logger.error(f"Error: Input file '{input_path}' does not exist.")
        return

    stem = os.path.splitext(os.path.basename(input_path))[0]
    stem_clean = args.protocol + "-" + stem.replace("_", "-")

    if output_path is None:
        output_dir = os.path.dirname(input_path)
        output_path = os.path.join(output_dir, f"{stem}-v2.maude")

    rel_load_path = calculate_relative_load_path(output_path)

    with open(input_path, 'r') as f:
        json_content = f.read()

    parser = JsonToMaudeV2Parser(
        model_name=stem_clean,
        stem=stem,
        load_path=rel_load_path
    )
    maude_content = parser.generate(json_content)

    with open(output_path, 'w') as f:
        f.write(maude_content)

    print(f"Generated: {output_path}")


def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        description="Convert v2 Markov-action JSON configs to Maude MAModel-v2 format."
    )
    subparsers = parser.add_subparsers(dest="command", help="sub-command help")

    # Batch mode (directory)
    batch_parser = subparsers.add_parser("batch", help="Batch convert a directory of JSON files.")
    batch_parser.add_argument("protocol", help="The protocol name, for naming purposes.")
    batch_parser.add_argument("input_dir", help="The input directory containing JSON files.")
    batch_parser.add_argument("output_dir", help="The output directory for Maude files.")

    # Single file mode
    single_parser = subparsers.add_parser("single", help="Convert a single JSON file.")
    single_parser.add_argument("protocol", help="The protocol name, for naming purposes.")
    single_parser.add_argument("input_file", help="The input JSON file.")
    single_parser.add_argument("output_file", nargs="?", default=None,
                               help="The output Maude file (default: same dir as input, with -v2.maude extension).")

    return parser.parse_args(argv)


def main():
    logging.basicConfig(level=logging.DEBUG)
    args = parse_args()
    if args.command == "batch":
        process_directories(args, args.input_dir, args.output_dir)
    elif args.command == "single":
        convert_single_file(args)
    else:
        print("Usage: markovV2JsonToMaudeParser.py {batch,single} ...")
        sys.exit(1)


if __name__ == "__main__":
    main()
