--- MAUDE_HCS: maude_hcs
---
--- Software Markings (UNCLASS)
--- Maude-HCS Software
---
--- Copyright (C) 2025 RTX BBN Technologies Inc. All Rights Reserved
---
--- The computer software and computer software documentation are licensed
--- under the Apache License, Version 2.0 (the "License"); you may not use
--- this file except in compliance with the License. A copy of the License
--- is provided in the LICENSE file, but you may obtain a copy of the
--- License at:  https://www.apache.org/licenses/LICENSE-2.0
---
--- The computer software and computer software documentation are based
--- upon work supported by the Defense Advanced Research Projects Agency (DARPA)
--- under Agreement No. HR00l 12590083.
---
--- This document does not contain technology or technical data controlled under
--- either the U.S. International Traffic in Arms Regulations or the U.S. Export
--- Administration Regulations.
---
--- DISTRIBUTION STATEMENT A: Approved for public release; distribution is
--- unlimited.
---
--- Notice: Markings. Any reproduction of this computer software, computer
--- software documentation, or portions thereof must also reproduce the markings
--- contained herein. Refer to the provided NOTICE file.
---
--- MAUDE_HCS: end

sload ../../obfs4/_obfs4_aux
sload ../../obfs4/obfs4_prob
sload ../../irc/irc_prob-v2
sload ../../irc/ircMonitor
sload ../../irc/irc-byteseq-interface
sload ../../irc/irc-mamodel-v2
sload ../../common/maude/irc-action-actor-v2.maude
sload ../../network/tcp.maude
sload ../../network/net_prob-clt.maude
sload ../../../deps/dns_formalization/Maude/common/apmaude.maude
sload ../../common/maude/structured-addresses.maude

mod OBFS4_TESTS is
  pr IRC-V2 .
  pr IRC_MONITOR .
  pr IRC-MAMODEL-V2 .
  pr IRC-USER-ACTION-ACTOR-V2 .
  pr OBFS4 .
  pr SCHEDULER .
  pr IRC_NAMES .
  pr IRC-BYTESEQ-INTERFACE .
  pr TCP_SOCKET .
  pr NETWORK_CONNECTION .
  inc STRUCTURED-ADDRESSES .

  **** the user model database
  eq MAModelMap = ("irc-test" |-> irc-mamodel-v2 ) .

  ops aliceAddr bobAddr                                                   : -> Address .
  ops aliceIrcClientAddr bobIrcClientAddr                                 : -> Address .
  ops aliceIrcUserModelAddr bobIrcUserModelAddr                           : -> Address .
  ops aliceIfaceAddr bobIfaceAddr aliceServerIfaceAddr bobServerIfaceAddr : -> Address .
  ops aliceObfs4ClientAddr bobObfs4ClientAddr                             : -> Address .
  ops obfs4AliceServerAddr obfs4BobServerAddr ircServerAddr               : -> Address .
  ops aliceNetClientAddr bobNetClientAddr                                 : -> Address .
  ops serverAliceNetServerAddr serverBobNetServerAddr                     : -> Address .

  eq aliceIrcClientAddr = a(cl[1],hcs,irc,cl,1) .
  eq bobIrcClientAddr = a(cl[2],hcs,irc,cl,1) .
  eq aliceIrcUserModelAddr = a(cl[1],hcs,irc,um,1) .
  eq bobIrcUserModelAddr = a(cl[2],hcs,irc,um,1) .
  eq ircServerAddr = a(srvN,srv,irc,srv,0) .

  eq aliceIfaceAddr = a(cl[1],hcs,irc,if,1) .
  eq bobIfaceAddr = a(cl[2],hcs,irc,if,1) .
  eq aliceServerIfaceAddr = a(srvN[1],hcs,irc,if,1) .
  eq bobServerIfaceAddr = a(srvN[2],hcs,irc,if,1) .

  eq aliceObfs4ClientAddr = a(cl[1],hcs,obfs,cl,1) .
  eq bobObfs4ClientAddr = a(cl[2],hcs,obfs,cl,1) .
  eq obfs4AliceServerAddr = a(srvN[1],hcs,obfs,srv,1) .
  eq obfs4BobServerAddr = a(srvN[2],hcs,obfs,srv,1) .

  eq aliceNetClientAddr = a(cl[1],tcp,obfs,cl,1) .
  eq bobNetClientAddr = a(cl[2],tcp,obfs,cl,1) .
  eq serverAliceNetServerAddr = a(srvN[1],tcp,obfs,srv,1) .
  eq serverBobNetServerAddr = a(srvN[2],tcp,obfs,srv,1) .

  ops aliceIrcClient bobIrcClient                         : -> Actor .
  ops aliceIrcUserModel bobIrcUserModel                   : -> Actor .
  ops aliceObfs4Client bobObfs4Client                     : -> Actor .
  ops obfs4AliceServer obfs4BobServer ircServer           : -> Actor .
  ops aliceIface bobIface aliceServerIface bobServerIface : -> Actor .
  ops aliceNetClient bobNetClient                         : -> Actor .
  ops serverAliceNetServer serverBobNetServer             : -> Actor .

  op advAddr : -> Address .
  op advActor : -> Actor .
  eq advActor = mkAdversaryCp3(advAddr) .

  eq aliceIrcClient = mkIrcClient-v2(aliceIrcClientAddr,
                                  aliceIfaceAddr,
                                  "alice") .
  eq aliceIrcUserModel = mkIrcUMV2Actor(aliceIrcUserModelAddr,
                                        "irc-test",
                                        aliceIrcClientAddr) .
  eq aliceIface = mkIrcByteSeqIface(aliceIfaceAddr, aliceIrcClientAddr, aliceObfs4ClientAddr) .
  eq aliceObfs4Client = makeObfs4Node(aliceObfs4ClientAddr, aliceIfaceAddr, obfs4AliceServerAddr) .

  eq aliceNetClient = makeNetClient(aliceNetClientAddr,
                                    obfs4AliceServerAddr,
                                    aliceObfs4ClientAddr,
                                    true,
                                    nullAddr,
                                    nullName)
  .
  eq bobNetClient   = makeNetClient(bobNetClientAddr,
                                    obfs4BobServerAddr,
                                    bobObfs4ClientAddr,
                                    true,
                                    nullAddr,
                                    nullName)
  .

  eq bobIrcClient = mkIrcClient-v2(bobIrcClientAddr,
                                bobIfaceAddr,
                                "bob")
  .
  eq bobIrcUserModel = mkIrcUMV2Actor(bobIrcUserModelAddr,
                                      "irc-test",
                                      bobIrcClientAddr) .
  eq bobIface = mkIrcByteSeqIface(bobIfaceAddr,
                                  bobIrcClientAddr,
                                  bobObfs4ClientAddr)
  .
  eq bobObfs4Client = makeObfs4Node(bobObfs4ClientAddr, bobIfaceAddr, obfs4BobServerAddr) .

  eq ircServer = mkIrcServer(ircServerAddr) .
  --- Server Iface facing Alice.
  eq aliceServerIface = mkIrcByteSeqIface(aliceServerIfaceAddr, ircServerAddr, obfs4AliceServerAddr) .
  --- Obfs4 Server facing Alice.
  eq obfs4AliceServer = makeObfs4Node(obfs4AliceServerAddr, aliceServerIfaceAddr, aliceObfs4ClientAddr) .
  --- Server Iface facing Bob.
  eq bobServerIface = mkIrcByteSeqIface(bobServerIfaceAddr, ircServerAddr, obfs4BobServerAddr) .
  --- Obfs4 Server facing Bob.
  eq obfs4BobServer = makeObfs4Node(obfs4BobServerAddr, bobServerIfaceAddr, bobObfs4ClientAddr) .

  eq serverAliceNetServer = makeNetServer(serverAliceNetServerAddr,
                                          obfs4AliceServerAddr)
  .
  eq serverBobNetServer   = makeNetServer(serverBobNetServerAddr,
                                          obfs4BobServerAddr)
  .

  ops ircMonitorAddr : -> Address .

  eq transport(any:Address) = tcp(any:Address) .
  
  vars caddrs : AddrSet .
  vars rooms : StringAddrsSet .

  vars dt : Float .
  vars icAddr isAddr ifsAddr : Address .
  vars room : String .
  op mkJoin : Float String Address Address Address -> ScheduleMsg .
  eq mkJoin(dt,room,icAddr, isAddr, ifsAddr) =
       [dt,
       (to isAddr from ifsAddr :
        JoinChannel(makeIrcChannelName(room), icAddr )),
        0]
  .

  op LinkParams : -> AttributeSet .
  eq LinkParams =
    (4stateLoss: (p13: 0.0,
                  p31: 1.0,
                  p32: 0.0,
                  p23: 0.0,
                  p14: 0.0,
                  oneWayDelay: 0.01))
  .

  eq LinkData =
    aaa(aliceObfs4ClientAddr, obfs4AliceServerAddr, LinkParams)
    aaa(obfs4AliceServerAddr, aliceObfs4ClientAddr, LinkParams)
    aaa(bobObfs4ClientAddr, obfs4BobServerAddr, LinkParams)
    aaa(obfs4BobServerAddr, bobObfs4ClientAddr, LinkParams)

    aaa(obfs4AliceServerAddr, IXP-DEFAULT-ADDR, LinkParams)
    aaa(IXP-DEFAULT-ADDR, obfs4AliceServerAddr, LinkParams)
    aaa(aliceObfs4ClientAddr, IXP-DEFAULT-ADDR, LinkParams)
    aaa(IXP-DEFAULT-ADDR, aliceObfs4ClientAddr, LinkParams)

    aaa(obfs4BobServerAddr, IXP-DEFAULT-ADDR, LinkParams)
    aaa(IXP-DEFAULT-ADDR, obfs4BobServerAddr, LinkParams)
    aaa(bobObfs4ClientAddr, IXP-DEFAULT-ADDR, LinkParams)
    aaa(IXP-DEFAULT-ADDR, bobObfs4ClientAddr, LinkParams)
  .

  op initState : -> Config .
  eq initState = 
    rCtr(0)
    aliceIrcClient
    aliceIrcUserModel
    aliceIface
    aliceObfs4Client
    aliceNetClient
    bobIrcClient
    bobIrcUserModel
    bobIface
    bobObfs4Client
    bobNetClient
    ircServer
    aliceServerIface
    obfs4AliceServer
    serverAliceNetServer
    bobServerIface
    obfs4BobServer
    serverBobNetServer
    mkIrcMonitor(ircMonitorAddr)
    advActor
    mkJoin(1.0, "#chat", aliceIrcClientAddr, ircServerAddr, aliceServerIfaceAddr)
    mkJoin(1.1, "#general", aliceIrcClientAddr, ircServerAddr, aliceServerIfaceAddr)
    mkJoin(1.2, "#random", aliceIrcClientAddr, ircServerAddr, aliceServerIfaceAddr)
    mkJoin(1.3, "#chat", bobIrcClientAddr, ircServerAddr, bobServerIfaceAddr)
    mkJoin(1.4, "#general", bobIrcClientAddr, ircServerAddr, bobServerIfaceAddr)
    mkJoin(1.5, "#random", bobIrcClientAddr, ircServerAddr, bobServerIfaceAddr)
    [2.0, to aliceIrcUserModelAddr from aliceIrcUserModelAddr : burstDelayTO, 0]
    [2.1, to bobIrcUserModelAddr from bobIrcUserModelAddr : burstDelayTO, 0]
  .

  op initConfig : -> Config .
  eq initConfig = run({0.0 | nil} initState, 300.) .
endm

set print attribute on .
---set trace on .

--- Experiment with 2 IRC clients and 1 IRC server, traffic encapsulated with obfs4
rew initConfig .
q