--- MAUDE_HCS: maude_hcs
---
--- Software Markings (UNCLASS)
--- Maude-HCS Software
---
--- Copyright (C) 2025 RTX BBN Technologies Inc. All Rights Reserved
---
--- The computer software and computer software documentation are licensed
--- under the Apache License, Version 2.0 (the "License"); you may not use
--- this file except in compliance with the License. A copy of the License
--- is provided in the LICENSE file, but you may obtain a copy of the
--- License at:  https://www.apache.org/licenses/LICENSE-2.0
---
--- The computer software and computer software documentation are based
--- upon work supported by the Defense Advanced Research Projects Agency (DARPA)
--- under Agreement No. HR00l 12590083.
---
--- This document does not contain technology or technical data controlled under
--- either the U.S. International Traffic in Arms Regulations or the U.S. Export
--- Administration Regulations.
---
--- DISTRIBUTION STATEMENT A: Approved for public release; distribution is
--- unlimited.
---
--- Notice: Markings. Any reproduction of this computer software, computer
--- software documentation, or portions thereof must also reproduce the markings
--- contained herein. Refer to the provided NOTICE file.
---
--- MAUDE_HCS: end

sload ../../irc/common/irc_name
sload ../../irc/common/_aux
sload ../../irc/common/app_chat
sload ../../irc/irc_monitor
sload ../../irc/_irc_aux
sload ../../irc/irc_prob
sload ../../cp3-tests/skyhook/irc-mamodel-v2.maude
sload ../../common/maude/irc-action-actor-v2.maude
sload ../../common/maude/cp2-interfaces
sload ../../../deps/dns_formalization/Maude/common/apmaude.maude
sload ../../obfs4/_obfs4_aux.maude
sload ../../obfs4/obfs4_prob.maude

mod OBFS4_TESTS is
  pr IRC_NAMES .
  pr APP_CHATS .
  pr IRC_NODE .
  pr IRC_MONITOR .
  pr IRC .
  pr IRC-MAMODEL-V2 .
  pr IRC-USER-ACTION-ACTOR-V2 .
  pr OBFS4 .
  pr SCHEDULER .
  pr IRC-DISPATCHER-INTERFACE .

  ***** Global constants  
  **** the user model database
  eq MAModelMap = ("irc-test" |-> irc-ma-v2 ) .

  *** for the default case
  eq noiseMax(msg:Msg) = 0.00001 .
     
  ops aliceIrcClientAddr bobIrcClientAddr : -> Address .
  ops aliceIrcUserModelAddr bobIrcUserModelAddr : -> Address .
  ops aliceIfaceAddr bobIfaceAddr aliceServerIfaceAddr bobServerIfaceAddr : -> Address .
  ops aliceObfs4ClientAddr bobObfs4ClientAddr : -> Address .
  ops obfs4AliceServerAddr obfs4BobServerAddr ircServerAddr : -> Address .

  ops aliceIrcClient bobIrcClient : -> Actor .
  ops aliceIrcUserModel bobIrcUserModel : -> Actor .
  ops aliceObfs4Client bobObfs4Client : -> Actor .
  ops obfs4AliceServer obfs4BobServer ircServer : -> Actor .
  ops aliceIface bobIface aliceServerIface bobServerIface : -> Actor .

  eq aliceIrcClient = mkIrcClient(aliceIrcClientAddr,
                                  aliceIfaceAddr,
                                  "Alice")
  .
  eq aliceIrcUserModel = mkIrcUMV2Actor(aliceIrcUserModelAddr,
                                        "irc-test",
                                        aliceIrcClientAddr)
  .
  eq aliceIface = mkIrcByteSeqIface(aliceIfaceAddr, aliceIrcClientAddr, aliceObfs4ClientAddr, aliceObfs4ClientAddr) .
  eq aliceObfs4Client = makeObfs4Node(aliceObfs4ClientAddr, aliceIfaceAddr, obfs4AliceServerAddr) .



  eq bobIrcClient = mkIrcClient(bobIrcClientAddr,
                                bobIfaceAddr,
                                "Bob")
  .
  eq bobIrcUserModel  = mkIrcUMV2Actor(bobIrcUserModelAddr,
                                       "irc-test",
                                       bobIrcClientAddr)
  .
  eq bobIface = mkIrcByteSeqIface(bobIfaceAddr,
                                  bobIrcClientAddr,
                                  bobObfs4ClientAddr,
                                  bobObfs4ClientAddr)
  .
  eq bobObfs4Client = makeObfs4Node(bobObfs4ClientAddr, bobIfaceAddr, obfs4BobServerAddr) .

  eq ircServer = mkIrcServer(ircServerAddr) .
  --- Server Iface facing Alice.
  eq aliceServerIface = mkIrcByteSeqIface(aliceServerIfaceAddr, ircServerAddr, obfs4AliceServerAddr, obfs4AliceServerAddr) .
  --- Obfs4 Server facing Alice.
  eq obfs4AliceServer = makeObfs4Node(obfs4AliceServerAddr, aliceServerIfaceAddr, aliceObfs4ClientAddr) .
  --- Server Iface facing Bob.
  eq bobServerIface = mkIrcByteSeqIface(bobServerIfaceAddr, ircServerAddr, obfs4BobServerAddr, obfs4BobServerAddr) .
  --- Obfs4 Server facing Bob.
  eq obfs4BobServer = makeObfs4Node(obfs4BobServerAddr, bobServerIfaceAddr, bobObfs4ClientAddr) .

  ops ircMonitorAddr : -> Address .

  vars caddrs : AddrSet .
  vars rooms : StringAddrsSet .

  op initState : -> Config .
  eq initState = 
    rCtr(0)
    aliceIrcClient
    aliceIrcUserModel
    aliceIface
    aliceObfs4Client
    bobIrcClient
    bobIrcUserModel
    bobIface
    bobObfs4Client
    ircServer
    aliceServerIface
    obfs4AliceServer
    bobServerIface
    obfs4BobServer
    mkIrcMonitor(ircMonitorAddr,
                 (aliceIrcClientAddr ;; bobIrcClientAddr ;; ircServerAddr),
                 (aliceIrcClientAddr ;; bobIrcClientAddr),
                 **** TODO: The following room mapping needs to be fixed.
                 (rm("#room1", aliceIrcClientAddr ;; bobIrcClientAddr)))
    **** start alice
    [0.1, (to aliceIrcUserModelAddr from aliceIrcUserModelAddr : burstDelayTO), 0]
    **** start bob
    [0.2, (to bobIrcUserModelAddr from bobIrcUserModelAddr : burstDelayTO), 0]
  .

  op initConfig : -> Config .
  eq initConfig = run({0.0 | nil} initState, 1300.) .
endm

set print attribute on .
---set trace on .

--- Experiment with 2 IRC clients and 1 IRC server, traffic encapsulated with obfs4
rew initConfig .
q

