--- This maude file has been created automatically from the Python representation ---

set clear rules off .
set print attribute off .
set show advisories off .

load ../../../dns/maude/probabilistic/iodine_dns
load ../../../common/maude/user-action-actor.maude
load ../../../dns/maude/probabilistic/dnsTgen-actor.maude
load ../../../common/maude/router
load ../../../common/maude/adversary-observer
load ../../../app/maude/probabilistic

mod HCS_TEST is
  inc DNS .
  inc USER-ACTION-ACTOR .
  inc DNS-TGEN .
  inc DNS-MAMODEL .
  inc IODINE_DNS . --- + TEST-HELPERS .
  inc CP2_APP .
  inc ADVERSARY-OBSERVER .


****** DNSTask / UserModel params

  op dnameDb : -> NameList .
  eq dnameDb =
      (('www . 'internet. 'com . root)
       ('www0 . 'internet . 'com . root)
       ('www1 . 'internet . 'com . root)
       ('www2 . 'internet . 'com . root) )
 .

inc ROUTER .

eq monitorQueryLog? = true .

eq fileSize = 10000 .
eq packetSize = 871 .
eq packetOverhead = 33 .
eq maxMinimiseCount = 0 .
eq maxFragmentLen = 200 .
eq maxFragmentTx = 20 .
eq maxPacketSize = 1097 .
eq pacingTimeoutDelay = 0.01 .
eq pacingTimeoutDelayMax = 0.05 .
eq ackTimeoutDelay = 1.0 .

op initT : -> Float .
eq initT = 2.222 .

--- Actor addresses
ops Alice Bob bobapp application-client application-server dnsperf internet-dns local-dns mAddr monAddr public-dns root-dns tld-dns : -> Address .
ops clientContentMgr serverContentMgr clientDestini serverDestini clientUserModel serverUserModel : -> Address .

***!!!
op router : -> Address .
op adversary : -> Address .

---- the sendtime / receive time collection patterns
ops ObsS ObsR : -> Observable .
eq ObsS = mtObs [owise] .
eq ObsR = mtObs [owise] .

--- uncomment to model aversary at router inside corporate
--- collects msgs received by router from interal actors
--- (stored as sent by local-dns)
eq ObsR = obsC .  

--- uncomment to model adversary at the router external interface
--- collects messages sent by router after NAT
--- the sending time is essentially the time the internal
--- source sent the message
**** eq ObsS = obsX .


---- uncomment this to model an aversay that sees both side
---- of the router
**** eq ObsS = obsX . eq ObsR =  obsC .

--- uncomment to model adversary observing receives by the 
--- actor with address serverAddr (such as mastodon server)
---  collects msgs received by this server at receive time
**** eq ObsR = obsM(serverAddr) .


--- "SBELT": fallback if there are no known name servers
op sb : -> ZoneState .
eq sb = < root ('a . 'root-servers . 'net . root |-> root-dns) > .

--- Zone files
op zone : -> List{Record} .
eq zone =
  < root, soa, 3600.0, soaData(3600.0) >
  < root, ns, 3600.0, 'a . 'root-servers . 'net . root >
  < 'a . 'root-servers . 'net . root, a, 3600.0, root-dns >
  < 'com . root, ns, 3600.0, 'ns . 'com . root >
  < 'ns . 'com . root, a, 3600.0, tld-dns > .

op zoneCorporateCom : -> List{Record} .
eq zoneCorporateCom =
  < 'corporate . 'com . root, soa, 3600.0, soaData(3600.0) >
  < 'corporate . 'com . root, ns, 3600.0, 'ns . 'corporate . 'com . root >
  < 'ns . 'corporate . 'com . root, a, 3600.0, local-dns >
  < 'tmp0 . 'corporate . 'com . root, a, 0.0, 3 . 0 . 1 . 2 >
  < wildcard . 'corporate . 'com . root, a, 0.0, 3 . 1 . 1 . 2 > .

op zoneInternetCom : -> List{Record} .
eq zoneInternetCom =
  < 'internet . 'com . root, soa, 3600.0, soaData(3600.0) >
  < 'internet . 'com . root, ns, 3600.0, 'ns . 'internet . 'com . root >
  < 'ns . 'internet . 'com . root, a, 3600.0, internet-dns >
  < 'tmp0 . 'internet . 'com . root, a, 0.0, 1 . 0 . 1 . 2 >
  < wildcard . 'internet . 'com . root, a, 0.0, 1 . 1 . 1 . 2 > .

op zoneCom : -> List{Record} .
eq zoneCom =
  < 'com . root, soa, 3600.0, soaData(3600.0) >
  < 'com . root, ns, 3600.0, 'ns . 'com . root >
  < 'ns . 'com . root, a, 3600.0, tld-dns >
  < 'internet . 'com . root, ns, 3600.0, 'ns . 'internet . 'com . root >
  < 'ns . 'internet . 'com . root, a, 3600.0, internet-dns >
  < 'pwnd . 'com . root, ns, 3600.0, 'ns . 'pwnd . 'com . root >
  < 'ns . 'pwnd . 'com . root, a, 3600.0, application-server >
  < 'corporate . 'com . root, ns, 3600.0, 'ns . 'corporate . 'com . root >
  < 'ns . 'corporate . 'com . root, a, 3600.0, local-dns > .

op zonePwndCom : -> List{Record} .
eq zonePwndCom =
  < 'pwnd . 'com . root, soa, 3600.0, soaData(3600.0) >
  < 'pwnd . 'com . root, ns, 3600.0, 'ns . 'pwnd . 'com . root >
  < 'ns . 'pwnd . 'com . root, a, 3600.0, application-server >
  < 'tmp0 . 'pwnd . 'com . root, a, 0.0, 2 . 0 . 1 . 2 >
  < wildcard . 'pwnd . 'com . root, a, 0.0, 2 . 1 . 1 . 2 > .

--- Caches
op resolverCache : -> Cache .
eq resolverCache =
  cacheEntry(< root, ns, 3600.0, 'a . 'root-servers . 'net . root >, 1)
  cacheEntry(< 'a . 'root-servers . 'net . root, a, 3600.0, root-dns >, 1)
  cacheEntry(< 'com . root, ns, 3600.0, 'ns . 'com . root >, 1)
  cacheEntry(< 'ns . 'com . root, a, 3600.0, tld-dns >, 1)
  cacheEntry(< 'internet . 'com . root, ns, 3600.0, 'ns . 'internet . 'com . root >, 1)
  cacheEntry(< 'ns . 'internet . 'com . root, a, 3600.0, internet-dns >, 1)
  cacheEntry(< 'pwnd . 'com . root, ns, 3600.0, 'ns . 'pwnd . 'com . root >, 1)
  cacheEntry(< 'ns . 'pwnd . 'com . root, a, 3600.0, application-server >, 1)
  cacheEntry(< 'corporate . 'com . root, ns, 3600.0, 'ns . 'corporate . 'com . root >, 1)
  cacheEntry(< 'ns . 'corporate . 'com . root, a, 3600.0, local-dns >, 1) .

var freq : Nat .
var dur : Float .
vars dnsMA : MAModel .
vars umADDR dnsTADDR : Address .


**** DNSTgen addresses
  ops umDAddr dnsTAddr  : -> Address .


--- Initial configuration
*****
op initState : 
****            umAd   dnsTAdd  rsvAddr  dns-ma
               Address Address  MAModel
                -> Config .

eq initState (umADDR,dnsTADDR,dnsMA) =
--- Initial configuration
  --- Client start messages
  --- Clients
  --- Resolvers
  rCtr(1)
  < public-dns : Resolver |
    cache: resolverCache,
    nxdomainCache: nilNxdomainCache,
    nodataCache: nilNodataCache,
    sbelt: sb,
    workBudget: emptyIN,
    blockedQueries: eptQSS,
    sentQueries: eptQSS >
  --- Nameservers
  < root-dns : Nameserver |
    db: (zone),
    queue: nilQueue,
    forwardonly: nullAddr,
    queriesFwd: nilTAQL >
  < tld-dns : Nameserver |
    db: (zoneCom),
    queue: nilQueue,
    forwardonly: nullAddr,
    queriesFwd: nilTAQL >
  < internet-dns : Nameserver |
    db: (zoneInternetCom),
    queue: nilQueue,
    forwardonly: nullAddr,
    queriesFwd: nilTAQL >
  < local-dns : Nameserver |
    db: (zoneCorporateCom),
    queue: nilQueue,
***!!!    forwardonly: public-dns,
    forwardonly: X(public-dns),
    queriesFwd: nilTAQL >
  --- tunnels
  < application-client : WClient |
    resv: local-dns,
    wDom: 'pwnd . 'com . root,
    weirdQType: a,
    queryCtr: 0,
        outSeqNo: 0,
    fragmentsToSend: mtfl,
    fragmentsSize: 0,
    outFragNo: 0,
    appAddrMap: mtIdAddr,
    numAttempts: 0,
    fragmentsReceived: mtfl,
    inSeqNo: 0,
    inFragNo: 0,
    lastFragment: false,
    severWResponseTTL: 0.0 >
  < application-server : WNameserver |
    fragmentsReceived: mtfl,
    inSeqNo: 0,
    inFragNo: 0,
    lastFragment: false,
    severWResponseTTL: 0.0,
    conf: (< application-server : Nameserver |
    db: (zonePwndCom),
    queue: nilQueue,
    forwardonly: nullAddr,
    queriesFwd: nilTAQL >),
    outSeqNo: 0,
    fragmentsToSend: mtfl,
    fragmentsSize: 0,
    outFragNo: 0,
    numAttempts: 0 >
  --- applications
  < Alice : SendApp |
    fileDestAddr: Bob,
    toAddr: (application-client),
    queuePopulated: false,
    queue: (mtpl),
    numAdmittedPkts: 1,
    iodineReady: true,
    sent: mtpl,
    rcvd: mtpl > 
  < Bob : RcvApp |
    rcvd: mtpl,
    fileDestAddr: bobapp,
    toAddr: (application-server),
    queuePopulated: false,
    queue: (mtpl),
    numAdmittedPkts: 1,
    iodineReady: true,
    sent: mtpl >
  < bobapp : RxApp |
      rcvd: emptyFileList,
      rbUserModelAddr: serverUserModel,
      rbContentMgrAddr: serverContentMgr >
  --- WMonitor
  < monAddr : WMonitor |
    querySent: nilQueryTimestamp,
    queryRcvd: nilQueryTimestamp,
    pktSent: nilPacketTimestamp,
    pktRcvd: nilPacketTimestamp >
***!!!
  mkRouter(router)    
  mkAdversary(adversary,ObsS,ObsR)
**** umActor
  mkUMactor(umADDR,dnsMA,dnsTADDR)
**** dnsTActor
  mkDnsTgenA(dnsTADDR,local-dns,dnameDb, 5.0, 2)
  [0.0, (to umADDR from umADDR : actionR("")), 0]
  --- App start messages
  [1.0, (to Alice : start), 0] 
  .

 --- Link Characteristic definitions
op LinkType-0 : -> AttributeSet .
eq LinkType-0 = 
  (delayStd: 0.),
  (delayType: "Constant"),
  (delayMean: 0.),
  (delayConst: 0.),
  (noiseMin: 0.),
  (noiseMax: 0.00001),
  (dropP: 0.),
  (canDrop: false)
  .

op LinkType-1 : -> AttributeSet .
eq LinkType-1 = 
  (delayStd: 0.),
  (delayType: "Constant"),
  (delayMean: 0.),
  (delayConst: 0.005),
  (noiseMin: 0.),
  (noiseMax: 0.00001),
  (dropP: 0.),
  (canDrop: false)
  .

op LinkType-2 : -> AttributeSet .
eq LinkType-2 = 
  (delayStd: 0.),
  (delayType: "Constant"),
  (delayMean: 0.),
  (delayConst: 0.01),
  (noiseMin: 0.),
  (noiseMax: 0.00001),
  (dropP: 0.),
  (canDrop: false)
  .

op LinkType-3 : -> AttributeSet .
eq LinkType-3 = 
  (delayStd: 0.01334),
  (delayType: "Normal"),
  (delayMean: 0.025),
  (delayConst: 0.),
  (noiseMin: 0.),
  (noiseMax: 0.),
  (dropP: 0.),
  (canDrop: false)
  .

eq LinkData =
  aaa(local-dns,application-client,LinkType-0)
	aaa(local-dns,dnsTAddr,LinkType-0)
  ****!!!  
  aaa(public-dns,local-dns,LinkType-1)
  aaa(X(public-dns),local-dns,LinkType-0) --- to router
  aaa(local-dns,X(public-dns),LinkType-0) --- from router
  aaa(public-dns,application-server,LinkType-1)
  aaa(public-dns,root-dns,LinkType-2)
  aaa(public-dns,tld-dns,LinkType-2)
  aaa(public-dns,internet-dns,LinkType-3)
  aaa(dnsTAddr,umDAddr,LinkType-1)
.
**** adversary does not send or receive


eq defaultDelay = 0.0015 .

op initConfig : -> Config .
eq initConfig = run({0.0 | nil} initState (umDAddr,dnsTAddr, dns-ma),limit) .

endm
eof


red initConfig .

rew initConfig .


