--- MAUDE_HCS: maude_hcs
---
--- Software Markings (UNCLASS)
--- Maude-HCS Software
---
--- Copyright (C) 2025 RTX BBN Technologies Inc. All Rights Reserved
---
--- The computer software and computer software documentation are licensed
--- under the Apache License, Version 2.0 (the "License"); you may not use
--- this file except in compliance with the License. A copy of the License
--- is provided in the LICENSE file, but you may obtain a copy of the
--- License at:  https://www.apache.org/licenses/LICENSE-2.0
---
--- The computer software and computer software documentation are based
--- upon work supported by the Defense Advanced Research Projects Agency (DARPA)
--- under Agreement No. HR00l 12590083.
---
--- This document does not contain technology or technical data controlled under
--- either the U.S. International Traffic in Arms Regulations or the U.S. Export
--- Administration Regulations.
---
--- DISTRIBUTION STATEMENT A: Approved for public release; distribution is
--- unlimited.
---
--- Notice: Markings. Any reproduction of this computer software, computer
--- software documentation, or portions thereof must also reproduce the markings
--- contained herein. Refer to the provided NOTICE file.
---
--- MAUDE_HCS: end

set clear rules off .
set print attribute off .
set show advisories off .

sload ../../../mastodon/maude/probabilistic/mastodon
sload ../../../dns/maude/probabilistic/iodine_dns
sload ../../../common/maude/user-action-actor.maude
sload ../../../dns/maude/probabilistic/dnsTgen-actor.maude
sload ../../../common/maude/masTGen.maude
sload ../../../common/maude/router
sload ../../../common/maude/adversary-observer
sload ../../../app/maude/probabilistic

mod HCS_TEST is
  inc DNS .
  inc USER-ACTION-ACTOR .
  inc DNS-TGEN .
  inc DNS-MAMODEL .
  inc MASTODON .
  inc MAS-TGEN .
  inc IODINE_DNS . --- + TEST-HELPERS .
  inc CP2_APP .
  inc ROUTER .
  inc ADVERSARY-OBSERVER .


****** DNSTask / UserModel params

  op dnameDb : -> NameList .
  eq dnameDb =
      (('www . 'internet. 'com . root)
       ('www0 . 'internet . 'com . root)
       ('www1 . 'internet . 'com . root)
       ('www2 . 'internet . 'com . root) )
 .

eq monitorQueryLog? = true .

eq fileSize = 10000 .
eq packetSize = 80 .
eq packetOverhead = 33 .
eq maxMinimiseCount = 0 .
eq maxFragmentLen = 136 .
eq maxFragmentTx = 20 .
eq maxPacketSize = 1097 .
eq pacingTimeoutDelay = 0.01 .
eq pacingTimeoutDelayMax = 1.0 .
eq ackTimeoutDelay = 1.0 .
eq maxMinimiseCount = 0 .
eq pingInterval = 1.0 .
eq initialPingDelay = 0.001 .
eq receiveToPingDelay = 0.001 .

--- Actor addresses
--- Top-level apps aliceapp and bobapp talk to each other and are connected to Iodine Alice and Bob, and alice/bobMasClient.
--- Iodine Tx and Rx apps iodineAlice and iodineBob are connected to iodine-client and iodine-server.
ops aliceapp bobapp iodineAlice iodineBob iodine-client iodine-server dnsperf internet-dns local-dns mAddr monAddr public-dns root-dns tld-dns : -> Address .
ops clientContentMgr serverContentMgr clientDestini serverDestini clientUserModel serverUserModel : -> Address .
ops aliceMasClient bobMasClient mastodonServer : -> Address .

***!!!
op router : -> Address .
op adversary : -> Address .

---- the sendtime / receive time collection patterns
ops ObsS ObsR : -> Observable .
eq ObsS = mtObs [owise] .
eq ObsR = mtObs [owise] .

--- uncomment to model aversary at router inside corporate
--- collects msgs received by router from interal actors
--- (stored as sent by local-dns)
--- eq ObsR = obsC .  

--- uncomment to model adversary at the router external interface
--- collects messages sent by router after NAT
--- the sending time is essentially the time the internal
--- source sent the message
---eq ObsS = obsC .


---- uncomment this to model an aversay that sees both side
---- of the router
--- eq ObsS = obsX . eq ObsR =  obsC .

--- uncomment to model adversary observing receives by the 
--- actor with address serverAddr (such as mastodon server)
---  collects msgs received by this server at receive time
eq ObsR = obsM(mastodonServer) .


--- "SBELT": fallback if there are no known name servers
op sb : -> ZoneState .
eq sb = < root ('a . 'root-servers . 'net . root |-> root-dns) > .

--- Zone files
op zone : -> List{Record} .
eq zone =
  < root, soa, 3600.0, soaData(3600.0) >
  < root, ns, 3600.0, 'a . 'root-servers . 'net . root >
  < 'a . 'root-servers . 'net . root, a, 3600.0, root-dns >
  < 'com . root, ns, 3600.0, 'ns . 'com . root >
  < 'ns . 'com . root, a, 3600.0, tld-dns > .

op zoneCorporateCom : -> List{Record} .
eq zoneCorporateCom =
  < 'corporate . 'com . root, soa, 3600.0, soaData(3600.0) >
  < 'corporate . 'com . root, ns, 3600.0, 'ns . 'corporate . 'com . root >
  < 'ns . 'corporate . 'com . root, a, 3600.0, local-dns >
  < 'tmp0 . 'corporate . 'com . root, a, 0.0, 3 . 0 . 1 . 2 >
  < wildcard . 'corporate . 'com . root, a, 0.0, 3 . 1 . 1 . 2 > .

op zoneInternetCom : -> List{Record} .
eq zoneInternetCom =
  < 'internet . 'com . root, soa, 3600.0, soaData(3600.0) >
  < 'internet . 'com . root, ns, 3600.0, 'ns . 'internet . 'com . root >
  < 'ns . 'internet . 'com . root, a, 3600.0, internet-dns >
  < 'tmp0 . 'internet . 'com . root, a, 0.0, 1 . 0 . 1 . 2 >
  < wildcard . 'internet . 'com . root, a, 0.0, 1 . 1 . 1 . 2 > .

op zoneCom : -> List{Record} .
eq zoneCom =
  < 'com . root, soa, 3600.0, soaData(3600.0) >
  < 'com . root, ns, 3600.0, 'ns . 'com . root >
  < 'ns . 'com . root, a, 3600.0, tld-dns >
  < 'internet . 'com . root, ns, 3600.0, 'ns . 'internet . 'com . root >
  < 'ns . 'internet . 'com . root, a, 3600.0, internet-dns >
  < 'pwnd . 'com . root, ns, 3600.0, 'ns . 'pwnd . 'com . root >
  < 'ns . 'pwnd . 'com . root, a, 3600.0, iodine-server >
  < 'corporate . 'com . root, ns, 3600.0, 'ns . 'corporate . 'com . root >
  < 'ns . 'corporate . 'com . root, a, 3600.0, local-dns > .

op zonePwndCom : -> List{Record} .
eq zonePwndCom =
  < 'pwnd . 'com . root, soa, 3600.0, soaData(3600.0) >
  < 'pwnd . 'com . root, ns, 3600.0, 'ns . 'pwnd . 'com . root >
  < 'ns . 'pwnd . 'com . root, a, 3600.0, iodine-server >
  < 'tmp0 . 'pwnd . 'com . root, a, 0.0, 2 . 0 . 1 . 2 >
  < wildcard . 'pwnd . 'com . root, a, 0.0, 2 . 1 . 1 . 2 > .

--- Caches
op resolverCache : -> Cache .
eq resolverCache =
  cacheEntry(< root, ns, 3600.0, 'a . 'root-servers . 'net . root >, 1)
  cacheEntry(< 'a . 'root-servers . 'net . root, a, 3600.0, root-dns >, 1)
  cacheEntry(< 'com . root, ns, 3600.0, 'ns . 'com . root >, 1)
  cacheEntry(< 'ns . 'com . root, a, 3600.0, tld-dns >, 1)
  cacheEntry(< 'internet . 'com . root, ns, 3600.0, 'ns . 'internet . 'com . root >, 1)
  cacheEntry(< 'ns . 'internet . 'com . root, a, 3600.0, internet-dns >, 1)
  cacheEntry(< 'pwnd . 'com . root, ns, 3600.0, 'ns . 'pwnd . 'com . root >, 1)
  cacheEntry(< 'ns . 'pwnd . 'com . root, a, 3600.0, iodine-server >, 1)
  cacheEntry(< 'corporate . 'com . root, ns, 3600.0, 'ns . 'corporate . 'com . root >, 1)
  cacheEntry(< 'ns . 'corporate . 'com . root, a, 3600.0, local-dns >, 1) .

var freq : Nat .
var dur : Float .
vars dnsMA : MAModel .
vars umADDR dnsTADDR : Address .


**** DNSTgen addresses
  ops umDAddr dnsTAddr  : -> Address .
**** MasTgen addresses
  ops mtgA mcA  umA : -> Address .

--- Initial configuration
*****
op initState : 
****            umAd   dnsTAdd  rsvAddr  dns-ma
               Address Address  MAModel
                -> Config .

eq initState (umADDR,dnsTADDR,dnsMA) =
--- Initial configuration
  --- Client start messages
  --- Clients
  --- Resolvers
  rCtr(1) 
  < public-dns : Resolver |
    cache: resolverCache,
    nxdomainCache: nilNxdomainCache,
    nodataCache: nilNodataCache,
    sbelt: sb,
    workBudget: emptyIN,
    blockedQueries: eptQSS,
    sentQueries: eptQSS >
  --- Nameservers
  < root-dns : Nameserver |
    db: (zone),
    queue: nilQueue,
    forwardonly: nullAddr,
    queriesFwd: nilTAQL >
  < tld-dns : Nameserver |
    db: (zoneCom),
    queue: nilQueue,
    forwardonly: nullAddr,
    queriesFwd: nilTAQL >
  < internet-dns : Nameserver |
    db: (zoneInternetCom),
    queue: nilQueue,
    forwardonly: nullAddr,
    queriesFwd: nilTAQL >
  < local-dns : Nameserver |
    db: (zoneCorporateCom),
    queue: nilQueue,
***!!!    forwardonly: public-dns,
    forwardonly: X(public-dns),
    queriesFwd: nilTAQL >
  --- tunnels
  ----- Iodine
  makeWClient(iodine-client, local-dns, 'pwnd . 'com . root, a, 0.0)
  makeWNameServer(iodine-server, 0.0, (zonePwndCom))
  ----- Mastodon
  makeMastodonClient(aliceMasClient,
                     mastodonServer,
                     clientContentMgr)
  makeMastodonClient(bobMasClient,
                     mastodonServer,
                     serverContentMgr)
  makeMastodonServer(mastodonServer)
  makeRbClient(clientUserModel, clientContentMgr, clientDestini, aliceMasClient)
  makeRbServer(serverUserModel, serverContentMgr, serverDestini, bobMasClient, bobapp)
  --- applications
  ----- Top level apps
  makeTxApp(aliceapp, bobapp, iodineAlice, clientUserModel, clientContentMgr, file(0, 400))
  makeRxApp(bobapp, iodineBob, serverUserModel, serverContentMgr)
  ----- Iodine apps
  < iodineAlice : SendApp |
      fileDestAddr: iodineBob,
      toAddr: (iodine-client),
      queuePopulated: false,
      queue: (mtpl),
      numAdmittedPkts: 1,
      iodineReady: true,
      sent: mtpl,
      rcvd: mtpl > 
  < iodineBob : RcvApp |
      rcvd: mtpl,
      fileDestAddr: bobapp,
      fileSrcAddr: iodineAlice,
      toAddr: iodine-server,
      queuePopulated: true,
      queue: (mtpl),
      numAdmittedPkts: 1,
      iodineReady: true,
      sent: mtpl >
  --- WMonitor
  < monAddr : WMonitor |
    querySent: nilQueryTimestamp,
    queryRcvd: nilQueryTimestamp,
    pktSent: nilPacketTimestamp,
    pktRcvd: nilPacketTimestamp >
***!!!
  mkRouter(router)    
  mkAdversary(adversary,ObsS,ObsR)
**** umActor
  mkUMactor(umADDR,dnsMA,dnsTADDR)
**** dnsTActor
  mkDnsTgenA(dnsTADDR,local-dns,dnameDb, 5.0, 2)
  [0.0, (to umADDR from umADDR : actionR("")), 0]
**** masTActor
  mkMasTGenActor(mtgA, mcA, IM0 :: IM1, mas-ma) 
  --- App start messages
---  [1.0, (to iodineAlice : start), 0] 
  [1.5, (to aliceapp : start), 0]
  [10., (to bobapp : start), 0]
  .

 --- Link Characteristic definitions
op LinkType-0 : -> AttributeSet .
eq LinkType-0 = 
  (delayStd: 0.),
  (delayType: "Constant"),
  (delayMean: 0.),
  (delayConst: 0.),
  (noiseMin: 0.),
  (noiseMax: 0.00001),
  (dropP: 0.),
  (canDrop: false)
  .

op LinkType-1 : -> AttributeSet .
eq LinkType-1 = 
  (delayStd: 0.),
  (delayType: "Constant"),
  (delayMean: 0.),
  (delayConst: 0.027),
  (noiseMin: 0.),
  (noiseMax: 0.00001),
  (dropP: 0.05),
  (canDrop: true)
  .

op LinkType-2 : -> AttributeSet .
eq LinkType-2 = 
  (delayStd: 0.),
  (delayType: "Constant"),
  (delayMean: 0.),
  (delayConst: 0.01),
  (noiseMin: 0.),
  (noiseMax: 0.00001),
  (dropP: 0.),
  (canDrop: false)
  .

op LinkType-3 : -> AttributeSet .
eq LinkType-3 = 
  (delayStd: 0.01334),
  (delayType: "Normal"),
  (delayMean: 0.025),
  (delayConst: 0.),
  (noiseMin: 0.),
  (noiseMax: 0.),
  (dropP: 0.),
  (canDrop: false)
  .

eq LinkData =
  aaa(local-dns,iodine-client,LinkType-0)
	aaa(local-dns,dnsTAddr,LinkType-0)
  ****!!!  
  aaa(public-dns,local-dns,LinkType-1)
  aaa(X(public-dns),local-dns,LinkType-0) --- to router
  aaa(local-dns,X(public-dns),LinkType-0) --- from router
  aaa(public-dns,iodine-server,LinkType-1)
  aaa(public-dns,root-dns,LinkType-2)
  aaa(public-dns,tld-dns,LinkType-2)
  aaa(public-dns,internet-dns,LinkType-3)
  aaa(dnsTAddr,umDAddr,LinkType-1)
.
**** adversary does not send or receive


eq defaultDelay = 0.0015 .

op initConfig : -> Config .
eq limit = 300.0 .
eq initConfig = run({0.0 | nil} initState (umDAddr,dnsTAddr, dns-ma),limit) .

endm
rew initConfig .
eof


red initConfig .



