--- MAUDE_HCS: maude_hcs
---
--- Software Markings (UNCLASS)
--- Maude-HCS Software
---
--- Copyright (C) 2025 RTX BBN Technologies Inc. All Rights Reserved
---
--- The computer software and computer software documentation are licensed
--- under the Apache License, Version 2.0 (the "License"); you may not use
--- this file except in compliance with the License. A copy of the License
--- is provided in the LICENSE file, but you may obtain a copy of the
--- License at:  https://www.apache.org/licenses/LICENSE-2.0
---
--- The computer software and computer software documentation are based
--- upon work supported by the Defense Advanced Research Projects Agency (DARPA)
--- under Agreement No. HR00l 12590083.
---
--- This document does not contain technology or technical data controlled under
--- either the U.S. International Traffic in Arms Regulations or the U.S. Export
--- Administration Regulations.
---
--- DISTRIBUTION STATEMENT A: Approved for public release; distribution is
--- unlimited.
---
--- Notice: Markings. Any reproduction of this computer software, computer
--- software documentation, or portions thereof must also reproduce the markings
--- contained herein. Refer to the provided NOTICE file.
---
--- MAUDE_HCS: end

set clear rules off .
set print attribute on .
set show advisories off .
set verbose off .

load ../../../dns/maude/probabilistic/iodine_dns
load ../../../mastodon/maude/probabilistic/mastodon
load ../../../raceboat/rb-integration
load ../../../common/maude/_aux
load ../../../common/maude/cp2-interfaces
load ../../../common/maude/router
load ../../../common/maude/adversary-observer
load ../probabilistic

mod CP2_TEST is
inc IODINE_DNS .
inc MASTODON .
inc RB-CLIENT + RB-SERVER .
inc CP2_APP .
inc ROUTER .
inc ADVERSARY-OBSERVER .
inc MC-INTERFACE .

ops alice bob iodineSendApp iodineRecvApp iodineClient iodineServer aliceMasClient bobMasClient masServer : -> Address .
ops clientContentMgr serverContentMgr clientDestini serverDestini clientUserModel serverUserModel : -> Address .
ops monAddr : -> Address .

op zonePwnd2Com : -> List{Record} .
eq zonePwnd2Com =
  < 'pwnd2 . 'com . root, soa, 3600.0, soaData(3600.0) >
  < 'pwnd2 . 'com . root, ns, 3600.0, 'ns . 'pwnd2 . 'com . root >
  < 'ns . 'pwnd2 . 'com . root, a, 3600.0, iodineServer >
  < 'www0 . 'pwnd2 . 'com . root, a, 3600.0, 2 . 0 . 1 . 2 >
  < 'www1 . 'pwnd2 . 'com . root, a, 3600.0, 2 . 1 . 1 . 2 >
  < wildcard . 'pwnd2 . 'com . root, txt, 3600.0, nullAddr > .

eq monitorQueryLog? = true .

eq fileSize = 10000 .
---eq MAX-NUM-MEDIA-PER-TOOT = 4 .
eq packetSize = 1000 .
eq maxPacketSize = 967 .
eq packetOverhead = 33 .
eq maxFragmentLen = 200 .
eq maxFragmentTx = 20 .
eq pacingTimeoutDelay = 0.01 .
eq pacingTimeoutDelayMax = 0.05 .
eq ackTimeoutDelay = 1.0 .
eq maxMinimiseCount = 0 .

op router : -> Address .
op adversary : -> Address .
---- the sendtime / receive time collection patterns
ops ObsS ObsR : -> Observable .
eq ObsS = mtObs [owise] .
eq ObsR = mtObs [owise] .

--- uncomment to model aversary at router inside corporate
--- collects msgs received by router from interal actors
--- (stored as sent by local-dns)
eq ObsR = obsC .  

--- uncomment to model adversary at the router external interface
--- collects messages sent by router after NAT
--- the sending time is essentially the time the internal
--- source sent the message
**** eq ObsS = obsX .

eq weirdHashtags = jl(js("person") ;
                      js("man") ;           
                      js("woman") ;
                      js("camera") ;
                      js("TV") )
  .

  --- Initial configuration
op initState : -> Config .
eq initState =
  rCtr(0)
  makeTxApp(alice, bob, iodineSendApp, clientUserModel, clientContentMgr, file(0, 400))
  makeRxApp(bob, iodineRecvApp, serverUserModel, serverContentMgr)
  < iodineSendApp : SendApp | 
      fileDestAddr: iodineRecvApp,
      toAddr: iodineClient,
      queuePopulated: false,
      queue: mtpl,
      numAdmittedPkts: 1,
      iodineReady: true,
      sent: mtpl,
      rcvd: mtpl >
  < iodineRecvApp : RcvApp | rcvd: mtpl,
      fileDestAddr: bob,
      fileSrcAddr: iodineSendApp,
      toAddr: iodineServer,
      queuePopulated: true,
      queue: (mtpl),
      numAdmittedPkts: 1,
      iodineReady: true,
      sent: mtpl > 
  makeWClient(iodineClient, iodineServer, 'pwnd2 . 'com . root, a, 0.0)
  makeWNameServer(iodineServer, 0.0, (zonePwnd2Com))
  --- Make a Raceboat client for Alice.
  makeRbClient(clientUserModel, clientContentMgr, clientDestini, aliceMasClient)
  makeRbServer(serverUserModel, serverContentMgr, serverDestini, bobMasClient, bob)
  makeMastodonClient(aliceMasClient,
                     masServer,
                     clientContentMgr)
  makeMastodonClient(bobMasClient,
                     masServer,
                     serverContentMgr)
  makeMastodonServer(masServer)
  --- WMonitor
  < monAddr : WMonitor |
      querySent: nilQueryTimestamp,
      queryRcvd: nilQueryTimestamp,
      pktSent: nilPacketTimestamp,
      pktRcvd: nilPacketTimestamp >
  mkRouter(router)    
  mkAdversary(adversary,ObsS,ObsR)
  --- App start message:
  [1.0, (to alice : start), 0]
---   [1.0, (to bob : start), 0]
  .

op initConfig : -> Config .
eq initConfig = run({0.0 | nil} initState,limit) .
endm

set print attribute on .

eof

rew 
run(rCtr(2) {1.000005928446164, to aliceMasClient from clientContentMgr : tootQ(bHashTag(0), noBytes)}
{1.000005928446164 | nil} 
< aliceMasClient : MasClient | thisAddr: aliceMasClient, masServerAddr: masServer, requesterAddr: serverContentMgr, opStack: emptyOpStack, postingMedia: emptyMediaFileList, postingMediaIds:
    emptyMasIdList, postingText: "", gettingMediaUrls: emptyUrlList, gettingMedias: emptyMediaFileList, gettingPosts: emptyMasIdList >, 1.0e+8) 
.

rew 
run(rCtr(0) {1.0, to mastodon-client from clientContentMgr : tootQ(bHashTag(0), noBytes)} 
{1.0 |
nil} 
< mastodon-client : MasClient | thisAddr: mastodon-client, masServerAddr: mastodon-server, requesterAddr: alice-raceboat, opStack: emptyOpStack, postingMedia: emptyMediaFileList, postingMediaIds:
    emptyMasIdList, postingText: "", gettingMediaUrls: emptyUrlList, gettingMedias: (makeMediaFile("img0.jpg", 1000) :: makeMediaFile("img2.jpg", 1000)), gettingPosts: emptyMasIdList > 
< mastodon-server : MasServer | thisAddr: mastodon-server, currentMapId: 3, tootMap: (3 ~> makeToot("This is the #media toot with media", url("randimg0.com") ; url("randimg2.com"), 1 : 2)), mediaMap: ((1
    ~>(makeMediaFile("img0.jpg", 1000), url("randimg0.com"))) : (2 ~>(makeMediaFile("img1.jpg", 1000), url("randimg1.com"))) : 3 ~>(makeMediaFile("img2.jpg", 1000), url("randimg2.com"))), tagMap: (
    makeTag("media") ~> 3) >, 1.0e+8) 
.    
