--- MAUDE_HCS: maude_hcs
---
--- Software Markings (UNCLASS)
--- Maude-HCS Software
---
--- Copyright (C) 2025 RTX BBN Technologies Inc. All Rights Reserved
---
--- The computer software and computer software documentation are licensed
--- under the Apache License, Version 2.0 (the "License"); you may not use
--- this file except in compliance with the License. A copy of the License
--- is provided in the LICENSE file, but you may obtain a copy of the
--- License at:  https://www.apache.org/licenses/LICENSE-2.0
---
--- The computer software and computer software documentation are based
--- upon work supported by the Defense Advanced Research Projects Agency (DARPA)
--- under Agreement No. HR00l 12590083.
---
--- This document does not contain technology or technical data controlled under
--- either the U.S. International Traffic in Arms Regulations or the U.S. Export
--- Administration Regulations.
---
--- DISTRIBUTION STATEMENT A: Approved for public release; distribution is
--- unlimited.
---
--- Notice: Markings. Any reproduction of this computer software, computer
--- software documentation, or portions thereof must also reproduce the markings
--- contained herein. Refer to the provided NOTICE file.
---
--- MAUDE_HCS: end

sload ../irc/common/irc_name
sload ../irc/common/_aux
sload ../irc/common/app_chat
sload ../irc/irc_monitor
sload ../irc/_irc_aux
sload ../irc/irc_prob
sload ./_obfs4_aux
sload ./obfs4_prob
sload ../../deps/dns_formalization/Maude/common/apmaude.maude
sload ../common/maude/cp2-interfaces

mod OBFS4_TESTS is
  pr IRC_NAMES .
  pr APP_CHATS .
  pr IRC_NODE .
  pr IRC_MONITOR .
  pr IRC .
  pr OBFS4 .
  pr SCHEDULER .
  pr IRC-DISPATCHER-INTERFACE .

  ops aliceAddr bobAddr : -> Address .
  ops aliceIrcClientAddr bobIrcClientAddr : -> Address .
  ops aliceIfaceAddr bobIfaceAddr aliceServerIfaceAddr bobServerIfaceAddr : -> Address .
  ops aliceObfs4ClientAddr bobObfs4ClientAddr : -> Address .
  ops obfs4AliceServerAddr obfs4BobServerAddr ircServerAddr : -> Address .

  ops aliceIrcClient bobIrcClient : -> Actor .
  ops aliceObfs4Client bobObfs4Client : -> Actor .
  ops obfs4AliceServer obfs4BobServer preconfiguredIrcServer : -> Actor .
  ops aliceIface bobIface aliceServerIface bobServerIface : -> Actor .

  eq aliceIrcClient = mkIrcClient(aliceIrcClientAddr,
                                  aliceIfaceAddr,
                                  "Alice",
                                  imd(0.000, "#room1", 279) :: imd(28.0, "#room1", 388)) .
  eq aliceIface = mkIrcByteSeqIface(aliceIfaceAddr, aliceIrcClientAddr, aliceObfs4ClientAddr, aliceObfs4ClientAddr) .
  eq aliceObfs4Client = makeObfs4Client(aliceObfs4ClientAddr, obfs4AliceServerAddr, ircServerAddr, aliceIfaceAddr) .



  eq bobIrcClient = mkIrcClient(bobIrcClientAddr, bobIfaceAddr, "Bob") .
  eq bobIface = mkIrcByteSeqIface(bobIfaceAddr, bobIrcClientAddr, bobObfs4ClientAddr, bobObfs4ClientAddr) .
  eq bobObfs4Client = makeObfs4Client(bobObfs4ClientAddr, obfs4AliceServerAddr, ircServerAddr, bobIfaceAddr) .



  eq preconfiguredIrcServer =
    < ircServerAddr : IrcServer |
        thisAddr: ircServerAddr,
        channelMap: (makeIrcChannelName("#room1") ~> (makeIrcUserName(aliceIrcClientAddr) : makeIrcUserName(bobIrcClientAddr))),
        clientTimestampMap: emptyClientTimestampMap,
        clientAddressMap: registerIrcUserAddress(
                            registerIrcUserAddress(emptyClientAddressMap, 
                                                   makeIrcUserName(aliceIrcClientAddr), aliceServerIfaceAddr),
                                                   makeIrcUserName(bobIrcClientAddr), bobServerIfaceAddr)
    >
  .
  --- Server Iface facing Alice.
  eq aliceServerIface = mkIrcByteSeqIface(aliceServerIfaceAddr, ircServerAddr, obfs4AliceServerAddr, obfs4AliceServerAddr) .
  --- Obfs4 Server facing Alice.
  eq obfs4AliceServer = makeObfs4Server(obfs4AliceServerAddr, aliceServerIfaceAddr, aliceObfs4ClientAddr, aliceIfaceAddr) .
  --- Server Iface facing Bob.
  eq bobServerIface = mkIrcByteSeqIface(bobServerIfaceAddr, ircServerAddr, obfs4BobServerAddr, obfs4BobServerAddr) .
  --- Obfs4 Server facing Bob.
  eq obfs4BobServer = makeObfs4Server(obfs4BobServerAddr, bobObfs4ClientAddr, bobObfs4ClientAddr, bobIfaceAddr) .

  ops ircMonitorAddr : -> Address .

  vars caddrs : AddrSet .
  vars rooms : StringAddrsSet .

  op initState : -> Config .
  eq initState = 
    rCtr(0)
    aliceIrcClient
    aliceIface
    aliceObfs4Client
    bobIrcClient
    bobIface
    bobObfs4Client
    preconfiguredIrcServer
    aliceServerIface
    obfs4AliceServer
    bobServerIface
    obfs4BobServer
    mkIrcMonitor(ircMonitorAddr,
                 (aliceIrcClientAddr ;; bobIrcClientAddr ;; ircServerAddr),
                 (aliceIrcClientAddr ;; bobIrcClientAddr),
                 (rm("#room1", aliceIrcClientAddr ;; bobIrcClientAddr)))
    [1.0,
      (to aliceIrcClientAddr from aliceIrcClientAddr : ircMsgSendTime),
      0]
  .

  op initConfig : -> Config .
  eq initConfig = run({0.0 | nil} initState, 300.) .
endm

set print attribute on .
---set trace on .

--- Experiment with 2 IRC clients and 1 IRC server, traffic encapsulated with obfs4
rew initConfig .

