--- MAUDE_HCS: maude_hcs
---
--- Software Markings (UNCLASS)
--- Maude-HCS Software
---
--- Copyright (C) 2025 RTX BBN Technologies Inc. All Rights Reserved
---
--- The computer software and computer software documentation are licensed
--- under the Apache License, Version 2.0 (the "License"); you may not use
--- this file except in compliance with the License. A copy of the License
--- is provided in the LICENSE file, but you may obtain a copy of the
--- License at:  https://www.apache.org/licenses/LICENSE-2.0
---
--- The computer software and computer software documentation are based
--- upon work supported by the Defense Advanced Research Projects Agency (DARPA)
--- under Agreement No. HR00l 12590083.
---
--- This document does not contain technology or technical data controlled under
--- either the U.S. International Traffic in Arms Regulations or the U.S. Export
--- Administration Regulations.
---
--- DISTRIBUTION STATEMENT A: Approved for public release; distribution is
--- unlimited.
---
--- Notice: Markings. Any reproduction of this computer software, computer
--- software documentation, or portions thereof must also reproduce the markings
--- contained herein. Refer to the provided NOTICE file.
---
--- MAUDE_HCS: end

sload ../irc/common/irc_name
sload ../irc/common/_aux
sload ../irc/common/app_chat
sload ../irc/_irc_aux
sload ../irc/irc_nondet
sload ./_obfs4_aux
sload ./obfs4_nondet

mod OBFS4_TESTS is
  pr IRC_NAMES .
  pr APP_CHATS .
  pr IRC_NODE .
  pr IRC .
  pr OBFS4 .

  ops aliceAddr bobAddr : -> Address .
  ops aliceIrcClientAddr bobIrcClientAddr : -> Address .
  ops aliceObfs4ClientAddr bobObfs4ClientAddr : -> Address .
  ops obfs4ServerAddr ircServerAddr : -> Address .

  ops aliceIrcClient bobIrcClient : -> Actor .
  ops aliceObfs4Client bobObfs4Client : -> Actor .
  ops obfs4Server preconfiguredIrcServer : -> Actor .

  eq aliceIrcClient = mkIrcClient(aliceIrcClientAddr,
                                  aliceObfs4ClientAddr,
                                  "Alice",
                                  imd(0.000, "#room1", 279) :: imd(28.0, "#room1", 388)) .
  eq bobIrcClient = mkIrcClient(bobIrcClientAddr, bobObfs4ClientAddr, "Bob") .

  eq aliceObfs4Client = makeObfs4Client(aliceObfs4ClientAddr, obfs4ServerAddr, ircServerAddr, aliceIrcClientAddr) .
  eq bobObfs4Client = makeObfs4Client(bobObfs4ClientAddr, obfs4ServerAddr, ircServerAddr, bobIrcClientAddr) .

  eq obfs4Server = makeObfs4Server(obfs4ServerAddr, ircServerAddr) .

  eq preconfiguredIrcServer =
    < ircServerAddr : IrcServer |
        thisAddr: ircServerAddr,
        channelMap: (makeIrcChannelName("#room1") ~> (makeIrcUserName(aliceIrcClientAddr) : makeIrcUserName(bobIrcClientAddr))),
        clientTimestampMap: emptyClientTimestampMap,
        clientAddressMap: registerIrcUserAddress(
                            registerIrcUserAddress(emptyClientAddressMap, 
                                                   makeIrcUserName(aliceIrcClientAddr), aliceIrcClientAddr),
                            makeIrcUserName(bobIrcClientAddr), bobIrcClientAddr)
    >
  .
endm

set print attribute on .
---set trace on .

--- Experiment with 2 IRC clients and 1 IRC server, traffic encapsulated with obfs4
rew aliceIrcClient
    aliceObfs4Client
    bobIrcClient
    bobObfs4Client
    obfs4Server
    preconfiguredIrcServer
    (to aliceIrcClientAddr from aliceAddr : makeAppChat(makeIrcChannelName("bbn"), "Hello Bob!"))
.
